### ISSUE TITLE
Switch to main branch

### ISSUE THREAD

**Issue by gregorwolf** [abap2xlsx/abap2xlsx#1002]
I think we should rename to main or?

**Comment by larshp** [comment]
yea, I think you have access to change it?

note, things will keep working in abapGit and regular git clients

**Comment by sandraros** [comment]
No problem for me. I guess the reason of renaming `master` to `main` is [this one](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/)?

**Comment by gregorwolf** [comment]
Correct.

**Comment by gregorwolf** [comment]
Done.
