### ISSUE TITLE
ReadMe: Broken Links + Link to Demo Repo

### ISSUE THREAD

**Issue by g-back** [abap2xlsx/abap2xlsx#1003]
Hi, it seems that links that direct to https://abap2xlsx.github.io are broken - in the ReadMe thats the links to the documentation and the abapGit-installation.
I could fix the links myself, but you'd have to tell me which URLs to use (just point to the markdown files of the repo for example)

Also, it may make sense to mention the demo-Repo directly in the ReadMe? (Something like: "Note, the demo programs have moved to ...")

**Comment by larshp** [comment]
https://abap2xlsx.github.io/abap2xlsx/ now works, https://github.com/abap2xlsx/abap2xlsx/deployments/activity_log?environment=github-pages

demo programs: yea, just open a PR

**Comment by gregorwolf** [comment]
To get something to https://abap2xlsx.github.io we must create a repo named abap2xlsx.github.io. See: [Creating a GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site)
