### ISSUE TITLE
7.15.0: ZCL_EXCEL_WORKSHEET, local test class, method INT8: leftover int8 declaration may break compile

### ISSUE THREAD

**Issue by Cyberman-tM** [abap2xlsx/abap2xlsx#1007]
Currently here: https://github.com/abap2xlsx/abap2xlsx/blob/main/src/zcl_excel_worksheet.clas.testclasses.abap#L1582

The method int8 checks if int8 is available in the system, but has a leftover(?) int8 declaration - so if the system doesn't support it, it won't even compile.

**Comment by AndreaBorgia-Abo** [comment]
@Cyberman-tM thank you for the report!
@sandraros this is related to your PR #979 that I reviewed, somehow I missed that. PR incoming.
