### ISSUE TITLE
SCI Check Error: The exception ZCX_EXCEL is not caught or declared in the RAISING clause of "GET_CELL_COORD".

### ISSUE THREAD

**Issue by gregorwolf** [abap2xlsx/abap2xlsx#1011]
Hello abap2xlsx Team,

at one client abap2xlsx needs to pass the SCI Check Variant TRANSPORT without any errors and warnings. When running a SCI Inspection with this variant for the $abap2xlsx package I get one error:

```
Class ZCL_EXCEL_READER_HUGE_FILE Method GET_CELL_COORD Row 3 Column 0
Syntax check warning. The exception ZCX_EXCEL is not caught or declared in the RAISING clause of "GET_CELL_COORD".
```

I will try to provide a PR for this.

CU
Gregor

**Comment by larshp** [comment]
suggest enabling https://rules.abaplint.org/uncaught_exception/

![image](https://user-images.githubusercontent.com/5888506/161904438-558e39dc-b70a-4561-a3ae-736331b17ae4.png)
