### ISSUE TITLE
Transport available?

### ISSUE THREAD

**Issue by AndreMatjasic** [abap2xlsx/abap2xlsx#1014]
Hey,

I am new to this whole github and I would like to ask if there is a transport for this tool?
My organisation doesn´t allow to pull it via abapgithub. They only allow it if there is a .zip-File with transports to transport it to our dev-system.

Maybe someone can help me, please.

Dear
Andre

**Comment by gregorwolf** [comment]
Dear @AndreMatjasic,

don't get why transports which are binary files unless you use gCTS are allowed and the transparent abapGit format is not. Maybe it's worth another discussion with your SAP Basis Team. If you have the urgent need then please try to create it on your own using an ABAP Developer Edition or a Sandbox Sytem.

CU
Gregor

**Comment by AndreMatjasic** [comment]
Dear @gregorwolf,

I think that was the reason.
Is it possible that you can make me the transport?
It would really help me.

CU
Andre

**Comment by gregorwolf** [comment]
Not for free.

**Comment by AndreMatjasic** [comment]
How much?
Is the Developer edition for free?

**Comment by gregorwolf** [comment]
abap2xlsx is free. But if you ask for an additonal service you should also pay the person providing you that service. You find my contact information via my GitHub profile.

**Comment by AndreMatjasic** [comment]
I mean If the ABAP Developer Edition is free?

**Comment by gregorwolf** [comment]
Yes, the ABAP Developer Edition is free. Unfortunately the Docker Version is not available right now. But you can install the old 7.52 ABAP which you get from https://developers.sap.com/trials-downloads.html?search=abap

**Comment by sandraros** [comment]
Another very easy solution is to create the unique program `ZABAPGIT_STANDALONE` and import the ZIP file of `abap2xlsx`. Is there really a good reason to require the use of Transport Requests?

**Comment by AndreMatjasic** [comment]
@sandraros Well I think my SAP-Basis wouldn´t like that too... unfortunately they only allow Transport Requests.

**Comment by sandraros** [comment]
Is there any rationale behind this rule, or is it just a sound belief? 😀

**Comment by AndreMatjasic** [comment]
I think it is sound belief :)

**Comment by AlexandreHT** [comment]
If you’ve got a developer key, nothing stops you from 
  - installing [standalone ABAPGit](https://docs.abapgit.org/guide-install.html#install-standalone-version) as a local program in your dev environnement (as @sandraros suggested)
  - Install abap2xlsx as an offline project (in a non-local package) in you dev environment => which gives you the transport request your basis colleagues need.

**Comment by AndreaBorgia-Abo** [comment]
@AndreMatjasic I can confirm that the ZIP option works well even for upgrading an existing installation: you still get a TR if the package is non-local. This way the fight to remove nonsensical rules can wait for another day.

**Comment by AndreaBorgia-Abo** [comment]
Question was already answered, closing the issue.
