### ISSUE TITLE
Value type Integer 8 - Error during bind_table

### ISSUE THREAD

**Issue by marfl-git** [abap2xlsx/abap2xlsx#1021]
In the class: ZCL_EXCEL_WORKSHEET mehtod SET_CELL Line 68 the type int8 is missing.
Without this fix the excel generator fall into an error if the value is int8.

`        case LV_VALUE_TYPE.
          when CL_ABAP_TYPEDESCR=>TYPEKIND_INT or CL_ABAP_TYPEDESCR=>TYPEKIND_INT1 or CL_ABAP_TYPEDESCR=>TYPEKIND_INT2 or CL_ABAP_TYPEDESCR=>typekind_int8.`

![image](https://user-images.githubusercontent.com/62929737/165284255-2990f570-8c47-4140-8d50-82f01f7757f0.png)

**Comment by sandraros** [comment]
It has been fixed with #676, please pull the latest version of abapGit.
If it solves, please close the issue.
Thank you.
