### ISSUE TITLE
Font "Libre Barcode 39" not loading

### ISSUE THREAD

**Issue by ramc-v** [abap2xlsx/abap2xlsx#1038]
I am trying to add barcodes in the spreadsheet by setting the font as "Libre Barcode 39", the font is set as expected but doesn't load when opening in the desktop version of the excel. This loads fine if opened from office online or the web version of office.

Here's a simplified report of what the issue boils down to and to replicate this issue :
```
DATA: lo_excel                TYPE REF TO zcl_excel.
DATA: lo_worksheet            TYPE REF TO zcl_excel_worksheet.
DATA: lo_style_barcode        TYPE REF TO zcl_excel_style.
DATA: lv_style_barcode        TYPE        zexcel_cell_style.

CONSTANTS: gc_save_file_name TYPE string VALUE 'Barcode_Style.xlsx'.

INCLUDE zdemo_excel_outputopt_incl.

START-OF-SELECTION.

  CREATE OBJECT lo_excel.

  lo_style_barcode                  = lo_excel->add_new_style( ).
  lo_style_barcode->font->name      = 'Libre Barcode 39'.
  lo_style_barcode->font->scheme    = zcl_excel_style_font=>c_scheme_none.
  lo_style_barcode->font->size      = 25.
  lv_style_barcode                  = lo_style_barcode->get_guid( ).

  lo_excel->set_default_style( lv_style_barcode ).

  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_title( 'Barcode Style' ).
  lo_worksheet->set_cell( ip_column = 1 ip_row = 1 ip_value = '*ABC123*' ).

  lcl_output=>output( lo_excel ).
```

I am not sure if we can use a font that is not in zcl_excel? However the cell properties do reflect the font that I set here.
![image](https://user-images.githubusercontent.com/107599713/173988610-08bb0cc5-92f5-4b43-8cfe-9e67529823cf.png)

The same file opened in the office online excel:
![image](https://user-images.githubusercontent.com/107599713/173988521-f21fbe79-ad93-46a6-a29c-05c2bd2cb45e.png)

Any help?Thanks in advance

**Comment by sandraros** [comment]
Thank you for the code to reproduce. Could you attach an Excel file which works so that we can compare the two? Thank you!

**Comment by ramc-v** [comment]
Thanks @sandraros! It is the same file when opened on O365 (the web version of excel from browser that works) and other from excel installed in local machine (which doesn't work). The 2 screenshots are of the same file.
[Barcode_styles.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/8916379/Barcode_styles.xlsx)

**Comment by gregorwolf** [comment]
@ramc-v is the required font installed on your local machine? I guess in the web version web fonts are used and automatically loaded.

**Comment by ramc-v** [comment]
Oh yeah, that was the first bit I checked too. I do have the fonts and the barcodes are displayed with the font if I apply it manually on my machine.

**Comment by sandraros** [comment]
I don't have any issue with Excel 365. Could you give more information? What do you get when you open the Excel file generated by abap2xlsx?
![image](https://user-images.githubusercontent.com/34005250/174034706-67e7ca22-97d7-43fe-b2c9-91263f5043b6.png)

**Comment by ramc-v** [comment]
@sandraros May I know what is the version of excel you are on?
I am on "Version 2204 Build 16.0.15128.20128" on my machine.

This is the the what I see on running the code I mentioned in my post, 
![image](https://user-images.githubusercontent.com/107599713/174084495-89f70640-9f80-4f54-a3b7-621970cb1b93.png)

**Comment by sandraros** [comment]
Office 365 version 2108...
![image](https://user-images.githubusercontent.com/34005250/174092603-436c69ce-045b-4b17-be5a-540cb1b5038b.png)

**Comment by ramc-v** [comment]
Oddly, we chose to use a different font "Free 3 of 9 Extended" that is similar to this and that loads fine.
I am not sure why this happens with "Libre Barcode 39" though, but there's an alternative.

Thanks for your help @sandraros

**Comment by sandraros** [comment]
Thanks for the feedback. That will surely help others!
