### ISSUE TITLE
Autosize of Columns not working with Excel365

### ISSUE THREAD

**Issue by Kidokann** [abap2xlsx/abap2xlsx#1040]
> I think ZCL_EXCEL_WRITER_2007->CREATE_XL_SHEET (Row 461) is wrong.
> 
> `IF NOT lo_column_iterator IS BOUND`
> 
> should be changed to:
> 
> `IF lo_column_iterator IS BOUND`
> 
> Same game for ZCL_EXCEL_WRITER_HUGE_FILE (Row 306).

I have debbuged this case on my side, having the same behaviour. You are totally right. This should be the code change applied in ZCL_EXCEL_WRITER_2007->CREATE_XL_SHEET

  " Calculate col
    IF NOT lo_column_iterator IS BOUND.     
      lo_column_iterator = io_worksheet->get_columns_iterator( ).
    ENDIF.
 io_worksheet->calculate_column_widths( ).

Same for ZCL_EXCEL_WRITER_HUGE_FILE.
No other suggested patches work.

_Originally posted by @Kidokann in https://github.com/abap2xlsx/abap2xlsx/issues/646#issuecomment-1140213086_

**Comment by sandraros** [comment]
Please, check the comment I added to #646, I explained how column auto-size works. If you want to post a new issue, please indicate the steps so that we can reproduce the error, don't only show the code that you think is wrong.
