### ISSUE TITLE
Error from DDIF_DOMA_PUT when pulling from offline repository

### ISSUE THREAD

**Issue by mainakaich** [abap2xlsx/abap2xlsx#1041]
Hello, 
I have downloaded the ABAP2XLSX latest offline version from github(abap2xlsx-main.zip). We have SAP ECC 6 with NW ABAP 7.5 here. While debugging I found that the DOMNAME field of DD07V_TAB parameter in FM 'DDIF_DOMA_PUT' is not filled up with domain name from the input XML files. Can you please help me to fix the issue. The similar problem happened for in FM DDIF_TABLE_PUT as well.

![abap2xlsx issue](https://user-images.githubusercontent.com/54839961/175285203-06930c38-fd26-471a-9383-601ce08ebf70.jpg)

**Comment by sandraros** [comment]
Which ABAP 7.5x version? `7.56` or another one?
Which abapGit version did you use?

**Comment by mainakaich** [comment]
> Which ABAP 7.5x version? `7.56` or another one? Which abapGit version did you use?

ABAP 7.5 with SP-Level 14, Support Package mentioned as SAPK-75014INSAPABA
abapGit version was latest version 7.15.0 I believe, I went to  https://github.com/abap2xlsx/abap2xlsx and downloaded the zip file by clicking on Code Button.

**Comment by mainakaich** [comment]
@sandraros, I have understood the reason behind this issue. I was running old version of ZABAPGIT which was causing this error. Once I updated with the latest version and executed, everything worked smoothly. Hence I am closing this issue. Thanks anyway for your time to support.

**Comment by sandraros** [comment]
@mainakaich Well done/thanks for the feedback!
