### ISSUE TITLE
Unable to find ZEXCEL_T_WORKSHEET_COLUMNDIME

### ISSUE THREAD

**Issue by ajayjhav** [abap2xlsx/abap2xlsx#1045]
HI,

I was trying to implement program ZDEMO_EXCEL3 and came across adding line data COLUMN_DIMENSIONS type ZEXCEL_T_WORKSHEET_COLUMNDIME in class ZCL_EXCEL_WORKSHEET. Can anyone help me what is the properties of ZEXCEL_T_WORKSHEET_COLUMNDIME. Need help urgently..

**Comment by larshp** [comment]
are you running the latest version? I cannot find any code references, https://github.com/abap2xlsx/abap2xlsx/search?q=ZEXCEL_T_WORKSHEET_COLUMNDIME

**Comment by ajayjhav** [comment]
where to get the latest version and how to download and install it to use in our SAP environment..?

**Comment by larshp** [comment]
see https://abap2xlsx.github.io/abap2xlsx/abapGit-installation

**Comment by ajayjhav** [comment]
I am unable to find the program code for ZABAPGIT_FULL. Can you please help me.

**Comment by gregorwolf** [comment]
Have you read the first step of the instructions and followed the link to install abapGit?

**Comment by sandraros** [comment]
For information, [abapGit instructions](https://docs.abapgit.org/guide-install.html) say to `create a new report named ZABAPGIT_STANDALONE (formerly ZABAPGIT_FULL)` but [abap2xlsx](https://abap2xlsx.github.io/abap2xlsx/abapGit-installation) still refers to the old name `ZABAPGIT_FULL`, I propose to reflect the latest name proposed by abapGit in the abap2xlsx doc → https://github.com/abap2xlsx/abap2xlsx/pull/1047.

**Comment by gregorwolf** [comment]
Thank you @sandraros for the correction. Hope @ajayjhav you get forward now.
