### ISSUE TITLE
Send spool data as excel attachment

### ISSUE THREAD

**Issue by ajayjhav** [abap2xlsx/abap2xlsx#1049]
Hi,

I am having a requirement to convert a dynamic ALV List spool to Excel email attachment.  Are we having any programs to look into.

**Comment by gregorwolf** [comment]
Have you checked [zdemo_excel32](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel32.prog.abap)?

**Comment by sandraros** [comment]
In abap2xlsx, there is no example for getting data from a spool request, especially because it's not recommended. Instead, you should intercept data before it's sent to spool, and then you can export the data via abap2xlsx.

**Comment by AndreaBorgia-Abo** [comment]
Question was answered, closing this issue.
