### ISSUE TITLE
Custom named cell styles

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#105]
READER and WRITER classes to support writing to named cell styles created
[[url:https://cw.sdn.sap.com/cw/servlet/JiveServlet/showImage/2-54823-9001/custom_styles.jpg|Screenshot of named cell Style in Excel]]

to Styles.xml
[[url:https://cw.sdn.sap.com/cw/servlet/JiveServlet/showImage/9003/input_style_xml.JPG|Screenshot of cellStyle xml node]]

**Comment by ivanfemia** [comment]
Updating issues (#23, #28, #31, #32, #49, #53, #71, #94, #97, #99, #107, #110)

**Comment by ivanfemia** [comment]
Updating issues (#23, #28, #31, #49, #53, #71, #94, #97, #99, #107, #112, #127)

Moved to Release 7.0

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Closed because no objections have arisen.
