### ISSUE TITLE
Wrong date format when converting internal table to excel file and currency and quantity values are coming in text format instead of numeric  

### ISSUE THREAD

**Issue by PoddarKrishna** [abap2xlsx/abap2xlsx#1058]
Hello,

I'm using zclexcel_common=>date_to_excel_string( ip_value = yyyymmdd ) convert internal date excel date and I'm getting  ########(-693595)
```abap
lo_style_filled->number_format->format_code = zclexcel_style_number_format=>c_format_date_std.
lv_style_filled_guid = lo_style_filled->get_guid( ).
lo_worksheet->set_cell(
                                EXPORTING
                                  ip_column    = 'A'
                                  ip_row       = '1'
                                  ip_value     = 'value from date_to_excel_string()'
                                  ip_abap_type = 'D'
                                  ip_style     = lv_style_filled_guid
```
for Currency and Quantity, I'm using the below code 
```abap
lv_style_filled_guid = lo_style_filled->number_format->format_code = zclexcel_style_number_format=>c_format_number_comma_sep2.
lv_style_filled_guid = lo_style_filled->get_guid( ).
lo_worksheet->set_cell(
                                EXPORTING
                                  ip_column    = 'B'
                                  ip_row       = '1'
                                  ip_value     = '32465'
                                  ip_abap_type = 'N'
                                  ip_style     = lv_style_filled_guid
```
It would be a great help.

![one](https://user-images.githubusercontent.com/113054224/188945930-03555ecc-03ca-4071-9a7d-cc676bf436ce.jpg)

**Comment by sandraros** [comment]
I think that you have converted an incorrect value:

- In Excel a date is required to be equal or greater than `1/1/1900`.
- Numbers should be passed as numbers (`32465`), not characters (`'32465'`). Note that you can't pass directly a number with fraction, you need to use an intermediate variable (i.e. `ip_value = conv decfloat16( '3.14' )`).

Could you please provide a complete program so that we can reproduce? This kind of program requires something like 20-30 lines of code.

NB: I have formatted your code. Excel uses `#######` to say that you should increase the width of the column to see the value.

**Comment by PoddarKrishna** [comment]
Thanks for the quick response.

I got the solution while preparing the code to send you.

For date : 
we should not use method zclexcel_common=>date_to_excel_string( ip_value = yyyymmdd ) we just pass directly yyyymmdd.

like below:
lo_style_filled->number_format->format_code = zclexcel_style_number_format=>c_format_date_std.
lv_style_filled_guid = lo_style_filled->get_guid( ).
lo_worksheet->set_cell(
                                EXPORTING
                                  ip_column    = 'B'
                                  ip_row       = '1'
                                  ip_value     = 20220901
                                  ip_abap_type = 'D'
                                  ip_style     = lv_style_filled_guid

For Currency :
we need pass ip_abap_type = 'P' I was passing 'N'

like below:
lo_style_filled->number_format->format_code = zclexcel_style_number_format=>c_format_number_comma_sep2.
lv_style_filled_guid = lo_style_filled->get_guid( ).

lo_worksheet->set_cell(
                                EXPORTING
                                  ip_column    = 'B'
                                  ip_row       = '1'
                                  ip_value     = 12345
                                  ip_abap_type = 'P'
                                  ip_style     = lv_style_filled_guid
