### ISSUE TITLE
ZDEMO_EXCEL32, BIND_ALV, NOT WORK FOR THE COLUMN AUTOFIT

### ISSUE THREAD

**Issue by onlylovehuan** [abap2xlsx/abap2xlsx#1060]
I have set is_optimized in the alv, but when I use bind to download the xlsx, the column autofit didn't work.

**Comment by sandraros** [comment]
abap2xlsx calculates approximately the width of columns based on the font metrics stored in transaction code `SE73`.
Could you show what you currently get by running `zdemo_excel32` please?

**Comment by onlylovehuan** [comment]
thank you Sandraros, I rechecked the code and find the problem is the Chinese code problem.
