### ISSUE TITLE
Remove Header row

### ISSUE THREAD

**Issue by aditya-deloitte** [abap2xlsx/abap2xlsx#1062]
Hi Team,
How do I remove the first row (header row) containing column names and only display data when using ZCL_EXCEL_WORKSHEET->BIND_TABLE( ) ?

**Comment by sandraros** [comment]
`BIND_TABLE` defines an Excel Table which requires headings, so we can't use this method for just pasting the values.
Instead, you may use the method `SET_TABLE` with the parameter `IP_NO_HEADER = abap_true`.

**Comment by AndreaBorgia-Abo** [comment]
Question was answered, closing this issue.
