### ISSUE TITLE
Is it possible to create an XML 2003 format multi-sheet excel file?

### ISSUE THREAD

**Issue by nchal7** [abap2xlsx/abap2xlsx#1063]
Hello!
I have been using your library from almost 6 months now and it is amazing!

I would like to ask if it is possible to create an XML-2003 format multi-sheet excel file?

Thank you in advance.

**Comment by sandraros** [comment]
Thank you. It would be a completely different project (abap2xmlss or something like that). It would take a lot of time to create and test the code. XML 2003 is an old format, so I don't know if there's a lot of demand for that. Concerning the "writer" part, an economical solution would be to start based on an existing template (to be inspired from [this solution for XLSX](https://blogs.sap.com/2020/05/22/best-way-to-generate-microsoft-excel-xlsx-from-template-in-abap/)). As it's a project by volunteers, that would be great if you could work on it and create your own repository 😉

**Comment by AndreaBorgia-Abo** [comment]
Question was answered, closing this issue.
