### ISSUE TITLE
SAP 740 install

### ISSUE THREAD

**Issue by BobTomkins** [abap2xlsx/abap2xlsx#1064]
Just installed the software on to SAP 740 system and am finding syntax errors does the system need to be 750?

Syntax error in ZCL_EXCEL_WORKSHEET method CONVERT_TO_TABLE field TYPEKIND_INT8 is unknown. A search on Google says that this type is defined in SAP 750.

Many thanks

**Comment by bigld** [comment]
Hi @BobTomkins 
Thanks for reporting - we will fix this.
