### ISSUE TITLE
change the website link to the GitHub pages (documentation) link

### ISSUE THREAD

**Issue by schmelto** [abap2xlsx/abap2xlsx#1067]
Maybe the link should be the GitHub pages Link (eq. https://abap2xlsx.github.io/abap2xlsx/) instead of linking back to the repository where the user already is.

![image](https://user-images.githubusercontent.com/30869493/196421959-24232cf4-6175-4605-8286-f56e91773bb8.png)
![image](https://user-images.githubusercontent.com/30869493/196422222-5d7c45fa-5db6-40c4-b81f-69d285eb2a3e.png)

**Comment by gregorwolf** [comment]
Thank you @schmelto for this tip. I've updated the link.
