### ISSUE TITLE
ABAP Unit fails in test class of zcl_excel_worksheet

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#1072]
With the latest abap2xlsx version, the test class `ltc_normalize_column_heading` of `zcl_excel_worksheet` reports these errors:
![image](https://user-images.githubusercontent.com/34005250/197853772-a5cb80ba-3b99-40a1-9fe3-bc7cef7a9ec6.png)

**Comment by Dwivedirahul44** [comment]
I guess either the code at 3307 - 3316 needs to change to fill `scrtext_l `or the Unit test needs to be updated to match the exp output to check for `column_name`, I assume it's the latter. I can add a pr on it based on your input. 
![image](https://user-images.githubusercontent.com/43263062/198393628-569b0c83-1912-4054-968c-a2e5c295ddfc.png)
