### ISSUE TITLE
Is it possible to execute VBA Code

### ISSUE THREAD

**Issue by QinYu11** [abap2xlsx/abap2xlsx#1074]
I want to execute bellow VBA CODE which copy one cell validation to another whole column:

    Range("J2").Select
    Application.CutCopyMode = False
    Selection.Copy
    Columns("Q:Q").Select
    Selection.PasteSpecial Paste:=xlPasteValidation, Operation:=xlNone, _
        SkipBlanks:=False, Transpose:=False

Is it possible to do so in ABAP2xlsx?

**Comment by sandraros** [comment]
abap2xlsx can:
- read an XLSX file (all classic features)
- create an XLSX file (all classic features)
- create an XLSM file with macros inside
- but cannot run macros

So, globally, the answer is yes. You have some [demos](https://github.com/abap2xlsx/demos) provided in a distinct repository.

EDIT: to answer exactly your question, abap2xlsx can't "copy" a cell validation already set. But it's easy to set a cell validation in the whole column.

**Comment by QinYu11** [comment]
Hi Sandraros, 
    We want to download excel template with data validation, currently we found abap2xlsx validation only apply to some rows we assign in a loop. How can I apply the data validaton to one column and entire rows? Dut to we cannot execute VBA code, I give up this approach.

**Comment by gregorwolf** [comment]
Do you mean adding a drop-down-list with values from another worksheet to a field @QinYu11 ?

**Comment by sandraros** [comment]
Maybe you can provide an Excel example of what you want to achieve, so that to clarify? I'm not aware of abap2xlsx limitations concerning Data Validations.

**Comment by QinYu11** [comment]
The excel generated as bellow:
[ZQINYUTEST26.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/9957356/ZQINYUTEST26.xlsx)


I create 2 worksheets named Data Validation and Mass Upload. At column REASON of Mass Upload, the first 10 rows have dropdown list which come from wroksheet Data Validation column A.  The first 10 rows drop down list  ABAP code as bellow: 
 lv_rows = 10
  DO lv_rows TIMES.
      row = row + 1.
      lo_data_validation              = lo_worksheet_old->add_new_data_validation( ).
      lo_data_validation->type        = zcl_excel_data_validation=>c_type_list.
      lo_data_validation->formula1    = c_reason.
      lo_data_validation->cell_row    = row.
      lo_data_validation->cell_column = col_str.
    ENDDO.
Currenly I used loop to fill in the drop down list. My pourpose is to fill in the drop down list for the whole rows of column REASON.

**Comment by sandraros** [comment]
The demo program [ZDEMO_EXCEL45](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel45.prog.abap) shows how to define the data validation in cells A2 to A4, you can define any number of rows, and you don't need to do a loop:

https://github.com/abap2xlsx/demos/blob/a958f6cd5a86205e3c709fd32bf075dc288e4e9b/src/zdemo_excel45.prog.abap#L45-L56

**Comment by QinYu11** [comment]
Bellow Code is a loop which loop from line 2 to line 4:

* add some fields with validation
  lv_row = 2.
  WHILE lv_row <= 4.
    lo_worksheet->set_cell( ip_row = lv_row ip_column = 'A' ip_value = 'Select' ).
    lv_row = lv_row + 1.
  ENDWHILE.

The excel template can only use the dropdown list from line 2 to line 4. Actually, I don't know howmany rows user want to fill. So how can I set column A and any row with the drop down list?

**Comment by sandraros** [comment]
The last possible row is 1048576 so go from A2 to A1048576. No loop needed.
```abap
  lo_data_validation->type           = zcl_excel_data_validation=>c_type_list.
  lo_data_validation->formula1       = lv_validation_string.
  lo_data_validation->cell_row       = 2.
  lo_data_validation->cell_row_to    = 1048576.
  lo_data_validation->cell_column    = 'A'.
  lo_data_validation->cell_column_to = 'A'.
```
