### ISSUE TITLE
Date format issue

### ISSUE THREAD

**Issue by calltobharath** [abap2xlsx/abap2xlsx#1075]
Experts,

I am using ABAP2XLSX to get input excel file in my program and upload to application server. I tried all the date formats in my excel file and its giving either Index out of Bounds or Unable to interpret date error.
I tried 30.08.2022, 30/08/2022, 20220830, 20223008. Just every possible combination I can think of.

I am executing method EXCEL_STRING_TO_DATE in class ZCL_EXCEL_COMMON. I tried all possible date formats as input to this method. And I have not been successful with a single date format so far. 

What is the correct date format that we should pass to ABAP2XLSX code?

Thanks
Bharath

**Comment by sandraros** [comment]
Dates should be stored in Excel as true dates. A true date is a value which varies depending on the date format you choose in Excel ("Number Formats" in the category "Date").

The method EXCEL_STRING_TO_DATE in class ZCL_EXCEL_COMMON converts a true Excel date value, e.g. "44894" corresponds to today and is converted into ABAP Date "20221129" (other examples [here](https://github.com/abap2xlsx/abap2xlsx/blob/ac8f4a701e40750e14dbe7c14a3624fc1b68e219/src/zcl_excel_common.clas.testclasses.abap#L589-L620)).

If you have a date which is not stored as a true Excel date, it's up to you to write your own logic to decode the string. We can't help on that.

**Comment by calltobharath** [comment]
Sandra,

You are the best! I converted my incorrect dates in excel file to true dates and abap2xlsx functionality is working perfectly now. 

Thanks
Bharath
