### ISSUE TITLE
Write Excel File in background

### ISSUE THREAD

**Issue by mainakaich** [abap2xlsx/abap2xlsx#1076]
As per the blog, https://blogs.sap.com/2010/07/12/abap2xlsx-generate-your-professional-excel-spreadsheet-from-abap/ says background processing of excel file is possible. While I can see it is possible to read an excel file in background using the method call like below :
        CREATE OBJECT reader TYPE zcl_excel_reader_2007.
        excel = reader->load_file( input_file_path ).
But how to write the excel file in background? I couldn't find any example as such. Am I missing something or it is a limitation in ABA2XLSX that the excel output can't be written to local file system in background though can be read in background.

**Comment by sandraros** [comment]
You can write an Excel file too. For instance almost all demo programs do it. Short example:
```abap
DATA(lo_excel) = NEW zcl_excel( ).
DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
lo_worksheet->set_cell( ip_column = 1 ip_row = 1 ip_value = 'Hello world' ).
DATA(lo_writer) = NEW zcl_excel_writer_2007( ).
DATA(xstring) = lo_writer->zif_excel_writer~write_file( lo_excel ).
"here you can add any processing of xstring, e.g. GUI_DOWNLOAD in BIN format
```

**Comment by mainakaich** [comment]
@sandraros the problem I want to highlight is lo_writer->zif_excel_writer~write_file( lo_excel ) only writes to the excel object in memory. But the moment you want to finally place the file in a file system you are using GUI_DOWNLOAD which can't work in background. So if I write a program to create an excel file in a file system, I can't execute my program in background because the app server won't be able to find the local system directory in background processing.

**Comment by sandraros** [comment]
GUI_DOWNLOAD can't work in a background job, this is ABAP limitation, it's not related to abap2xlsx. In background, you can only write a file to the SAP server:
```abap
DATA(fullpath) = '/usr/sap/file.xlsx'.
OPEN DATASET fullpath FOR OUTPUT IN BINARY MODE.
TRANSFER xstring TO fullpath.
CLOSE DATASET fullpath.
```

**Comment by mainakaich** [comment]
Yes, I agree GUI_DOWNLOAD can't work in a background job and it is an ABAP limitation. I just wanted to check if there is any other possibility as such. Thanks for the clarification Sandra. Closing this issue.
