### ISSUE TITLE
`bind_table` with numeric `top_left_column` accepted but generates a corrupted Excel file

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#1080]
Run the program below:
1. Choose "direct display":
   ![image](https://user-images.githubusercontent.com/34005250/215270470-e0e3dfee-443c-4a54-8583-504deca97695.png)
1. I get this error
   > "We found a problem with some content in 'test.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."
   ![image](https://user-images.githubusercontent.com/34005250/215270445-d4fb5951-fa3d-49c7-8bec-4527d8c1d749.png)
```abap
DATA: gc_save_file_name TYPE string VALUE 'test.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  SELECT * FROM scarr INTO TABLE @DATA(itab).
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->bind_table(
          ip_table          = itab
          is_table_settings = VALUE #( top_left_column = 1 top_left_row = 1 ) ).
  lcl_output=>output( cl_excel = lo_excel ).
```
Workaround:
- It works well by using `top_left_column = 'A'`

Possible solutions:
1. Either `bind_table` could raise an exception if the column is a number
2. Or convert the column number to the corresponding letter(s) (`zcl_excel_common=>convert_column2alpha`)

NB:
- I didn't check `bottom_right_column`, I guess there could be the same error.

**Comment by bigld** [comment]
I think this is a duplicate of #1215?

**Comment by sandraros** [comment]
oO yes, sorry, let's close this one.
