### ISSUE TITLE
Read of file generated by abap2xlsx fails "Please provide either row and column, or cell reference" 

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#1081]
Steps to reproduce:
1. Create this program:
    ```abap
    REPORT.
    DATA: gc_save_file_name TYPE string VALUE 'test.xlsx'.
    INCLUDE zdemo_excel_outputopt_incl.
    START-OF-SELECTION.
      DATA(lo_excel) = NEW zcl_excel( ).
      DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
      DATA(style_large_bold) = lo_excel->add_new_style( ).
      lo_excel->set_default_style( style_large_bold->get_guid( ) ).
      lo_worksheet->set_cell( ip_columnrow = 'A2' ip_value = 'test' ).
      DATA(lo_writer) = CAST zif_excel_writer( NEW zcl_excel_writer_2007( ) ).
      DATA(xstring) = lo_writer->write_file( lo_excel ).
      DATA(lo_reader) = NEW zcl_excel_reader_2007( ).
      DATA(lo_excel_2) = lo_reader->zif_excel_reader~load( i_excel2007 = xstring ). " <=== Exception
      lo_excel = lo_excel_2.
      lcl_output=>output( cl_excel = lo_excel ).
    ```
1. Run the program > Choose "direct display":
   <img src="https://user-images.githubusercontent.com/34005250/215270470-e0e3dfee-443c-4a54-8583-504deca97695.png" width="250">
1. There is a short dump while calling the method `LOAD` due to uncaught exception `zcx_excel` with `error` text "Please provide either row and column, or cell reference"
   <img src="https://github.com/abap2xlsx/abap2xlsx/assets/34005250/78b77460-225b-4df7-a60b-bd535985272e" width="500">
   <img src="https://github.com/abap2xlsx/abap2xlsx/assets/34005250/08115c4d-baba-44a4-85ad-1c2617c05c7f" width="500">
   <img src="https://github.com/abap2xlsx/abap2xlsx/assets/34005250/b92645c2-a6c1-43bb-9d7d-af37d83c9abb" width="500">
   <img src="https://github.com/abap2xlsx/abap2xlsx/assets/34005250/d37edaaf-1d0a-4ffa-b49e-3b8f18a9ba14" width="500">
   Link to the code:
    https://github.com/abap2xlsx/abap2xlsx/blob/34a8ed4865dc11a91ffcad80e6135bac9d30747c/src/zcl_excel_worksheet.clas.abap#L3354-L3361

Analysis:
- It happens while reading the generated file but it's when the Excel file is written/generated that the `sheet<number>.xml` file is created with a weird empty `r` attribute (should be a range, like e.g. `A1` in our case):
  ![image](https://user-images.githubusercontent.com/34005250/215275974-f08443fa-2a9b-494d-bff8-4c0a69debb6a.png)

Workaround:
- Set explicitly a value in the first row (e.g. `lo_worksheet->set_cell( ip_columnrow = 'A1' ip_value = '' ).`

Possible solution:
1. Fix the value while generating the Excel file, so that the `r` attribute is set to `A1`. To do that, add `ls_sheet_content_empty-cell_coords = 'A1'.` here: https://github.com/abap2xlsx/abap2xlsx/blob/34a8ed4865dc11a91ffcad80e6135bac9d30747c/src/zcl_excel_writer_2007.clas.abap#L4265-L4271
3. Excel handles that cell with empty `r` attribute without failing. So, maybe we could also fix the reader class to ignore these cells.
4. Both fixes could be done.

NB:
- I didn't check the below code for the "last line". maybe there is an error too (?)
  https://github.com/abap2xlsx/abap2xlsx/blob/34a8ed4865dc11a91ffcad80e6135bac9d30747c/src/zcl_excel_writer_2007.clas.abap#L4297-L4303

**Comment by sandraros** [comment]
Note that [`ZDEMO_EXCEL1`](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel1.prog.abap) and many other demo programs generate the code `<row r="1" spans="1:3"><c r=""/></row>` which is maybe weird but doesn't generate a bug.

It's only the `LOAD` method which doesn't handle it correctly.

If I keep `r=""` but I change manually the XLSX file to `<row r="1" spans="1:3"><c r="" s="2"><v>44561</v></c></row>`, we can see that Excel considers `<c r=""` as being `<c r="A1"`:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/669564b4-802f-4549-927a-ac70ddb8b4dd)

If I repeat the whole `c` tag above four times, Excel shows:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/982f83c2-4d76-4d4a-a3d6-656e17f11bb7)

After more tests, I can deduce that Excel logic is to keep in memory the position of the last cell initialized in the current row and if the new cell is `<c r=""` then the position is just the next column (+1). Also, it seems to always start from column 1, it doesn't depend on `spans` (e.g. starts from 1 even if `spans="2:3"`).

So, maybe the best solution is to mimic this Excel behavior.

**Comment by AndreaBorgia-Abo** [comment]
> So, maybe the best solution is to mimic this Excel behavior.

I agree: until Excel has a problem with the files abap2xlsx produces (be that the first or the last line), I would only change the reading logic to follow Excel's footsteps.
