### ISSUE TITLE
QUIT-NO constant does not exist on 731

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abap2xlsx/abap2xlsx#1085]
After pulling in #1082 the syntax checker reports the following errors on a 731 system:
![grafik](https://user-images.githubusercontent.com/25269970/216325642-a4830ac8-676a-47e1-bb60-30d48d2063ab.png)
Additionally, a missing method is used in a report though this issue is already known ( #1077 )

**Comment by sandraros** [comment]
This is the code in ABAP 7.52:
```
interface if_Aunit_Constants public.
  ...
  constants:
    "! Control flow
    begin of quit,
      "! Raise failure and continue with test
      no          type   aunit_Flowctrl       value 0,
      "! Raise failure and exit the current test
      test        type   aunit_Flowctrl       value 1,
    end of quit.
```
Does ABAP Unit work well in ABAP 7.31 if you compile with `'0'`? (with '0', it should continue testing other methods in the class, while '1' interrupts the test class)
![image](https://user-images.githubusercontent.com/34005250/216333827-8a4fc62e-1a3d-47a6-98f7-a6da56ba2b5a.png)

**Comment by rplantiko** [comment]
IF_ABAP_UNIT_CONSTANT is a newer version for IF_AUNIT_CONSTANTS. In my release, SAP_BASIS 756, they both exist and both have a component QUIT-NO. This is the intended value in the test: the test method should make more than one assertion and list all the failures when the method is completed. 

IF_AUNIT_CONSTANTS is 

This should also work when passing 0 (with no apostrophs: **0**, not **'0'**, as it is an integer). 

But constants have a name for a reason...

**Comment by AndreaBorgia-Abo** [comment]
With 0 the test results are as follows:
![grafik](https://user-images.githubusercontent.com/25269970/216342947-83076d95-7a50-45d0-86fb-cf1c0cec7f72.png)
(sorry, I tested with 0 so the screenshot is correct but I originally wrote '0' here above, thus editing)

**Comment by rplantiko** [comment]
The values of constants IF_ABAP_UNIT_CONSTANT=>QUIT-NO and IF_AUNIT_CONSTANTS=>QUIT-NO differ (the former is 5, and the latter is 0).  Both constants exist in my release (SAP_BASIS 7.56).

QUIT-NO is the intended value in this case, as the method should check several assertions and not leave if one of them fails. At the end, the method is marked as failed if at least one of the assertions failed, and one gets a list of all failures. 


But the answer is 'yes', the value **0** (not **'0'**, as it is an integer, not a character field) can be used, since the codes works identical with both values (see method RAISE_FAILURE in CL_ABAP_UNIT_ASSERT):
 
```
      when if_Aunit_Constants=>quit-no or if_Abap_Unit_Constant=>quit-no.
        " assertion gets logged via event, proceed with test case
```

**Comment by rplantiko** [comment]
> With '0' the test results are as follows:  (...)

Great, this warning comes from a test which has nothing to with the test that I changed.

BTW: could you take 0, not '0' ?

**Comment by AndreaBorgia-Abo** [comment]
> BTW: could you take 0, not '0' ?

I mistyped in the comment, but the code ran with 0 as number.

**Comment by sandraros** [comment]
At least the "QUIT" parameter exists in 7.31, so I guess it works the same as in recent versions. I would opt for a simple fix just in the class `zcl_excel_worksheet`. No issue for me to use a literal or a constant. If we want to code it in a clean way, there may be these solutions in order:
1. look for a standard constant (but I'm afraid it might not exist in 7.31)
2. create an interface for defining reusable constants like that one
3. local constant in `zcl_excel_worksheet`
4. hardcode (with number 0 😉)
Your opinion? Who can do it?

**Comment by rplantiko** [comment]
I have no 731 system at hand, but I find it strange that supposedly no constant exists in 731 to specify values of the quit parameter in an upward-compatible way.

I would look for calls of cl_abap_unit=>assert. ..( ) in a 731 system which do pass the quit parameter. (This would be Sandra's option 1)

Options 2 and 3 appear overdone to me. I mean, we are talking about an option of a unit test assert call. I am petty sure that an own constant (let alone a constant in a separate interface) will only pollute the code, without anybody else ever using it.

So if (1) fails, I would suggest (4): to write "quit = 0".

**Comment by AndreaBorgia-Abo** [comment]
I self-assigned this ticket upon creation because I have this system, I can try the fixes you guys suggested. Tomorrow I have a presentation so I'll apply the dirtiest fix (n.4), then I'll deal with it once that is over.

**Comment by rplantiko** [comment]
OK. Good luck with your presentation!

**Comment by AndreaBorgia-Abo** [comment]
Seems like they basically renamed it, so I went for this solution:
![grafik](https://user-images.githubusercontent.com/25269970/216554774-61e4ab36-e662-4b80-931d-8d754c88e011.png)
I'll handle this later, git-wise

**Comment by sandraros** [comment]
It still exists in 7.52 in `if_Aunit_Constants`:
```
  "! Control flow: Do not quit just raise a failure
  constants no type aunit_Flowctrl value 0.
```

**Comment by rplantiko** [comment]
Same here in 7.56 

So it looks `IF_AUNIT_CONSTANTS=>NO` is our friend
