### ISSUE TITLE
Excel String to date conversion issue

### ISSUE THREAD

**Issue by aditya-deloitte** [abap2xlsx/abap2xlsx#1087]
When uploading an excel file with date values, the get_table throws error. 
I tried both internal format (YYYYMMDD) and external format (DD.MM.YYYY), in both cases it fails.

My code:
```
TYPES: BEGIN OF ty_excel,
         mblnr TYPE mblnr,
         mjahr TYPE mjahr,
         budat TYPE budat,
         usnam TYPE usnam,
         bktxt TYPE bktxt,
       END OF ty_excel.
PARAMETERS p_file TYPE string LOWER CASE DEFAULT 'C:\temp\Test.Upload.File.xlsx'.
DATA gt_upload TYPE TABLE OF ty_excel.
TRY.
    DATA(o_reader)    = CAST zif_excel_reader( NEW zcl_excel_reader_2007( ) ).
    DATA(o_excel)     = o_reader->load_file( i_filename = p_file ).
    DATA(o_worksheet) = o_excel->get_active_worksheet( ).
    o_worksheet->get_table( EXPORTING iv_skipped_rows = 1
                            IMPORTING et_table = gt_upload ).
  CATCH zcx_excel INTO DATA(o_error).
    DATA(xl_err_msg) = o_error->get_text( ).
    WRITE xl_err_msg.
ENDTRY.
```  

  Date example: 20230302
[Test Upload File.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/10577312/Test.Upload.File.xlsx)

**Comment by sandraros** [comment]
Could you provide an Excel file to reproduce the case? Thank you.

NB: not sure but the expected format is possibly the Excel Date format, the one which is used when you type a date manually in Excel.

**Comment by aditya-deloitte** [comment]
Sample Upload file
[Test Upload File.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/10577333/Test.Upload.File.xlsx)

**Comment by sandraros** [comment]
Thanks. Reproduced. The error message is `Unable to interpret date`.
I confirm that the expected format is the Excel Date format, the one which is used when you type a date manually in Excel.
![image](https://user-images.githubusercontent.com/34005250/216564158-0b39affb-55ef-468e-8e7e-5b8e6473d433.png)

If you have a date stored in a non-date format in the Excel file, you should handle the conversion yourself, so it should be a neutral C type for `BUDAT` field.

**Comment by aditya-deloitte** [comment]
> Thanks. Reproduced. The error message is `Unable to interpret date`. I confirm that the expected format is the Excel Date format, the one which is used when you type a date manually in Excel. ![image](https://user-images.githubusercontent.com/34005250/216564158-0b39affb-55ef-468e-8e7e-5b8e6473d433.png)
> 
> If you have a date stored in a non-date format in the Excel file, you should handle the conversion yourself, so it should be a neutral C type for `BUDAT` field.

Hi Sandra, 
Thanks for fast reply.
But have to point out that in both formats (Internal and External), the date is not converted and throws error.
In case of external format, the error comes _Index out of bounds_

Test File
[Test Upload File (External Format).xlsx](https://github.com/abap2xlsx/abap2xlsx/files/10577782/Test.Upload.File.External.Format.xlsx)

**Comment by sandraros** [comment]
I'm not talking about these 2 SAP formats. I'm talking about the format in your Excel file.

GET_TABLE only reads the Date Excel format:
![image](https://user-images.githubusercontent.com/34005250/216603267-f667d2ab-aec8-48d2-895b-1b47dd60b1cc.png)

If you have a date stored in a non-date format in the Excel file, you should handle the conversion yourself, so it should be a neutral C type for `BUDAT` field.

**Comment by aditya-deloitte** [comment]
Thanks Sandra, I got it now. 
I made the BUDAT field string and converted it later myself.
Closing the issue.
