### ISSUE TITLE
No zero values

### ISSUE THREAD

**Issue by aditya-deloitte** [abap2xlsx/abap2xlsx#1090]
Hi,
I want to hide zero values (0 or 0.00) from showing up in excel except in the formula bar. I tried to find in Demo programs or online but could not find a way. Kindly help to provide a solution.

Thanks in advance.

[Sample File.XLSX](https://github.com/abap2xlsx/abap2xlsx/files/10760621/Sample.File.XLSX)

**Comment by sandraros** [comment]
Thank you for the example. You can use the [Number Formats](https://support.microsoft.com/en-us/office/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68) to arrange the display of the cell values as you wish. The demos don't provide all Excel possibilities of number formats but you can find answers in the Web.

In your case. it's the format number `0;-0;;@` as explained in the article [Display or hide zero values, by Microsoft](https://support.microsoft.com/en-us/office/display-or-hide-zero-values-3ec7a433-46b8-4516-8085-a00e9e476b03):
- either at chapter "Hide zero values in selected cells"
- or in the video from 27" to 45"

Demo:
```abap
DATA: gc_save_file_name TYPE string VALUE 'test.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  TRY.
      DATA(lo_excel) = NEW zcl_excel( ).
      DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
      DATA(lo_style) = lo_excel->add_new_style( ).
      lo_style->number_format->format_code = '0;-0;;@'.
      lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = 0 ip_style = lo_style ).
      lcl_output=>output( cl_excel = lo_excel ).
    CATCH cx_root INTO DATA(lx_root).
      MESSAGE lx_root TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
```

**Comment by aditya-deloitte** [comment]
Thank you Sandra!
I also needed to hide zero values as well as wanted to keep two decimal places, so the format I found is `0.00;-0.00;;@` from here https://www.excelforum.com/excel-general/1162692-hide-zero-values-but-keep-number-format.html
