### ISSUE TITLE
Converter does not work if Grid not yet displayed

### ISSUE THREAD

**Issue by hardyp** [abap2xlsx/abap2xlsx#1097]
In online mode I would like to send the email before the ALV grid is displayed in the GUI.

I have a dirty trick to make this work as follows:

```ABAP
METHOD create_spreadsheet.
    "Convert SALV object into excel
    DATA: l_ws TYPE c LENGTH 10 VALUE 'ITS'.

    "If we do this (call the convertor) in the foreground we get a dump unless we do a dirty trick
    IF sy-batch EQ abap_false.
      EXPORT l_ws = l_ws TO MEMORY ID 'WWW_ALV_ITS'.
    ENDIF.

    DATA(converter) = NEW zcl_excel_converter( ).

    TRY.
        IF mo_alv IS BOUND.
          converter->convert(
            EXPORTING
              io_alv        = mo_alv
              it_table      = it_table[]
              i_table       = abap_true "Create as Table
              i_style_table = zcl_excel_table=>builtinstyle_medium2
            CHANGING
              co_excel      = mo_excel ).
        ELSE.
          RETURN.
        ENDIF.

        FREE MEMORY ID 'WWW_ALV_ITS'.

      CATCH zcx_excel INTO DATA(exception).
        DATA(message) = exception->get_text( ).
        MESSAGE message TYPE 'I'.
    ENDTRY.

  ENDMETHOD.
```

I was wondering if my "dirty trick" could somehow be embedded inside the converter class, so it does not matter in which order the conversion and the display of the ALV object happens.

Cheersy Cheers

Paul

**Comment by gregorwolf** [comment]
It's better than a dump or? Keep the pull request coming.

I hope you are aware that you can copy paste ABAP code and get it correctly formatted like this:

```ABAP
WRITE: / 'Hello World'.
```

**Comment by hardyp** [comment]
Just to re-iterate - if I display the SALV first and then call the convertor online all is well. If I call the converter online before displaying the SALV then I get a dump. In background everything is fine, I can call them in either order.

It would be amazingly simple to put the EXPORT/IMPORT memory statements at the start and end of the CONVERTER method. I suppose the question I am really asking is can anyone see any downside to doing this? If not, then I will indeed raise a pull request.

Code added properly. Why does it not format the first and last line?

```ABAP
METHOD create_spreadsheet.
    "Convert SALV object into excel
    DATA: l_ws TYPE c LENGTH 10 VALUE 'ITS'.

    "If we do this (call the convertor) in the foreground we get a dump unless we do a dirty trick
    IF sy-batch EQ abap_false.
      EXPORT l_ws = l_ws TO MEMORY ID 'WWW_ALV_ITS'.
    ENDIF.

    DATA(converter) = NEW zcl_excel_converter( ).

    TRY.
        IF mo_alv IS BOUND.
          converter->convert(
            EXPORTING
              io_alv        = mo_alv
              it_table      = it_table[]
              i_table       = abap_true "Create as Table
              i_style_table = zcl_excel_table=>builtinstyle_medium2
            CHANGING
              co_excel      = mo_excel ).
        ELSE.
          RETURN.
        ENDIF.

        FREE MEMORY ID 'WWW_ALV_ITS'.

      CATCH zcx_excel INTO DATA(exception).
        DATA(message) = exception->get_text( ).
        MESSAGE message TYPE 'I'.
    ENDTRY.

  ENDMETHOD.
```

**Comment by gregorwolf** [comment]
Did improve your comment. Please check [Quoting code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

**Comment by sandraros** [comment]
Thank you. I'd like to reproduce the issue before adding the code. I did a copy of [`ZDEMO_EXCEL33`](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel33.prog.abap) and added `cl_salv_table=>factory` and `salv->display` before `lcl_output=>output`, as follows, but there was no short dump. Could you propose a minimal reproducible example please?
```abap
  ...

  cl_salv_table=>factory(
    IMPORTING
      r_salv_table   = DATA(salv)
    CHANGING
      t_table        = lt_test ).
  salv->display( ).

** Create output
  lcl_output=>output( lo_excel ).
```

**Comment by hardyp** [comment]
The trick is to call the convertor BEFORE the grid is displayed. If you call it afterwards all is well. And I still cannot work out tat code insertion thing. I press the <> button, put code in the middle, nothing happens. Anyway, in the below example the convertor is called straight away and so you get a short dump.
```abap
START-OF-SELECTION.

  SELECT *
       FROM sflight
       INTO TABLE @DATA(lt_output_data)
       ORDER BY PRIMARY KEY.

  TRY.
      cl_salv_table=>factory(
        IMPORTING r_salv_table = DATA(lo_alv)
        CHANGING  t_table      = lt_output_data ).
    CATCH cx_salv_msg INTO DATA(lx_salv_msg).
      MESSAGE lx_salv_msg->get_text( ) TYPE 'I'.
  ENDTRY.

  DATA(lo_excel)     = NEW zcl_excel( ).
  DATA(lo_converter) = NEW zcl_excel_converter( ).

  lo_converter->convert(
            EXPORTING
              io_alv        = lo_alv
              it_table      = lt_output_data[]
              i_table       = abap_true "Create as Table
              i_style_table = zcl_excel_table=>builtinstyle_medium2
            CHANGING
              co_excel      = lo_excel ).
 ```

**Comment by sandraros** [comment]
Thanks. Code edited above (put code in middle of 2 lines with triple back quotes, first triple back quotes followed by the word "abap").

I still can't reproduce, even after adding `lo_alv->display( )` at the end of the code. I'm running S/4HANA with ABAP 7.57. What is your version?

**Comment by hardyp** [comment]
I wrote the above in a 7.51 system this morning and got a short dump. The problem also occurs in a 7.50 system. I did not bother adding the "display" in my example because the dump happens during the call to the convertor, so it never gets that far.

My suspicion is the dump happens deep in the bowels of standard SAP code, which is bound to have changed dramatically between 7.50 and 7.57. 

I have no recollection at all as to how I worked out that exporting the value "ITS" to memory ID "WWW_ALV_ITS" would solve the problem, but it does.

**Comment by hardyp** [comment]
Found it
![image](https://user-images.githubusercontent.com/7078215/232423468-cd4242f1-d45d-4d51-aeeb-5651365c9a52.png)
![image](https://user-images.githubusercontent.com/7078215/232423503-dad0b8f7-b5a4-45a2-bd98-a0efe3b2f62e.png)

**Comment by hardyp** [comment]
If "offline" resolves to false then the dump occurs in CL_SALV_TABLE->GET_METADATA( ) presumably because the ALV gird has not yet been displayed. In offline mode the program does not expect the grid to have been displayed and so does not attempt to get the metadata from a null instance.

**Comment by sandraros** [comment]
Thanks. Are you using SAP GUI for HTML? If so, could you try with SAP GUI for Windows?
NB: I'll try later today on an older SAP system, on Web GUI too. Also, I'll try to understand better what is `WWW_ALV_ITS`, just to be convinced that clearing it has no side-effect.

**Comment by hardyp** [comment]
I am aware that there is such a thing as SAP GUI for HTML. Round about 2001 one of our business analysts did some experiments using it, but none of us at work liked the look of it so we never used it again. As a result, the only times in my career I have used SAP GUI for HTML would be by accident when using standard SAP systems like XI/PI/PO (XI used multiple UI technologies for different transaction codes).

One line summary - I used SAP GUI for Windows in the example, I have no way of using SAP GUI for HTML, nor would I want to.

**Comment by hardyp** [comment]
I just had a look in an S/4HANA system (7.55) and the method in CL_SALV_MODEL looks exactly the same.
![image](https://user-images.githubusercontent.com/7078215/232629787-bf483c67-6ded-4221-a9b4-02bd09d3c760.png)
I am not allowed to install ABAP2XLSX in that system as yet though.

**Comment by sandraros** [comment]
I could reproduce the short dump in an ABAP 7.52 SP 0 system, with your exact program above. Now, that will be easier to analyze and fix it as you proposed. Thank you!

[abap2xlsx issue 1097 short dump.txt](https://github.com/abap2xlsx/abap2xlsx/files/11258689/abap2xlsx.issue.1097.short.dump.txt)

**Comment by KonstantinKhrushchev** [comment]
@hardyp my simple fast solution for convert ALV to XLSX in background.
It works fine in online/offline mode. Ofcourse grid not displayed couse gui_custom_container hasn`t link to screen.
1. create inheritance from CL_GUI_ALV_GRID to ZCL_MY_GUI_ALV_GRID and redefine SET_TABLE_FOR_FIRST_DISPLAY and clear m_batch_mode.
```abap  
CLEAR m_batch_mode.
  CALL METHOD super->set_table_for_first_display
    EXPORTING
      i_buffer_active               = i_buffer_active
      i_bypassing_buffer            = i_bypassing_buffer
      i_consistency_check           = i_consistency_check
      i_structure_name              = i_structure_name
      is_variant                    = is_variant
      i_save                        = i_save
      i_default                     = i_default
      is_layout                     = is_layout
      is_print                      = is_print
      it_special_groups             = it_special_groups
      it_toolbar_excluding          = it_toolbar_excluding
      it_hyperlink                  = it_hyperlink
      it_alv_graphics               = it_alv_graphics
      it_except_qinfo               = it_except_qinfo
      ir_salv_adapter               = ir_salv_adapter
    CHANGING
      it_outtab                     = it_outtab
      it_fieldcatalog               = it_fieldcatalog
      it_sort                       = it_sort
      it_filter                     = it_filter
```
2. modify ZCL_EXCEL_CONVERTER class constructor 
```abap  
  ls_objects-seoclass  = 'ZCL_MY_GUI_ALV_GRID'.
  ls_objects-clsname   = 'ZCL_EXCEL_CONVERTER_ALV_GRID'.
  INSERT ls_objects INTO TABLE wt_objects.
```
3. call ALV and converter
```abap  

  DATA lo_cont TYPE REF TO cl_gui_custom_container.
  DATA lo_grid TYPE REF TO zcl_my_gui_alv_grid.
  CREATE OBJECT lo_grid
    EXPORTING
      i_parent = lo_cont.

  CALL METHOD lo_grid->set_table_for_first_display
    EXPORTING
      is_layout         = ls_lay
      i_save            = 'A'
      it_special_groups = it_field_group
    CHANGING
      it_sort           = lt_sort
      it_filter         = lt_filter
      it_fieldcatalog   = lt_field
      it_outtab         = lt_cofp.


  DATA lo_excel TYPE REF TO zcl_excel.
  CREATE OBJECT lo_excel.

  DATA lo_worksheet TYPE REF TO zcl_excel_worksheet.
  lo_worksheet = lo_excel->get_active_worksheet( ).

  lo_worksheet->bind_alv( io_alv = lo_grid it_table = lt_cofp i_table = abap_false ).

  DATA lo_writer TYPE REF TO zcl_excel_writer_2007.
  CREATE OBJECT lo_writer.

  rv_xstr = lo_writer->zif_excel_writer~write_file( lo_excel ).
```

**Comment by hardyp** [comment]
In regard to the proposed CL_GUI_ALV_GRID solution, I am sure that works, but in my example, I am using CL_SALV_TABLE. I have no idea if the problem was also happening with CL_GUI_ALV_GRID. In any event the proposed pull request from Sandra to fix the problem for CL_SALV_TABLE looks really good to me.
