### ISSUE TITLE
Internal Hyperlink assignment dump

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#110]
Class: ZCL_EXCEL_WORKSHEET
Method: SET_CELL

ERROR: zcx_excel is raised when the ip_value and ip_formula parameters are not passed. 

Scenario:
   I have 2 internal tables containing data where hyperlink should be implemented.
1.  Create sheet1 with first internal table data and set rows, columns and  values.
2. Create sheet2 with the second internal table and set rows, columns and values.
3. Now that we know in which cell are the data of both internal table, I want to set hyperlinks
4. Create Hyperlink for sheet2 and update the hyperlink process for sheet2
5. Create hyperlink for sheet1 and update hyperlink process for sheet1

The problem is the method SET_CELL has a validation where the ip_value or the ip_formula has to be passed otherwise it raise the zcx_excel.

<pre><code>IF ip_value  IS NOT SUPPLIED AND ip_formula IS NOT SUPPLIED.
    RAISE EXCEPTION TYPE zcx_excel
      EXPORTING
        error = 'Pleas provide the value or formula'.
ENDIF.</code></pre>

POSSIBLE CORRECTION:
The method should be modified to check has well the ip_hyperlink before raising the error.

<pre><code>IF ip_value  IS NOT SUPPLIED AND ip_formula IS NOT SUPPLIED AND ip_hyperlink IS NOT SUPPLIED.
    RAISE EXCEPTION TYPE zcx_excel
      EXPORTING
        error = 'Pleas provide the value or formula'.
ENDIF.</code></pre>

Doing so, we can assign the value at the first step than assign the hyperlink when we know in which cells all the data are stored.  
EXAMPLE based on zdemo_excel4:

<pre><code>  " Get active sheet
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_title( ip_title = 'Sheet1' ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 2 ip_value = 'This is the first sheet' ).
*  lo_hyperlink = zcl_excel_hyperlink=>create_internal_link( iv_location = 'Sheet2!B2' ).
*  lo_worksheet->set_cell( ip_column = 'B' ip_row = 3 ip_value = 'This is link to second sheet' ip_hyperlink = lo_hyperlink ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 3 ip_value = 'This is link to second sheet' ).

  lo_worksheet = lo_excel->add_new_worksheet( ).
  lo_worksheet->set_title( ip_title = 'Sheet2' ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 2 ip_value = 'This is the second sheet' ).
*  lo_hyperlink = zcl_excel_hyperlink=>create_internal_link( iv_location = 'Sheet1!B2' ).
*  lo_worksheet->set_cell( ip_column = 'B' ip_row = 3 ip_value = 'This is link to first sheet' ip_hyperlink = lo_hyperlink ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 3 ip_value = 'This is link to first sheet' ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 4 ip_value = 'Sheet3 is hidden' ).

  lo_worksheet = lo_excel->add_new_worksheet( ).
  lo_worksheet->set_title( ip_title = 'Sheet3' ).
  lo_worksheet->zif_excel_sheet_properties~hidden = zif_excel_sheet_properties=>c_hidden.

  lo_worksheet = lo_excel->add_new_worksheet( ).
  lo_worksheet->set_title( ip_title = 'Sheet4' ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 2 ip_value = 'Cell B3 has value 0' ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 3 ip_value = 0 ).
  lo_worksheet->zif_excel_sheet_properties~show_zeros = zif_excel_sheet_properties=>c_hidezero.

* --- Hyperlink
  lo_excel->set_active_sheet_index_by_name( 'Sheet2' ).
  lo_hyperlink = zcl_excel_hyperlink=>create_internal_link( iv_location = 'Sheet1!B2' ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 3 ip_hyperlink = lo_hyperlink ).

  lo_excel->set_active_sheet_index_by_name( 'Sheet1' ).
  lo_hyperlink = zcl_excel_hyperlink=>create_internal_link( iv_location = 'Sheet2!B2' ).
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 3 ip_hyperlink = lo_hyperlink ).</code></pre>

Regards
Daniel St-Jacques

**Comment by ivanfemia** [comment]
To insert hyperlink we have to have cell node in <sheetData>.
There was similar issue about setting style  ( https://code.sdn.sap.com/spaces/abap2xlsx/tickets/44 )
I suggest to follow the same pattern and create new method SET_CELL_HYPERLINK with following logic

 READ TABLE sheet_content ASSIGNING &lt;fs_sheet_content&gt; WITH KEY cell_row    = ip_row
                                                                 cell_column = lv_column.

  IF sy-subrc EQ 0.
    updated hyperlink
  ELSE.
    set_cell( ip_column = ip_column ip_row = ip_row ip_value = '' ip_hyperlink = hyperlink ).
  ENDIF.

**Comment by ivanfemia** [comment]
I'm agree with your analysis.
I move this issue as related to Release 6.0

**Comment by ivanfemia** [comment]
Updating issues (#23, #28, #31, #49, #53, #71, #94, #97, #99, #107, #112, #127)

Moved to Release 7.0

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Closed because no objections have arisen.
