### ISSUE TITLE
HTTP error 411 occured: Direct connect to github.com: 443 failed: NIECONN_REFUSED(-10)

### ISSUE THREAD

**Issue by VladGhitulescu** [abap2xlsx/abap2xlsx#1110]
Hey,

following the [Procedure in order to create an online repo for abap2xlsx](https://abap2xlsx.github.io/abap2xlsx/abapGit-installation) I've got the error

`HTTP error 411 occured: Direct connect to github.com: 443 failed: NIECONN_REFUSED(-10)`

![CleanShot 2023-05-08 at 20 02 30@2x](https://user-images.githubusercontent.com/3112128/236899744-dddf80cd-ede8-482a-8d68-bae90b6afde4.png)

The local package $ABAP2XLSX was created and is currently empty.

Do you have any suggestions how can I solve this?

Thanks!

Regards,
Vlad

**Comment by gregorwolf** [comment]
Please check the [abapGit SSL Setup documentation](https://docs.abapgit.org/guide-ssl-setup.html). This is not an issue with abap2xlsx. So I'm closing this issue.
