### ISSUE TITLE
How to read content of a row in excel worksheet

### ISSUE THREAD

**Issue by mainakaich** [abap2xlsx/abap2xlsx#1112]
Hello, 

My requirement is, I want to get the content of a given row in a given excel worksheet when I pass the row number. Currently there is no method available in ZCL_EXCEL_WORKSHEET to do that. All I can do is, first I can call ZCL_EXCEL_WORKSHEET->GET_TABLE( ) to get all the entries in an internal table and then I can get my required record by reading the internal table. 

Can we have a method for this requirement if there is nothing already. I can contribute to develop this if you allow. 

Thanks,
Mainak

**Comment by sandraros** [comment]
Hi. In fact, you may use the method `GET_TABLE` to just read one line (here the line number 10). Just my opinion, I don't think it's worth creating a method, but of course other people in the team might think the opposite:
```
DATA(row_to_read) = 10.
worksheet->get_table( EXPORTING iv_skipped_rows = row_to_read - 1
                                iv_max_row      = row_to_read
                      IMPORTING et_table        = your_table ).
DATA(line_number_10) = your_table[ 1 ].
```
NB: anybody is permitted to propose a Pull Request, it will be reviewed by anybody of the team to see if it's to be directly merged, needs rework or clarification, and possibly rejected. Of course, as you are doing, people may open an issue first if they feel that the change needs to be discussed first.

**Comment by kjetil-kilhavn** [comment]
I agree with @sandraros and think this issue can be closed since the current functionality covers the use case. 
If you disagree, @mainakaich - now is the time to speak (read: add a comment).

**Comment by mainakaich** [comment]
Sure, I agree with @sandraros on this on the workaround. I am closing it.
