### ISSUE TITLE
Please check method zcl_excel_writer_2007->create_xl_sheet_pagebreaks

### ISSUE THREAD

**Issue by darnoc312** [abap2xlsx/abap2xlsx#1114]
Check the Code at  the end of method zcl_excel_writer_2007->create_xl_sheet_pagebreaks:

    lv_value = lines( lt_rows ).
    CONDENSE lv_value.
    lo_node_rowbreaks->set_attribute( name = 'count'             value = lv_value ).
    lo_node_rowbreaks->set_attribute( name = 'manualBreakCount'  value = lv_value ).

    lv_value = lines( lt_rows ).
    CONDENSE lv_value.
    lo_node_colbreaks->set_attribute( name = 'count'             value = lv_value ).
    lo_node_colbreaks->set_attribute( name = 'manualBreakCount'  value = lv_value ).

I think for lo_node_colbreaks the filled but unused table lt_columns shoud be used to determine lv_value.

**Comment by sandraros** [comment]
Thanks for the feedback. Is it possible to provide an example program to reproduce the issue, and explain what's wrong from user perspective?
