### ISSUE TITLE
Can abap2xlsx upload/download Excel in Steampunk(ABAP for Cloud Development)?

### ISSUE THREAD

**Issue by Yoloyoda** [abap2xlsx/abap2xlsx#1117]
Since Steampunk(ABAP for Cloud Development) does not support SAP GUI, frontend & file server access, I assume abap2xlsx does not support upload/download Excel. However, I see there is an open issue where this has been worked on. 
  ##https://github.com/abap2xlsx/abap2xlsx/issues/632

I also see in this blog that abap2xlsx is going to be Steampunk compatible.
https://blogs.sap.com/2022/01/03/steampunk-released-abap-api-first-draft-is-up/

As far as I see it, Steampunk does not provide mass file uploader functionality. So before I start building my own, just want to make sure if abap2xlsx supports it.

**Comment by gregorwolf** [comment]
Already in NetWeaver abap2xlsx did not implement any own functionality for upload/download. If you used the SAP GUI you would use the corresponding classes / function modules. For web based UIs you would implement the binary download/upload in a SEGW service using the methods:

- /iwbep/if_mgw_appl_srv_runtime~get_stream
- /iwbep/if_mgw_appl_srv_runtime~update_stream

So if you want abap2xlsx support for Steampunk please help working on the topics mentioned in #632. With SAP BTP Free Tier you even can get your own Steampunk instance that will not disappear after 3 month.

**Comment by Yoloyoda** [comment]
Thanks for clarifying. 
By using UI5 as frontend, I managed to build Excel uploader/downloader for Steampunk. 
However, achieving this using ABAP for Cloud Development alone, some tweaking and geeking are needed. I will update in the issue if I come with a solution.
