### ISSUE TITLE
SALV: Download with initial layout

### ISSUE THREAD

**Issue by oberhm** [abap2xlsx/abap2xlsx#1119]
Hello,

in addition to ticket #745 one point to discuss.

If the initial layout is set with this statement lo_layout->set_initial_layout( 'ABCD' ) it is not handled in the method ZCL_EXCEL_CONVERTER_SALV_TABLE->LOAD_DATA

This leads to wrong output.

Here is a test report:
[issue_report.txt](https://github.com/abap2xlsx/abap2xlsx/files/11982453/issue_report.txt)

I changed this by adding ls_vari-variant   = lo_layout->get_initial_layout( ). in line 38 of the method.

What do you think about it?

thanks and regards
Matthias

**Comment by sandraros** [comment]
I tested in 7.57, that sounds good. Would you mind proposing a pull request please?
Thank you!

Just a few comments in case we need it in the future:
- "Line 38" corresponds to inserting your line right below line 78 in this code:
  https://github.com/abap2xlsx/abap2xlsx/blob/9a424149fd4967fa2a7a90a8f1e594973c6a62db/src/zcl_excel_converter_salv_table.clas.abap#L72-L82 
- To reproduce:
  1. Create test program below (few changes done to your example code)
  1. Run it with ALV_ONLY option activated, to show the ALV only (it doesn't run abap2xlsx).
  2. Save any layout to `ABCD` (e.g. change the order of columns)
  3. Run again with ALV_ONLY option deactivated to generate the Excel file
     - It creates an empty Excel file:
       ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/0a70092a-107f-4414-ad7c-b92166f34136)
     - Unhide the first columns, they are shown in wrong order:
       ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/5c86777a-b99e-46dd-8bb8-92152aaa2c3d)
- After the fix you proposed, it shows correctly, columns are ordered according to the variant:
  ![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/a7b67007-62bb-467b-b44b-263237e88b92)

Test program:
```abap
REPORT.
PARAMETERS alv_only AS CHECKBOX DEFAULT 'X'.
CONSTANTS gc_save_file_name TYPE string VALUE 'issue_1119.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.

START-OF-SELECTION.
  SELECT * FROM sbook UP TO 15 ROWS
  INTO TABLE @DATA(gt_sbook).
  TRY.
      cl_salv_table=>factory(
        IMPORTING
          r_salv_table = DATA(lo_salv)
        CHANGING
          t_table      = gt_sbook[] ).
      DATA(layout) = lo_salv->get_layout( ).
      layout->set_key( VALUE salv_s_layout_key( report = sy-repid ) ).
      layout->set_default( abap_true ).
      layout->set_initial_layout( 'ABCD' ).        "INITIAL LAYOUT
      layout->set_save_restriction( if_salv_c_layout=>restrict_none ).
      IF alv_only = abap_true.
        lo_salv->display( ).
      ELSE.
        cl_salv_bs_runtime_info=>clear_all( ).
        cl_salv_bs_runtime_info=>clear_all( ).
        cl_salv_bs_runtime_info=>set(
          EXPORTING
            display  = abap_false
            metadata = abap_true
            data     = abap_true ).
        lo_salv->display( ).
        DATA(excel)     = NEW zcl_excel( ).
        DATA(worksheet) = excel->get_active_worksheet( ).
        NEW zcl_excel_converter( )->set_option( VALUE #(
            filter           = abap_true
            subtot           = abap_true
            hidenc           = abap_true
            hidehd           = abap_false
            conv_exit_length = abap_true ) ).
        worksheet->bind_alv(
            io_alv   = lo_salv
            it_table = gt_sbook  ).
        lcl_output=>output( excel ).
      ENDIF.
    CATCH cx_root INTO DATA(lx).
      MESSAGE lx TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
```

**Comment by oberhm** [comment]
Hi,
thanks for your answer. You get me puzzled, but I found the problem again.

Following steps are additionally done:
- create layout ABCD and set default flag
- create layout DCBA
- run the report with set_initial_layout( 'DCBA' ).

The output will be with the layout ABCD.

If the variable ls_vari-variant is initial, the function module LT_VARIANT_LOAD loads the default variant ( done because of layout->set_default( abap_true ). ).

Could you cross check again.

thanks
Matthias

**Comment by sandraros** [comment]
Sorry, I meant that I reproduced the bug in 7.57, and **your fix** sounds good ;-)
So, would you mind proposing a pull request please?
