### ISSUE TITLE
CX_SY_RANGE_OUT_OF_BOUNDS in ZCL_EXCEL_READER_2007 method UNESCAPE_STRING_VALUE

### ISSUE THREAD

**Issue by vcatx** [abap2xlsx/abap2xlsx#1122]
In class ZCL_EXCEL_READER_2007 method UNESCAPE_STRING_VALUE in following line:

```
        IF substring( val = result off = lv_character_position_plus_2 len = 4 ) CO '0123456789ABCDEFGHIJKLMNOPQRSTUVWabcdefghijklmnopqrstuvw'
          AND substring( val = result off = lv_character_position_plus_6 len = 1 ) = '_'.
```
if the result is shorter then lv_character_position_plus_2 + 4 is generating an exception type CX_SY_RANGE_OUT_OF_BOUNDS.

Try importing in a cell a text value - for example "TEST_X" - this is generating a short dump shortdump.

**Comment by larshp** [comment]
thanks, a pull request with a fix is welcome

**Comment by sandraros** [comment]
Link to concerned code:
https://github.com/abap2xlsx/abap2xlsx/blob/1fe298d5bebc01982d90efeef37b14e46a4eb7d3/src/zcl_excel_reader_2007.clas.abap#L4134-L4135

Another issue: why considering the letters `G` to `W`, it's non-sense.

That would be a very good idea to add a Test Method for the case `TEST_X` here:
https://github.com/abap2xlsx/abap2xlsx/blob/1fe298d5bebc01982d90efeef37b14e46a4eb7d3/src/zcl_excel_reader_2007.clas.testclasses.abap#L27-L55
