### ISSUE TITLE
How to insert blank row in Excel template using ABAP2XLSX

### ISSUE THREAD

**Issue by sky5685610** [abap2xlsx/abap2xlsx#1129]
Is it possible to insert blank row in Excel template using ABAP2XLSX, is there any demos to refer to?

**Comment by sandraros** [comment]
Probably, but I don't get what is the issue of inserting a "blank" (or even "non blank") row. What do you mean exactly?

**Comment by sky5685610** [comment]
![image](https://github.com/abap2xlsx/abap2xlsx/assets/123931755/d2435eea-f1d3-43ba-94f6-19e4ca0bf870)
For example, In order to keep the whole style, I want to insert a new row in line 28 in the screenshot above.

**Comment by sandraros** [comment]
To insert lines, you may use the template feature of abap2xlsx, which gives the possibility to insert rows:
- https://blogs.sap.com/2020/05/22/best-way-to-generate-microsoft-excel-xlsx-from-template-in-abap/
  - (the author has merged the feature into abap2xlsx)
- demo: [zdemo_excel_fill_template](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel_fill_template.prog.abap)
- initial PR: https://github.com/abap2xlsx/abap2xlsx/pull/669

**Comment by sky5685610** [comment]
![image](https://github.com/abap2xlsx/abap2xlsx/assets/123931755/0c5a3b95-3411-4846-b6e0-378adbccdee4)
hi

If I create a new excel template, It's null for "mt_range", what's difference for the excel template?

**Comment by sandraros** [comment]
If I run the demo program above, with the default options, `mt_range` is filled:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/4f5c38cc-d535-4ba8-9d68-0b801013fc89)
Please clarify your question.
I suggest that you read the blog post and view the video which explains how it works.

**Comment by sky5685610** [comment]
hi

It's ok now, I found there're something different in the Excel Template, thanks

**Comment by sandraros** [comment]
Thanks for the feedback!

**Comment by hamida-ashna** [comment]
> ![image](https://private-user-images.githubusercontent.com/123931755/257971234-d2435eea-f1d3-43ba-94f6-19e4ca0bf870.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTg5MzAsIm5iZiI6MTcwMTUxODYzMCwicGF0aCI6Ii8xMjM5MzE3NTUvMjU3OTcxMjM0LWQyNDM1ZWVhLWYxZDMtNDNiYS05NGY2LTE5ZTRjYTBiZjg3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxMjAzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTQ2MGExYTg0NmRlNDQyOTQxNDY0NDdlMzBmYmI1OGFkMWVjYmFmYzk4ZjYyYmRiMjM1MzYwODI3NGI5MDRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vTAMLOz9-bB6qxxiKmcGaTPAAms0Zku9nwINH1demME) For example, In order to keep the whole style, I want to insert a new row in line 28 in the screenshot above.


@sky5685610,
Can you please tell me how you did it?
I also want to write data to an existing Excel file, in order to keep the whole style of that file.

**Comment by sky5685610** [comment]
hi

you need to config something in excel template

![image](https://github.com/abap2xlsx/abap2xlsx/assets/123931755/db604d74-6383-4066-802a-705aa7a33928)

the coding is shown as below:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/123931755/07e21391-1513-461f-8640-f50e93d12887)
![image](https://github.com/abap2xlsx/abap2xlsx/assets/123931755/96970617-8586-402d-949a-8c4bff90dc81)
![image](https://github.com/abap2xlsx/abap2xlsx/assets/123931755/e9526b62-35a0-4442-9a52-d23034fe379e)

**Comment by hamida-ashna** [comment]
Ok, thanks

**Comment by sandraros** [comment]
Hi please paste code as text, not as image.
```abap
TYPES: BEGIN OF ty_item1,
         bukrs  TYPE cosp-bukrs,
         period TYPE c LENGTH 6,
         type   TYPE c LENGTH 2,
         zcost1 TYPE cosp-wkg001,
         zcost2 TYPE cosp-wkg001,
         zcost3 TYPE cosp-wkg001,
         zpurc1 TYPE cosp-wkg001,
         zditt1 TYPE cosp-wkg001,
         zratel TYPE p LENGTH 8  DECIMALS 4,
         zrate2 TYPE p LENGTH 8  DECIMALS 4,
         zrate3 TYPE p LENGTH 8  DECIMALS 4,
       END OF ty_item1,
       lt_item1 TYPE STANDARD TABLE OF ty_item1 WITH DEFAULT KEY,
       lt_item2 TYPE STANDARD TABLE OF ty_item1 WITH DEFAULT KEY,
       BEGIN OF ty_sheet1,
         uname TYPE sy-uname,
         date  TYPE sy-datum,
         time  TYPE sy-uzeit,
         iteml TYPE lt_item1,
         item2 TYPE lt_item1,
       END OF ty_sheet1.
DATA lt_item1  TYPE TABLE OF ty_item1.
DATA lt_item2  TYPE TABLE OF ty_item1.
DATA ls_iteml  TYPE ty_item1.
DATA ls_sheet1 TYPE ty_sheet1.

SELECT *
    INTO CORRESPONDING FIELDS OF TABLE lt_item1
    FROM zco06001
    WHERE blikrs = '6000' AND
    type = '01'.
SELECT *
    INTO CORRESPONDING FIELDS OF TABLE lt_item2
    FROM zco06001
    WHERE blikrs = '6000' AND
    type = '02'.
ls_sheet1-uname = sy-uname.
ls_sheet1-date  = sy-datum.
ls_sheet1-time  = sy-uzeit.
ls_sheet1-iteml = lt_item1.
ls_sheet1-item2 = lt_item2.
" prepare data
lo_data = NEW #( ).
lo_data->add( iv_sheet = 'Sheetl' iv_data = ls_sheet1 ).
" create reader
lo_reader = NEW zcl_excel_reader_2007( ).
lo_reader->load_tile( p_fpath ).
" merge data With template
lo_excel->fill_template( lo_data ).
```

**Comment by AiolosYang** [comment]
expert, thanks for your contribution.
the demo is working fine, but i found another issue. the column height was not copied. 
sees below.

template 
![image](https://github.com/user-attachments/assets/16d53754-fd35-4e79-9260-56d47e09e234)

result
![image](https://github.com/user-attachments/assets/8e3efe03-7466-4c91-9d4a-9c76511cd704)

your response is appriciated.

**Comment by sandraros** [comment]
@AiolosYang Please post a new issue and I'll answer. Thank you.
