### ISSUE TITLE
Autosize of Columns not working with Excel365 

### ISSUE THREAD

**Issue by tk-am501** [abap2xlsx/abap2xlsx#1136]
Hey guys,

I just installed the great project and got some problems with downloading the excel-file and autosizing.
If I set a column with the parameter "autosize = abap_true" the size doesn´t change. I got the same problem like the others.

For example I set the column "P" with autosize and the column is nearly not visible.
![image](https://github.com/abap2xlsx/abap2xlsx/assets/138573610/a5826eb1-dc3e-4da9-b01f-2868ac2d0242)

greets and thanks

**Comment by tk-am501** [comment]
![image](https://github.com/abap2xlsx/abap2xlsx/assets/138573610/d3c12139-0ffa-46b4-b9c1-db1c8211256d)
 my coding and the files from Report 30 and 31.
[31_AutosizeWithDifferentFontSizes.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/12470583/31_AutosizeWithDifferentFontSizes.xlsx)
[30_CellDataTypes.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/12470584/30_CellDataTypes.xlsx)

**Comment by sandraros** [comment]
Hello, thank you. It can work only as described in #646 (also referred by #1095). Could you test this solution please?

**Comment by tk-am501** [comment]
> Hello, thank you. It can work only as described in #646 (also referred by #1095). Could you test this solution please?

Hello, thanks I tried a little bit and it worked for me after the Method "BIND_TABLE". 
My coding:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/138573610/808b8ee9-ee63-46bb-a29a-a67388804b92)

After I did this it worked for me :) it seems like the method won´t work unless the table has been binded before.
