### ISSUE TITLE
abap2xlsx license: unchanged original "Copyright {yyyy} {name of copyright owner}"

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#1153]
I guess this should be changed:

https://github.com/abap2xlsx/abap2xlsx/blob/ccda3a0aa8ea4dbcabd8e7be46848af1849ab71e/LICENSE#L186-L191

**Should we change it to the below proposal?**
```
Copyright 2010 abap2xlsx Contributors
```
- "abap2xlsx Contributors" same as in https://github.com/abapGit/abapGit/blob/main/LICENSE
- The year comes from the creation of the original blog post (https://blogs.sap.com/2010/07/12/abap2xlsx-generate-your-professional-excel-spreadsheet-from-abap/)

**Comment by larshp** [comment]
yes, I think so
