### ISSUE TITLE
(new functionality) Bind Table by Header row (its content). Option to download also Technical fieldnames.

### ISSUE THREAD

**Issue by vkostas** [abap2xlsx/abap2xlsx#1161]
Don't know if this request was ever discussed.
Parsing excel content to table by column index (col.1 -> first field, col.2 -> 2nd, etc.) is nice but once you need to change the order of the columns in Excel, all is ruined.
I would like to bind the Excel columns by their header content, which can be the label or Technical name.

It would be nice to have an option to:
* Download (also) technical fieldnames in header section. 4 mode in total. 1) Label only (as-is), 2) Technical fieldname only, 3) Label + Technical, 4) Technical + Label (reverse of 3),
* Bind the table based on 1) column index (as-is), 2) Technical fieldnames row or 3) Label row.

I understand upload excel files are filled based on a template. However Excel column sequence does not follow always the the internal table one (e.g. hidden fields, auxiliary excel columns).
Any thoughts?

**Comment by sandraros** [comment]
Thanks for the proposal.

abap2xlsx has already many methods which are utilities built over the main methods of abap2xlsx (e.g. ALV, OLE, MIME).

But I personally think that abap2xlsx should only propose the minimal API to read and write an Excel file, anything based on this API should be an add-on e.g. another Git repository. Of course, abap2xlsx could propose a link to all these utilities.

I don't mean your idea is not worth developing, utilities can be very helpful. It's just my vision of what abap2xlsx should be (should have been).

**Comment by vkostas** [comment]
I created this thread since current abap2xlsx is useless in the upload for the case reported. In fact parsing by column index is too restrictive (I call it "beta version" from design point of view).
SAP provides some excel classes which help to parse the header row first and then parse all content vs header row. Reinventing the wheel, but that's the way it is.
I could create a push request in the future just to help but it looks "this functionality won't be endorsed in the abap2xlsx no matter what", since we live in a democreatic (dictatorship) world.

**Comment by sandraros** [comment]
I don't get your point. I'm not the owner of abap2xlsx, it's just my point of view. The other guys working on abap2xlsx may think differently.

Concerning your proposal, it's quite easy to do it on top of abap2xlsx, no need to use something else than just abap2xlsx. And so, having a utility to do that could be reused by other people.

**Comment by vkostas** [comment]
Sorry, I don't know who owns abap2xlsx nor how feasible it is to convince the owner(s) about a new feature request.
Could you give some hints how this reusable tool would interact with abap2xlsx?
Do you mean, it parses the header row and then creates an intermediary dynamic itab from the header row?

**Comment by gregorwolf** [comment]
I support @sandraros suggestion to keep that functionality separate from the core abap2xlsx functionality. Maybe @vkostas you can start with a sample in https://github.com/abap2xlsx/demos.

**Comment by vkostas** [comment]
@gregorwolf,
It's not clear what do you expect from me on the sample (demo).
Current solution for the problem reported is simple: skip abap2xlsx functionality, reinvent the wheel and do not bother with abap2xlsx in this case.
So adding a demo for something not using abap2xlsx seems odd.
Maybe you can give some hint (I asked the same @sandraros without any feedback yet) how abap2xlsx could be used here?

**Comment by sandraros** [comment]
You have the demo programs to help you. You have the following members of `zcl_excel_worksheet`: `sheet_content`, `get_cell`, `get_table`, `get_tables_iterator`, etc.
