### ISSUE TITLE
Excel Removed Records: Document Theme from /xl/workbook.xml part (Workbook) SAP_BASIS 701

### ISSUE THREAD

**Issue by Jimboken** [abap2xlsx/abap2xlsx#1172]
When generating excel from ZDEMO_EXCEL3 for example, Excel issues a message that it found a problem with some content in the xlsx.

Allowing recovering generates the spreadsheet with the repair summarised "Removed Records: Document Theme from /xl/workbook.xml part (Workbook)"

<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<logFileName>error142280_01.xml</logFileName>
<summary>Errors were detected in file 'C:\Users\A911ND\AppData\Local\Temp\~SAP{81A877B8-2148-476E-8FF8-31E1497F870C}.xlsx'</summary>
<removedRecords>
<removedRecord>Removed Records: Document Theme from /xl/workbook.xml part (Workbook)</removedRecord>
</removedRecords>
</recoveryLog>

I also notice that the dates are not formatted as dates but as a general excel value (e.g. 43962 instead of 11/05/2020),

Thanks for any help.

**Comment by sandraros** [comment]
I propose that you start a discussion for anything related to 7.01 (and older versions) because abap2xlsx is supported only from 7.02, I'll try to help you if I have some time.

I close this issue, please post a new discussion.
