### ISSUE TITLE
Making Date as blank instead of '00.00.0000' in CSV export

### ISSUE THREAD

**Issue by aditya-deloitte** [abap2xlsx/abap2xlsx#1187]
Hi team,
When using `ZCL_EXCEL_WRITER_CSV` (with latest changes), date when blank is displayed as 00.00.0000 in AL11 CSV file. 
Is there any way to make the date blank? 

**Edit**:
For the time being in my system, I changed the following code in method CREATE_CSV (LINE 152) of class [`ZCL_EXCEL_WRITER_CSV`](https://github.com/abap2xlsx/abap2xlsx/blob/242a3d4e43041a92146080f94ca11d82550317ee/src/zcl_excel_writer_csv.clas.abap#L219-L242):
```abap
CASE <fs_sheet_content>-data_type.

        WHEN 'd' OR 'D'.
          If <fs_sheet_content>-cell_value IS NOT INITIAL. **Added by me
            lc_value = zcl_excel_common=>excel_string_to_date( ip_value = <fs_sheet_content>-cell_value ).
            TRY.
                lv_date = lc_value.
                CALL FUNCTION 'CONVERT_DATE_TO_EXTERNAL'
                  EXPORTING
                    date_internal            = lv_date
                  IMPORTING
                    date_external            = lv_tmp
                  EXCEPTIONS
                    date_internal_is_invalid = 1
                    OTHERS                   = 2.
                IF sy-subrc = 0.
                  lc_value = lv_tmp.
                ENDIF.

              CATCH cx_sy_conversion_no_number.

            ENDTRY.
       ENDIF.
` 
```

I understand it may not work for all because some may want to display date as _00.00.0000_.
Maybe we can add a flag to toggle whether to display or make it blank.

**Comment by sandraros** [comment]
Thanks for the information. Do you mind proposing a pull request? I suggest to create a method [like others for setting CSV options](https://github.com/abap2xlsx/abap2xlsx/blob/242a3d4e43041a92146080f94ca11d82550317ee/src/zcl_excel_writer_csv.clas.abap#L12-L20), with "00.00.0000" as default, and adapt the CSV demo program for options [`zdemo_excel28`](https://github.com/abap2xlsx/demos/blob/d3b82106f41cf5bd04a8967d62ab33585e96ccd7/src/zdemo_excel28.prog.abap#L63-L70) to demonstrate the new method.

**Comment by aditya-deloitte** [comment]
Hi Sandra,
I have created a pull request:
https://github.com/abap2xlsx/abap2xlsx/pull/1190

**Comment by aditya-deloitte** [comment]
I have also created pull request for ZDEMO_EXCEL28. 
https://github.com/abap2xlsx/demos/pull/53

**Comment by sandraros** [comment]
Thanks very much for your help! PR slightly modified and merged. If it works as you expect, please close the issue.

**Comment by aditya-deloitte** [comment]
Hi Sandra,
Thanks for accepting my pull requests.
Though, I have one doubt regarding this [modification](https://github.com/abap2xlsx/demos/blob/e9b8f04322348e89931be9cff11394f1d5dc409b/src/zdemo_excel28.prog.abap#L58) because both this line of code and the [one before it](https://github.com/abap2xlsx/demos/blob/e9b8f04322348e89931be9cff11394f1d5dc409b/src/zdemo_excel28.prog.abap#L57) produces the same output.
Maybe you meant to replace the previous line?

**Comment by sandraros** [comment]
I guess the use case is one variable (second line below), not one space (first line below).

https://github.com/abap2xlsx/demos/blob/e9b8f04322348e89931be9cff11394f1d5dc409b/src/zdemo_excel28.prog.abap#L57-L58
```abap
  lo_worksheet->set_cell( ip_column = 'B' ip_row = 4 ip_value = space ip_abap_type = 'D' ).
  lo_worksheet->set_cell( ip_column = 'C' ip_row = 4 ip_value = c_initial_date ).
```

To simplify, would you mind deleting the first line of code?

**Comment by aditya-deloitte** [comment]
Hi Sandra,
I have created pull request https://github.com/abap2xlsx/demos/pull/58

**Comment by sandraros** [comment]
Thanks, merged!

**Comment by aditya-deloitte** [comment]
Thank you, Sandra, for your help!
Closing the issue.
