### ISSUE TITLE
Sometimes values of referenced Filed are empty

### ISSUE THREAD

**Issue by ReinholdMr** [abap2xlsx/abap2xlsx#1192]
I have an application in which I import parts lists. There are 2 fields in it that are referenced from other fields. In some cases, the field content of the referenced fields is empty.
Example file:
When I import the fields B7 and B8, the field contents are empty. 
[SAP_Stueckliste_UMIXP22.3.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/14296880/SAP_Stueckliste_UMIXP22.3.xlsx)

- B7 formula: `=F21&G21`
- B8 formula: `=H21`

**Comment by sandraros** [comment]
abap2xlsx doesn't interpret the formulas, it can only read the stored values. The issue was first posted in #575 . There is no solution apart either store the value if it's known, or develop a brand new feature to calculate the formulas...
