### ISSUE TITLE
CX_SY_CONVERSION_NO_NUMBER because of conversion exit EXCRT

### ISSUE THREAD

**Issue by fst-at** [abap2xlsx/abap2xlsx#1194]
Hello,

conversion exit EXCRT as it is used e. g. in domain KURSF (Exchange rate) may cause a CX_SY_CONVERSION_NO_NUMBER due to the conversion of let's say 10.22 to /10.22 which later on cannot be correctly assigned to a variable of technical type p.

I think, there might be conversion exits with similar undesired side effects. 

In our system I patched this as follows which I would like to provide as a suggestion for a general solution:

**Class: ZCL_EXCEL_WORKSHEET**

*Private instance attribute:* IGNORED_CONVEXITS 
*Typ:* STRING
*Description:* ;-separated list of conversion exits to be ignored
*Initial value:* ''

<u>Private Section</u>:

```ABAP
methods CONVEXIT_IS_IGNORED                 “ Checks if a conversion exit has to be ignored
 importing
  !IP_CONVEXIT type CONVEXIT default SPACE  “ Conversion exit to be checked
 returning
  value(R_IGNORE) type ABAP_BOOL .          “ TRUE: Ignore conversion exit
```

```ABAP
METHOD convexit_is_ignored.

 IF ip_convexit = space.
  RETURN.
 ENDIF.
 IF find( val = ignored_convexits sub = ip_convexit ) <> -1.
  r_ignore = abap_true.
 ENDIF.

ENDMETHOD.
```

<u>Public Section:</u>

```ABAP
methods SET_IGNORED_CONVEXITS           “ Set list of conversion exits that should be ignored
 importing
  !IP_IGNORE type STRING default SPACE . “ List of conversion exits to be ignored

METHOD set_ignored_convexits.

 ignored_convexits = ip_ignore.

ENDMETHOD.
```

<u>Change Method GET_VALUE_TYPE:</u>

```  ABAP
*   IF ls_dfies-convexit IS NOT INITIAL.  <-- DEL
    IF ls_dfies-convexit IS NOT INITIAL AND convexit_is_ignored( ls_dfies-convexit ) = abap_false. "<-- INS
 \* We need to convert with output conversion function
     CONCATENATE 'CONVERSION_EXIT_' ls_dfies-convexit '_OUTPUT' INTO l_function.
```

**Comment by darnoc312** [comment]
Hello Franz,

Try to set parameter ip_conv_exit_length of zcl_excel_worksheets' method set_cell or bind_table as described in ZDEMO_EXCEL49.
This should provide a character type value for get_value_type's ep_value parameter to host your conversion output.

Bernd

**Comment by fst-at** [comment]
Hello, Bernd,

I see I will have to update the repository of ZDEMO*-reports... Delivering a character type should solve the problem but I would prefer to remain the numeric character of the original value.

Franz

**Comment by sandraros** [comment]
Could you provide an example how to reproduce the error? I'm thinking of one Excel file and one minimal program.

**Comment by fst-at** [comment]
Hello, 

here is a short demo report and a screenshot of the debugging session:

``` ABAP
REPORT zabap2xlsx_error_demo.

DATA: BEGIN OF gs_demo,
        hwaer   TYPE waers,
        ex_rate TYPE kursf,
      END OF gs_demo,
      gt_demo LIKE STANDARD TABLE OF gs_demo.

START-OF-SELECTION.
  APPEND VALUE #( hwaer   = 'EUR'
                  ex_rate = '12-' ) TO gt_demo.
  DATA(go_excel) = NEW zcl_excel( ).
  DATA(go_worksheet) = go_excel->add_new_worksheet( ip_title = 'Demo' ).
  DATA(gt_field_catalog) = zcl_excel_common=>get_fieldcatalog( ip_table = gt_demo ).
  go_worksheet->bind_table( ip_table         = gt_demo
                            it_field_catalog = gt_field_catalog ).
```
![image](https://github.com/abap2xlsx/abap2xlsx/assets/5331383/5cbf141c-8422-4d27-bd67-3471d02ae727)

Kind regards,

Franz

**Comment by darnoc312** [comment]
Hello Franz,

the current code at this point in method get_value_type should look like this:
(lines 3226 to 3240 of current zcl_excel_worksheet)

```abap
            CALL FUNCTION l_function
              EXPORTING
                input  = ip_value
              IMPORTING
                output = l_value
              EXCEPTIONS
                OTHERS = 1.
            IF sy-subrc <> 0.
            ELSE.
              TRY.
                  ep_value = l_value.
                CATCH cx_root.
                  ep_value = ip_value.
              ENDTRY.
            ENDIF.
```

Then this exception will be avoided.

Bernd

**Comment by fst-at** [comment]
Hello, Bernd,

thanks a lot. I see that upgrading to the latest version is required - and of course the official solution is much more efficient than mine.

Franz
