### ISSUE TITLE
CONVT_NO_NUMBER in ZCL_EXCEL_READER_2007=>LOAD_WORKSHEET

### ISSUE THREAD

**Issue by dkle-1** [abap2xlsx/abap2xlsx#1203]
Hi all,

we are getting above short dump trying to load the following XLSX-file:
[Planlieferzeit_MPE_03.2024.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/14942276/Planlieferzeit_MPE_03.2024.xlsx)
We are on SAP_BASIS 758.

LS_COLUMN-HIDDEN is a CString and has value 'false', this is why LOAD_WORKSHEET dumps in line 532:
![grafik](https://github.com/abap2xlsx/abap2xlsx/assets/15609772/1f282e01-4816-4982-a4d7-c25bd16bbd93)

I assume `IF ls_column-hidden = 1` is obsolete, as LS_COLUMN-HIDDEN can only be 'true' or 'false' or ''.

Thanks and Regards
Daniel

**Comment by sandraros** [comment]
Thank you. It's clear that comparing a string and a number is incorrect (`1` should be changed into `'1'`). I didn't check, but adding `'true'` to the test makes sense. The test with `'1'` should not be removed as the situation may still happen.

https://github.com/abap2xlsx/abap2xlsx/blob/35425c3220b82644fd998c2a501001cb54fad3f3/src/zcl_excel_reader_2007.clas.abap#L2779-L2783

If possible, could you propose a pull request? Thank you.

**Comment by dkle-1** [comment]
Hi @sandraros,
sorry, we don't use git/github on a daily basis, therefore I am not able to create the pull request.
Best Regards
Daniel

**Comment by sandraros** [comment]
No issue, thanks, I'll take care of it.

Reproduced. To reproduce:

1. Run `zdemo_excel37` to download or display the Excel file above.
2. Short dump happens.

**Comment by dkle-1** [comment]
Ich kehre zurück am 10.05.2024.

Vertretung in dringenden Fällen: Nils Höhl

Mit freundlichen Grüßen
Schukat IT
Daniel Klein


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [abap2xlsx/abap2xlsx]
CONVT_NO_NUMBER in ZCL_EXCEL_READER_2007=>LOAD_WORKSHEET (Issue #1203)" gesendet am 27.04.2024
12:14:50.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by sandraros** [comment]
@ all , ignore the message above, it's an automatic absence message (in German)

**Comment by dkle-1** [comment]
Ich kehre zurück am 10.05.2024.

Vertretung in dringenden Fällen: Nils Höhl

Mit freundlichen Grüßen
Schukat IT
Daniel Klein


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [abap2xlsx/abap2xlsx]
CONVT_NO_NUMBER in ZCL_EXCEL_READER_2007=>LOAD_WORKSHEET (Issue #1203)" gesendet am 28.04.2024
09:48:49.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.
