### ISSUE TITLE
Position drawing in middle of a cell

### ISSUE THREAD

**Issue by oadaid5** [abap2xlsx/abap2xlsx#1212]
hi folks,
is there a way to set_position for drawing in the middle of cell ?

**Comment by sandraros** [comment]
Hi, you may define a little shift. I just added an example how it works in `ZDEMO_EXCEL16`:
https://github.com/abap2xlsx/demos/blob/0ed3c2e8102892bc6f33d31d3b48c258b639c1af/src/zdemo_excel16.prog.abap#L128-L131
  ```abap
  lo_drawing->set_position( ip_from_row = 3
                            ip_from_col = 'B'
                            ip_rowoff   = 85725    " optional little shift
                            ip_coloff   = 47625 ). " optional little shift
  ```
![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/b1d4877b-3659-4cd3-8092-b637dd7e0a2f)

**Comment by oadaid5** [comment]
Thanks

**Comment by oadaid5** [comment]
Thanks
