### ISSUE TITLE
Reading Smart Tables

### ISSUE THREAD

**Issue by DarTas1** [abap2xlsx/abap2xlsx#1213]
### Discussed in https://github.com/abap2xlsx/abap2xlsx/discussions/1211

<div type='discussions-op-text'>

<sup>Originally posted by **DarTas1** April 18, 2024</sup>
Hello,
looking for a way to read smart tables using abap2xlsx, but could not identify a way, since zcl_excel_reader loads the ZCL_EXCEL_WORKSHEET object without any information about tables. Tried to upload a generated version from ZDEMO_EXCEL3 and read it, but no info on the generated table was found in the runtime. Is there actually no possibility to read these tables from imported excel file or am I doing something wrong?
Code snippet with which I tried to check it:

```abap
SELECTION-SCREEN BEGIN OF BLOCK blx WITH FRAME.
PARAMETERS: p_upfile TYPE string LOWER CASE MEMORY ID gr8.
SELECTION-SCREEN END OF BLOCK blx.

DATA: excel          TYPE REF TO zcl_excel,
      reader         TYPE REF TO zif_excel_reader,
      worksheet      TYPE REF TO zcl_excel_worksheet,
      lt_files       TYPE filetable,
      lv_rc          TYPE i,
      lv_file_filter TYPE string.

lv_file_filter = 'Excel Files (*.XLSX;*.XLSM)|*.XLSX;*.XLSM'.
cl_gui_frontend_services=>file_open_dialog( EXPORTING
                                              default_filename        = p_upfile
                                              file_filter             = lv_file_filter
                                            CHANGING
                                              file_table              = lt_files
                                              rc                      = lv_rc
                                            EXCEPTIONS
                                              OTHERS                  = 1 ).
READ TABLE lt_files INDEX 1 INTO p_upfile.

CREATE OBJECT reader TYPE zcl_excel_reader_2007.
excel = reader->load_file( i_filename = p_upfile ).

worksheet = excel->get_active_worksheet( ).

write: 'size of tables ', worksheet->get_tables_size( ).
```

Result is always 0
![image](https://github.com/abap2xlsx/abap2xlsx/assets/75167233/a86c9477-70b5-4eeb-a057-d646f2fea633)
Used the file:
[generated table.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/15024862/generated.table.xlsx)

BR,
Dartas1</div>

**Comment by darnoc312** [comment]
Hello,
are you using an ABAP2XLSX with the changes of pull request #1159 ? If you do not this is always the result.
In according issue #1158 the same symptom was described.

**Comment by sandraros** [comment]
@darnoc312 Thanks, I couldn't find it.

**Comment by sandraros** [comment]
@DarTas1 Sorry to [mislead](https://github.com/abap2xlsx/abap2xlsx/discussions/1211) you, in fact this issue was already fixed, as @darnoc312 said. Is it okay to close this issue?

**Comment by DarTas1** [comment]
I have pulled the latest version of the project. The example code indeed shows the count correctly, but inside no information on values of the cells.

**Comment by sandraros** [comment]
@DarTas1 Currently your question refers to the old issue which is solved. If I understand well your point about "no information on values of the cells", it doesn't refer to a bug but to a feature request like creating a kind of `get_data` public method in the class `zcl_excel_table`. Remember that the attribute `table_data` of `zcl_excel_table` is private.

**Comment by DarTas1** [comment]
table data attribute contains found cells, but the values, even though they should contain something, are empty.
![image](https://github.com/abap2xlsx/abap2xlsx/assets/75167233/584e62ab-a126-45e6-923c-548937a92425)
is the one im trying to read.
In debugger looks very promising. (except for name which is not there)
![image](https://github.com/abap2xlsx/abap2xlsx/assets/75167233/47a5bb13-14dc-4f33-9468-be11dac9985f)
but sadly no values
![image](https://github.com/abap2xlsx/abap2xlsx/assets/75167233/dc283431-18da-4982-8712-ea81fbad3df8)

**Comment by sandraros** [comment]
Yes exactly. But I told you that this attribute is PRIVATE, it's internal, you can't use it in your ABAP code, it's not intended to be used.
So, again, it's not a bug, it's a feature request like creating a kind of `get_data` (public method) in the class `zcl_excel_table`.
I just want you to confirm, thank you.

NB: just to clarify what is in my mind, in the solution, I want the attribute to remain private and empty, only the method `get_data` would be able to fill your own internal table (not `table_data`).

**Comment by DarTas1** [comment]
thanks for clarification. then it is all good ;)
