### ISSUE TITLE
Using abap2xlsx to read Excel with Excel open

### ISSUE THREAD

**Issue by WoWFrostmourne** [abap2xlsx/abap2xlsx#1216]
I understand this is not an ideal question, but we have indeed encountered such a scenario. 
The customer wishes to access the content within an Excel file while it is still open.
Could you inform me if abap2xlsx currently supports this scenario? If not, are there plans to support this in the future?

Thanks a lot！

**Comment by sandraros** [comment]
Maybe it's not a question concerning abap2xlsx itself but about reading a locked file from the frontend (`cl_gui_frontend_services`) each time abap2xlsx needs it. I solved it by copying the file to a temporary folder, read the file copy and load to abap2xlsx via the method `zif_excel_reader_2007~load` of `zcl_excel_reader_2007`.

**Comment by WoWFrostmourne** [comment]
Hello!
Thank you very much for sandaros reply. 
Copying temporary files may be a good idea.
But I consider copying files, reading files, and deleting files, which may lead to unnecessary waste of system resources.

Reading Excel with Excel open is indeed not an issue with abap2xlsx,
When abap2xlsx reads Excel, it also calls cl_gui_frontend_services=>gui_upload for implementation.
I still want to try again, can I read open Excel in a format similar to C #.

Lastly, thank you very much

**Comment by sandraros** [comment]
It's a waste but anyway it's a limitation of `cl_gui_frontend_services` so no other solution according to me.

I consider that abap2xlsx should have never managed all user interface stuff like `cl_gui_frontend_services`, OLE and so on, so I'm personally not fan of "enhancing" the method `load_file` of `zcl_excel_reader_2007`, but I don't know the opinion of the other project people.

**Comment by WoWFrostmourne** [comment]
Thank you for your prompt response. I concur with your perspective that the "enhanced" approach is not preferable. 
As for the topic of "Using abap2xlsx to read Excel with Excel open", I believe it can be temporarily closed. 
If we find a good method in the future, I will share it with everyone.
﻿
I appreciate your input, sandraros. This was my inaugural attempt at initiating discussions and addressing issues within the community, and it has been a truly enriching experience.
Lastly, I ask for forgiveness regarding any shortcomings in my English proficiency.

**Comment by sandraros** [comment]
Closing temporarily then, thank you.
