### ISSUE TITLE
UTCLONG type (ABAP 7.54) not supported

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#1252]
The UTCLONG data type was added in ABAP 7.54 ([reference](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abennews-754-types.htm)) but is not supported by abap2xlsx.

The below program does a short dump because the method [`set_cell`](https://github.com/abap2xlsx/abap2xlsx/blob/48db7f0b1b737d71a9e6ed2c9c1d45487df4f6af/src/zcl_excel_worksheet.clas.abap#L3994) of the class `zcl_excel_worksheet` generates an exception with the text `Invalid data type of input value`:
```abap
REPORT.
DATA(lo_excel) = NEW zcl_excel( ).
DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
data(utclong) = utclong_current( ).
lo_worksheet->set_cell( ip_columnrow = 'A1' ip_value = utclong ).
DATA(lo_writer) = CAST zif_excel_writer( NEW zcl_excel_writer_2007( ) ).
DATA(xstring) = lo_writer->write_file( lo_excel ).
```

**Comment by gregorwolf** [comment]
What do you think: Should we expect that the user uses [WRITE, TO](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapwrite_to.htm) or this is implemented inside [set_cell](https://github.com/abap2xlsx/abap2xlsx/blob/48db7f0b1b737d71a9e6ed2c9c1d45487df4f6af/src/zcl_excel_worksheet.clas.abap#L3994)?

**Comment by sandraros** [comment]
The issue also happens with `bind_table` (which calls `set_cell`).

So, I guess it should be fixed inside `set_cell`, like the `INT8` type.
