### ISSUE TITLE
Column autosizing not working on worksheet with fieldcatalog table

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#132]
Hi,

First I am using ABAP2XLSX release 6.0 

I am creating a workbook with two worksheets (summary/detail). The first one does not include a table and I am able to determine the column width myself using :

<pre><code>  go_column_dimension = go_worksheet->get_column_dimension( 'A' ).
  go_column_dimension->set_width( ip_width = '11').
</code></pre>

On the second worksheet, I present a detail view of Z DB table. First, is it normal the table columns are not auto-sized? Secondly, I am not able to auto_size the column after I the Bind_table with the active worksheet.  As an information I would like to be able to set a frame around my account summary from A1:J23?

<pre><code>  gt_field_catalog = zcl_excel_common=>get_fieldcatalog( ip_table = gt_inv_dtl_sel ).

  gs_table_settings-table_style      = zcl_excel_table=>builtinstyle_light1.
  gs_table_settings-show_row_stripes = abap_true.
  gs_table_settings-top_left_column  = 'A'.
  gs_table_settings-top_left_row     = '1'.

* Add table to worksheet
  go_worksheet->bind_table( ip_table          = gt_inv_dtl_sel
                            is_table_settings = gs_table_settings
                            it_field_catalog  = gt_field_catalog ).

* Adjust Columns Dimension 
  CLEAR: l_lines.
  DESCRIBE TABLE gt_field_catalog LINES l_lines.

  DO l_lines TIMES.

*    Table containing column names: A, B, C... AA, AB
    READ TABLE gt_column_names INDEX sy-index.

    IF sy-subrc NE 0. " Max Column reached
      EXIT.
    ENDIF.

    go_column_dimension = go_worksheet->get_column_dimension( gt_column_names ).
    go_column_dimension->set_auto_size( ip_auto_size = abap_true ).
  ENDDO.
</code></pre>

**Comment by ivanfemia** [comment]
[[file:agxcOsqHqr4BxveJe8ay1r]]: Latest version of the file

**Comment by ivanfemia** [comment]
I can set manually the each column width of the table using command:

```
go_column_dimension->set_width( ip_width = '15' ).
```

but I would rather be able to use _set_auto_size_ instead of fixing myself the width for each one.

**Comment by ivanfemia** [comment]
Updating issues (#174, #31, #71, #134, #137, #141, #155, #156, #170, #176, #179, #180, #182)

**Comment by ivanfemia** [comment]
[[file:cv8h1gdcKr473dacwqjQYw]]
Latest version of the file

**Comment by ivanfemia** [comment]
[[file:cBqPNsdcKr473dacwqjQYw]]
Collective Bill

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Closed because no objections have arisen.
