### ISSUE TITLE
With a large number of lines in a worksheet data validations get removed

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#139]
It was reported to me that with a large number of lines (> 8000) the data validations get removed. I will first extend the demo report ZDEMO_EXCEL9 to optionally output the SBOOK table including data validations.

**Comment by ivanfemia** [comment]
Updating issues (#174, #31, #71, #134, #137, #141, #155, #156, #170, #176, #179, #180, #182)

**Comment by StefanSchmoecker** [comment]
Closed.
Data validation has changed significantly during the last years - and we have a newer discussion with topic #366
