### ISSUE TITLE
Auto filter for single columns

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#140]
I am still working on/with the converter and I would realy appriciate the possibility to add to the writer the possibility of autofilter for specific columns.
Are there any plans to add this or is there at leastn interest for it?

**Comment by ivanfemia** [comment]
Hi
I have created now 2 new objects: zcl_excel_autofilter and zcl_excel_autofilters.
In addtion I propose two new methods to ZCL_EXCEL:
Add_new_autofilter and get_autofilters_reference

In addtion I would propose to change the writer ZCL_EXCEL_WRITER_2007 to add changes to the method create_XL_workbook 

<pre><code>
    lo_sub_element->set_value( value = lv_value ).
    lo_element->append_child( new_child = lo_sub_element ). " range node
  endwhile.
  lo_autofilters = excel->get_autofilters_reference( ).
  if lo_autofilters->is_empty( ) = abap_false.
    lo_iterator = excel->get_worksheets_iterator( ).
    while lo_iterator->if_object_collection_iterator~has_next( ) eq abap_true.
      lo_worksheet ?= lo_iterator->if_object_collection_iterator~get_next( ).
      lv_syindex = sy-index - 1 .
      l_guid = lo_worksheet->get_guid( ).
      lo_autofilter = lo_autofilters->get( i_sheet_guid = l_guid ) .
      if lo_autofilter is bound.
        lo_sub_element = lo_document->create_simple_element_ns( name   = lc_xml_node_definedname
                                                                parent = lo_document ).
        lv_value = lo_autofilters->c_autofilter.
        lo_sub_element->set_attribute_ns( name  = lc_xml_attr_name
                                          value = lv_value ).
        lv_value = lv_syindex.
        condense lv_value no-gaps.
        lo_sub_element->set_attribute_ns( name  = lc_xml_attr_localsheetid
                                          value = lv_value ).
        lv_value = '1'. " Always hidden
        lo_sub_element->set_attribute_ns( name  = lc_xml_attr_hidden
                                          value = lv_value ).
        lv_value = lo_autofilter->get_data_reference( ).
        lo_sub_element->set_value( value = lv_value ).
        lo_element->append_child( new_child = lo_sub_element ). " range node
      endif.
    endwhile.
  endif.
</code></pre>

 and 3 changes to CREATE_XL_SHEET:

<pre><code>
  " sheetData node
  lo_element = lo_document->create_simple_element( name   = lc_xml_node_sheetdata
                                                   parent = lo_document ).
  " Get column count
  col_count      = io_worksheet->get_highest_column( ).
  " Get autofilter
  l_guid         = io_worksheet->get_guid( ) .
  lo_autofilters = excel->get_autofilters_reference( ).
  lo_autofilter  = lo_autofilters->get( i_sheet_guid = l_guid ) .
  lt_values      = lo_autofilter->get_values( ) .
  ls_area        = lo_autofilter->get_data_area( ) .
  loop at io_worksheet->sheet_content assigning <ls_sheet_content>.
    if lo_autofilter is bound.
      l_autofilter_hidden = abap_true. " First defautl is not showing
      read table lt_values into ls_values with key column = <ls_sheet_content>-cell_column.
      if ( sy-subrc = 0 and ls_values-value = <ls_sheet_content>-cell_value ) or
        ls_area-row_start >=  <ls_sheet_content>-cell_row or " One less for header
        ls_area-row_end   < <ls_sheet_content>-cell_row .
        clear l_autofilter_hidden.
      endif.
    else.
      clear l_autofilter_hidden.
    endif.
</code></pre>

and again:

<pre><code>
      " Do we need the row dimension attributes?
      if row_dimension->get_row_height( )   >= 0 or
         row_dimension->get_visible( )       = abap_false or
         row_dimension->get_collapsed( )     = abap_true or
         row_dimension->get_outline_level( ) > 0 or
         row_dimension->get_xf_index( )     <> 0 or
         l_autofilter_hidden = abap_true.
        " Row dimensions
        if row_dimension->get_row_height( ) >= 0.
          lo_element_2->set_attribute_ns( name  = 'customHeight' value = '1').
          lv_value = row_dimension->get_row_height( ).
          lo_element_2->set_attribute_ns( name  = 'ht' value = lv_value ).
        endif.
        " Row visibility
        if row_dimension->get_visible( ) = abap_false or
           l_autofilter_hidden = abap_true.
          lo_element_2->set_attribute_ns( name  = 'hidden' value = 'true').
        endif.
</code></pre>

and again: 

<pre><code>
 lo_element_root->append_child( new_child = lo_element ). " sheetData node
  create_autofilter_node( io_root        = lo_element_root   " autofilter node
                                            io_document    = lo_document
                                            io_autofilter  = lo_autofilter ) .
  if io_worksheet->zif_excel_sheet_protection~protected eq abap_true.
</code></pre>

If you agree with the proposed changes, than I create a demo program and make the changes.
Thanks
Rene

**Comment by ivanfemia** [comment]
Rene,

thanks for this enhancement...
I will wait for your commit in order to include it in the latest daily build.

Thanks again
Ivan

**Comment by ivanfemia** [comment]
Hi
The changes have been implemented a bit different as I found a few more problems with it.
Both updates of today need each other  ( Converter and autofilter ( example ) )
Let me know what you think.
Rene

**Comment by ivanfemia** [comment]
When adding support to repeated rows/columns of a worksheet I detected some problems with autofilters, since both topics are related in so far as they use named ranges with limited visibility to one sheet.

The following topics came up:
- There seems to be no option to create a filter that isn't filtering anything but just exists for the user to select what to filter.
- There seems to be a problem in the writer in deciding which rows are visible.  If you use Demoreport 33 and extend the filter to a second column, the filtersymbol will be visible, the correct value will be ticked but the affected rows won't be made unvisible.
- The autofilterclass has an attribute that holds the filtervalues.  When adding another value to be filtered there is a "delete adjacent duplicates" but it is not  assured, that the entries in the table are ordered.  

<pre><code>  ...
lo_worksheet->get_cell( EXPORTING
                             ip_column    = 'C'
                             ip_row       = 5
                          IMPORTING
                             ep_value     = l_cell_value ).
  lo_autofilter->set_value( i_column = 3
                            i_value  = l_cell_value ).
</code></pre>Additional 2nd column to be filtered<pre><code>  lo_worksheet->get_cell( EXPORTING
                             ip_column    = 'D'
                             ip_row       = 5
                          IMPORTING
                             ep_value     = l_cell_value ).
  lo_autofilter->set_value( i_column = 4
                            i_value  = l_cell_value ).
</code></pre>

**Comment by StefanSchmoecker** [comment]
I close this topic since we have a newer discussion with issue #368
