### ISSUE TITLE
Setting row height does not work if row is empty

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#154]
Setting row height does not work if row is empty.  If at least one cell is set ( I tried before adjusting rowheight ) it works all right.

**Comment by ivanfemia** [comment]
Updating issues (#174, #31, #71, #134, #137, #141, #155, #156, #170, #176, #179, #180, #182)

**Comment by StefanSchmoecker** [comment]
Fixed with commit revision 403
