### ISSUE TITLE
Run time issue with new style changes

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#171]
The new solution for the styles is creating performance issues with method GET_STYLE_TO_GUID in ZCL_EXCEL
The code:

<pre><code>
  " # issue 139

  READ TABLE me->t_stylemapping2 INTO ep_stylemapping WITH TABLE KEY guid = ip_guid.
  IF sy-subrc <> 0.
    RAISE EXCEPTION TYPE zcx_excel
      EXPORTING
        error = 'GUID not found'.
  ENDIF.

  IF ep_stylemapping-dynamic_style_guid IS NOT INITIAL.
    zcl_excel_common=>recursive_class_to_struct( EXPORTING i_source = ep_stylemapping-cl_style
                                                 CHANGING  e_target =  ep_stylemapping-complete_style
                                                           e_targetx = ep_stylemapping-complete_stylex ).
  ENDIF.
</code></pre>

The calls ( almost 2,000,000 ) to method recursive_class_to_struct with a 5000 lines excel spreadsheet and 65 columns takes more than 20% of the runtime (Creation takes more than a minute).
I am not sure why this has happens like this, but we need to reconsider and find a better solution.

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Closed because no objections have arisen.
