### ISSUE TITLE
Ability To Add Cell Comments!

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#180]
Hi,

I don't see anyway in the latest build to be able to add cell comments. If this feature is already available then could you please tell me how to set it or else could you please add this feature to this project.

I myself would be more than glad to assist towards this project (however mostly ABAP) if required!

Thanks,
SG

**Comment by ivanfemia** [comment]
Updating issues (#174, #31, #71, #134, #137, #141, #155, #156, #170, #176, #179, #180, #182)

**Comment by ivanfemia** [comment]
Hello SG,

this topic is older then one year.  Are you still willing to assist here?
Participating isn't really that difficult and mostly ABAP-knowledge is ok I guess.

**Comment by StefanSchmoecker** [comment]
Topic is older than 2 years regarding Ivan's last comment and adding cell comments is not quite as easy as one would think at first glance.

--> Closed

**Comment by guillaumegarcia13** [comment]
Hi,

I have been working on this and it is a bit tedious as you have to create the comment but also a drawing to host this comment.
I have a first implementation (only for WRITER_2007) that I have to clean before pushing it as a pull request.

Best regards,
Guillaume

**Comment by ivanfemia** [comment]
I reopen the issue so you can reference this

**Comment by guillaumegarcia13** [comment]
Done!
Proposed pull request #418

**Comment by fidley** [comment]
Hello @guillaumegarcia13 , 
I see it's hanging since long time but there are conflicts and this pull request cannot be merged automatically. Can attached your version of a2x here or at least point the changes in writer and main class so I can retrieve it from your pull request and include to the project?

Thanks 
Łukasz

**Comment by guillaumegarcia13** [comment]
Hi @fidley,
SAP and I are on a break. I decided to move on to new (startup, Web) adventures.
Sorry I can't help you further with this...
Best regards,
Guillaume

**Comment by sandraros** [comment]
As we say in French, a lot of water flowed under the bridge... Comments work (`ZDEMO_EXCEL_COMMENTS`). I propose to close this issue. If needed, please open a new issue.
