### ISSUE TITLE
Read page layout info from worksheet

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#190]
In ZCL_EXCEL_WORKSHEET=>LOAD_WORKSHEET, I've provided code to read most of the page layout information:
- page margins
- page setup
- footer info

<pre><code>
  " Read in page margins
  pagemargins_elem = worksheet->find_from_name( 'pageMargins' ).
  if pagemargins_elem is not initial.
    fill_struct_from_attributes( exporting ip_element = pagemargins_elem changing cp_structure = pagemargins ).
    io_worksheet->sheet_setup->margin_bottom = pagemargins-bottom.
    io_worksheet->sheet_setup->margin_footer = pagemargins-footer.
    io_worksheet->sheet_setup->margin_header = pagemargins-header.
    io_worksheet->sheet_setup->margin_left = pagemargins-left.
    io_worksheet->sheet_setup->margin_right = pagemargins-right.
    io_worksheet->sheet_setup->margin_top = pagemargins-top.
  endif.

  " Read in page setup
  pagesetup_elem = worksheet->find_from_name( 'pageSetup' ).
  if pagesetup_elem is not initial.
    fill_struct_from_attributes( exporting ip_element = pagesetup_elem changing cp_structure = pagesetup ).
    io_worksheet->sheet_setup->orientation = pagesetup-orientation.
    io_worksheet->sheet_setup->scale = pagesetup-scale.
  endif.

  " Read header footer
  headerfooter_elem = worksheet->find_from_name( 'headerFooter' ).
  if headerfooter_elem is not initial.
    fill_struct_from_attributes( exporting ip_element = headerfooter_elem changing cp_structure = headerfooter ).
    io_worksheet->sheet_setup->diff_oddeven_headerfooter = headerfooter-differentoddeven.

    hf_value_elem = headerfooter_elem->find_from_name( 'oddFooter' ).
    if hf_value_elem is not initial.
      odd_footer-left_value = hf_value_elem->get_value( ).
    endif.

    " TODO.. get the rest.

    io_worksheet->sheet_setup->set_header_footer(
                  ip_odd_header   = odd_header
                  ip_odd_footer   = odd_footer
                  ip_even_header  = even_header
                  ip_even_footer  = even_footer ).

  endif.
</code></pre>

**Comment by ivanfemia** [comment]
Why is this still at "new"?
I checked the class ZCL_EXCEL_READER_2007 and found the implementation there.

**Comment by ivanfemia** [comment]
Half a year has gone by.  Still in status "new".  Whoever commited these changes - PLEASE set this to "ready to test" or at least leave a comment why that isn't feasable.

**Comment by ivanfemia** [comment]
I submitted the update (see Attachments), but I do not have access to commit the changes myself.  I am interested in supporting this project more if given the authorization to do so.

**Comment by ivanfemia** [comment]
[[file:cKfLv2dcKr473dacwqjQYw]]

**Comment by StefanSchmoecker** [comment]
No need to keep this open.
I have seen it works for pagemargins and assume the rest will do as well.
Close....
