### ISSUE TITLE
Write row dimension even when no sheet content exists

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#195]
Discovered that a row in my template workbook was not being carried into my result workbook in the case that the row contains no data.  Here is a correction...

<pre><code>
                                                            "v #197
  " #197 Write row dimension even when no sheet content exists
  LOOP AT row_dimensions ASSIGNING <row_dimension>.
    READ TABLE io_worksheet->sheet_content TRANSPORTING NO FIELDS
          WITH KEY cell_row = <row_dimension>-row.
    " if no cell content
    IF sy-subrc NE 0.
      " Add new row
      lo_element_2 = lo_document->create_simple_element( name   = lc_xml_node_row
                                                         parent = lo_document ).
      " r
      lv_value = <row_dimension>-row.
      SHIFT lv_value RIGHT DELETING TRAILING space.
      SHIFT lv_value LEFT DELETING LEADING space.

      lo_element_2->set_attribute_ns( name  = lc_xml_attr_r
                                      value = lv_value ).
      " Spans
      lv_value = col_count.
      CONCATENATE '1:' lv_value INTO lv_value.
      SHIFT lv_value RIGHT DELETING TRAILING space.
      SHIFT lv_value LEFT DELETING LEADING space.
      lo_element_2->set_attribute_ns( name  = lc_xml_attr_spans
                                      value = lv_value ).
      row_dimension = io_worksheet->get_row_dimension( <ls_sheet_content>-cell_row ).
      " Do we need the row dimension attributes?
      IF row_dimension->get_row_height( )   >= 0 OR
         row_dimension->get_collapsed( )     = abap_true OR
         row_dimension->get_outline_level( ) > 0 OR
         row_dimension->get_xf_index( )     <> 0 OR
         l_autofilter_hidden = abap_true.
        " Row dimensions
        IF row_dimension->get_row_height( ) >= 0.
          lo_element_2->set_attribute_ns( name  = 'customHeight' value = '1').
          lv_value = row_dimension->get_row_height( ).
          lo_element_2->set_attribute_ns( name  = 'ht' value = lv_value ).
        ENDIF.
        " Collapsed
        IF row_dimension->get_collapsed( ) = abap_true.
          lo_element_2->set_attribute_ns( name  = 'collapsed' value = 'true').
        ENDIF.
        " Outline level
        IF row_dimension->get_outline_level( ) > 0.
          lv_value = row_dimension->get_outline_level( ).
          SHIFT lv_value RIGHT DELETING TRAILING space.
          SHIFT lv_value LEFT DELETING LEADING space.
          lo_element_2->set_attribute_ns( name  = 'outlineLevel' value = lv_value ).
        ENDIF.
        " Style
        IF row_dimension->get_xf_index( ) <> 0.
          lv_value = row_dimension->get_xf_index( ).
          lo_element_2->set_attribute_ns( name  = 's' value = lv_value ).
          lo_element_2->set_attribute_ns( name  = 'customFormat'  value = '1').
        ENDIF.
      ENDIF.
      l_autofilter_hidden = abap_true. " First default is not showing

      lo_element->append_child( new_child = lo_element_2 ). " row node
    ENDIF.
  ENDLOOP.                                                  "^ #197
</code></pre>

Placed right before...

<pre><code>
  lo_element_root->append_child( new_child = lo_element ). " sheetData node
</code></pre>

**Comment by StefanSchmoecker** [comment]
Fixed with commit revision 403 I guess
