### ISSUE TITLE
Dump MEM_ALLOC_FAILED when creating bigger excel files

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#196]
Hello,
when creating bigger xlsx files the system dumps in method IF_IXML_DOCUMENT~CREATE_SIMPLE_ELEMENT because of insufficient allocated memory. In one example we try to create an excel with 2 sheets, the first has about 30 colums and 135 lines, the second has 135 colums and 17500 lines. Our system administration allocated already 4 GB memory to each user and is not able to allocate more.
So our question is if it would be possible to create bigger excels in a different way, may be to split the creation into smaller parts?

Regards,
Wolfgang

Short Dump Extract:

<pre><code>Runtime Errors         MEM_ALLOC_FAILED
Date and Time          23.07.2012 19:24:38
-
----
-
----

|Short text |
|    Internally required memory is not available                                                   |
-
----
-
----

|What happened? |
|    Resource bottleneck                                                                           |
| |
|    The current program "CL_IXML=======================CP" had to be terminated                   |
|     because |
|    a capacity limit has been reached.                                                            |
-
----
-
----

|System environment                                                                                |
|    SAP-Release 701                                                                               |
| |
|    Application server... "sapgp1f0405"                                                           |
|    Network address...... "10.164.41.190"                                                         |
|    Operating system..... "Windows NT"                                                            |
|    Release.............. "5.2"                                                                   |
|    Hardware type........ "16x AMD64 Level"                                                       |
|    Character length.... 16 Bits                                                                  |
|    Pointer length....... 64 Bits                                                                 |
|    Work process number.. 1                                                                       |
|    Shortdump setting.... "full"                                                                  |
| |
|    Database server... "SAPGP1F0405"                                                              |
|    Database type..... "ORACLE"                                                                   |
|    Database name..... "GQC"                                                                      |
|    Database user ID.. "SAPSR3"                                                                   |
| |
|    Terminal.......... "10.164.42.119"                                                            |
| |
|    Char.set.... "C"                                                                              |
| |
|    SAP kernel....... 701                                                                         |
|    created (date)... "Apr 4 2011 00:05:43"                                                       |
|    create on........ "NT 5.2 3790 Service Pack 2 x86 MS VC++ 14.00"                              |
|    Database version. "OCI_10201_SHARE (11.2.0.2.0) "                                             |
| |
|    Patch level. 137                                                                              |
|    Patch text.. " "                                                                              |
| |
|    Database............. "ORACLE 10.1.0.*.*, ORACLE 10.2.0.*.*, ORACLE 11.2.*.*.*"               |
|    SAP database version. 701                                                                     |
|    Operating system..... "Windows NT 5.0, Windows NT 5.1, Windows NT 5.2, Windows                |
|     NT 6.0, Windows NT 6.1"                                                                      |
| |
|    Memory consumption                                                                            |
|    Roll.... 2718352                                                                              |
|    EM...... 2003319376                                                                           |
|    Heap.... 2000016464                                                                           |
|    Page.... 319488                                                                               |
|    MM Used. 4000330928                                                                           |
|    MM Free. 128 |
-
----
-
----

|User and Transaction                                                                              |
|    Client.............. 101                                                                      |
|    User................ ""                                                               |
|    Language Key........ "D"                                                                      |
|    Transaction......... " "                                                                      |
|    Transactions ID..... "38E7D4E1B30DF13DB0A600237DCF281A"                                       |
| |
|    Program............. "CL_IXML=======================CP"                                       | 
|    Screen.............. "SAPMHTTP 0010"                                                          | 
|    Screen Line......... 2                                                                        | 
| | 
|    Information on Caller ofr "HTTP" Connection:                                                  | 
|    Plug-in Type.......... "HTTP"                                                                 | 
|    Caller IP............. "10.164.42.119"                                                        | 
|    Caller Port........... 8030                                                                   | 
|    Universal Resource Id. "/sap/bc/bsp/sap/crm_ui_frame/BSPWDApplication.do"                     |
-
----
-
----

|Information on where terminated                                                                   |
|    Termination occurred in the ABAP program "CL_IXML=======================CP" -                 | 
|     in "IF_IXML_DOCUMENT~CREATE_SIMPLE_ELEMENT".                                                 | 
|    The main program was "SAPMHTTP ".                                                             | 
| | 
|    In the source code you have the termination point in line 691                                 | 
|    of the (Include) program "BCCIIXML_LCLI".                                                     |
-
----
-
----

|Source Code Extract                                                                               |
-
----

|Line |SourceCde |
-
----

|  661|    method if_ixml_document~get_document_type                                               | 
|  662|       by kernel module abkm_iXMLDocument_GetDocumentType.                                  | 
|  663|    endmethod.                                                                              | 
|  664| | 
|  665|    method if_ixml_document~set_document_type                                               |
|  666|       by kernel module abkm_iXMLDocument_SetDocumentType.                                  |
|  667|    endmethod.                                                                              |
|  668| |
|  669|    method if_ixml_document~get_elements_by_tag_name                                        | 
|  670|       by kernel module abkm_iXMLDocument_GetElementsByTagName.                             | 
|  671|    endmethod.                                                                              | 
|  672| | 
|  673|    method if_ixml_document~get_elements_by_tag_name_ns                                     | 
|  674|       by kernel module abkm_iXMLDocument_GetElementsByTagNameNS.                           | 
|  675|    endmethod.                                                                              | 
|  676| | 
|  677|    method if_ixml_document~create_document_type                                            | 
|  678|       by kernel module abkm_iXMLDocument_CreateDocumentType.                               | 
|  679|    endmethod.                                                                              | 
|  680| | 
|  681|    method if_ixml_document~create_element                                                  |
|  682|       by kernel module abkm_iXMLDocument_CreateElement.                                    |
|  683|    endmethod.                                                                              |
|  684| |
|  685|    method if_ixml_document~create_element_ns                                               | 
|  686|       by kernel module abkm_iXMLDocument_CreateElementNS.                                  | 
|  687|    endmethod.                                                                              | 
|  688| | 
|  689|    method if_ixml_document~create_simple_element                                           |
|  690|       by kernel module abkm_iXMLDocument_CreateSimpleElement.                              |
|>>>>>|    endmethod.                                                                              |
|  692| |
|  693|    method if_ixml_document~create_simple_element_ns                                        | 
|  694|       by kernel module abkm_iXMLDocument_CreateSimpleElementNS.                            | 
|  695|    endmethod.                                                                              | 
|  696| | 
|  697|    method if_ixml_document~create_document_fragment                                        |
|  698|       by kernel module abkm_iXMLDocument_CreateDocumentFragment.                           |
|  699|    endmethod.                                                                              |
|  700| |
|  701|    method if_ixml_document~create_text                                                     | 
|  702|       by kernel module abkm_iXMLDocument_CreateText.                                       | 
|  703|    endmethod.                                                                              | 
|  704| | 
|  705|    method if_ixml_document~create_comment                                                  | 
|  706|       by kernel module abkm_iXMLDocument_CreateComment.                                    | 
|  707|    endmethod.                                                                              | 
|  708| | 
|  709|    method if_ixml_document~create_cdata_section                                            | 
|  710|       by kernel module abkm_iXMLDocument_CreateCDATASection.                               |
-
----</code></pre>

**Comment by ivanfemia** [comment]
Sorry, I posted the issue in the wrong area, this is not really an error.

**Comment by ivanfemia** [comment]
Well... We've encountered the same issue during the same operation. We had 1 worksheet with 22k records, 150 fields, 4 header rows with merged cells, styles for header and data (for data there were only 4 styles: general, text, date and currency). Maybe, the issue should be reopened in order to optimize performance? Or is there nothing to do?

**Comment by ivanfemia** [comment]
Hello,
to be able to allocate more memory, we changed the program execution to a background job. Now there are about 20 GB available. The excel limitation is now 17k record and 600 fields. But this is more a workaround than a good solution.
Sap note 1229110 describes the problem and gives some solution proposals. One suggests to optimize the coding to save memory.
I think it would be a good idea to optomize the performance.
Best regards
Wolfgang

**Comment by ivanfemia** [comment]
S0000848528, we got dump when running a background job. The report based on an organization structure and personnel data ran quite slowly, so to avoid dumps by time-out we executed it in background. We had 'only' 150 columns but more than 20k records. Probably, our server had more limited memory per BG job than yours, that's why the report crashed.

**Comment by ivanfemia** [comment]
Performance issue can be discussed not as an issue.
I suggest to open a discussion and propose some ideas.
Currently abap2xlsx generates the excel first in memory and the on file system.

**Comment by rotda** [comment]
@ivanfemia we have the same problem at ~10.000 we get the dump. Can you tell me or give me hint which is right kernel parameter to change ?

**Comment by ivanfemia** [comment]
For big files, you need to use the huge file writer. It has less functionalities, but it works perfectly.

**Comment by rotda** [comment]
Hi thx . can this also *.xlsm ?

**Comment by ivanfemia** [comment]
no just xlsx.
