### ISSUE TITLE
Method ZCL_EXCEL_WRITER_XLSM->CREATE has syntax errors

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#203]
Causes after implementation of fix for [[url:https://code.sdn.sap.com/spaces/abap2xlsx/tickets/188-read-and-write-chart-data-in-abap2xlsx|#188]]

**Comment by ivanfemia** [comment]
(In [[r:329]]) Ready to test #205

**Comment by ivanfemia** [comment]
Hi Ivan

Could it be that you miss structure ZEXCEL_DRAWING_POSITION.
I could not find it in the trunk and I can not compile the latest updates?
Rene

**Comment by ivanfemia** [comment]
Missing object added

**Comment by ivanfemia** [comment]
Still erronous
<pre><code>**********************************************************************
- STEP 11: Add media
  lo_iterator = me->excel->get_drawings_iterator( ).
  </code></pre>the obligatory parameter "IP_TYPE" isn't passed.

**Comment by ivanfemia** [comment]
(In [[r:339]]) ready to test #205

**Comment by ivanfemia** [comment]
Installed complete project yesterday from scratch on a 7.00 system.  No more syntax errors in this class - compiles fine.
Demoreport 29 gives expected result.

--> fixed

**Comment by oliviermuff** [comment]
I just installed latest daily build and again got a syntax error.
Says that "exception ZCX_EXCEL is not intercepted nor declared in the 
RAISING clause of the "CREATE" method.

**Comment by ivanfemia** [comment]
Try to import the nugget twice.
Ivan

**Comment by oliviermuff** [comment]
Thanks Ivan.  I did import twice which did not solve it, but I found a solution that worked which Gregor suggested here:
https://sap.assembla.com/spaces/abap2xlsx/messages/3282273
Essentially: Go to edit mode and redefine the ZIF_EXCEL_WRITER~WRITE_FILE method of the class.
Best regards, Olivier

**Comment by oliviermuff** [comment]
Dear Ivan,

 

Is there an open discussion board for ABAP2XLSX ?

It seems the links run you round in circles from Assembla to GitHub to SAP CW which is also closed.

 

Thanks for the help,

Olivier

 

 

Gesendet: Dienstag, 03. Juni 2014 um 16:47 Uhr
Von: Ivan notifications@github.com
An: ivanfemia/abap2xlsx abap2xlsx@noreply.github.com
Cc: Olivier olimu@gmx.net
Betreff: Re: [abap2xlsx] Method ZCL_EXCEL_WRITER_XLSM->CREATE has syntax errors (#203)

Try to import the nugget twice.
Ivan

**Comment by ivanfemia** [comment]
Hi Olivier,

you can use SCN open source space and the tag [abap2xlsx] in the subject of the thread

http://scn.sap.com/community/open-source

Ivan
