### ISSUE TITLE
Custom formatting is not preserved when loading the XLSX-template

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#205]
After loading an original XLSX-template and outputting it back - even with no data - the original formatting is lost. Particularly, fonts and number formats are not preserved.

In the attached template the whole worksheet is formatted with TrebuchetMS font, size 9; columns filled with the light-orange color are formatted as currency, 2 decimal places, no currency symbol.

After outputting the file with ZCL_EXCEL_WRITER_2007, all cells are formatted with the default Calibri font, size 9 for the header, size 11 for the data. Number formats are set to General for all the columns mentioned above.

**Comment by ivanfemia** [comment]
[[file:dvAUa8aqqr4O-5eJe8ay1r]]: Template with custom formatting (font, number formatting, wordwrapping)

**Comment by ivanfemia** [comment]
Can we close this and add it to issue #194?

**Comment by ivanfemia** [comment]
I think it's possible. However, issue #194 has to be renamed to avoid confusing when searching through the bug tracker.

**Comment by ivanfemia** [comment]
Currently reader doesn't support all excel features...

**Comment by ivanfemia** [comment]
(In [[r:340]]) Ready to test #193 #194 #207
Thanks to Vladimir Scheglov

**Comment by ivanfemia** [comment]
Hi Ivan,

There is no problem with usupported features. There are problems with features claimed to be supported. For instance, number format IDs are numbered starting with sy-tabix + 163, though Excel makes references in a different way. In my templates I used date formatting for several columns, and currency formatting - 2 adjusted number formats in total. According to the OpenXML specification, date format is country dependent. So, Excel saved it with number format ID 43 (predefined format). Currency format had ID 164 (custom format).

However, loader class overrided date format because of its predefined ID. Moreover, writer class rendered resulting file incorrectly giving format IDs starting with 165 (date format - 165, currency format - 166), because the lowest possible custom format ID was occupied. At the same time, all cells referred to format IDs 43 and 164, which led to an inconsistent file.

I couldn't dig deeper but I hope that my analysis and file sets I attached would help someone to fix this bug. If I find something that can help in this work, I will definitely share the results.

**Comment by ivanfemia** [comment]
I passed the latest file from Vladimir through the reader and then back out through the writer.  The result is a file that excel claims to have unreadable content.
 Repair log:

<pre><code>
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<logFileName>error021200_01.xml</logFileName><summary>Fehler in Datei 'C:\temp\Passthrough.xlsx'</summary>
-<removedRecords summary="Folgende DatensÃ¤tze wurden entfernt:">
<removedRecord>Entfernte DatensÃ¤tze: Benannter Bereich von /xl/workbook.xml-Part (Arbeitsmappe)</removedRecord>
</removedRecords>
</recoveryLog>
</code></pre>

Outline was not preserved.
All content is unreadable ( but this might be me using an non-unicode system that is unable to handle russian letters )

Columns 36-39:  The output has cellborders  the original had not
Orange coloring in was ok , but again unexpected cellborderlines in all orange cells

**Comment by ivanfemia** [comment]
[[file:cuUMH-dcKr473dacwqjQYw]]
Original template with unsupported formatting

**Comment by ivanfemia** [comment]
[[file:cKu5igdcKr473dacwqjQYw]]
Template with custom formatting (font, number formatting, wordwrapping)

**Comment by StefanSchmoecker** [comment]
There have been some enhancements of the readerclass during the last 1.5 years.
Please retry if your problem still exists.

Topic should be closed if no answers appear in the next 2 or 3 months

**Comment by StefanSchmoecker** [comment]
Corrected with latest daily build + some final corrections today commited to svn-directory with revision 470
