### ISSUE TITLE
As I can remove the filter header?

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#209]
Hi,

I need to create an Excel file without the header, only the data of the table

Is that possible?

**Comment by ivanfemia** [comment]
AFAIK, with BIND_TABLE method you can't. SET_TABLE method does the work but it deals \with DD structures, so, if that's your case, use that method.

**Comment by ivanfemia** [comment]
I do not use at all the BIND_TABLE?

 currently I pass the contents of my table and field catalog with BIND_TABLE

 and so using the SET_TABLE, but I still get the header only without formatting

 I be doing wrong?

**Comment by ivanfemia** [comment]
I made it! It was just using the SET_TABLE and DD
 Thank you!

**Comment by spacy0212** [comment]
Can you give a sample code to solve this problem? I dont known how to use DD structure.
Thank you!
