### ISSUE TITLE
Pimp my code

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#228]
To allow easier collaboration we should have our code meet standards/conventions we are setting in the wiki( work in progress ) 
http://wiki.sdn.sap.com/wiki/display/ABAP/Code+convention

Many people collaborating --> many different opinions what the perfect code should look like.  Maybe we can come up with something we all like.
To start this process I used a (quite simple) method and took some time to rewrite it into a state I'd like to see a program in.
Of course personal preferences are used due to no real conventions/rules installed so far.

Please - use that method or this issue to comment on and/or enhance the method further.

Method used:   ZCL_EXCEL_READER->ZIF_EXCEL_READER~LOAD_FILE( )

Commit to SVN/Source: 360

**Comment by ivanfemia** [comment]
Wanted to continue with ZCL_EXCEL_READER_2007 and came about method ZIF_EXCEL_READER~CAN_READ_FILE.  What is this method good for since only the filename is passed?  Currently the coding is negligible and is method is referenced nowhere for good reasons.
Any objections to killing this method since we have an alternative in raising an exception in the "Load_File"-method?

**Comment by StefanSchmoecker** [comment]
Only a suggestion - no follow-up comments since way-back-when.
Closed.
