### ISSUE TITLE
Reader does not read drawings correctly

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#231]
The readerclass ZCL_EXCEL_READER_2007 seems to behave incorrectly when reading a file with drawings included.

Example:  
Use demoreport 16 to create an excelfile with some drawings.
Now use demoreport37 ( read excelfile and output to screen ) and an error "can't read excelfile" occurs

**Comment by yoavi2** [comment]
I have the same issue and do not seem to understand what background processing have to do with it.
I'd be happy for a more extensive explanation.

**Comment by StefanSchmoecker** [comment]
One of the latest commits has fixed the problem with the errormessage.
The output is still not what it should be though

**Comment by StefanSchmoecker** [comment]
Corrected with revision 463
