### ISSUE TITLE
Multiple problems with LibreOffice (read and write)

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#232]
Hi, maybe when I will find time myself, I will join this project and make some fixes, but now only shortly with most urgent problem:

according to OpenXML .XLSX specification (http://www.ecma-international.org/publications/standards/Ecma-376.htm) there is no exact need for attribute "customWidth" at element "col" to indicate other than standard width of column (attribute "width"). OO Calc programmers probably also understood it in this way, because Calc does not add "customWidth" attribute (MS Excel 2010 adds it, but can handle .xlsx correctly also without it). But ABAP2XLSX has in ZCL_EXCEL_READER_2007, method LOAD_WORKSHEET, at line 334 following coding:

_Â Â Â Â Â Â Â  IF column-customwidth = lc_xml_attr_true OR column-customwidth = lc_xml_attr_true_int. \ Â Â Â Â Â Â Â Â Â Â  column_dimension->set_width( column-width ). \ Â Â Â Â Â Â Â Â  ENDIF._

So it does not consider "width" attribute without "customWidth". This might be changed to:

_Â Â Â Â Â Â Â  IF column-customwidth = lc_xml_attr_true OR column-customwidth = lc_xml_attr_true_int OR column-width IS NOT INITIAL._

Also another issue -> this solution has problems with .XLSX in .zip other than .zip with "deflate" compression method. It is because of used class for decompression: CL_ABAP_ZIP. Maybe class CL_ABAP_GZIP would help in this case (but I have not tested it...)

Thanks and best regards
Peter\* \*

**Comment by ivanfemia** [comment]
Hello Peter,
please upload an excel-sheet that causes the problem in the reader.

**Comment by ivanfemia** [comment]
[[file:axI-GAlCyr4RBBeJe8ay1r]]: .xlsx created in LibreOffice Calc

**Comment by ivanfemia** [comment]
1st analysis from last night :  ZIP-Structure of the submitted file
I am not sure if the file submitted is not zipped using the DEFLATE-mechanism.  And I am surely no expert on ZIP-compression.  But looking at the basic documentation and a little debugging of the cl_abap_zip-class lets me assume that the approach SAP has implemented is somewhat optimistic about how a zip-directory should be set up.
From what I have seen so far the class tries to extract the filenames and location of the files contents in the zip-structure by reading the local file headers in sequence and hoping that the zip-algorithm correctly inserted length of filecontent into the local header. 
This does not have to be the case as the zip-documentation states ( and obviously the provided file is such an example ).  The correct way would be to read the Central directory file header and determine the filepositions/content from this.
Actually this is not an ABAP2XLSX-problem but an incorrect implementation of the ZIP-definition.  But since SAP didn't document the zip-class maybe it is what they really wanted to support.
Anyways - I might be able to copy this class and implement a different LOAD-method in such a way that it'll support these cases also.

**Comment by ivanfemia** [comment]
2nd analysis: ZIP-Structure of submitted file
The problem is definitly the incorrect implementation of SAP in cl_abap_zip->load method.  I have a local copy of this class with changed load-method and now I can read the file.  Have to think now how to put this into our classes though and then check the other topic about column width.

@Peter:  Unfortunately I can't produce such "bad files" you provided but I'd like to open an issue in OSS with such a file as example that the class isn't working right.  Do you mind sending to me ( or uploading)  another such file ( that does not work with the current reader ) but that is anonymized.

**Comment by ivanfemia** [comment]
Hi Stefan, here is another file. It is not so hard to produce it -> I just simply created .XLSX file in LibreOffice Writer (newest version - http://www.libreoffice.org/download/ ), then unpacked .xlsx (via 7-Zip, but I think any compression tool can be used), after repacked back into .xlsx using ZIP with Deflate method and here is the result: abap2xlsx_-_created_by_LO_Writer.xlsx

**Comment by ivanfemia** [comment]
[[file:cgTRxul_Wr4OOAeJe8ay1r]]

**Comment by ivanfemia** [comment]
(In [[r:364]]) #230 . Pimp my code:  Some methods in ZCL_EXCEL_READER_2007 have been normalized
set ready to test #234 : Various problems with files created by LibreOffice
set ready to test #186 : Seems to be integrated for some time already
set ready to test #194 : Reading state Hidden, Outlinelevel, Collapsed of rows and columns

**Comment by ivanfemia** [comment]
Hello Peter,

I didn't want to change the usage of the cl_abap_zip-class because for most users it seems to be ok.
The workaround for you and others who are experiencing problems with the zip-class, please find an additional (optional) parameter in the Reader->load method where you may specify to use thecopied and modified zip-class I just provided.  I'm going to contact SAP about the original zipclass - maybe they can be convinced to alter their current coding and I can get rid of this workaround in the future.  But this is a topic that does not belong into abap2xlsx.

Furthermore I used your coding to get the correct width of the columns - thank you for pointing out the correct spot to do this.

**Comment by ivanfemia** [comment]
Hello Peter,

looks like I came into conflicts with the terms of use by providing a solution based on patching the SAP-internal class CL_ABAP_ZIP.  Thus I had to remove it from our working directory.
To get this done correctly it would be necessary for us that SAP patches the class by themselves.  So it would be helpful if you open up an issue in the OSS about the incorrect ZIP-Class.  
I'll also open up an OSS-message sometime during this week with suggesting the patch I worked out.

If you look into the new demoreport 37 ( EXCEL-Reader ) you'll see a commented section in the code that shows how you could use your files from LibreOffice as well by using an alternate ZIP-Class as long as the original ZIP-Class isn't fixed. 
I still have to find out if/how it is possible to post what is necessary to get such a zip-alternative for your files to be read - but if need be just google my name (it is unique) and get in touch privatly

**Comment by ivanfemia** [comment]
Thank you Stefan for quick fix. When I will tomorrow find some time, I will open that OSS ticket. Thanks once more.

**Comment by ivanfemia** [comment]
Hello Peter,

I just checked the new file you submitted - and that can be read by our reader w/o any modifications.
What did you do to create the first file?  Did you unzip it, modify it and then rezip it?  If yes - which zip-program did you use?
I need an example of a "broken" but anonymized file.

**Comment by ivanfemia** [comment]
Hi, yes, I unziped it, and then rezip, using 7-Zip as I have mentioned above. Here is example of pure, non-reziped file: abap2xlsx_-_created_by_LO_Writer_2.xlsx

**Comment by ivanfemia** [comment]
[[file:acMX9MmJ8r4PrIeJe8ay1r]]

**Comment by ivanfemia** [comment]
Thank you Peter,

the last file was exactly what I needed to open an issue in the OSS

**Comment by ivanfemia** [comment]
Hello Peter,

it looks like this error in CL_ABAP_ZIP is already known by SAP and was fixed.
Please check OSS-note 1438754 .  It seems to solve the problem.

**Comment by ivanfemia** [comment]
[[file:cvwnPudcKr473dacwqjQYw]]

**Comment by ivanfemia** [comment]
[[file:cx9nAwdcKr473dacwqjQYw]]
.xlsx created in LibreOffice Calc

**Comment by ivanfemia** [comment]
[[file:cFop0qdcKr473dacwqjQYw]]

**Comment by rplantiko** [comment]
Is this still open? 
- Has the class `CL_ABAP_ZIP` been fixed in the meantime by SAP so that the example file could be read? 
- If not, could I have a look at a counter example?
- Any experiences with class `CL_OPENXML_ZIP` which seems to be a kind of corrected version of `CL_ABAP_ZIP` with the same public interface?

If this is done, we could throw away Stefan Schmöcker's workaround ("use alternate zip") in method `LOAD_FILE` and `LOAD` of `ZIF_EXCEL_READER` (and the code which belongs to it) to remain with a more readable code.

Regards,
Rüdiger
