### ISSUE TITLE
Extend parameters for bind_alv method

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#236]
Hello,
on my instalation i've added possibility to set if the bind_alv method will create spreadsheet with data binded as table or not. Currently it's always as table. I think this could be also a nice option for others.

To do that you need only to add parameter i_table (abap_bool) to bind_alv method and put in the implemetation during the call of converter.

BR
Åukasz

**Comment by StefanSchmoecker** [comment]
Has anybody considered this? 
I have problems identifying the method "bind_alv" and where to add this option.

If no one else is interested we might as well close this topic for now or reopen it if someone else requests it.
Or Lukasz might consider becoming a contributor and add this enhancement by himself.

If no one answers this in the next to weeks I'll close this issue which has been open and unanwered for 1.5 years.

**Comment by StefanSchmoecker** [comment]
No answers - closed.
