### ISSUE TITLE
bind_table method overrides styles

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#245]
Hi,

i set a style like

Â  style_arial20Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â  = lo_excel->add_new_style( ).\ Â  style_arial20->font->nameÂ Â Â Â Â  = zcl_excel_style_font=>c_name_arial.\ Â  style_arial20->font->schemeÂ  = zcl_excel_style_font=>c_scheme_none.\ Â  style_arial20->font->sizeÂ Â Â Â Â Â Â  = 20.\ Â  style_arial20_guidÂ Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â  = style_arial20->get_guid( ).

and set this as an default style. Afterrwards i bind a table for display with _worksheet->bind_table_.
The generated output does not reflect the style. The font is calibri (excel's standard) and not arial.
But all the untouched cells have the right style. Maybe the style is not delegated. I cannot find ystyle attributes in the table settings.

Regards, Stefan

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Closed because no objections have arisen.
