### ISSUE TITLE
Problem with autofilter

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#251]
Hello all,

i have problem with autofilter when i read and save following file via example program ZDEMO_EXCEL37:

[[url:http://monka.hysteria.cz/~chemik/bad.xlsx]]

Source file not contain autofilter, but after read and save autofilter is there. Problem is probably because we use wrong xml element for autofilter in workbook.xml:

<pre><code><definedNames>
  <definedName name="_xlnm._FilterDatabase" localSheetId="0" hidden="1">List1!$A$1:$B$1</definedName>
</definedNames> </code></pre>

the right element is in worksheetssheet1.xml:

<pre><code><autoFilter ref="A1:B1"/></code></pre>

problem can be solved by commented following code in ZCL_EXCEL_READER_2007->LOAD_WORKBOOK:

<pre><code>*--------------------------------------------------------------------*
* insert autofilters
*--------------------------------------------------------------------*
*          when zcl_excel_autofilters=>c_autofilter.
*            lo_autofilter = io_excel->add_new_autofilter( io_sheet = <worksheet>-worksheet ) .
*            zcl_excel_common=>convert_range2column_a_row( EXPORTING i_range        = lv_range_value
*                                                          IMPORTING e_column_start = lv_col_start_alpha
*                                                                    e_column_end   = lv_col_end_alpha
*                                                                    e_row_start    = ls_area-row_start ).
*            ls_area-col_start = zcl_excel_common=>convert_column2int( lv_col_start_alpha ).
*            ls_area-col_end   = zcl_excel_common=>convert_column2int( lv_col_end_alpha ).
*            lo_autofilter->set_filter_area( is_area = ls_area ).

and move this code with little modificaton into ZCL_EXCEL_READER_2007->LOAD_WORKSHEET.</code></pre>

**Comment by ivanfemia** [comment]
[[file:cZ4YIQAFCr4RJHeJe8ay1r]]: Source file

**Comment by ivanfemia** [comment]
[[file:cHlrTwdcKr473dacwqjQYw]]
Source file

**Comment by StefanSchmoecker** [comment]
This is one of the errors mentioned in issue #368.  ( hidden autofilter displaying when user reader_2007 )
I'll close this here for to have only one issue concerning various autofilter topicx
