### ISSUE TITLE
Error while using grid object and reuse_alv table.

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#252]
When we use alv object taken from reuse_alv_grid_display and we use color column in source table then due to fact that color field has different length than in OO ALV then in zcl_excel_converter_alv->get_color we got an error.Â  This can be corrected with following code :
https://cw.sdn.sap.com/cw/docs/DOC52403

**Comment by ivanfemia** [comment]
page is changing the link of the document. There should be "-1" between DOC and 52403

**Comment by ivanfemia** [comment]
p882987,

is this still an open issue with the current daily build of ABAP2XLSX?  
I am also not able to read the link you supplied ( insufficient rights ) - could you please upload your suggestion as an attachment to this thread?

**Comment by fidley** [comment]
Sorry that I come back so late but I totally forgot about this issue as I have corrected it directly on my instalation. I have no idea if in the new build it's still there or not cause I'm haven't install new version so far but here is the code I used:

method get_color.
  data: ls_con_col type zexcel_s_converter_col,
        ls_color   type ts_col_converter,
        l_line     type i,
        l_color(4) type c.
  field-symbols: <fs_tab> type standard table,
                 <fs_stab> type any,
                 <fs>      type any,
                 <fs_tcol>  type lvc_t_scol,
                 <fs_scol>  type lvc_s_scol,
                 <ft_slis> type standard table,
                 <fs_slis> type any.
- Loop trough the table to set the color properties of each line. The color properties field is
- Char 4 and the characters is set as follows:
- Char 1 = C = This is a color property
- Char 2 = 6 = Color code (1 - 7)
- Char 3 = Intensified on/of = 1 = on
- Char 4 = Inverse display = 0 = of
  
  assign io_table->\* to <fs_tab>.
  
  if ws_layo-info_fname is not initial or
     ws_layo-ctab_fname is not initial.
    loop at <fs_tab> assigning <fs_stab>.
      l_line = sy-tabix.
      if ws_layo-info_fname is not initial.
        assign component ws_layo-info_fname of structure <fs_stab> to <fs>.
        if sy-subrc = 0.
          if <fs> is not initial.
            l_color = <fs>.
            if l_color(1) = 'C'.
              read table wt_colors into ls_color with table key col = l_color+1(1)
                                                                int = l_color+2(1)
                                                                inv = l_color+3(1).
              if sy-subrc = 0.
                ls_con_col-rownumber  = l_line.
                ls_con_col-columnname = space.
                ls_con_col-fontcolor  = ls_color-fontcolor.
                ls_con_col-fillcolor  = ls_color-fillcolor.
                insert ls_con_col into table et_colors.
              endif.
            endif.
          endif.
        endif.
      endif.
      if ws_layo-ctab_fname is not initial.
  
  ```
    assign component ws_layo-ctab_fname of structure <fs_stab> to <ft_slis>.
    if sy-subrc = 0.
      loop at <ft_slis> assigning <fs_slis>.
        assign component 'COLOR' of structure <fs_slis> to <fs>.
        if sy-subrc = 0.
          if <fs> is not initial.
            field-symbols: <col> type any,
                           <int> type any,
                           <inv> type any,
                           <fname> type any,
                           <nokeycol> type any.
            assign component 'COL' of structure <fs> to <col>.
            assign component 'INT' of structure <fs> to <int>.
            assign component 'INV' of structure <fs> to <inv>.
            read table wt_colors into ls_color with table key col = <col>
                                                              int = <int>
                                                              inv = <inv>.
            if sy-subrc = 0.
              ls_con_col-rownumber  = l_line.
              assign component 'FNAME' of structure <fs_slis> to <fname>.
              if sy-subrc ne 0.
                assign component 'FIELDNAME' of structure <fs_slis> to <fname>.
                if sy-subrc eq 0.
                  ls_con_col-columnname = <fname>.
                endif.
              else.
                ls_con_col-columnname = <fname>.
              endif.
  
              ls_con_col-fontcolor  = ls_color-fontcolor.
              ls_con_col-fillcolor  = ls_color-fillcolor.
              assign component 'NOKEYCOL' of structure <fs_slis> to <nokeycol>.
              if sy-subrc eq 0.
                ls_con_col-nokeycol   = <nokeycol>.
              endif.
              insert ls_con_col into table et_colors.
            endif.
          endif.
        endif.
      endloop.
    endif.
  ```
  
  _--------------------------------------------------------------------_
- oryginal code
  _--------------------------------------------------------------------_
-        assign component ws_layo-ctab_fname of structure <fs_stab> to <fs_tcol>.
-        if sy-subrc = 0.
-          loop at <fs_tcol> assigning <fs_scol>.
-            read table wt_colors into ls_color with table key col = <fs_scol>-color-col
-            int = <fs_scol>-color-int
-            inv = <fs_scol>-color-inv.
-            if sy-subrc = 0.
-              ls_con_col-rownumber  = l_line.
-              ls_con_col-columnname = <fs_scol>-fname.
-              ls_con_col-fontcolor  = ls_color-fontcolor.
-              ls_con_col-fillcolor  = ls_color-fillcolor.
-              ls_con_col-nokeycol    = <fs_scol>-nokeycol.
-              insert ls_con_col into table et_colors.
-            endif.
-          endloop.
-        endif.
    endif.
  endloop.
  endif.
  endmethod.

**Comment by StefanSchmoecker** [comment]
1.5 year old issue, last commented one year ago with the original poster not knowing whether this has been fixed in the lates daily build or not.

I'll close this unless someone provides an example in 2 weeks.

**Comment by StefanSchmoecker** [comment]
No answers in 4 weeks --> Closed

**Comment by fidley** [comment]
Stefan, 
I was not able to check it before, sorry. The issue still remains in the latest version. I will change the code in next few days. Can you reopen the issue and assign me to the task?
