### ISSUE TITLE
Excel Reader: Error while reading file containing PDF object

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#253]
Hello,

I'm currently developping a Webdynpro application to upload xlsx files and next attach them in some DMS documents.
I need to read a defined sheet of each xlsx file to have some data which determine the DMS document.

It works fine until business decide to include some PDF files in another sheet.

Reader raises exception with error text "File not found inÂ  zip-archive".

Regards,
Christophe

_Abap2xlsx version 7.0_
_SAP 7.02 SP8_

**Comment by ivanfemia** [comment]
Good evening Christophe,

could you please upload a demo excelfile that demonstrates this error ( Tab attachments)?

**Comment by ivanfemia** [comment]
[[file:cZtSzOHlyr4PHheJe8ay1r]]: Sample of excel file with pdf inside

**Comment by ivanfemia** [comment]
hello,
sorry for the late reply, I was on vacation (and secretly I was hoping that the problem would be solved ^ ^).

I have added a sample of excel file with a pdf inside.

I also tried to upload this file with program ZDEMO_EXCEL37: same error occurs.

I found the program ROPENXML_LISTER (S_OOXML_CORE package) and it works. File is correctly analysed.

best regards
Christophe.

**Comment by ivanfemia** [comment]
Hello Christophe,

interesting case:  the error can be reproduced on my system as well.  
Looks like an embedded .pdf creates some binary data + a drawing - most likely the first page of the embedded pdf as a picture.
This is where the current error occurs - the method that tries to read a drawing looks for a certain file in the zip-archive that isn't existing for this kind implicitly created drawing.
I guess we need a fix for this - but I am not sure who is proficient of the layout of the zip-structure concerning drawings.

If you can provide a solution - please feel free to do so.

As a quick workaround I suggest you change method ZCL_EXCEL_READER_2007->LOAD_WORKSHEET_DRAWING and add a "TRY...CATCH"-block around the following line and exit this routine if the requested drawing is not encountered.

<pre><code>  rels_drawing = me->get_ixml_from_zip_archive( rels_drawing_path ).</code></pre>

  This is far from perfect - but I guess it might be enough to enable you to extract the other information in the excel-sheet.

**Comment by ivanfemia** [comment]
Hello Stephan,

A big thank you for the rapid correction of the bug. It is very useful to continue my project.

Unfortunately, I guess I can not help you. I discovered a xlsx file is a zip file with xml only a few weeks ago. :/
I have work to do to increase my knowledge at a sufficient level if I want to be useful on the project.

I think problem occurs for every object included in the excel file using "Insert-> Object-> from a file". It Creates OLE object in the file and _vmldrawing, drawing and embedding_ parts ... even for a picture. I checked it with ROPENXML_LISTER.
If the image is inserted using the menu "Insert-> Picture", it works fine.

What sould I do with this issue? 
Should I close it and you create it as more general enhancement in the dedicated section?

Christophe.

**Comment by ivanfemia** [comment]
Good evening Christophe,

let's leave this topic open since it isn't really resolved.   If we get another issue with embedded objects I'll reference that one to here and try to change this issues' topic.

**Comment by ivanfemia** [comment]
[[file:cHG5vedcKr473dacwqjQYw]]
Sample of excel file with pdf inside

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Reader doesn't dump any more - seems to have been corrected in the last 1.5 years.
