### ISSUE TITLE
ZCL_EXCEL -> GET_STATIC_CELLSTYLE_GUID -> GUID_CREATE is obsolete

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#270]
ZCL_EXCEL -> GET_STATIC_CELLSTYLE_GUID -> GUID_CREATE is flagged as obsolete
Is the alternative listed in this link a possible alternative? 
[[url:https://scn.sap.com/thread/1599893]]

**Comment by ivanfemia** [comment]
I have to verify class support across components

TRY. 
            CALL METHOD cl_system_uuid=>if_system_uuid_static~create_uuid_c32  " Create UUID 
              RECEIVING 
                uuid = lv_sysuuid_c32. 
          CATCH cx_uuid_error INTO lref_cx_uuid_error.                         " Catch Exceptions 
            lv_string = lref_cx_uuid_error->get_text( ). 
        ENDTRY.

**Comment by ivanfemia** [comment]
CL_SYSTEM_UUID is not available in all SAP 7.0x system
I'll put on hold the ticket in order to guarantee a back compatibility for a while

Note 935047 - Creating and using GUIDs (UUIDs)

**Comment by StefanSchmoecker** [comment]
This has been solved in the last months.
We have encapsulated GUID-Creation into an own class ( ZCL_EXCEL_OBSOLETE_FUNC_WRAP ) which will use the new class-based approach.
For older systems the activation of this class will fail but you'll find the alternative (function based approach ) in the coding + an explanation what to do.
