### ISSUE TITLE
Data Validation get lost when modifying Macro Excel Template

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#276]
Hi,

I got a macro excel template to modify. It contains validation data in several cells. 
However, when i read it and modifying it, the data validation are lost. 

<pre><code>

  DATA: lc_excel            TYPE REF TO zcl_excel,
        lci_excel_writer    TYPE REF TO zif_excel_writer,
        lci_reader          TYPE REF TO zif_excel_reader,
        lc_excel_exc        TYPE REF TO zcx_excel,
        lw_file             TYPE xstring,
        lc_exception        TYPE REF TO cx_root,
        lw_error            TYPE string.

 CREATE OBJECT lci_reader TYPE zcl_excel_reader_xlsm.
  sy-batch = 'X'.

  TRY.
      CALL METHOD lci_reader->load_file
        EXPORTING
          i_filename = p_template_filepath
        RECEIVING
          r_excel    = lc_excel.
    CATCH zcx_excel INTO lc_excel_exc.
      RAISE erreur_lecture_template.
  ENDTRY.

  " DonnÃ©es EntÃªte - Perform in which i'm setting some data in the first sheet using set_cell()
  PERFORM set_header_excel_data   USING         ps_entete_cat
                                                p_type_frs
                                  CHANGING      lc_excel.

  CREATE OBJECT lci_excel_writer TYPE zcl_excel_writer_xlsm.

  TRY.

      lw_file = lci_excel_writer->write_file( lc_excel ).

    CATCH cx_root INTO lc_exception.
      lw_error = lc_exception->get_text( ).
  ENDTRY.

</code></pre>

Am i missing an option to keep the data validation in the excel file? 
Thx in advance for your help !

**Comment by ivanfemia** [comment]
[[file:cHgqsAdcKr473dacwqjQYw]]

**Comment by alsp80** [comment]
I've enhanced method ZCL_EXCEL_READER_2007->LOAD_WORKSHEET to support data validations which are now read from the file and created as new validations in the worksheet. My personal tests with a worksheet were fine, however I didn't test all possible attributes.

Would love to send you the slinkee, but as far as I can see I'm only allowed to attach images in here. Let me know how to send the file to you.

**Comment by gregorwolf** [comment]
@alsp80 please fork the project, apply the patch on your fork and send us a pull request.

**Comment by ivanfemia** [comment]
Pull request accepted!
Thanks @alsp80 for your contribution

**Comment by grknaveen** [comment]
@ivanfemia Could you please provide me an XLSM file with Validations that worked for you.
