### ISSUE TITLE
Collapsing hierarchy rows/columns does not work

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#278]
Hi,

trying to collapsing hierarchyÂ  rows for exapmle by:

ZDEMO_EXCEL12Â  

row_dimension->set_outline_level( ip_outline_level = 2 ).\ row_dimension->set_collapsed( ip_collapsed = 'X' ).
...

with no effect. Am i totally wrong, or is it a bug?

Regards, Stefan
ZDEMO_EXCEL12

**Comment by ivanfemia** [comment]
Dear Stefan,

I've also think that this is still a bug. You could help us fixing the bug by providing a patch. The worksheet is generated in the CREATE_XL_SHEET method of class ZCL_EXCEL_WRITER_2007. You will find there a line:

<pre><code>        " Collapsed
        IF <column_dimension>-column_dimension->get_collapsed( ) = abap_true.</code></pre>

I think that should be the place to put a breakpoint and check if that is correctly evaluated. To investigate further on check the Output of a simple Excel file where you've done the collapsing manually and compare that with the a2x output.

Best regards
Gregor

**Comment by ivanfemia** [comment]
Gregor,

it is empty:

method GET_COLLAPSED.
  r_collapsed = me->collapsed. <-   empty
endmethod.

**Comment by ivanfemia** [comment]
Sorry wrong row, it is filled

The information seems to be right generated and incorporated in the XML.
- <row r="6" spans="1:9">
- <c r="B6" t="s">
  <v>8</v> 
  </c>
  </row>
- <row r="7" spans="1:9" outlineLevel="1">
- <c r="B7" t="s">
  <v>9</v> 
  </c>
  </row>
- <row r="8" spans="1:9" collapsed="true" outlineLevel="2">
- <c r="B8" t="s">
  <v>10</v> 
  </c>
  </row>
  </sheetData>
  <pageMargins left="0.70" right="0.70" top="0.75" bottom="0.75" header="0.30" footer="0.30" /> 
  <pageSetup /> 
  </worksheet>

**Comment by ivanfemia** [comment]
Please compare that as suggested against a Worksheet that you've created in Excel. For further details consult the specification for ISO 29500 Office Open XML at http://www.ecma-international.org/publications/standards/Ecma-376.htm

**Comment by ivanfemia** [comment]
i found no method in Excel 2010 to stor the document as xml. if using Office2003-XML Document. i get a xml. But this contains no information about collased or expanded hierarchy groups. 

is it also a bug on your environment?

**Comment by ivanfemia** [comment]
Gregor, 

i dont' know about the Open Office Specs, but Microsoft awaits 1 nad 0 instead of true and false.

See:

http://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.row.aspx

I change thsi and report about the result

**Comment by ivanfemia** [comment]
no success

**Comment by StefanSchmoecker** [comment]
Actually collapsing does work - but you have to hide all rows that are being not shown by yourself and put the "collapsed"-flag in the row following the last row not being shown.
This isn't intuitive - I guess we'll have to implement another an other mechanism for outlining
See also #346

**Comment by StefanSchmoecker** [comment]
New method for outlining ( rows only currently ) implemented with revision 404

**Comment by sandraros** [comment]
Currently `ZDEMO_EXCEL12` does collapse the rows, so I propose to close this issue. Please reopen it if I'm wrong.
![image](https://user-images.githubusercontent.com/34005250/151714283-63eeaec9-e37e-4598-bc92-3cdc1a552662.png)
