### ISSUE TITLE
Error mixing default-styles and bind_table or column-width settings

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#291]
Reported by Stefan on old code exchange and not migrated...

ABAP2XLSX produces incorrect output when mixing default styles (for worksheet ) with bind_table and/or column-width settings.

Attached:
- Demoreport that creates this incorrect output
- Output of demoreport.

2 obvious errors. Column B has incorrect style out of bound table area and the last line of the table is formatted with the default style instead of the style of the table

**Comment by ivanfemia** [comment]
[[file:dtWPaGjYur455jacwqjQWU]]

**Comment by ivanfemia** [comment]
[[file:dD0cR6jYur45ddacwqEsg8]]

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Closed because no objections have arisen.
