### ISSUE TITLE
set_default_style() + column resizing

### ISSUE THREAD

**Issue by marco-remondini** [abap2xlsx/abap2xlsx#295]
If I try to change a column width after setting a default style, all empty cells of that column come with a 12.5% gray pattern, but the filled cells don't have such pattern. I have to either comment out the set_default_style() or the column resizing to remove the pattern.
I'm using MS excel 2003, so I faced this issue on a converted version of the file.

Here's an example:

DATA: ob_excel        TYPE REF TO zcl_excel,
      ob_worksheet    TYPE REF TO zcl_excel_worksheet,
      ob_excel_error  TYPE REF TO zcx_excel,
      msg             TYPE string.

DATA: lo_style_def      TYPE REF TO zcl_excel_style,
      lv_style_def_guid TYPE zexcel_cell_style.
- create ob_excel with default style
  TRY.
  CREATE OBJECT ob_excel.
  lo_style_def = ob_excel->add_new_style( ).
  lo_style_def->font->name = zcl_excel_style_font=>c_name_arial.
  lo_style_def->font->size = 10.
  lo_style_def->font->scheme = zcl_excel_style_font=>c_scheme_none.
  lv_style_def_guid = lo_style_def->get_guid( ).
  ob_excel->set_default_style( lv_style_def_guid ).
  CATCH zcx_excel INTO ob_excel_error.
    msg = ob_excel_error->get_text( ).
    MESSAGE msg TYPE 'E'.
  ENDTRY.
- fill 2 cells
  TRY.
  ob_worksheet = ob_excel->get_active_worksheet( ).
  ob_worksheet->set_cell( ip_column = 'A' ip_row = 4 ip_value = 'Pos' ).
  ob_worksheet->set_cell( ip_column = 'B' ip_row = 4 ip_value = 'Ben' ).
  CATCH zcx_excel INTO ob_excel_error.
    msg = ob_excel_error->get_text( ).
    MESSAGE msg TYPE 'E'.
  ENDTRY.
- resize columns
  DATA: column_dimension TYPE REF TO zcl_excel_worksheet_columndime.
  TRY.
  column_dimension = ob_worksheet->get_column_dimension( ip_column = 'A' ).
  column_dimension->set_width( 5 ).
  column_dimension = ob_worksheet->get_column_dimension( ip_column = 'B' ).
  column_dimension->set_auto_size( ip_auto_size = abap_true ).
  CATCH zcx_excel INTO ob_excel_error.
    msg = ob_excel_error->get_text( ).
    MESSAGE msg TYPE 'E'.
  ENDTRY.
- download file
  DATA: filename TYPE string VALUE 'C:\test.xlsx'.
  DATA: cl_writer TYPE REF TO zif_excel_writer.
  DATA: xdata       TYPE xstring,
    t_rawdata   TYPE solix_tab,
    bytecount   TYPE i.

CREATE OBJECT cl_writer TYPE zcl_excel_writer_2007.
xdata = cl_writer->write_file( ob_excel ).

t_rawdata = cl_bcs_convert=>xstring_to_solix( iv_xstring  = xdata ).
bytecount = XSTRLEN( xdata ).

cl_gui_frontend_services=>gui_download( EXPORTING bin_filesize = bytecount
                                                  filename     = filename
                                                  filetype     = 'BIN'
                                         CHANGING data_tab     = t_rawdata ).

**Comment by marco-remondini** [comment]
I think it's an error in method GET_STYLE_INDEX_IN_STYLES of class ZCL_EXCEL: after looking for the style with an iterator it corrects the index with a SUBTRACT:

``` ABAP
  IF ep_index IS INITIAL.
    RAISE EXCEPTION TYPE zcx_excel
      EXPORTING
        error = 'Index not found'.
  else.
    SUBTRACT 1 from ep_index.  " In excel list starts with "0"
  ENDIF.
```

but this method is only called in ZCL_EXCEL_WRITER_2007=>CREATE_XL_SHEET and the index is decreased again after the call:

``` ABAP
        lv_style_index = me->excel->get_style_index_in_styles( lv_style_guid ).                             "ins issue #237
        IF lv_style_index > 0.                                                                              "ins issue #237
          lv_value = lv_style_index - 1.                                                                    "ins issue #237
          SHIFT lv_value RIGHT DELETING TRAILING space.
          SHIFT lv_value LEFT DELETING LEADING space.
          lo_element_2->set_attribute_ns( name  = lc_xml_attr_style
                                          value = lv_value ).
        ENDIF.                                                                                              "ins issue #237
```

commenting out the first SUBTRACT seems to solve this issue:

``` ABAP
  IF ep_index IS INITIAL.
    RAISE EXCEPTION TYPE zcx_excel
      EXPORTING
        error = 'Index not found'.
*  else.                                                         " --MR
*    SUBTRACT 1 from ep_index.  " In excel list starts with "0"  " --MR
  ENDIF.
```

**Comment by marco-remondini** [comment]
I tested new daily build 5fe3e01419, but it doesn't solve this issue, It is solved changing ZCL_EXCEL_WRITER_2007=>CREATE_XL_SHEET method from:

``` ABAP
*        lv_value = me->excel->get_style_index_in_styles( lv_style_guid ).                                  "del issue #237
        CLEAR ls_style_mapping.
        READ TABLE styles_mapping INTO ls_style_mapping WITH KEY guid = lv_style_guid.
        lv_style_index = ls_style_mapping-style.
        IF lv_style_index > 0.                                                                              "ins issue #237
          lv_value = lv_style_index - 1.                                                                    "ins issue #237
          SHIFT lv_value RIGHT DELETING TRAILING space.
          SHIFT lv_value LEFT DELETING LEADING space.
          lo_element_2->set_attribute_ns( name  = lc_xml_attr_style
                                          value = lv_value ).
        ENDIF.
```

to:

``` ABAP
*        lv_value = me->excel->get_style_index_in_styles( lv_style_guid ).                                  "del issue #237
        CLEAR ls_style_mapping.
        READ TABLE styles_mapping INTO ls_style_mapping WITH KEY guid = lv_style_guid.
*        lv_style_index = ls_style_mapping-style. " --MR
*        IF lv_style_index > 0.                   " --MR                                                           "ins issue #237
*          lv_value = lv_style_index - 1.         " --MR                                                           "ins issue #237
        IF sy-subrc = 0.                          " --MR                                                   
          lv_value = ls_style_mapping-style.      " --MR
          SHIFT lv_value RIGHT DELETING TRAILING space.
          SHIFT lv_value LEFT DELETING LEADING space.
          lo_element_2->set_attribute_ns( name  = lc_xml_attr_style
                                          value = lv_value ).
        ENDIF.  
```

because styles are numbered beginning from 0 in styles_mapping table, so it's wrong changing the style index with:

``` ABAP
lv_value = lv_style_index - 1.
```

**Comment by ivanfemia** [comment]
Hi Marco,

this is issue was not solved with latest daily build I will check you fix and include in the next one.

Thank you for your contribution.

Ivan
