### ISSUE TITLE
GETWA_NOT_ASSIGNED in ZCL_EXCEL_TABLE

### ISSUE THREAD

**Issue by uweku** [abap2xlsx/abap2xlsx#296]
method GET_REFERENCE. might dump in line 23 when the table which has been previously provided is freed by garbage collector. This might happen when you bind a local internal table to the excel worksheet and leave the method afterwards.

The follwing implementation in ZCL_EXCEL_TABLE solves this issue:
METHOD set_data.
  DATA lr_temp TYPE REF TO data.
  FIELD-SYMBOLS &lt;lt_table_temp&gt; TYPE ANY TABLE.
  FIELD-SYMBOLS &lt;lt_table&gt; TYPE ANY TABLE.
  GET  REFERENCE OF ir_data INTO lr_temp.
  ASSIGN lr_temp-&gt;\* TO &lt;lt_table_temp&gt;.
  CREATE DATA table_data LIKE &lt;lt_table_temp&gt;.
  ASSIGN table_data-&gt;\* TO &lt;lt_table&gt;.
  &lt;lt_table&gt; = &lt;lt_table_temp&gt;.
ENDMETHOD.

**Comment by ivanfemia** [comment]
Fixed in latest commit

Thank you for reporting
