### ISSUE TITLE
Can't "install" newest Daily Nugg

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#300]
Hi,
I tried to "install" the actual nugg file - but it's not working.
Get error message "Class ZIF_EXCEL_CONVERTER does not exist" (or something similar, sorry, logged in in german).

I first tried to update my existing ABAB2XLSX, this error. OK, tried to delete everything and then - same error.

I get a Red LED after installing ZIF_EXCEL_CONVERTER

![zwischenablage01](https://f.cloud.github.com/assets/6636061/2293690/f53e1f82-a072-11e3-9f13-b1021626482e.jpg)

Can anyone confirm?

**Comment by gregorwolf** [comment]
Please make sure you have the latest SAPlink version from the SVN reporitory at http://saplink.org

**Comment by mfallen** [comment]
Is there any way to check my "actual" version?

**Comment by gregorwolf** [comment]
Unfortunately there is no such check. I've created the issue https://www.assembla.com/spaces/zake/tickets/34-replace-a-string-i-e----build---in-the-build-process-with-revision-number in the ZAKE project. Hope you can perhaps help to implement. Otherwise please just install the new SAPlink version over the current.

**Comment by mfallen** [comment]
Just installed the new version, problem remains:

![image](https://f.cloud.github.com/assets/6636061/2293800/46413584-a075-11e3-9b97-bfec94796d12.png)

**Comment by gregorwolf** [comment]
So now make sure that you have also the latest plug-ins from http://plugins.saplink.org

**Comment by mfallen** [comment]
Aprblem comes up when trying to create Interace ZIF_EXCEL_SHEET_VBA_PROJECT

![image](https://f.cloud.github.com/assets/6636061/2293938/2a32f49c-a078-11e3-8d12-139ea9a103cd.png)

![image](https://f.cloud.github.com/assets/6636061/2293939/2ff6e79e-a078-11e3-8b91-4d5dc7712830.png)

![image](https://f.cloud.github.com/assets/6636061/2293942/38da54a4-a078-11e3-9e05-975cb43819d8.png)

![image](https://f.cloud.github.com/assets/6636061/2293944/40a1db62-a078-11e3-8c19-76be2f3a58f9.png)

![image](https://f.cloud.github.com/assets/6636061/2293946/44e890a8-a078-11e3-821f-e9fe903a2615.png)

Sy-Subrc = 4 (COMPONENT_ERROR)

**Comment by ivanfemia** [comment]
Hi,

I tested the latest daily build on a new system using the latest SAPLink version and it works properly.
Please verify that SAPLink is installed without any issue and try again.

**Comment by mfallen** [comment]
Got it!
Problem were only the interfaces. Seems like they remain somehow in the system, but can't see them im SE24.
I created them then manually in SE24 with the name from ABAP2XLSX. Then all the methods already exist in my newly created interface, so there must be something wrong when deleting them.

Thanks all for your help!
