### ISSUE TITLE
Error in the ABAP Application Program

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#301]
Hi,

had just installed the latest Nugg file, now I have a bug in ZCL_EXCEL_WRITER_2007->CREATE_XL_STYLES on line 777:

READ TABLE lt_fonts into ls_font INDEX ls_cellxfs-FONTID + 1.

Bug says Unable to interpret "+". Possible causes: Incorrect spelling or comma error.

I think it's because of an old version of NetWeaver or something like that? Current version doesn't support the statement "index xy + 1" correct?

So where do I have to correct this?

**Comment by ivanfemia** [comment]
Which version of SAP_BASIS have you?
You can change the code according to your version in your local copy.

Thanks
Ivan

**Comment by mfallen** [comment]
SAP_BASIS is on 701, SP Level 14.

No problem, the code is very easy to change.

**Comment by rplantiko** [comment]
By the way, it is a cool new feature of ABAP 7.40 to allow expressions for
all operands of the READ TABLE statement. As here: READ TABLE ...
INDEX *ls_cellxfs-fontid
- 1*.

http://help.sap.com/saphelp_nw74/helpdata/en/c2/dbf231ac4c4ee99e8cc0aea20be407/content.htm?frameset=/en/05/f324517b92fa50e10000000a441470/frameset.htm&fullscreen=true

You needed auxiliary variables in previous ABAP versions.

For ABAP, this feature is cool and new. For other languages (Java, C/C++,
...), it always was standard.

Regards,
Rüdiger

On Tue, Mar 4, 2014 at 7:00 AM, mfallen notifications@github.com wrote:

> SAP_BASIS is on 701, SP Level 14.
> 
> No problem, the code is very easy to change.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ivanfemia/abap2xlsx/issues/301#issuecomment-36594667
> .

## 

Dr. Rüdiger Plantiko
Bachwiesenstrasse 28
CH-8405 Winterthur

http://ruediger-plantiko.net
https://twitter.com/rplantiko

**Comment by ivanfemia** [comment]
Fixed in the latest daily build.

Thank you for reporting.
