### ISSUE TITLE
Copy cell format of a whole cell

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#302]
Hi experts,

question:

Is it possible to copy the cell format of a complete row (or for example the format of A1:H1) to a different row?
Or do I have to do this for each cell?

What I need:

I have a table with 100 lines, at the end I have 4 "template" rows. Depending on the values, the 100 lines have to be formated like template 1, 2, 3 or 4. I could use the style for each cell, but would be nice to use a "row style" - something like copying the format in Excel itself...

**Comment by ivanfemia** [comment]
Hi,

this function is not available.
Generating the excel from ABAP, I suppose in a cycle, applying a style for each cell based on a check is pretty straightforward. 

Best
Ivan
