### ISSUE TITLE
Problem isntalling actual NUGG - ZDEMO_EXCEL_WDA01

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#305]
Morning,

just for information - get error "CX_WDY_MD_NOT_EXISTING" when trying to install actuall daily Nugget, it's DEMO_EXCEL_WDA01.

Active Calls/Events
1. EVENT - ZSAPLINK
2 FORM INSTALLOBJECT
3 METHID CREATEOBJECTFROMIXMLDOC

select \* from wdy_component into table itab_wdy_component [...] - sy-subrc ne 0

Get it installed by debugging SAPLINK and ignore the Web Dynpro Component...

Regards

**Comment by gregorwolf** [comment]
Do you have the latest SAPlink and SAPlink Plugins version installed?

**Comment by mfallen** [comment]
Absolutly! Installed it last Monday

**Comment by ivanfemia** [comment]
I've createad a new daily build without WDA demos.
WDA demos are now collected in an extra package.
