### ISSUE TITLE
SYNTAX_ERROR in ABAP Demo Reports

### ISSUE THREAD

**Issue by nielsdegreef** [abap2xlsx/abap2xlsx#306]
Came across the following error:
![untitled](https://f.cloud.github.com/assets/6931544/2399490/fcf3e366-a9fe-11e3-9d10-84c922091397.png)

I followed the installation guide step by step and every output I got was the same (all objects are activated).

He complains on the following:
![untitled](https://f.cloud.github.com/assets/6931544/2399556/d09c4a00-a9ff-11e3-8196-6e8cbb6af6bd.JPG)

Any ideas?

Thanks in advance.

Regards,

Niels

**Comment by ivanfemia** [comment]
ENDMETHOD is duplicated.
Which version of SAPlink are you using?

**Comment by nielsdegreef** [comment]
Indeed, saw that too, tried to remove the duplicate but this is giving more errors on method.

Any way of checking that version? I installed it into my system a while ago (January 2014).

**Comment by ivanfemia** [comment]
No way AFAIK.
The latest nugg was created with the latest daily build, with latest plugin daily build.
@gregorwolf is there any way to check?

**Comment by nielsdegreef** [comment]
I use the latest ABAP2XLSX nugg daily build and the latest saplink plugin daily build.
As far as I can see there is no new SAPLink available for download (latest stable is from Oct 2008)

**Comment by ivanfemia** [comment]
Try to use this one
https://www.assembla.com/code/saplink/subversion/nodes/388/trunk/build

Plugins
https://www.assembla.com/code/saplink-plugins/subversion/nodes/124/build

**Comment by nielsdegreef** [comment]
Upon installing the new SAPLink daily build, I get the following error:
"There is no installed SAPlink plugin for object type CLAS".

Searching for the right plugin atm (can't install plugins daily build first, same error).

**Comment by ivanfemia** [comment]
It comes with the basic build.
I had the same issue in another system. I had to delete all the SAPlink objects and install SAPlink from scratch. (overwriting objects didn't solve the issue)

**Comment by nielsdegreef** [comment]
Okay, will try that now.
Thank you, I really like the support for this project :+1:

**Comment by nielsdegreef** [comment]
Reïnstall of the SAPLink, it's plugins and the ABAP2XLSX nugg solved the issue.

Thanks a lot for your help!
