### ISSUE TITLE
Writer XML encoding

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#307]
Move the encoding schema "UTF-8" as an attribute of the WRITER class (by default UTF-8, but it can be modified in UTF-16).

See issue #298 for details.

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by gregorwolf** [comment]
Please check my sample code at http://scn.sap.com/thread/3801086 showing problems with UTF-8 using ixml.

**Comment by sandraros** [comment]
I understand that the issue is about rendering all Unicode characters, which has been solved by #743 and #757, so closing.
