### ISSUE TITLE
COMPUTE_INT_TIMES_OVERFLOW when adding an image

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#308]
Hi,

I have an Excel only including one image (type PNG, Barcode).

I created a test program reading this file and then exporting, nothing more. I get error "COMPUTE_INT_TIMES_OVERFLOW".

have attached my excel
http://www.file-upload.net/download-8708025/test_drawing.xlsx.html

Screenshot of the error

![image](https://f.cloud.github.com/assets/6636061/2407151/2870cd0c-aa85-11e3-9339-bb6bd88282a3.png)

Position in coding:
![image](https://f.cloud.github.com/assets/6636061/2407154/3559b4a2-aa85-11e3-8c4c-3f195a82dec3.png)

Value of ip_pixel:
![image](https://f.cloud.github.com/assets/6636061/2407156/3e6ee7a6-aa85-11e3-8ae5-7e32834d2d1a.png)

Calls
![image](https://f.cloud.github.com/assets/6636061/2407158/4ae28e48-aa85-11e3-8173-12ca09031aa0.png)

Anyone that could confirm?

**Comment by ivanfemia** [comment]
Checking the OOXML standard the maximum value is 27273042316900, unfortunately INT4 maximum value is 2147483647.

We need to provide a fix for this issue of method pixel2emu.

OOXML XSD definition:

&lt;xsd:simpleType name="ST_PositiveCoordinate"&gt;
&lt;xsd:restriction base="xsd:long"&gt;
&lt;xsd:minInclusive value="0"/&gt;
&lt;xsd:maxInclusive value="27273042316900"/&gt;
&lt;/xsd:restriction&gt;
&lt;/xsd:simpleType&gt;

**Comment by ivanfemia** [comment]
Could you please update your copy with the new slinkee file of CLAS ZCL_EXCEL_DRAWING just committed in the repository and let me know?

**Comment by mfallen** [comment]
No dump anymore...but the barcode in the created Excel (Oringial was 1,43cm \* 3,52 cm) now has the size 5965,23  cm \* 5965,23  cm. Something must be wrong here also

**Comment by gregorwolf** [comment]
Could you provide a sample barcode for download?

**Comment by mfallen** [comment]
It's the Barcode in the attached XLSX from my first post

**Comment by gregorwolf** [comment]
I've checked to include the image with PHPExcel_1.8.0_doc and that worked. So we know it's not the image itself causing the problem.

**Comment by mfallen** [comment]
Seems to be a problem with the Excel Reader I think...
When I add the image exactly to a cell (at the border), it's working. Wehn I move the image with the arrow keys 3 "pixel" to the right and 3 pixel down, I have this problem...

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Seems to be fixed.  Tried the provided excel with the latest build and Demoreport 37 - no more errors even if I move the barcode a few pixels down and right.
