### ISSUE TITLE
Create a new line in an (existing) Excel sheet

### ISSUE THREAD

**Issue by alsp80** [abap2xlsx/abap2xlsx#309]
I'm wondering whether there is a simple way of creating a new line inside a worksheet which would be a copy of an existing line.

What I'm trying to do is: use the reader to get the content of a template file, add data and output again with the writer.
Imagine that I want to create further rows keeping the format of an existing row in the template and moving other rows one down.

Is there already a convenient function available to solve this (I didn't find one when searching). Otherwise I might look into creating one myself.

**Comment by ivanfemia** [comment]
No function available for this.
you should copy the style content of each cell of the row you are copying and apply it in the new copied row.
