### ISSUE TITLE
Question - how to get "offset" for an image?

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#311]
Hi,

Want to add an image - let's say in column G. I don't want to add directly at the border, want to move it to the right.

This could be done with set_position2 (zcl_excel_drawing) and adding a col_offset. I thought this is the offset from the left border of colum G, but seems to be an offset from the first column left. So I need to have this "value" from A to G. It's not simply counting all the column widths together, it's a different number.

Have done some tests, result for me was that I have to add a col_offset of 19080 (created an ecxel in SAP, checekd the drawing1.xml, then moved my image to the right, checked again the drawing1.xml).

So my question - where to get this number from?

Thanks for your help
Michael

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Hello Michael,

the number is indeed the offset to the top/left border of the cell the drawing is attached to .
But it is given in emu and not in pixels.

See method zcl_excel_drawing=>emu2pixel to retrieve the number of pixels.

For you col_offset of 19080 at a (default) 96 dpi you'd get 
19080 \* 96 / 914400 2,00314961 ~ 2 pixel ( I tried the same with my excel and found the value to be 19050 which gets exactly to 2 pixel )
