### ISSUE TITLE
Number format of style not working

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#316]
Hi, 
I want to set a cell to a specific number format (for example 09406151232 should be shown as 09406 151 232). That's easy with styles:

lo_style->number_format->format_code = '00000\ 000\ 000'.

When I export the Excel and open it, the cell is shown without the spaces between the blocks. Cheking the number format of that cell, everything's fine.
To "solve" this, I have to go in that cell, go into "change mode" (pressing F2) and then hit enter. Now the format is correct!

Had made a very simple programm to check this (with a hardcoded file path):
http://www.file-upload.net/download-8849678/test_style.txt.html

Thil will create an Excel, add a style, write a value to cell A1 with that style and save to a specific path, that's all.

Could anyone confirm this?

**Comment by mfallen** [comment]
Could anyone confirm this?

**Comment by marco-remondini** [comment]
I have tested it with Office 2010 and the xlsx generated behaves as described. I think the problem is that the number passed to set_cell method is a char type: if you define a variable of type p or type f the formatting is correct:

``` ABAP
...
DATA: num_as_p             TYPE p DECIMALS 0 VALUE '09406151232'.
...
lo_worksheet->set_cell( ip_column = 'A' ip_row = '1' ip_value = num_as_p ip_style = lt_style_guid ).
...
```

**Comment by ivanfemia** [comment]
Solution provided
