### ISSUE TITLE
issue with empty autofilter reference

### ISSUE THREAD

**Issue by KaiWalter** [abap2xlsx/abap2xlsx#317]
I want to load a workbook which somehow has an empty autofilter reference which causes the ZCL_EXCEL_READER_2007-LOAD_WORKBOOK method to raise an exception (without any text)

Debugging "section insert autofilters" I see, that 
LV_RANGE_VALUE has a value of Sheet2!#REF!
which will give LV_COL_START_ALPHA and LV_COL_END_ALPHA initial values.
The following call of "ls_area-col_start = zcl_excel_common=>convert_column2int( lv_col_start_alpha )." then causes the exception.

**Comment by ivanfemia** [comment]
Can you provide an example xlsx file?

**Comment by ivanfemia** [comment]
Close issue due to inactivity
