### ISSUE TITLE
Save excel file in XLS format (Microsoft Excel 2003)

### ISSUE THREAD

**Issue by termarco** [abap2xlsx/abap2xlsx#321]
Hi, 
how can i save the excel file in xls format? The file will be used on a machine with excel 2003 installed.

Thanks in advance.

**Comment by rplantiko** [comment]
Hi termarco,

the old [BIFF format](http://www.openoffice.org/sc/excelfileformat.pdf)  as in Excel 2003 is not supported by the abap2xlsx package. This is why it is called abap2xlsx and not abap2xls 

Ask your customers to work with CSV or with the new OpenXML format instead. If they insist on BIFF, you'll have to look around for other converters.

I once wrote an ABAP function module [Z_EXCEL_TO_INTERNAL_TABLE](http://bsp.mits.ch/code/fugr/zutil_excel) for _reading_ BIFF, but I don't know of any ABAP code for the other direction.

Regards, 
Rüdiger
