### ISSUE TITLE
Syntax error in program "ZCL_EXCEL_WRITER_2007=========CP "

### ISSUE THREAD

**Issue by danishsap** [abap2xlsx/abap2xlsx#324]
The following syntax error occurred in program
  "ZCL_EXCEL_WRITER_2007=========CP " in include
  "ZCL_EXCEL_WRITER_2007=========CM00I " in
 line 130:
 "After "'tableStyleInfo'", there must be a space or equivalent characte"
 "r (":", ",", "."). ."
 " "
 " "

> > > CREATE OBJECT lo_excel_writer TYPE zcl_excel_writer_2007.

What is the expected output? What do you see instead?
Excel report should be downloaded in Background

What version of SAP are you using?
SAP_ABA Release / Level: SAPKA70014
SAP_BASIS Release / Level: SAPKA70014
SAP Kernel 721

What version of SAPlink are you using: 0.1.4

**Comment by ivanfemia** [comment]
Are you running a demo report?
Which one?
