### ISSUE TITLE
Leading Blanks are not shown

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#326]
We have a problem with leading blanks.

For presenting the issue, we changed the report ZDEMO_EXCEL1.
![hc_334](https://cloud.githubusercontent.com/assets/8254028/3686889/739791ce-131e-11e4-95ce-063a7a5bbcab.png)

When we open the corresponding XML-file generated with ZCL_EXCEL_WRITER_2007
the text Looks like this:
![hc_332](https://cloud.githubusercontent.com/assets/8254028/3686787/0d294cda-131d-11e4-845c-2f5f6681cf7b.png)

Now we open the xlsx-document with Excel and the leadings blanks are gone.
![hc_333](https://cloud.githubusercontent.com/assets/8254028/3686798/3337b39e-131d-11e4-9266-bb9828604a2a.png)

So we modified the method ZCL_EXCEL_WRITER_2007->CREATE_XL_SHAREDSTRINGS:
![hc_335](https://cloud.githubusercontent.com/assets/8254028/3686916/c5c9d48e-131e-11e4-970e-4da3b78114b7.png)

With the new Attribute "space" with the value "preserve", the leading blanks are shown in Excel.
![hc_336](https://cloud.githubusercontent.com/assets/8254028/3686927/ffd863c0-131e-11e4-8790-c88a1560ca7d.png)
![hc_337](https://cloud.githubusercontent.com/assets/8254028/3686948/632c4eaa-131f-11e4-97ed-8d0061de0066.png)

Is it possible to implement a possibility to preserve leading blanks in standard?
Thanks in advance!

Kind Regards,
Kilian

**Comment by Gh14Cc10** [comment]
Issue solved - new daily build needed from TIR system @ivanfemia
