### ISSUE TITLE
Enhancement for Excel 2010

### ISSUE THREAD

**Issue by hagen** [abap2xlsx/abap2xlsx#327]
Hi there,
having _great_ fun with this library. In moving to Excel 2010, the files are still compatible, however Excel 2010 must do a brief repair on the file before opening. Just wondering if any work is planned for Excel 2010 compatibility?

**Comment by gregorwolf** [comment]
You're very welcome to fork the project make the required adustments for Excel 2010, test them also against 2007 and we merge it back in.

**Comment by hagen** [comment]
I might just do that. Thanks. Would you like to keep this issue open, and flag it enhancement?

**Comment by hagen** [comment]
You know what it was Gregor - not specifying the bytecount when doing GUI download. Which was in the countless examples. There is no need for changes to support Excel 2010.

Cheers and thanks. Issue closed.
