### ISSUE TITLE
Wrong initial value (check) for attribute indexed of bgcolor

### ISSUE THREAD

**Issue by oliver-huetkoeper** [abap2xlsx/abap2xlsx#329]
Hi,

in the constructor of class ZCL_EXCEL_STYLE_FILL bgcolor-indexed is filled with zcl_excel_style_color=>c_indexed_sys_foreground.

When writing the file, in method ZCL_EXCEL_WRITER_2007->CREATE_XL_STYLES_COLOR_NODE it is checked whether the value is still initial. This method is used for fgcolor and bgcolor. Unfortunately only the initial value for fgcolor is checked:
"is_color-indexed <> zcl_excel_style_color=>c_indexed_not_set"

I don't know if it is correct that fgcolor and bgcolor have different initial values. Therefore I open this issue instead of just fixing it on my own.
Either the initial value of bgcolor should be changed or the check should be extended to cover the initial value for bgcolor as well.

Best regards,
Oliver

**Comment by Gh14Cc10** [comment]
bgcolor default value is correct: when you set the color for a cell in excel, the system automatically assign to the bgcolor property the integer value 64, as the style constructor does.

![image](https://cloud.githubusercontent.com/assets/6337270/4660874/c9149382-551c-11e4-96bc-21c5cac4695a.png)

**Comment by oliver-huetkoeper** [comment]
If it is correct that they have different initial values, then the check needs to be adjusted.

**Comment by Gh14Cc10** [comment]
Not required if it is not creating issues: if you create an ZCL_EXCEL_STYLE_FILL class instance without changing any value, the node will be created in the final xml, but the bgcolor property will contain the default value. I don't think that this will create any issues. In case just come back to me

**Comment by oliver-huetkoeper** [comment]
You are correct, at the moment it "only" spams the Excel file. But you never know if future code changes will have more serious impacts. That is why I thought this should be corrected.

**Comment by ivanfemia** [comment]
Further investigation is requested, thank you Oliver for your feedback

**Comment by Gh14Cc10** [comment]
Fixed with commit 27b3467a8e4f8cc56c338634b54fc2408de31ee0
