### ISSUE TITLE
Installing - All DDIC objects aren't in transport request

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#334]
Hi,

just installed the actual nugget (7.0.1) with SAPlink, using my package for  all the objects.

For all the classes and interfaces, I get the request to chose a transport request.
When finished, I opened my inactive objects in SE80 and tried to activate.
But for ALL the DDIC objects (table types, data elemets,...) I get error message that it's not in a transport request. So I have to open each DDIC elemt, edit the short text (always empty), save, chose transport request and then I can activate.
I uploaded in German language, maybe this is the problem.

Any one knows what I have done wrong?

Thanks
Michael

**Comment by gregorwolf** [comment]
Dear Michael,

I would suggest that you try a fresh install but into a local package i.e. $A2X. 

Best regards
Gregor
