### ISSUE TITLE
Question: Change from iXML to sXML possible?

### ISSUE THREAD

**Issue by HannesRempel** [abap2xlsx/abap2xlsx#338]
We have still a lack of memory during the processing of a large XML document.

I found this in the ABAP Keyword Documentation: "If access to all nodes of an XML document in the memory is not required and no DTD is needed, sXML Library is an alternative to iXML Library with better performance."

SAP Note 1229110 recommend sXML, too.

Now my question: Is DOM really needed? Or is a change possible?

**Comment by gregorwolf** [comment]
Dear Hannes,

have you tried reading the file using the ZCL_EXCEL_READER_HUGE_FILE class? Or do you face the issue when you create from scratch? Sample code is always welcome.

Best regards
Gregor

**Comment by HannesRempel** [comment]
Dear Gregor,

I see the work is already started by Rüdiger. I haven't noticed that I have to replace creation of ZCL_EXCEL_READER_2007 with ZCL_EXCEL_READER_HUGE_FILE.

Kind regards
Hannes

**Comment by rplantiko** [comment]
Hannes,

see http://scn.sap.com/community/abap/blog/2014/05/05/huge-file-reader-now-part-of-apab2xlsx-package and http://scn.sap.com/community/abap/blog/2014/01/27/a-way-of-reading-huge-excel-files for details. 

Cheers,
Rüdiger
