### ISSUE TITLE
Dump in ZCL_EXCEL_READER_2007 opening file with wrong filename

### ISSUE THREAD

**Issue by marco-remondini** [abap2xlsx/abap2xlsx#344]
Trying to open a file with method zif_excel_reader~load_file of class ZCL_EXCEL_READER_2007 results in a dump if GUI_UPLOAD or OPEN DATASET fail.

It happens because methods READ_FROM_APPLSERVER and READ_FROM_LOCAL_FILE raise an excpetion (zcx_excel) which is missing from the methods exceptions. Adding the exception solves the issue.

Marco

**Comment by StefanSchmoecker** [comment]
Correct analysis.  Will update this asap

**Comment by StefanSchmoecker** [comment]
Corrected with revision 401
