### ISSUE TITLE
Gradient Fill for cell -> code

### ISSUE THREAD

**Issue by fidley** [abap2xlsx/abap2xlsx#347]
Hello, 
I've seen that gradient fill was not supported so far for cell style so I've added it to my local copy of A2X. Maybe you want to include this also to project. Unfortunatelly I cannot attach any files here, so I need to point every step to reproduce it.

1) Create structure ZEXCEL_S_GRADIENT_TYPE with following components
TYPE    ZEXCEL_FILL_TYPE
DEGREE  CHAR3
BOTTOM  CHAR3
LEFT    CHAR3
TOP         CHAR3
RIGHT   CHAR3
POSITION1   CHAR3
POSITION2   CHAR3
POSITION3   CHAR3

2) Update structure ZEXCEL_S_STYLE_FILL by adding component GRADTYPE -> ZEXCE_S_GRADIENT_TYPE

3) Update class ZCL_EXCEL_STYLE_FILL by adding:

a) in class definition publoc section
    constants c_fill_gradient_horizontal90 type zexcel_fill_type value 'horizontal90'. "#EC NOTEXT
    constants c_fill_gradient_horizontal270 type zexcel_fill_type value 'horizontal270'. "#EC NOTEXT
    constants c_fill_gradient_horizontalb type zexcel_fill_type value 'horizontalb'. "#EC NOTEXT
    constants c_fill_gradient_vertical type zexcel_fill_type value 'vertical'. "#EC NOTEXT
    constants c_fill_gradient_fromcenter type zexcel_fill_type value 'fromCenter'. "#EC NOTEXT
    constants c_fill_gradient_diagonal45 type zexcel_fill_type value 'diagonal45'. "#EC NOTEXT
    constants c_fill_gradient_diagonal45b type zexcel_fill_type value 'diagonal45b'. "#EC NOTEXT
    constants c_fill_gradient_diagonal135 type zexcel_fill_type value 'diagonal135'. "#EC NOTEXT
    constants c_fill_gradient_diagonal135b type zexcel_fill_type value 'diagonal135b'. "#EC NOTEXT
    constants c_fill_gradient_cornerlt type zexcel_fill_type value 'cornerLT'. "#EC NOTEXT
    constants c_fill_gradient_cornerlb type zexcel_fill_type value 'cornerLB'. "#EC NOTEXT
    constants c_fill_gradient_cornerrt type zexcel_fill_type value 'cornerRT'. "#EC NOTEXT
    constants c_fill_gradient_cornerrb type zexcel_fill_type value 'cornerRB'. "#EC NOTEXT
    data gradtype type zexcel_s_gradient_type.
b) class definition private section
    methods build_gradient.
    methods check_filltype_is_gradient returning value(rv_is_gradient) type abap_bool.
c) class implementation add new methods

method check_filltype_is_gradient.
    rv_is_gradient = switch #( filltype when c_fill_gradient_horizontal90 then abap_true
                                        when c_fill_gradient_horizontal270  then abap_true
                                        when c_fill_gradient_horizontalb then abap_true
                                        when c_fill_gradient_vertical  then abap_true
                                        when c_fill_gradient_fromcenter  then abap_true
                                        when c_fill_gradient_diagonal45  then abap_true
                                        when c_fill_gradient_diagonal45b  then abap_true
                                        when c_fill_gradient_diagonal135  then abap_true
                                        when c_fill_gradient_diagonal135b  then abap_true
                                        when c_fill_gradient_cornerlt  then abap_true
                                        when c_fill_gradient_cornerlb  then abap_true
                                        when c_fill_gradient_cornerrt  then abap_true
                                        when c_fill_gradient_cornerrb  then abap_true
                                        ).
  endmethod.

 method build_gradient.
    check check_filltype_is_gradient( ) eq abap_true.
    case filltype.
      when c_fill_gradient_horizontal90.
        gradtype-degree = '90'.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
      when c_fill_gradient_horizontal270.
        gradtype-degree = '270'.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
      when c_fill_gradient_horizontalb.
        gradtype-degree = '90'.
        gradtype-position1 = '0'.
        gradtype-position2 = '0.5'.
        gradtype-position3 = '1'.
      when c_fill_gradient_vertical.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
      when c_fill_gradient_fromcenter.
        gradtype-type      = c_fill_gradient_path.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
        gradtype-bottom    = '0.5'.
        gradtype-top       = '0.5'.
        gradtype-left      = '0.5'.
        gradtype-right     = '0.5'.
      when c_fill_gradient_diagonal45.
        gradtype-degree = '45'.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
      when c_fill_gradient_diagonal45b.
        gradtype-degree = '45'.
        gradtype-position1 = '0'.
        gradtype-position2 = '0.5'.
        gradtype-position3 = '1'.
      when c_fill_gradient_diagonal135.
        gradtype-degree = '135'.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
      when c_fill_gradient_diagonal135b.
        gradtype-degree = '135'.
        gradtype-position1 = '0'.
        gradtype-position2 = '0.5'.
        gradtype-position3 = '1'.
      when c_fill_gradient_cornerlt.
        gradtype-type      = c_fill_gradient_path.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
      when c_fill_gradient_cornerlb.
        gradtype-type      = c_fill_gradient_path.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
        gradtype-bottom    = '1'.
        gradtype-top       = '1'.
      when c_fill_gradient_cornerrt.
        gradtype-type      = c_fill_gradient_path.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
        gradtype-left      = '1'.
        gradtype-right     = '1'.
      when c_fill_gradient_cornerrb.
        gradtype-type      = c_fill_gradient_path.
        gradtype-position1 = '0'.
        gradtype-position2 = '1'.
        gradtype-bottom    = '0.5'.
        gradtype-top       = '0.5'.
        gradtype-left      = '0.5'.
        gradtype-right     = '0.5'.
    endcase.

  endmethod.
d) class implementation update of get_strucuture method
  method get_structure.
    es_fill-rotation  = me->rotation.
    es_fill-filltype  = me->filltype.
    es_fill-fgcolor   = me->fgcolor.
    es_fill-bgcolor   = me->bgcolor.
    me->build_gradient( ).
    es_fill-gradtype  = me->gradtype.
  endmethod.

4) Update ZCL_EXCEL_WRITER_2007 class, method create_xl_styles.
a) add constants:
                lc_xml_attr_type            type string value 'type',
                lc_xml_attr_bottom          type string value 'bottom',
                lc_xml_attr_top             type string value 'top',
                lc_xml_attr_right           type string value 'right',
                lc_xml_attr_left            type string value 'left'.
b) replace loop at lt_fills unto ls_fill... endloop by

```
" create fill elements
loop at lt_fills into ls_fill.
  lo_element_fill = lo_document->create_simple_element( name   = lc_xml_node_fill
                                                        parent = lo_document ).


  if ls_fill-gradtype is not initial.
    "gradient

    lo_sub_element = lo_document->create_simple_element( name   = lc_xml_node_gradientfill
                                                        parent = lo_document ).
    if ls_fill-gradtype-degree is not initial.
      lv_value = ls_fill-gradtype-degree.
      lo_sub_element->set_attribute_ns( name  = lc_xml_attr_degree  value = lv_value ).
    endif.
    if ls_fill-gradtype-type is not initial.
      lv_value = ls_fill-gradtype-type.
      lo_sub_element->set_attribute_ns( name  = lc_xml_attr_type  value = lv_value ).
    endif.
    if ls_fill-gradtype-bottom is not initial.
      lv_value = ls_fill-gradtype-bottom.
      lo_sub_element->set_attribute_ns( name  = lc_xml_attr_bottom  value = lv_value ).
    endif.
    if ls_fill-gradtype-top is not initial.
      lv_value = ls_fill-gradtype-top.
      lo_sub_element->set_attribute_ns( name  = lc_xml_attr_top  value = lv_value ).
    endif.
    if ls_fill-gradtype-right is not initial.
      lv_value = ls_fill-gradtype-right.
      lo_sub_element->set_attribute_ns( name  = lc_xml_attr_right  value = lv_value ).
    endif.
    if ls_fill-gradtype-left is not initial.
      lv_value = ls_fill-gradtype-left.
      lo_sub_element->set_attribute_ns( name  = lc_xml_attr_left  value = lv_value ).
    endif.

    if ls_fill-gradtype-position3 is not initial.
      "create <stop> elements for gradients, we can have 2 or 3 stops in each gradient
      lo_sub_element_2 =  lo_document->create_simple_element( name   = lc_xml_node_stop
                                                              parent = lo_sub_element ).
      lv_value = ls_fill-gradtype-position1.
      lo_sub_element_2->set_attribute_ns( name  = lc_xml_attr_position value = lv_value ).

      create_xl_styles_color_node(
          io_document        = lo_document
          io_parent          = lo_sub_element_2
          is_color           = ls_fill-bgcolor
          iv_color_elem_name = lc_xml_node_color ).
      lo_sub_element->append_child( new_child = lo_sub_element_2 ).

      lo_sub_element_2 = lo_document->create_simple_element( name   = lc_xml_node_stop
                                                             parent = lo_sub_element ).

      lv_value = ls_fill-gradtype-position2.
      lo_sub_element_2->set_attribute_ns( name  = lc_xml_attr_position
                                          value = lv_value ).

      create_xl_styles_color_node(
          io_document        = lo_document
          io_parent          = lo_sub_element_2
          is_color           = ls_fill-fgcolor
          iv_color_elem_name = lc_xml_node_color ).
      lo_sub_element->append_child( new_child = lo_sub_element_2 ).

      lv_value = ls_fill-gradtype-position3.
      lo_sub_element_2->set_attribute_ns( name  = lc_xml_attr_position
                                          value = lv_value ).

      create_xl_styles_color_node(
          io_document        = lo_document
          io_parent          = lo_sub_element_2
          is_color           = ls_fill-bgcolor
          iv_color_elem_name = lc_xml_node_color ).
      lo_sub_element->append_child( new_child = lo_sub_element_2 ).

    else.
       "create <stop> elements for gradients, we can have 2 or 3 stops in each gradient
      lo_sub_element_2 =  lo_document->create_simple_element( name   = lc_xml_node_stop
                                                              parent = lo_sub_element ).
      lv_value = ls_fill-gradtype-position1.
      lo_sub_element_2->set_attribute_ns( name  = lc_xml_attr_position value = lv_value ).

      create_xl_styles_color_node(
          io_document        = lo_document
          io_parent          = lo_sub_element_2
          is_color           = ls_fill-bgcolor
          iv_color_elem_name = lc_xml_node_color ).
      lo_sub_element->append_child( new_child = lo_sub_element_2 ).

      lo_sub_element_2 = lo_document->create_simple_element( name   = lc_xml_node_stop
                                                             parent = lo_sub_element ).

      lv_value = ls_fill-gradtype-position2.
      lo_sub_element_2->set_attribute_ns( name  = lc_xml_attr_position
                                          value = lv_value ).

      create_xl_styles_color_node(
          io_document        = lo_document
          io_parent          = lo_sub_element_2
          is_color           = ls_fill-fgcolor
          iv_color_elem_name = lc_xml_node_color ).
      lo_sub_element->append_child( new_child = lo_sub_element_2 ).
    endif.




  else.
    "pattern
    lo_sub_element = lo_document->create_simple_element( name   = lc_xml_node_patternfill
                                                         parent = lo_document ).
    lv_value = ls_fill-filltype.
    lo_sub_element->set_attribute_ns( name  = lc_xml_attr_patterntype
                                      value = lv_value ).

    " fgcolor
    create_xl_styles_color_node(
        io_document        = lo_document
        io_parent          = lo_sub_element
        is_color           = ls_fill-fgcolor
        iv_color_elem_name = lc_xml_node_fgcolor ).

    " bgcolor
    create_xl_styles_color_node(
        io_document        = lo_document
        io_parent          = lo_sub_element
        is_color           = ls_fill-bgcolor
        iv_color_elem_name = lc_xml_node_bgcolor ).
  endif.




  lo_element_fill->append_child( new_child = lo_sub_element )."pattern
  lo_element_fills->append_child( new_child = lo_element_fill ).
endloop.
```

5) then you can use one of the new filltypes from zcl_excel_style_fill and enjoy new functionallity

**Comment by gregorwolf** [comment]
Dear Łukasz,

can you please fork the project on GitHub, clone your fork to a local drive, export the affected objects from your system into your local Git repository, commit the changes and then send a pull request. Also it would be great if you haven't already done so to create a unit test for the newly added features.

Best regards
Gregor

**Comment by fidley** [comment]
Hello Gregor, 
I'll try to do it in next days so you can easily include it in the project. I'll keep you informed.

Best Regards
Łukasz

**Comment by StefanSchmoecker** [comment]
Hello Łukasz,

maybe you can add code to the ZCL_EXCEL_READER_2007 as well - that way we can use it for templates as well.

To check whether both works out you can use Demoreport 37.
Create an excel with a few cells filled with a gradient and check whether the output matches the input.

And finally it would be nice if you extend one or two of the demoreports that demonstrate how to fill a cell ( simple color fill currently ) to demonstrate the new functionality.  
I suggest ZDEMO_EXCEL2 and ZDEMO_EXCEL34 ( the chessboard would look really neat with a slight gradient fill )

**Comment by fidley** [comment]
Hello Stefan, 
I will firstly to add my code to writer, and maybe also some other changes which I've done on local version and then I'll try to update also reader and demo reports. It should not be a big deal I guess.

**Comment by fidley** [comment]
I've send pull request with writer changes and demo reports 2 & 34. For the reader I need more time that I could spend on it, so I'll try to do it next 2 weeks.

**Comment by fidley** [comment]
Writer and reader updated. Incident closed.
