### ISSUE TITLE
DEVC is missing

### ISSUE THREAD

**Issue by luissismeiro** [abap2xlsx/abap2xlsx#353]
I Ivan, great work that you have here! Thanks for sharing this project.
I have a problem, when i am trying to install the latest version V_7_0_3 the saplink gave this error: DEVC is missing.
I can't find this saplink plugin, can you help me with this issue?
Best Regards

**Comment by gregorwolf** [comment]
You can get all SAPlink Plugins at http://plugins.saplink.org/.

**Comment by luissismeiro** [comment]
Thanks @gregorwolf, your link is very usefull! :) continue the goodwork. :+1:

**Comment by StefanSchmoecker** [comment]
Should the developmentclass/Package really be part of the ABAP2XLSX installation nugget?
I thought that was removed some time ago since SAPLINK allows you to decide where to import the objects.

**Comment by gregorwolf** [comment]
Yes, I think also that the DEVC should not be part of the build.

**Comment by ivanfemia** [comment]
Yes it should not be part of the nugget, it was an issue with the latest
nugget.

**Comment by ivanfemia** [comment]
Fixed with latest commit

**Comment by asuji20** [comment]
Hello Ivan, Gregor.

I am unable to find a slinkee file for DEVC plugin anywhere. Everything is removed.
Is it included in the nugget file for ABAP2XLSX, if so, could you please separate and provide a slinkee file for DEVC.

**Comment by ivanfemia** [comment]
Asu,
Please do not cross post
