### ISSUE TITLE
Domains/Data Elements not setting up correctly

### ISSUE THREAD

**Issue by TheGoalMachine** [abap2xlsx/abap2xlsx#356]
Hi,

When I run the latest build into SAP it does not copy/setup the Domains and Data Elements correctly - Short Description, Data Type etc etc are missing.
![domain - zexcel_cell_protection](https://cloud.githubusercontent.com/assets/10740868/5939719/1b65b228-a6fe-11e4-9923-83b1909d84c0.JPG)

I changed the slinkee back to the previous version for Domain ZEXCEL_BOOLE01 and reimported it and it set up fine.
![slinkee - zexcel_boole01](https://cloud.githubusercontent.com/assets/10740868/5939892/584f8bf4-a6ff-11e4-955c-61a21456215f.JPG)

Thought I would let you know encase anybody else is experiencing the same thing or I am doing something wrong, but I am now going to try and install an older build file to get around this problem.

**Comment by ivanfemia** [comment]
Hi,

which SAPlink version are you using?
Is it hte latest one? Did you check also plugins?

Thank you
Ivan

**Comment by StefanSchmoecker** [comment]
The Dataelements and Domains have been exported by the very latest version of the SAPLINK-DTEL and SAPLINK-DOMA plugins which support translations of fixed values and field-descriptions but have not been set to "tested" yet and thus are not in the official plugin-nugget.

Unfortunately the new version isn't compatible with the old version and even more unfortunate the old version seems understands enough of the XML to try to create the object.

I'll see if I can fit in some redundant information into the XML-Output of the new versions to have the old versions be able to import the (incomplete in translation but sufficient in attributes ) objects.

**Comment by TheGoalMachine** [comment]
I have updated SAP Link to the latest version along with the up to date plugin as per your installation guide.  It made no difference but I guess you knew that following Stefan's comments.
Thanks for your prompt response, will try again once new version is available.

**Comment by ivanfemia** [comment]
DOMA and DTEL slinkee are not included in the nugg yet, so you have to import manually.

**Comment by JMoulding1958** [comment]
Hi Ivan,
I've signed up to Github, but I'm unable to download slinkees:  I need to download the domain & data element definitions re. message from GoalMachine.
Is there (perhaps) a problem with the Firefox browser?  I can't even see a download button.
Best
John M.

**Comment by niz-yar** [comment]
Hi Guys. I've got exactly the same problem. All domains and data elements were imported incorrectly with zero values as mentioned above.

I'm using the latest version of SAPLink and also the latest nugget for abap2xlsx - ABAP2XLSX_V_7_0_3

I've installed all the latest plugins for SAPlink also rev 113

**Comment by ivanfemia** [comment]
Please install the latest DTEL and DOMA plugins from assembla, they are not included in the SAPlink plugin nugget https://sap.assembla.com/code/saplink-plugins/subversion/nodes/127/trunk/DDic

**Comment by JMoulding1958** [comment]
Hi there,
if you have trouble with the plugin (see Ivan's post above) you can always open the main NUGG file in Notepad (or similar), search for the problem domains and figure out the domain definitions.  I seem to remember the two I had problems with were predefined as type String.
However, I'm going to try the new DDIC plugin, fingers crossed.
Cheers
John M.

**Comment by niz-yar** [comment]
Hi Ivan. Thanks for the link. I'm going to try those latest dtel & doma plugins then try reimport the abap2xlsx nugg. I really can't wait to see it in action ;-)

**Comment by niz-yar** [comment]
Hi. Just retried after installing as per your above link but it still does not work.
Tomorrow I'll see if its worth recreating each and every Domain + Element manualy. 
@JMoulding1958 - Unfortunately in my case its ALL of them :-(

.... trying again one more time. Reimporting the plugins and reactivating them then reimporting abap2xlsx. - Maybe I missed something. Tired :-)

**Comment by ivanfemia** [comment]
If it is all, I suspect the plugin... But it seems strange that you have this issue after importing the new ones...

I'll try to double check once I have a fresh ABAP system

**Comment by StefanSchmoecker** [comment]
Hello niz-yar,

I just tried to import one of those dataelements with the latest version from the DTEL-Plugin and it works fine.

@Ivan:  I looked into most of the dataelements and domains - we don't have translations into any other language at the moment.  Maybe you could install the previous versions of domain and dataelement plugins to avoid this problem.
( or in case of dataelements - I have a version of the corresponding plugin that supports translations but also adds some data to the slinkee that allows the older versions of the class to import as well ( they just lose the translation if any would exist ).  Drop me an email if you'd like to use the improved plugin because I want to do some final tests before uploading it to saplink )

**Comment by ivanfemia** [comment]
Updated slinkee and nugg using the previous version (so official saplink-plugin.nugg)

**Comment by niz-yar** [comment]
Hiya. I eventually got it installed and working. I'm very impressed. This is one heck of a brilliant tool.

Well done guys. well done!

Is there documentation anywhere? or should I just use the demo programs as documentation?
- E D I T - 
  After looking at the demos I think they are all pretty self explanatory. ;-)

**Comment by ivanfemia** [comment]
Perfect!

**Comment by becksen** [comment]
Hi I followed the advise to install the plugins from assembla. Unfortunately when importing slinkee files I always get the same error.

Plugin for object type HTML is not installed on this system

Therefore I can't import the ABAP2XLS plugin. Has anyone faced the same issue?
Thanks.

**Comment by gregorwolf** [comment]
Hello,

it's not a nice behaviour to cross post issues. Please check what I've replied to http://wiki.scn.sap.com/wiki/display/ABAP/SAPlink+User+Documentation?focusedCommentId=426546130#comment-426546130.

Best regards
Gregor
