### ISSUE TITLE
Dump in BIND_ALV -> CONVT_NO_NUMBER

### ISSUE THREAD

**Issue by juansebastiansoto** [abap2xlsx/abap2xlsx#357]
Hi group, I have the same issue that this post
https://www.assembla.com/spaces/abap2xlsx/messages/3357453
We are from Argentina.
I tried SET COUNTRY 'US'.
We need run the program in background. Then I can not change the Windows Regional Config.

The issue is in CONVERSION_EXIT_EXCRT_OUTPUT
The diferent is the number. We have  1,523.08000. (I send an question to the FI team)

Thanks in advance!!

Sebastián

**Comment by StefanSchmoecker** [comment]
Hello Sebastian,

I tried to reproduce the error from what I guessed you might have done but I received no error.

Please copy ABAP2XLSX Demoreport ZDEMO_EXCEL3 ( this is the one that demonstrates the BIND TABLE ) and use a table that consists of for example 3 lines with one field having the dataelement/value which causes the dump.
Please don't read the contents of the table from database but fill them manually in the code - this way we are able to reproduce the error in our system and may try to find/correct the error

Since you can't attach files here just post the coding with the definition of your table and the code that fills the few lines that cause the dump.

**Comment by juansebastiansoto** [comment]
Here the ZDEMO_EXCEL3 copy with the changes

_&---------------------------------------------------------------------_
_& Report  ZDEMO_EXCEL3
*&
*&---------------------------------------------------------------------_
_&
*&
*&---------------------------------------------------------------------_

REPORT  ydemo_excel3_bkpf.

TYPE-POOLS: abap.

DATA: lo_excel                TYPE REF TO zcl_excel,
      lo_worksheet            TYPE REF TO zcl_excel_worksheet,
      column_dimension        TYPE REF TO zcl_excel_worksheet_columndime.

DATA: ls_table_settings       TYPE zexcel_s_table_settings.

DATA: lv_title TYPE zexcel_sheet_title,
      lt_carr  TYPE TABLE OF scarr,
      row TYPE zexcel_cell_row VALUE 2,
      lo_range TYPE REF TO zcl_excel_range.
DATA: lo_data_validation  TYPE REF TO zcl_excel_data_validation.
FIELD-SYMBOLS: <carr> LIKE LINE OF lt_carr.

CONSTANTS: c_airlines TYPE string VALUE 'Airlines'.

CONSTANTS: gc_save_file_name TYPE string VALUE '03_iTab.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.

PARAMETERS: p_empty TYPE flag.

START-OF-SELECTION.
  " Creates active sheet
  CREATE OBJECT lo_excel.

  " Get active sheet
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_title( ip_title = 'Internal table').

  DATA lt_test TYPE TABLE OF bkpf. " Changed sflight.

  DATA: lw_test TYPE bkpf.

  IF p_empty <> abap_true.
-    SELECT \* FROM sflight INTO TABLE lt_test. "#EC CI_NOWHERE
  lw_test-kursf = '1523.08000'. " Added to test
  APPEND lw_test TO lt_test.    " Added to test
  ENDIF.
  
  ls_table_settings-table_style  = zcl_excel_table=>builtinstyle_medium2.
  ls_table_settings-show_row_stripes = abap_true.
  
  lo_worksheet->bind_table( ip_table          = lt_test
                            is_table_settings = ls_table_settings ).
  
  lo_worksheet->freeze_panes( ip_num_rows = 3 ). "freeze column headers when scrolling
  
  column_dimension = lo_worksheet->get_column_dimension( ip_column = 'E' ). "make date field a bit wider
  column_dimension->set_width( ip_width = 11 ).
  " Add another table for data validations
  lo_worksheet = lo_excel->add_new_worksheet( ).
  lv_title = 'Data Validation'.
  lo_worksheet->set_title( lv_title ).
  lo_worksheet->set_cell( ip_row = 1 ip_column = 'A' ip_value = c_airlines ).
  SELECT \* FROM scarr INTO TABLE lt_carr.               "#EC CI_NOWHERE
  LOOP AT lt_carr ASSIGNING <carr>.
    lo_worksheet->set_cell( ip_row = row ip_column = 'A' ip_value = <carr>-carrid ).
    row = row + 1.
  ENDLOOP.
  row = row - 1.
  lo_range            = lo_excel->add_new_range( ).
  lo_range->name      = c_airlines.
  lo_range->set_value( ip_sheet_name    = lv_title
                       ip_start_column  = 'A'
                       ip_start_row     = 2
                       ip_stop_column   = 'A'
                       ip_stop_row      = row ).
  " Set Data Validation
  lo_excel->set_active_sheet_index( 1 ).
  lo_worksheet = lo_excel->get_active_worksheet( ).
  
  lo_data_validation              = lo_worksheet->add_new_data_validation( ).
  lo_data_validation->type        = zcl_excel_data_validation=>c_type_list.
  lo_data_validation->formula1    = c_airlines.
  lo_data_validation->cell_row    = 4.
  lo_data_validation->cell_column = 'C'.

**\* Create output
  lcl_output=>output( lo_excel ).

**Comment by StefanSchmoecker** [comment]
Hello Sebastian,

I was able to reproduce your error and I believe that this is a variation of issue #320 

I have currently no idea how to solve this and the other error in an elegant way worthy of uploading but I guess I have a quick and dirty workaround for you.

Please go to method ZCL_EXCEL_WORKSHEET~GET_VALUE_TYPE and change the following lines:
Before:

``` ABAP
          CALL FUNCTION l_function
            EXPORTING
              input  = ip_value
            IMPORTING
*             LONG_TEXT  =
              output = l_value
*             SHORT_TEXT =
            EXCEPTIONS
              OTHERS = 1.
          IF sy-subrc <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
          ELSE.
             ep_value = l_value.
      ENDIF.
```

After ( added try-catch-block to pass input-value if conversion fails )

``` ABAP
          CALL FUNCTION l_function
            EXPORTING
              input  = ip_value
            IMPORTING
*             LONG_TEXT  =
              output = l_value
*             SHORT_TEXT =
            EXCEPTIONS
              OTHERS = 1.
          IF sy-subrc <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
          ELSE.
            TRY.
                ep_value = l_value.
              CATCH cx_root.
                ep_value = ip_value.
            ENDTRY.
          ENDIF.
```

Nothing to be proud of - but if it will prevent your dump it should be worth while.
Please let us know if this is sufficient.

---

live long and prosper
Stefan Schmöcker

**Comment by juansebastiansoto** [comment]
Thanks Stefan. I do it and dont crash again.
Only a more question.
The fix must be added to the public source code?

**Comment by StefanSchmoecker** [comment]
Good evening Sebastian,

actually I am afraid to upload this to github, because the problem it solves deserves a solution that has really been thought through. This is just a quick fix.
But since it prevents a crash I'll consider if I update the svn-directory next time I find time to upload a few changes.

**Comment by sandraros** [comment]
I'd say this bug has been fixed as you can see below (TRY-CATCH block added at least 5 years ago - [this PR in SAPlink format](https://github.com/sapmentors/abap2xlsx/commit/24515b3a0af29b1239ff1de681c15b79315ca2cc)), so we should close the issue: https://github.com/sapmentors/abap2xlsx/blob/3167c6a8f26ca21b353a8b342c2d9a62acfa3b15/src/zcl_excel_worksheet.clas.abap#L2930-L2948
