### ISSUE TITLE
Excel reports problem with content on display of an Abap2xlsx which is reloaded into SAP

### ISSUE THREAD

**Issue by IMAC1138** [abap2xlsx/abap2xlsx#358]
Hi Ivan
I create a spreadsheet with Abap2xlsx which I email out to the users.  This is filled in and emailed back to SAP.  The entries are processed and I also store the spreadsheet for audit purposes.  When I try to display the XLSX inplace using the stored raw data, this works however I have to ignore an error which Excel issues.

this is the sheet http://1drv.ms/1DlJSwX

This is the error message ...
![pic1](https://cloud.githubusercontent.com/assets/10880869/6078314/5f903714-adef-11e4-8211-089393d35841.png)

If he/she proceeds, Excel reports an error with the spreadsheet 
![pic2](https://cloud.githubusercontent.com/assets/10880869/6078341/8d2b3282-adef-11e4-9618-620cea3b0ed8.png)

the log of the error from Excel is not useful  - there is no error
![pic3](https://cloud.githubusercontent.com/assets/10880869/6078351/99b90966-adef-11e4-93ee-b842e62c5eec.png)

my code is as follows where LT_RAWDATA holds the raw XLSX info.
![pic4](https://cloud.githubusercontent.com/assets/10880869/6078358/a62481bc-adef-11e4-9c76-648e629a2b46.png)

**Comment by StefanSchmoecker** [comment]
Hello Dr. Manhatten,

how do you create the lt_rawdata?  Or more precise:  Do you store the excel that is being sent back directly or do you process/change it with ABAP2XLSX ( reading it and then using the writer to create the ouput counts as changing it ) before storing it?

---

live long and prosper
Stefan Schmöcker

**Comment by ivanfemia** [comment]
Usually that error is due to some blank spaces (0020) at the end of the file. 
Unfortunately the file on online drive is not corrupted.

Check code in include ZDEMO_EXCEL_OUTPUTOPT_INCL METHOD: download_frontend

Ivan

**Comment by StefanSchmoecker** [comment]
Hello Dr. Manhattan,

has your problem been solved by the hint Ivan gave?

Since nothing has happened on this issue for 3 weeks and there is no  way to reproduce the error I'll close this issue next week if we don't get an answer.

**Comment by IMAC1138** [comment]
Hi Stefan

Following Ivan's hint, I wrote a test ABAP which takes the stored data and downloads to a fresh XLSX and this works so the stored data is correct; no spurious characters at the end of the byte stream.  

Problem is in the SOI class which is not really your concern I guess ... I might get one of our ABAPers to debug this out but its low priority ... the principle functions of the system transferring data between SAP and external systems via XLSX works beautifully.

Close the incident with my thanks.

regards,Ian

**Comment by ivanfemia** [comment]
Thank you
