### ISSUE TITLE
How to measure size of an excel?

### ISSUE THREAD

**Issue by AllenSML** [abap2xlsx/abap2xlsx#359]
Hi Ivan,

Thanks for your effort devoted to this project. It really helped us a lot.
However we currently have a problem with sending Excel via Email.

There is a maximum size allowed of sending Email via SAPConnect. Therefore we want to strictly control size of excels generated. In case the maximum size is exceeded, the excel should be split into several excels, so that it could be sent as attachment via Email successfully.

We want to ask is there any method we could use to detect the size of a to be generated excel? 

Thanks in advance!

Shengmao

**Comment by ivanfemia** [comment]
HI Shenmao,

you can check the length of the binary string generated.

Check include ZDEMO_EXCEL_OUTPUTOPT_INCL

``` ABAP
 * After 6.40 via cl_bcs_convert
    cl_output->t_rawdata = cl_bcs_convert=>xstring_to_solix( iv_xstring  = cl_output->xdata ).
    cl_output->bytecount = xstrlen( cl_output->xdata ).

* before 6.40
*  CALL FUNCTION 'SCMS_XSTRING_TO_BINARY'
*    EXPORTING
*      buffer        = cl_output->xdata
*    IMPORTING
*      output_length = cl_output->bytecount
*    TABLES
*      binary_tab    = cl_output->t_rawdata.
```

Best 
Ivan

**Comment by AllenSML** [comment]
Hi Ivan,

Thanks for your quick reply. We will try that out!

Regards,
Shengmao
