### ISSUE TITLE
Mail attachement extention not correct

### ISSUE THREAD

**Issue by tomdupond** [abap2xlsx/abap2xlsx#360]
Hello experts,

I used the demo reports to send via email the excel sheet but I receive in my (Lotus or gmail) inbox the following extention "=03_iTab.xlsx.XLS".
I don't understand why the "XLS" is added! Is there any way to avoid this situation?

Best Regards,
Tom

**Comment by ivanfemia** [comment]
Are the demo reports working fine?

**Comment by tomdupond** [comment]
No. I only did the tests with the demo reports and it's not working.
The attachement contain ".XLS" in the mail within my Gmail inbox (or Lotus) but in SOST evething is ok.

**Comment by ivanfemia** [comment]
I've tested on a brand new 7.40 SP 4 the demo ZEXCEL_DEMO1.
No issue on sending, I would suggest with Basis Team to verify any configuration in SCOT that can may affect the sending.

Which SAP release are you using?

**Comment by tomdupond** [comment]
I will try to check this also with Basis Team...
SAP_BASIS on release 732 with SP4.

**Comment by ivanfemia** [comment]
Please let us know the solution maybe someone else in the community will face the same issue.

**Comment by hagen** [comment]
BCS api is old and dumb. When attachments were built into SAP emails, extensions we're only three characters. When sending an email using CL_DOCUMENT_BCS->ADD_ATTACHMENT, set the attachment type (i_attachment_type) to BIN. When doing this, ensure the .xlsx extension is inlcuded in the file name (ip_attachment_subject).
Cheers

**Comment by ivanfemia** [comment]
It seems strange because I used also in 7.01 and 7.02 (maybe also on 7.00 I don't remember)
@hagend which version are you using?

**Comment by hagen** [comment]
7.00 (I think). In any case, the advice is in reference to usage outside of the demo programs, in which case .xls extension just causes problems. Your examples append the &SO_FILENAME header parameter, which is also correct.
![image](https://cloud.githubusercontent.com/assets/5161952/6343052/367c2e3c-bc36-11e4-949e-6f50db53e1d2.png)

**Comment by gregorwolf** [comment]
Hello Hagend,
I hopy you've already applied Note 1459896 - BCS: Support for four-digit file name extensions to your system. If that does not help please check all the threads on SCN about sending .xlsx from ABAP.
Best regards
Gregor

**Comment by hagen** [comment]
Thanks @gregorwolf 
I haven't, but I've no need to - I can send xlsx happily using the BIN attachment type, which actually makes sense, because although the filename parameter is used, the note you mention indicates the attachment type still needs to be specified - for zipfiles (.xlsx), this would be binary 'BIN'. In any case, we are resolving @tomdupond 's issue, and I think the collection of suggestions here should do that :+1: FYI @ivanfemia I've also sent to a Gmail account using ZDEMO_EXCEL1, and the attachment opens just fine.

**Comment by StefanSchmoecker** [comment]
Is this still open?

I'll close this topic in 2 weeks if no one objects.

**Comment by StefanSchmoecker** [comment]
No follow up in the last 4 weeks - closed!
