### ISSUE TITLE
Various issues with cell merging

### ISSUE THREAD

**Issue by StefanSchmoecker** [abap2xlsx/abap2xlsx#361]
When merging cells and in doing so creating overlapping merges ( i.e:  Merging A1:B2 and B2:C3 --> overlapping in B2 ) we don't get an exception but the writer will create a corrupt file that Excel then marks with "unreadable content found".

Solution:  Raise an exception if the new merge is overlapping with an existing merge

**Comment by StefanSchmoecker** [comment]
Further issues:
- Method SET_MERGE: all input parameters are marked as optional - but omitting any will lead to unreadable content
- Method SET_MERGE:  Input parameters for columns are typed strictly.  We should use type "simple" like in almost all other methods where we can pass the column either in character or in integer format
- the way merges are stored is interesting but not very intuitive.  Unfortunately the relevant table holding the merge information is declared as "public".   Still I don't see anyone using that attribute directly instead of using method GET_MERGE or IS_MERGED.  <b>Any vetos from the community before I switch that parameter to private and change the way merges are stored internally</b>
- Method DELETE_MERGE has no parameters and deletes the first merge???  What is that good for?  I propose to add an optional input parameter where a cell can be passed and the merge containing that cell will be removed.   Not passing anything or an empty cell should then delete all merges
- Merging Cells will keep all information from the merged cells in the ouput-xlsx.  Opening that file will show the merged cells and the content from the top-left cell.  But when unmerging the cells the output is somewhat indifferent:
  Example:  
  Merging A1:D4 and setting data into A1,B2,C3,D4 - Unmerging will show all 4 values<br>
  Merging A1:D4 and setting data into ~~A1~~,B2,C3,D4 - Unmerging will put the value from B2 into A1<br>
  We should match EXCEL behaviour and save only the top-left cell-value when creating the output in ZCL_EXCEL_WRITER_2007

**Comment by ivanfemia** [comment]
Thank you Stefan to point out these issues...
I'm agree on your comments, I haven't check the code, but they make absolutely sense.
