### ISSUE TITLE
Readerclass / Datavalidations, Conditional formatting

### ISSUE THREAD

**Issue by StefanSchmoecker** [abap2xlsx/abap2xlsx#366]
Conditional formatting:  Output from DemoReport 5 will not be shown correctly when used with Demoreport 37 (passthrough ) --> probably the reader does not read conditional formatting

Data Validations:  Demoreport 9 is not correct:   The data validation for Cell B8 is not working
Data Validations:  Output from demoreport 9 will not be shown correctly when used with Demoreport 37 (passthrough ) .  Some data validations are preserved ( Fruits , Vegetables ... ) , but the data validations for cells A2 and A5 are being lost.     --> probably error in readerclass

**Comment by StefanSchmoecker** [comment]
Follow up:  
Not all conditional format types supported: Missing:  Top10, AboveAverage
Not all cell formats of conditional formats supported:  Missing: Borderstyles

**Comment by StefanSchmoecker** [comment]
Follow up:
Conditional formatting:  Mode expression:  Formatting only recognizes background, but no other cell formatting options

**Comment by StefanSchmoecker** [comment]
First efforts in svn-directory: Conditional formatting
Readerclass adapted to support conditional formatting,
added two new rule-types to conditional formatting ( "top10" and "above average", 
changed writerclass to have a uniform way of writing dxfs-styles ( needed for conditional formatting ) 
Still no support of borderstyles in conditional formats, postponed until whenever I'll need this
Still no corrections of data validations - work in progress....

**Comment by GUTHM** [comment]
Hello, 
It seams field CELL_STYLE is missing in structure ZEXCEL_CONDITIONAL_TOP10 but used in Class ZCL_EXCEL_WRITER_2007,Method CREATE_XL_SHEET !
This is causing a syntax error.
Best Regards,
Mat

**Comment by StefanSchmoecker** [comment]
Error:  When a conditional style is applied to multiple areas, we get a dump in the reader
Error:  When conditional style has no end column we get a dump we get a dump in the reader
Error:  Multiple CellIs-conditions are not read - only the first

Example area which causes the problem: 
C18 E18:H18 L18 P18 T18 H16 P26:P28

**Comment by StefanSchmoecker** [comment]
Some issues solved with latest build - I'll update the topic to reflect which problems remain and which have been solved

**Comment by sandraros** [comment]
No more issue here: both `ZDEMO_EXCEL5` and read/write of the generated file via `ZDEMO_EXCEL37` give the same result:
![image](https://user-images.githubusercontent.com/34005250/151705257-e8ffcdb1-f2b2-413f-a728-3fa32edb07b2.png)

`ZDEMO_EXCEL9` has indeed an issue with the formula. I have just created #983 to clarify it.

No more issue here: both `ZDEMO_EXCEL9` and read/write of the generated file via `ZDEMO_EXCEL37` give the same result (both for A2 and A5):
![image](https://user-images.githubusercontent.com/34005250/151706982-d593b17a-6286-4193-97f9-db6ee5e7a66a.png)

I close this current issue. If you disagree, please reopen it and tell the reason. Thanks!
