### ISSUE TITLE
Excel file from application server into internal table (data in internal table readable format)

### ISSUE THREAD

**Issue by destinationpraveen** [abap2xlsx/abap2xlsx#370]
Hi Ivan,

We have a requirement to download excel file data from application server into internal table in readable format.We have downloaded data using OPEN DATASET in BINARY Mode and while converting it to BINARY to TEXT format we are getting junk characters.

We want excel data in tabular format with readable characters.

When we are downloading this binary data using FM C13Z_DOWNLOAD then same excel gets downloaded correctly same as what was uploaded but when we are trying to convert binary data of excel into text format we are getting junk characters.

Do you have any solution for our requirement?

Thanks in advance.

BR,
Praveen

**Comment by StefanSchmoecker** [comment]
This topic is 6 weeks old.  No one answered yet.
Praveen - I fear your question was not understood by us or we don't think it's a ABAP2XLSX error but maybe a handling error of SAP file-system.

Please provide more precise information about what's going wrong.

I'll close this issue in 2 or 3 weeks if no answers or clarifications appear.

**Comment by destinationpraveen** [comment]
Hi Stefan,

Please close this issue.

I have solved it,

Regards,
Praveen

**Comment by zakir2397** [comment]
Hi praveen,
                      Even I have the requirement of coverting excel to itab in background. I used the procedure mentioned below
[https://praveensg8.files.wordpress.com/2015/04/reading-excel-file-from-application-server-into-abap-internal-table_1.pdf](url)
 .after final Transformation I am getting blank Internal table,

One doubt I have is in the tranformation mentioned in the above link in place of <EXCEL_DATA-FIELD1> what I need to use is this internal table field name or Excel heading name.

**Comment by sandraros** [comment]
@zakir2397 Please don't post here questions which are not related to abap2xlsx. I will delete any further comment. Thanks for your understanding.
