### ISSUE TITLE
METHOD ZCL_EXCEL_CONVERTER->GET_FILE

### ISSUE THREAD

**Issue by wanlihong** [abap2xlsx/abap2xlsx#371]
THE METHOD ZCL_EXCEL_CONVERTER->GET_FILE, as method "write_file" is unkown or PROTECT or PRIVATE break out for active operate.

**Comment by ivanfemia** [comment]
Are the demo reports working properly?

**Comment by wanlihong** [comment]
No, All interface are activated, after some class as method xxx is unknown or PROTECT or PRIVATE interrupt activate. so the demo reports has not been activated.

**Comment by StefanSchmoecker** [comment]
Does demoreport ZDEMO_EXCEL1 work?  Or just the demoreports which use the converterclass?

**Comment by StefanSchmoecker** [comment]
Hello wanlihong,

do you still encounter the problem or did you solve it?
I'll leave this issue open for 2 more weeks - after that I'll assume it to be solved and close it

**Comment by sandraros** [comment]
Let's do what Stefan proposed some time ago → closing...
