### ISSUE TITLE
BIND_ALV_OLE2 doesn't use background colors 

### ISSUE THREAD

**Issue by klha** [abap2xlsx/abap2xlsx#373]
Hello

If I set the background color of an ALV Grid with the structure LVC_T_SCOL,
how can the zcl_excel_worksheet->bind_alv_ole2() method be forced to tranfer this information to the created Excel table?

**Comment by ivanfemia** [comment]
Bind_alv_ole2 should not be used, please use bind_alv instead

**Comment by klha** [comment]
And bind_alv will transfer the background color of the ALV grid into the Excel sheet cells?

**Comment by ivanfemia** [comment]
It should
