### ISSUE TITLE
zdemo_excel1 not working in background

### ISSUE THREAD

**Issue by hcolor** [abap2xlsx/abap2xlsx#374]
hi,

i  run the report on fornt and it's fine save in D:1.xls  
but when i tried in background i see in sm37 that the job finished and the file is not created..

i change gc_save_file_name TYPE string VALUE '01_HelloWorld.xlsx  to  D:1.xls  ..

what's is my problem...

**Comment by ivanfemia** [comment]
":" is not allowed as character by the file system.

**Comment by hcolor** [comment]
So what i will do...

i want to save it in directory in the example is file only...

**Comment by ivanfemia** [comment]
This is not related to abap2xlsx, but it is basic ABAP coding to save an xstring to file into a folder with a desired filename.
I would suggest to ask on SCN ABAP developer space a lot of people will help you with that.

**Comment by hcolor** [comment]
i tried a directory in file system without ':'  \sap\dir\01_HelloWorld.xlsx  and not work too....

**Comment by hcolor** [comment]
Ivan it's related to abap2xlsx i'm trying to download example of abap2xlsx, when you run ZDEMO_EXCEL1
in background where it save it in your system..?>>>>

**Comment by ivanfemia** [comment]
in the temp directory on the application server. 
Match your DIR_TEMP in AL11

**Comment by hcolor** [comment]
thanks i saw it...

now i want to put it in other directory.. what should i write....

**Comment by ivanfemia** [comment]
You can't save a background job stream in the frontend (your HD)

**Comment by hcolor** [comment]
Nice.....
Ivan i change gc_save_file_name TYPE string VALUE '\sap\dir\01_HelloWorld.xlsx' and it is not working....
and when it gc_save_file_name TYPE string VALUE '01_HelloWorld.xlsx'  it save in DIR_TEMP 
what i need to do if i want it in another background directory ...

Ivan why are angry...

**Comment by ivanfemia** [comment]
Angry?

Check include ZDEMO_EXCEL_OUTPUTOPT_INCL
METHOD download_backend.
OPEN DATASET p_backfn FOR OUTPUT IN BINARY MODE.

p_backfn contains the full path

That it is initialized in the INITIALIZATION 
  p_backfn = gc_save_file_name.  " Use as default if nothing else is supplied by submit

**Comment by hcolor** [comment]
Ivan you don't inderstand me...

I will ask other qa..

I want to save the file in /SAP/DIR/TEMP/ 01_HelloWorld.xlsx  how i can make it...>>

**Comment by ivanfemia** [comment]
Change the code and adjust the p_backfn  path accordingly.
I did a test in my system and worked perfectly.

Instead of 
p_backfn = gc_save_file_name. " Use as default if nothing else is supplied by submit

use 
CONCATENATE '/SAP/DIR/TEMP/ ' gc_save_file_name INTO gc_save_file_name.

Those are just demo examples, the functionality you are requesting is not related to the abap2xlsx framework (generation of the excel xstring), but it is related to the implementation of your logic in order to consume the file.

**Comment by hcolor** [comment]
1. The field gc_save_file_name can not be change.
2. I made it in another parameter and i get sy-subrc 8 ...

About my request, thats how our users work they want to put it in spesipic directory so Prinboss or websphere took the file and go on....

**Comment by gregorwolf** [comment]
Dear hcolor,

for writing to the application server you always should use logical path definitions. They can be customised in transaction FILE. Please talk to your basis admin to do that. That will allow you to de-couple the actual location on the app-server from your logic. Please check SCN for examples on how to retrieve the actual path from the logical path. If you have further questions regarding writing to the app server please get advise from a senior ABAP programmer colleague.

Best regards
Gregor

**Comment by StefanSchmoecker** [comment]
No ABAP2XLSX error but incorrect usage of DEMO!reports.
