### ISSUE TITLE
READ_SHARED_STRINGS carries previous value if t element is empty

### ISSUE THREAD

**Issue by KaiWalter** [abap2xlsx/abap2xlsx#376]
I have an Excel file which has an empty element <t/> (after <t>0120</t>) in the shared strings

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="25" uniqueCount="19"><si><t>MANDT</t></si><si><t>/BIC/AGFIR8046</t></si><si><t>/BIC/AGFIR1510</t></si><si><t>/BIC/AGFIR8041</t></si><si><t>FISCPER</t></si><si><t>/BIC/AGFIR8014</t></si><si><t>/BIC/AGFIR8003</t></si><si><t>/BIC/AGFIR8021</t></si><si><t>AMOUNT</t></si><si><t>035</t></si><si><t>YEC</t></si><si><t>MEC</t></si><si><t>2014</t></si><si><t>2014012</t></si><si><t>0872</t></si><si><t>0120</t></si><si><t/></si><si><t>M026951</t></si><si><t>M027110</t></si></sst>

When parsing the file with ZCL_EXCEL_READER_HUGE_FILE the empty value is not recognized and the value 0120 is carried on.  I then have 0120 twice in the shared strings table and cells in the worksheet which are supposed to have no value have 0120 as value.

In an own class which I inherited from ZCL_EXCEL_READER_HUGE_FILE I added an attribute
C_ELEMENT_VALUE Type=IF_SXML_NODE=>NODE_TYPE Value=F_SXML_NODE=>CO_NT_VALUE
and redefined & fixed the method READ_SHARED_STRINGS:
method read_shared_strings.

  data lv_value type string .

  while io_reader->node_type ne c_end_of_stream.

```
io_reader->next_node( ).

if io_reader->name eq `t`.
  case io_reader->node_type .

    when c_element_open .
      clear lv_value .

    when c_element_value .
      lv_value = lv_value && io_reader->value .

    when c_element_close .
      append lv_value to et_shared_strings.

  endcase .
endif.
```

  endwhile.

endmethod.

Let me know if I can help fixing this issue. I can also provide a stripped down sample file to test the issue.

**Comment by rplantiko** [comment]
Hello Kai, 

thanks for pointing out this bug and solution proposal. I could reproduce the problem with the following unit test. I will try to make the fix within the next days.

``` abap
  method test_shared_string_some_empty.
    data: lo_reader type ref to if_sxml_reader,
          lt_act type stringtab,
          lt_exp type stringtab.
    lo_reader = cl_sxml_string_reader=>create( cl_abap_codepage=>convert_to(
      `<sst><si><t/></si>` &
      `<si><t>Alpha</t></si>` &
      `<si><t/></si>` &
      `<si><t>Bravo</t></si></sst>`
      ) ).
    append :
     `` to lt_exp,
     `Alpha` to lt_exp,
     ``      to lt_exp,
     `Bravo` to lt_exp.

    lt_act = out->read_shared_strings( lo_reader ).

    assert_equals( act = lt_act
                   exp = lt_exp ).

  endmethod.
```

`lt_act` contains `('','Alpha','Alpha','Bravo')` which is wrong - should be `('','Alpha','','Bravo')`. 

Regards,
Rüdiger

**Comment by rplantiko** [comment]
Fixed with 

https://github.com/ivanfemia/abap2xlsx/commit/959b02aa1264308025b2aaa659a9111669dfd765

(I followed the fix you suggested).
