### ISSUE TITLE
Possibility to add Page Break in XLSX

### ISSUE THREAD

**Issue by GUTHM** [abap2xlsx/abap2xlsx#377]
Hello,

Thanks for the great work on ABAP2XLSX.
I have the need to add Page Breaks on defined rows (above new sections) to improve the printout result.
Is this possible with current version of ABAP2XLSX and if not can this function be added ?

Thanks,
Mat

**Comment by StefanSchmoecker** [comment]
Hello Mat,

this feature is currently not supported by us.  
I didn't even know that Excel had this feature but google helped me out and I made a rough test whether this is supportable or not.   Basically it looks like this is not really complicated to accomplish.

Would you like to contribute and provide a solution for this by yourself?

**Comment by StefanSchmoecker** [comment]
Hello Mat,

I saw that were syntax-errors in the current version of the writer- and the readerclass so I just fixed those and added minimal support of pagebreaks for reader- and writerclass.

If you want to use this, please update to the latest version of ABAP2XLSX - at least the following 4 classes:
ZCL_EXCEL_READER_2007
ZCL_EXCEL_WRITER_2007
ZCL_EXCEL_WORKSHEET
ZCL_EXCEL_WORKSHEET_PAGEBREAKS ( this is new )

To add a pagebreak:

``` ABAP
lo_pagebreaks = lo_worksheet->get_pagebreaks( ).
lo_pagebreaks->add_pagebreak( ip_row    = 7
                              ip_column = 'D' ).
```

Please indicate if this fixes your problem - if yes please close this issue.

**Comment by GUTHM** [comment]
Hi Stefan, 
Thanks for your reply and help.
I will try to test this in the coming days and let you know.
Best regards,
Mat

**Comment by GUTHM** [comment]
Hi Stefan,

I imported all last versions in our sandbox and had to fix 2 issue first :
**1. Syntax error** : Class ZCL_EXCEL_WRITER_2007,Method CREATE_XL_SHEET the data object "LS_CONDITIONAL_TOP10" does not have a component called "CELL_STYLE".

> **Fix**: I added field CELL_STYLE in structure ZEXCEL_CONDITIONAL_TOP10
>      Is file ZA2X\TABL\ZEXCEL_CONDITIONAL_TOP10.slnk up to date ? This is Linked to issue 366, I added a comment there also.

**2. Syntax error** : Class ZCL_EXCEL_WRITER_2007,Method CREATE_XL_SHEET Formal parameter "IO_WORKSHEET" does not exist.

> **Fix**: I changed code in Method CREATE_XL_SHEET to reverted back part of your change :
> - \*        lv_guid                     TYPE uuid,
> - \*  lv_guid        = io_worksheet-&gt;get_guid( ) .
> -  lo_autofilter  = lo_autofilters->get( io_worksheet = io_worksheet ) .
> +         lv_guid                     TYPE uuid,
> +   lv_guid        = io_worksheet-&gt;get_guid( ) .
> +  lo_autofilter  = lo_autofilters-&gt;get( i_sheet_guid = lv_guid ) .

Once both errors have been fixed the Page break test is successfull for me.
I leave the ticket open so that you can fix the 2 points described above.

Thanks,
Mat

**Comment by StefanSchmoecker** [comment]
Hello Mat,

thank you for your hints.  Looks like I messed or forgot when checking in the structureenhancement of ZEXCEL_CONDITIONAL_TOP10 and update to class ZCL_EXCEL_AUTOFILTERS

**Comment by becksen** [comment]
Was this issue fixed already?
In Method CREATE_XL_SHEET at line 728

lo_autofilter  = lo_autofilters->get( i_sheet_guid = io_worksheet->get_guid( ) ).

I get the error:
Class ZCL_EXCEL_WRITER_2007,Method CREATE_XL_SHEET  728 @0A\QError@
Unable to interpret "IO_WORKSHEET->GET_GUID(". Possible causes:  
Incorrect spelling or comma error.      

I was trying hard but couldn't find the mistake.

Thanks.
