### ISSUE TITLE
Multiple style at a cell

### ISSUE THREAD

**Issue by canhbn** [abap2xlsx/abap2xlsx#378]
Dear team,
I have a requirement format Bold for a part of a cell. Could you please tell me how I solve that. Thank you.
![abap2xlsx_multiple style at a cell](https://cloud.githubusercontent.com/assets/12727157/8029657/bf2c4f14-0de9-11e5-9955-66c5c8eab746.jpg)

**Comment by ivanfemia** [comment]
I don't think this functionality is supported yet.
You can propose a fix to the framework in order to include also this functionality.

Ivan

**Comment by StefanSchmoecker** [comment]
I definintly know that we don't support this at the moment.
We have adjusted the Readerclass in the past to be able to parse the stringtable correctly even if we encounter this when reading an excel template - but no attempts have been made to my knowledge to support this when creating a new excel.
