### ISSUE TITLE
Obsolete Functioncalls in ABAP2XLSX

### ISSUE THREAD

**Issue by StefanSchmoecker** [abap2xlsx/abap2xlsx#379]
I just received a comment from Stefan Schnell, that on newer releases in SAP the function GUID_CREATE is flagged as obsolete.  Unfortunately the replacement - call the method  cl_system_uuid=>if_system_uuid_static~create_uuid_x16 is not available on a 7.01 Release.

Now we have a problem that on one hand we are unable to switch to the new version of creating a guid because of older releases and that on newer releases ABAP2XLSX gets into conflict with Code-Inspector / Extended syntax checks checks that mention that the function may not be used.

Suggestions for a workaround ( and for further function calls that may - over time - become flagged if necessary ).

a)  Create a variable ( no constant ) in ZCL_EXCEL_COMMON called funcname_guid_create and replace 

``` ABAP
  CALL FUNCTION 'GUID_CREATE'
    IMPORTING
      ev_guid_16 = rd_guid.
```

with 

``` ABAP
  CALL FUNCTION zcl_excel_common=>functionname_guid_create
    IMPORTING
      ev_guid_16 = rd_guid.
```

b)  Create a class with a method that wraps the function call.  Replace all (4) uses of the function module with this new wrapper.  Whoever is using a newer system and is encountering problems with his transport management due to the code-inspector flagging should replace the coding then by using the new version which we might provide ourselves just commented out ( like in SAP does in class CL_RECA_GUID=>GET_NEW_GUID on a 7.01 system )

``` ABAP
METHOD get_new_guid .
*  DATA:
*    lo_exc TYPE REF TO cx_uuid_error.
*
** BODY
*  TRY.
*    rd_guid = cl_system_uuid=>if_system_uuid_static~create_uuid_x16( ).
*  CATCH cx_uuid_error INTO lo_exc.
*    MESSAGE lo_exc TYPE 'X'.
*  ENDTRY.

* old method: using the function module
  CALL FUNCTION 'GUID_CREATE'
    IMPORTING
      ev_guid_16 = rd_guid.

ENDMETHOD.
```

c)  Create two classes with a method that wrap the function call.  Create an abstract factory (in ZCL_EXCEL_COMMON) that returns the systemrelevant class.  Replace all (4) uses of the function module with this new wrapper. The end user can delete the class that annoys the code inspector and the abstract factory should be able to find the best/remaining version for the system used. 

All three suggestions have their merits and drawbacks.  
Please comment how to solve this issue - maybe by adding further suggestions.

**Comment by ivanfemia** [comment]
Hi Stefan,

I prefer to use just the new syntax and comment the old one
- if you run on a lower release ( < NW 7.01   ) use this code.

The idea of a wrapping method will help to maintain all these changes in one point.

IVan

**Comment by StefanSchmoecker** [comment]
Fixed with revision 455
