### ISSUE TITLE
aba2xlsx V 7 0 3 not upload in abap 7.4 SP08

### ISSUE THREAD

**Issue by sikkenb** [abap2xlsx/abap2xlsx#381]
i am trying to upload this nugg file and get 
"Error occurred during character conversion"...

**Comment by ivanfemia** [comment]
Are you using the latest SAPLink version?

**Comment by sikkenb** [comment]
Sorry ,, i add new one...

yes i'm sure...
 i upload abap2xlsx in our old system sp05 and work's fine...
 if you want me to check again...
 tell me what a knew objects is in and i will check...

**Comment by sikkenb** [comment]
i have this version  "SAPlink-plugins_Daily.nugg"

**Comment by ivanfemia** [comment]
No new objects, just changes and fixes to the code.
I would suggest to uninstall saplink and its components (delete from SE80) and also abap2xlsx and start with a new installation using the latest versions.

Ivan

**Comment by sikkenb** [comment]
what is the new version ??  "SAPlink-plugins_Daily.nugg" or i need to  upload NUGG_SAPLINK-0.1.4.nugg and after that SAPlink-plugins_Daily.nugg...

Any one made it in 7.4 sp08...

**Comment by Gh14Cc10** [comment]
Hi sikkenb, download and install the lastest daily nugg version 7.0.4

**Comment by sikkenb** [comment]
Thanks ...

i downlod SAPlink-plugins_Daily.nugg

**Comment by sikkenb** [comment]
and version 7.4 and get message
"Plugin for object type TABL is not installed on this system"
"Plugin for object type INTF is not installed on this system
Plugin for object type MSAG is not installed on this system""

**Comment by Gh14Cc10** [comment]
Hi,
download and install the right plugins for SAPLink from the official saplink website

**Comment by sikkenb** [comment]
i download it as you say from saplink.org

**Comment by gregorwolf** [comment]
Please get the missing Plugins from http://plugins.saplink.org

**Comment by sikkenb** [comment]
hi.. i am happy you wrote for me...
i made as you say in the saplink.or
"you can find SAPlink-plugins_Daily.nugg.zip which is the always latest and greatest"...
i remind you i am in abap 7/4 sp08...

**Comment by gregorwolf** [comment]
SAPlink should work on 7.40 SP08 but as you mentioned before your error is:

"Plugin for object type TABL is not installed on this system"
"Plugin for object type INTF is not installed on this system
Plugin for object type MSAG is not installed on this system""

You should find them at http://plugins.saplink.org

**Comment by sikkenb** [comment]
I search and not find.... do you find it??

**Comment by sikkenb** [comment]
I understand you...

when i click on " DDic - Data dictionary objects (DTEL, DOMA, TABL, TTYP) "..

i ger error page...

**Comment by Gh14Cc10** [comment]
here the link to download the plugins

https://www.assembla.com/code/saplink-plugins/subversion/nodes/133/build

**Comment by sikkenb** [comment]
thanks... champion... it's work..

**Comment by Gh14Cc10** [comment]
welcome :)
