### ISSUE TITLE
QA : Problem in activate the CLASS

### ISSUE THREAD

**Issue by sikkenb** [abap2xlsx/abap2xlsx#387]
i download abap2xlsx 7_0_4 in abap 7.4...

i made this steps 
https://github.com/ivanfemia/abap2xlsx/wiki/Installation-guide

and i get error when activate the class i get message "type ZEXCEL_T_FIELDCATALOG is unknown"

In step 5 there is written "5.Activate all interface/classes (activate anyway)"
and in 4. Types except: ZEXCEL_T_FIELDCATALOG so what i need to do..

PLS...

Hellppppp

**Comment by ivanfemia** [comment]
As stated in point 5 activate anyway.

**Comment by sikkenb** [comment]
Yes.. but now i can not activate step 6.. and it not given me  popup to ask me if activate any way..
i get error :  Field ROW_DIMENSION: Used reference type ZCL_EXCEL_WORKSHEET_ROWDIMENSI is not active

**Comment by sikkenb** [comment]
It's ok.. sorry i made step 6 as you mention and work....

**Comment by StefanSchmoecker** [comment]
OP stated problem to be solved.  Closed
