### ISSUE TITLE
Performance of Method Call SET_ATTRIBUTE_NC in CREATE_XL_SHEET of ZCL_EXCEL_WRITER_2007

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#388]
Hello community,

I want to create an Excel file from a great table, near by 500.000 records, but the program dumps with a timout error. I performed a runtime analysis and the result is that 44% of the runtime needs the method call lo_element_3->set_attribute_ns.

![001](https://cloud.githubusercontent.com/assets/13049097/8405780/43c7b6fa-1e57-11e5-9db6-affd2b431af9.jpg)

This is a result "only" from 50391 records with 24 fields in the table.

Is there a way to reduce the time consumption of the method call set_attribute_ns in the method CREATE_XL_SHEET of the class ZCL_EXCEL_WRITER_2007?

Thanks for hints.

Best regards
Stefan

**Comment by StefanSchmoecker** [comment]
Hello Stefan,

have you tried using the class "ZCL_EXCEL_WRITER_HUGE_FILE" instead of "ZCL_EXCEL_WRITER_2007".

It may not support all features but it should be faster and might be sufficient to fulfill your needs.

**Comment by ghost** [comment]
Hello Stefan,

thank you very much for your tip. I implement the class and the XSL transformations. The first run time analysis shows in my case a 12 times faster writing with 131.072 records :+1:
Now I transport the objects to the development system and try it with the same test cases. I will report my results later.

Thanks again.

Best regards
Stefan

**Comment by ghost** [comment]
Hello Stefan,

as you can see in comparisation to my previous measurement 42% faster over all.

![image](https://cloud.githubusercontent.com/assets/13049097/8430318/9aab597a-1f30-11e5-8186-63ccc96ef10f.png)

Now another question in the context of huge writer class: Is it necessary to change the creation of the table, set an attribute or anything else? The code, which works with WRITER_2007 perfect, doesn't work with WRITER_HUGE, it generates corrupted XLSX files.

Here my code:
  Create Object l_rcl_excel.
  l_rcl_worksheet = l_rcl_excel->get_active_worksheet( ).
  l_rcl_worksheet->set_title( Me->WORKSHEET_TITLE ).
  l_str_table_settings-table_style  = Me->TABLE_STYLE.
  l_rcl_worksheet->bind_table( ip_table          = i_table
                               is_table_settings = l_str_table_settings ).
  Create Object l_rif_excel_writer Type /GKV/CA03_cl_writer_huge.
  e_xlsx_datastream = l_rif_excel_writer->write_file( l_rcl_excel ).

Thanks again.

Best regards
Stefan

**Comment by ivanfemia** [comment]
Hi Stefan,

as mentioned by Stefan, not all the functionalities are available with that reader.
Could you please provide more details on the error that you are getting?

Ivan

**Comment by ghost** [comment]
Hello Ivan,

thanks for your reply. I get no error, I get only a corrupted XLSX file. You can try this report to reproduce my error:

```
Report ZTTTEST.

"-Structures--------------------------------------------------------
  Data: Begin Of TestStruc,
          ElemInt  Type i,
          ElemPack Type p,
          ElemFlt  Type f,
          ElemStr  Type String,
        End Of TestStruc.

"-Variables---------------------------------------------------------
  Data l_str_Test Like TestStruc.
  Data l_tab_Test Like Standard Table Of TestStruc.
  Data l_GUID Type SYSUUID_C.
  Data l_rcl_excel Type Ref To ZCL_EXCEL
  Data l_rcl_worksheet Type Ref To ZCL_EXCEL_WORKSHEET.
  Data l_rif_excel_writer Type Ref To ZIF_EXCEL_WRITER.
  Data l_cnt_Lines Type i Value 0.
  Data l_xlsx_datastream Type XString.
  Data l_FileName Type FILEEXTERN.

"-Main--------------------------------------------------------------
  Do 1024 Times.
    l_str_Test-ElemInt = sy-index.
    l_str_Test-ElemPack = sy-index * 1000.
    l_str_Test-ElemFlt = sy-index * '3.14'.
    l_str_Test-ElemStr = `Dies ist ein Test ` && sy-index.
    Append l_str_Test To l_tab_Test.
  EndDo.

  If l_tab_Test Is Not Initial.
    Describe Table l_tab_Test Lines l_cnt_Lines.
    If l_cnt_Lines <= 1048576.
      Create Object l_rcl_excel.
      l_rcl_worksheet = l_rcl_excel->get_active_worksheet( ).
      l_rcl_worksheet->bind_table( ip_table = l_tab_Test ).
      "The WRITER_2007 generates a perfect XLSX file
      "Create Object l_rif_excel_writer Type ZCL_EXCEL_writer_2007.
      "The WRITER_HUGE generates a corrupted XLSX file
      Create Object l_rif_excel_writer Type ZCL_EXCEL_writer_huge.
      l_xlsx_datastream = l_rif_excel_writer->write_file( l_rcl_excel ).

      l_GUID = cl_system_uuid=>CREATE_UUID_C32_STATIC( ).
      l_FileName = '/FTPSAP/NSP/001/TMP/' && l_GUID.
      Open Dataset l_FileName For Output In Binary Mode.
      Transfer l_xlsx_DataStream To l_FileName.
      Close Dataset l_FileName.

    EndIf.
  EndIf.
```

![image](https://cloud.githubusercontent.com/assets/13049097/8432102/460014a2-1f3e-11e5-9b47-07a95838349f.png)

![image](https://cloud.githubusercontent.com/assets/13049097/8432111/54d478d8-1f3e-11e5-922a-967bb2ed1f1d.png)

Thanks and best regards
Stefan

**Comment by StefanSchmoecker** [comment]
Hello Stefan,

it looks like the transformation ZEXCEL_TR_SHEET causes this problem.
Please try to replace the following line - seems to be a spelling error.  Unfortunately I don't have enough experience with transformations to know if this really causes problem - but if it fixes yours please let us know and we change the current transformation

Transformation: ZEXCEL_TR_SHEET - current version

``` XML
      <tt:cond check="WORKSHEET.TABLES_COUNT != 0">
        <mergeCells>
          <tt:attribute name="count" value-ref="WORKSHEET.TABLES_COUNT" />
          <tt:loop ref="WORKSHEET.TABLES">
            <tablePart>
              <tt:attribute name="r:id" value-ref="R_ID" />
            </tablePart>
          </tt:loop>
        </mergeCells>
      </tt:cond>
```

The tag "mergeCells" should be changed to "tableParts"

``` XML
      <tt:cond check="WORKSHEET.TABLES_COUNT != 0">
        <tableParts>
          <tt:attribute name="count" value-ref="WORKSHEET.TABLES_COUNT" />
          <tt:loop ref="WORKSHEET.TABLES">
            <tablePart>
              <tt:attribute name="r:id" value-ref="R_ID" />
            </tablePart>
          </tt:loop>
        </tableParts>
      </tt:cond>
```

**Comment by StefanSchnell** [comment]
Hallo Stefan,
vielen Dank. Zur Zeit bin ich gerade in Urlaub und habe keinen Zugriff auf unser System. Melde mich wenn ich wieder da bin. Nochmals Danke und beste Grüße
Stefan 

Von meinem Windows Phone gesendet

----- Ursprüngliche Nachricht -----
Von: "StefanSchmoecker" <notifications@github.com>
Gesendet: ‎11.‎07.‎2015 09:47
An: "ivanfemia/abap2xlsx" <abap2xlsx@noreply.github.com>
Cc: "Stefan Schnell" <mail@stefan-schnell.de>
Betreff: Re: [abap2xlsx] Performance of Method Call SET_ATTRIBUTE_NC in CREATE_XL_SHEET of ZCL_EXCEL_WRITER_2007 (#388)

Hello Stefan,

it looks like the transformation ZEXCEL_TR_SHEET causes this problem.
Please try to replace the following line - seems to be a spelling error.  Unfortunately I don't have enough experience with transformations to know if this really causes problem - but if it fixes yours please let us know and we change the current transformation

Transformation: ZEXCEL_TR_SHEET - current version
```XML
      <tt:cond check="WORKSHEET.TABLES_COUNT != 0">
        <mergeCells>
          <tt:attribute name="count" value-ref="WORKSHEET.TABLES_COUNT" />
          <tt:loop ref="WORKSHEET.TABLES">
            <tablePart>
              <tt:attribute name="r:id" value-ref="R_ID" />
            </tablePart>
          </tt:loop>
        </mergeCells>
      </tt:cond>
```
The tag "mergeCells" should be changed to "tableParts"
```XML
      <tt:cond check="WORKSHEET.TABLES_COUNT != 0">
        <tableParts>
          <tt:attribute name="count" value-ref="WORKSHEET.TABLES_COUNT" />
          <tt:loop ref="WORKSHEET.TABLES">
            <tablePart>
              <tt:attribute name="r:id" value-ref="R_ID" />
            </tablePart>
          </tt:loop>
        </tableParts>
      </tt:cond>
```

---

**Comment by ghost** [comment]
Hello Stefan,
thanks for your solution, but it doesn't solve the problem.

So it looks with Writer2007:
![001](https://cloud.githubusercontent.com/assets/13049097/8977686/9285561a-369b-11e5-8776-f1a75acb36a1.jpg)

And so it looks with HugeWriter and your correction:
![001](https://cloud.githubusercontent.com/assets/13049097/8977732/da6259d8-369b-11e5-983b-55f9b0598221.jpg)

Thanks again and best regards
Stefan

**Comment by StefanSchmoecker** [comment]
Stefan,
please try latest build.  Your demo program works with the huge-writer for me.

I'll keep this issue open, since there is a major performance issue with the 2007-Writer.  After some discussion with Marcus von Cube, the author of the Huge-Writer  and some precious hints from his side I'm going to do some intensive runtime checks and try some changes to alleviate some of the problems the 2007-writer is encountering so that we finally get a version that creates excel-sheets in acceptable time but is still supporting all features.
See screenshot of analysis - comparing writer-2007 vs. huge-writer vs. no output all in a double logarithmic scale graph
I also added a line with linear growth to compare against.
![runtime writerclasses](https://cloud.githubusercontent.com/assets/10195656/9154969/c87180a0-3ea7-11e5-8b8f-a20656e2bbaa.png)
As you can see - the creation of the excel itself scales linear, as does the huge writer.  But the 2007-writer experiences severe performance slump with the average time to create a line declining.  
As I am told this is most likely due to the ixml-routines that are getting slower and slower when building a gigantic xml.  
I'll do some testing and try to get the writer-2007 to at least behave more or less in a linear way the way the huge writer does.

**Comment by ghost** [comment]
Hello Stefan,

thank you very much for your activities and for your solution. The HugeWriter works now with my test program perfect. It needs in my case with 1k records approximately 25% of the time from the Writer2007 and it produces an error-free result.

Stefan, many thanks for your great support. I know you spend a lot of time to create this solution, thank you for that. It is superb to work with you.

Thanks and best regards
Stefan

**Comment by sandraros** [comment]
I guess we may close this issue as it's 6 years old and seems to be solved.
