### ISSUE TITLE
please add predefined format 165 to Zcl_excel_reader_2007

### ISSUE THREAD

**Issue by wrbi** [abap2xlsx/abap2xlsx#389]
In some Excel files created with Excel 2010 there is a date format 165.
i coded it with  'm/d/yy;@' and it works.

regards

Joachim

**Comment by StefanSchmoecker** [comment]
Hello Joachim,
could you provide an example file?
Up to know I thought that most number formats with such high numbers ( 164++ ) are explicitly written to styles.xml of the .xlsx-file.
These should be read by the reader - but if you encounter a problem here I'd like to find the error.

**Comment by wrbi** [comment]
Hello Stefan,

i dont know how to attach a file to a Comment.
can you please tell me.

Joachim

**Comment by gregorwolf** [comment]
Hi Joachim,

I see a hint below the textbox:

Attach images by dragging & dropping,  selecting them, or pasting from the clipboard.

perhpas you have to use a current version of Chrome, Firefox or IE.

Best regards
Gregor

**Comment by StefanSchmoecker** [comment]
Hello Gregor - that will probably not work since you can only add images but not attach any filetypes

Hello Joachim,  I temporarily set my emailaddress in my profile to public visibility.
You can send me your example and afterwards I hide my emailaddress again.

**Comment by StefanSchmoecker** [comment]
Update:  
Several problems:  
1st)  Excel-Reader 2007:  Incorrect definition of built-in style 14 which causes Joachim's problem
2nd)  Excel-Writer 2007:  Built-in styles not taken account of at all.  Internal styles were taken literally and are being output as additional style which then gets attached to the cell and output is not indepentant of user-settings while the built-in styles seem to change the visualisation in EXCEL depending on user-settings

**Comment by StefanSchmoecker** [comment]
Predefined Styles 41-44 are missing ( probably because they are not listed here http://polymathprogrammer.com/2011/02/15/built-in-styles-for-excel-open-xml/ )

When checking the index of predefined styles it is checked vs. the number-format-string explicitly in ZCL_EXCEL_READER_2007 instead of the constants defined in ZCL_EXCEL_STYLE_NUMBER_FORMAT

Not all predefined styles have a corresponding constant in ZCL_EXCEL_STYLE_NUMBER_FORMAT

**Comment by StefanSchmoecker** [comment]
Fixed with last update to classes with last commit
