### ISSUE TITLE
The abstract method "CHECKEXISTS" can only be implemented after its re definition (METHODS CHECKEXISTS REDEFINITION).

### ISSUE THREAD

**Issue by kratqep** [abap2xlsx/abap2xlsx#390]
I just downloaded and installed everything.  I am unable to activate the method CHECKEXISTS in class  ZSAPLINK_CLASS and get the error:  The abstract method "CHECKEXISTS" can only be implemented after its redefinition (METHODS CHECKEXISTS REDEFINITION).

Can anyone tell me what the issue may be here?

**Comment by kratqep** [comment]
![image](https://cloud.githubusercontent.com/assets/13425218/8788855/ba0e8574-2efa-11e5-8ec5-edd38a16ae40.png)

**Comment by ivanfemia** [comment]
Hi,

I would suggest to post this to the SAPLink support web site www.saplink.org
.

Ivan

**Comment by kratqep** [comment]
Thanks..........I did see someone else also just posted this there.  The solution is to run the installer twice........go figure........
