### ISSUE TITLE
ZCL_EXCEL_WRITER_XLSM - Does not handle charts built dynamically

### ISSUE THREAD

**Issue by pgraylish** [abap2xlsx/abap2xlsx#392]
I have created an ABAP report, which does the following:-
1.  Reads data from SAP.
2.  Opens a blank Macro enabled (*.xlsm) spreadsheet with some VBA code.
3.  Adds a sheet to the spreadsheet from the data read from SAP.
4.  Builds a chart based on the data just added.
5.  Saves the spreadsheet.

The class ZCL_EXCEL_WRITER_XLSM does not seem to be able handle create charts created dynamically by my code, whereas ZCL_EXCEL_WRITER_2007 does work (when creating *.xlsx files).

This issue occurs when processing a document that creates charts, during the “CREATE” step 12, the lv_content = lo_drawing->get_media() returns a blank XString.

The coding is slightly different in the two classes. The code from ZCL_EXCEL_WRITER_2007 needs porting to ZCL_EXCEL_WRITER_XLSM.

I have manually done this in my system, and it corrects the problem.

```
ZCL_EXCEL_WRITER_XLSM 
**********************************************************************
* STEP 12: Add charts
  lo_iterator = me->excel->get_drawings_iterator( zcl_excel_drawing=>type_chart ).
  WHILE lo_iterator->if_object_collection_iterator~has_next( ) EQ abap_true.
    lo_drawing ?= lo_iterator->if_object_collection_iterator~get_next( ).

    lv_content = lo_drawing->get_media( ).
    lv_value = lo_drawing->get_media_name( ).
    CONCATENATE 'xl/charts/' lv_value INTO lv_value.
    lo_zip->add( name    = lv_value
                 content = lv_content ).
  ENDWHILE.

ZCL_EXCEL_WRITER_2007
**********************************************************************
* STEP 12: Add charts
  lo_iterator = me->excel->get_drawings_iterator( zcl_excel_drawing=>type_chart ).
  while lo_iterator->if_object_collection_iterator~has_next( ) eq abap_true.
    lo_drawing ?= lo_iterator->if_object_collection_iterator~get_next( ).

    lv_content = lo_drawing->get_media( ).

    "-------------Added by Alessandro Iannacci - Only if template exist
    if lv_content is not initial and me->excel->use_template eq abap_true.
      lv_value = lo_drawing->get_media_name( ).
      concatenate 'xl/charts/' lv_value into lv_value.
      lo_zip->add( name    = lv_value
                   content = lv_content ).
    else. "ADD CUSTOM CHART!!!!
      lv_content = me->create_xl_charts( lo_drawing ).
      lv_value = lo_drawing->get_media_name( ).
      concatenate 'xl/charts/' lv_value into lv_value.
      lo_zip->add( name    = lv_value
                   content = lv_content ).
    endif.
    "-------------------------------------------------
  endwhile.
```

Example Code:-
Works:

```
lcl_output=>output( cl_excel = lo_excel ).
```

Does Not Work

```
 lcl_output=>output( cl_excel = lo_excel iv_writerclass_name = 'ZCL_EXCEL_WRITER_XLSM' ).
```

Where lcl_output is the one contained in the ZDEMO_EXCEL_OUTPUTOPT_INCL include.

**Comment by StefanSchmoecker** [comment]
I'll handle this in the near future.  
I've been aligning XLSM and 2007-Writers in the past already - but I didn't touch the method "CREATE" yet.
Basically I'm going to change the code to first call the super->create( ) and then do all the stuff necessary for the xlsm-creation.

@Paul:  Are you able to provide your ( or a slightly modified version that runs on any system ) demoprogram that causes the error?  I just set my emailaddress to public for this and will set it to private again if I receive a mail from you - thank you in advance

**Comment by pgraylish** [comment]
Hi Stefan,

I’ll knock up a demo program as soon as I get a chance and email it over to you.

Regards
Paul

**Comment by pgraylish** [comment]
Hi Stefan,

Here’s a quick sample.

For this to work you will need a copy of the TestMacro.xlsm (or any other macro enabled workbook).

Part of the reason why I need to be able to do this is because I need to build charts in Excel with multiple data series and different scales. ABAP2XLSX currently only supports one scale, so I’ll be creating a macro enabled workbook with the required code to add the extra series/scales.

Regards
Paul

From: Paul Graylish
Sent: 03 August 2015 08:20
To: 'ivanfemia/abap2xlsx'; ivanfemia/abap2xlsx
Subject: RE: [abap2xlsx] ZCL_EXCEL_WRITER_XLSM - Does not handle charts built dynamically (#392)

Hi Stefan,

I’ll knock up a demo program as soon as I get a chance and email it over to you.

Regards
Paul

**Comment by StefanSchmoecker** [comment]
Hello Paul,

I fear that your last postings are a bit extensive - they include information from Emails that shouldn't be seen here I guess.

But I have been able to get your errormessage with the demoreport + a simple macro-workbook as template.   Thank you - I'll get back to you as soon as I see how to fix this.

**Comment by StefanSchmoecker** [comment]
Hello Paul,

I think a prepared the 2007-Writer for this already some commits before and forgot to adjust the XLSM-Writer.

Please download the latest versions of these two classes from the subversion directory but make a copy of them before updating.

If you find that there have been quite some changes in the previous month and you don't know which classes to update and if you don't update from the svn-directory but from the daily-build nugget please wait a few days until I create a complete new daily-build of ABAP2XLSX

**Comment by StefanSchmoecker** [comment]
Hi Paul,

I just added a new daily build to the svn. 
Maybe you could check if your problem is solved by this - then I'd close this issue

**Comment by pgraylish** [comment]
Hi Stefan,
I can confirm that the latest daily build has fixed this issue.
Thank you for your assistance!
Regards
Paul
