### ISSUE TITLE
Error is not showing while entering Invalid Values in Drop Down List Boxes

### ISSUE THREAD

**Issue by SurenderKumarS** [abap2xlsx/abap2xlsx#393]
Hi ,

We have a template(.xlsm) in SAP Repository with few Drop Down Cells with fixed values and  its downloaded by Application Program , the entries are fetched from Database and it will populate on corresponding cells in that template. Once the file is downloaded to Local Drive of Presentation Server, User can modify/insert/delete the existing entries in that file and again it'll upload by Program to update in DB. **There is a possibility of entering Invalid Values in the Drop Down List boxes but its not Prompting an Error while changing.**

I noticed that  issue is in  below line of **ZCL_EXCEL_READER_2007/LOAD_WORKSHEET**, the Value '1' of  ls_datavalidation-showerrormessage (which is enabled the error in the below screenshot#1 for Cell)  is assigned to LO_DATA_VALIDATION->showerrormessage which is a type of Boolean and its overwritten the Boolean value ABAP_TRUE or 'X'  to '1'. 

```
  lo_data_validation->showerrormessage = ls_datavalidation-showerrormessage.
```

I added the below code  in our DEV instance and its working fine. Can you confirm it ?
      if ls_datavalidation-showerrormessage eq '1'.
        lo_data_validation->showerrormessage = abap_true.
      else.
        lo_data_validation->showerrormessage = abap_false.
     endif.

Screenshot#1
![image](https://cloud.githubusercontent.com/assets/13743318/9191554/2f55650a-4035-11e5-860f-50106a335180.png)
Screenshot#2
![image](https://cloud.githubusercontent.com/assets/13743318/9192381/317e49ac-403d-11e5-99ee-3f9a2f54cfcd.png)

Please let me know if you need any details .

Note: The latest patch in DEV Instance is ABAP2XLSX_V_7_0_3.nugg 

Thanks
Surender

**Comment by StefanSchmoecker** [comment]
Hello Surender,

your analysis and correction is valid.  
I made a quick further check - same holds true for attributes "showinputmessage" and "showdropdown" and for the latter there is an update of the writer_2007 needed as well (Currently we always show the dropdown ). 

Updated SVN-Directory with new version of class ZCL_EXCEL_WRITER_2007 and ZCL_EXCEL_READER_2007 to reflect the changes

**Comment by SurenderKumarS** [comment]
Hi Stefan,

Yes, i noticed that too. Thanks for Update. We'll Re-import the ABAP2XLSX Package again.

Thanks
Surender
