### ISSUE TITLE
Excel file corrupt due to double column names

### ISSUE THREAD

**Issue by DominikWerner** [abap2xlsx/abap2xlsx#395]
Hi, 

First of all: Gratulations to this great project ! :)
It took me quite a while to install it and to make it run but now it works and looks great.

In the first hours i always got an korrupt xlsx file and Excel always displayed  two Messages that it fixed the file itself.
It took me a while to find out, that the file becomes corrupt when there a two or more columns with the same headerline.
Excel fixes the file than in the way that it appends Digits to the colum texts.

e.g. Column Texts: Name, Name --> Name, Name2

maybe this could be easily fixed by checking the fieldcatalog before sending the file.

Kind regards
Dominik

I'm working with Version 7.0.5

**Comment by StefanSchmoecker** [comment]
Hello Dominik,

sounds somewhat like issue #386, but that has been marked as resolved and I see the changes of that issue in the 7.0.5-nugget.  I checked with a simple testreport and the solution works fine for me, so you have encountered something else.

Could you provide a **short and simple** demoreport that produces this error ( i.e. like ZDEMO_EXCEL_1 )

**Comment by sandraros** [comment]
No answer. Closing.
If you want to discuss this point again, please reopen the issue.
