### ISSUE TITLE
Could not create WB object from OCN (type),  (name), ZSAPLINK_NUGGET (encl.)

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#397]
Hi all,

when I activate the hole Class ZSAPLINK_NUGGET in transaction SE80 there is still an empty item under the class-name in the list of inactive objects (see image). When I click on it I get the information message with Message No. SEU_MANAGER005
"Could not create WB object from OCN (type),  (name), ZSAPLINK_NUGGET (encl.)".
I tried to do "Rebuild Object List" but the item is still there.
Can anybody tell me what´s wrong and how can I solve this?

Best regards.

Markus
![screenshot_se80](https://cloud.githubusercontent.com/assets/9315125/9376724/164d9342-4711-11e5-979a-f6056fcb1d59.jpg)

**Comment by ivanfemia** [comment]
Markus,

I would suggest to ask directly on saplink website www.saplink.org for a quicker and better support.

Ivan

**Comment by ghost** [comment]
Hi Ivan,

how can I ask directly on the saplink Website?
I created an account but I find no possibility to place my issue.
Can you give me a hint.

Markus

**Comment by gregorwolf** [comment]
Hi Markus,

in Assembla which is used for SAPlink still Issues are called Tickets:
https://www.assembla.com/spaces/saplink/tickets
But have you already tried to refresh the Object List?

Best regards
Gregor

**Comment by ghost** [comment]
Hi Gregor,
but when I login to assembla there is no opportunity like a button or something else to create a new ticket.

Yes, I tried to rebuild the object list. But no effect.

Best regards,
Markus

**Comment by gregorwolf** [comment]
Not even when you use the link I've posted? Can you add a Screenshot?

**Comment by ghost** [comment]
May be that I´m blind ...
![screenshot_ticket](https://cloud.githubusercontent.com/assets/9315125/9404543/e20ceb1a-47f0-11e5-94bd-5b5589439a96.jpg)

**Comment by DerekSMorin** [comment]
I found that rebuild object list didn't work for me one time.  After exiting all of my sap windows and coming back in through segw it was then working.  Shrug.
