### ISSUE TITLE
Download XLSX in background to presentation directory

### ISSUE THREAD

**Issue by gsharpe2000** [abap2xlsx/abap2xlsx#401]
Hello,

I'm receiving this error when running my program in background using gui_download.

 when 21.
        RAISE CONTROL_FLUSH_ERROR.

I have no problem reading from network share but writing back to same folder gives this error.

I used the following:

```
* Send file
  gv_file = lo_excel_writer->write_file( lo_excel ).
  REPLACE '.xlsm' IN gv_full_path WITH 'FromGreg.xlsm'.

  " Convert to binary
  CALL FUNCTION 'SCMS_XSTRING_TO_BINARY'
    EXPORTING
      buffer        = gv_file
    IMPORTING
      output_length = gv_bytecount
    TABLES
      binary_tab    = lt_file_tab.

  " Save the file
  cl_gui_frontend_services=>gui_download( EXPORTING bin_filesize = gv_bytecount
                                                    filename     = gv_full_path
                                                    filetype     = 'BIN'
                                           CHANGING data_tab     = lt_file_tab ).
```

Your help is much appreciated :-)

**Comment by gregorwolf** [comment]
Hello,
as your program is running in the background you can't use gui_download as no connection to SAP GUI exists. Please check the demo reports how to send mail or write to the application server.
Best regards
Gregor

**Comment by gsharpe2000** [comment]
Hi Gregor,

I'm running in background when reading from the network share using abap2xlsx.  Shouldn't I be able to also write to the network share using abab2xlsx?

My program successfully picks up the xlsx template, populates it and emails it successfully - all in background.  I just need it to write back to the same network share folder that it read the template from.

Cheers,

Greg

**Comment by gregorwolf** [comment]
Hi Greg,

but do you read from the network share with gui_upload or with file open?

Best regards
Gregor

**Comment by gsharpe2000** [comment]
HI Gregor,

file open.

Cheers,
Greg

**Comment by gsharpe2000** [comment]
If SAP/abap2xlsx allows you to read from network share, in background, it should allow you to write to the network share in background.

What is the alternative to gui_download for network share that would allow a multi-tabbed XLSX file to keep it's structure?

**Comment by gregorwolf** [comment]
Please check the Method download_backend of class lcl_output  in the include ZDEMO_EXCEL_OUTPUTOPT_INCL. It uses:

OPEN DATASET p_backfn FOR OUTPUT IN BINARY MODE.

**Comment by gsharpe2000** [comment]
Hi Gregor,

Yes, this worked and kept the multi-tabs if I saved as XLSX. But, and maybe this is a security issue, I couldn't open after saving as XLSM (Macro Enabled).

Cheers,

Greg
