### ISSUE TITLE
XLSM file - Macro Missing when emailed

### ISSUE THREAD

**Issue by gsharpe2000** [abap2xlsx/abap2xlsx#402]
Hi,

If I open up a template (macro enabled) populate it and then save to a local file, the macro stays intact.

But, if I email the same file, the Macro is removed.

Has anyone else had this issue and was it resolved?

Your help is much appreciated.  :-)

Greg

**Comment by gregorwolf** [comment]
Hi Greg,
you're mailing to another user or reading the file using abap2xlsx?
Best regards
Gregor

**Comment by gsharpe2000** [comment]
Hi Gregor,

During my testing, I'm emailing to one of my email accounts using abab2xlsx.

Cheers,

Greg

**Comment by gregorwolf** [comment]
Still don't get it completely. Perhaps there is a virus scanner removing the macro or when you opening it from the mail the macro is not executed because of a not trusted source?

**Comment by gsharpe2000** [comment]
hmmmm, how would I be able to tell?

Would there be a setting in my Outlook to make sure?

**Comment by gregorwolf** [comment]
If everything is fine when you just using abap2xlsx without using E-Mail then please search in a Outlook / Excel specific group for a solution.

**Comment by gsharpe2000** [comment]
ok, thank you very much for your help today Gregor.  I really appreciate it.  :-)

Greg

**Comment by gsharpe2000** [comment]
Hi Gregor,

For some reason, when sending email as XLSM, the file can't be opened.  Outlook gives the following error.  
![image](https://cloud.githubusercontent.com/assets/14054489/9908156/c4a762c6-5c68-11e5-9c1b-73113c6cc987.png)

Would you know what the issue is?

**Comment by gsharpe2000** [comment]
Hi Gregor,

Your help is very much appreciated.

![image](https://cloud.githubusercontent.com/assets/14054489/9908332/8b6be530-5c69-11e5-9dac-9a48db8291da.png)

I saw this in a post but didn't see the resolution to the 3 byte attachment type.  No wonder I didn't see the macro.

So the send_email method is basically setting the document type as XLSX instead of XLSM.

How do you get around this issue?

**Comment by StefanSchmoecker** [comment]
Hello Greg,

try to download the attachment to a local directory and see if excel is able to open it from there directly with excel.
Does the problem persist or do you get the error only when opening it directly from your outlook client?

**Comment by gsharpe2000** [comment]
Hi Stephan,

I can download locally in online mode and it keeps the macro.  Macro is lost in backend processing and gives this error.

![image](https://cloud.githubusercontent.com/assets/14054489/9941612/d197c1c6-5d4c-11e5-942c-cfe3a2640797.png)

For email, the logic below does not allow for XSLM.

![image](https://cloud.githubusercontent.com/assets/14054489/9941633/f44e4d48-5d4c-11e5-8375-d7cffb3d948b.png)

So, there's 2 issues.  

1 - Backend saving of the file to the network share as XLSM doesn't allow me to open the file but online does and keeps the macro.

2 - Email doesn't allow XLSM because the call in the picture above only allows 3 characters 'XLS', 'RAW' etc. and not XLSM as an option so macro not in file during email.

Greg

**Comment by StefanSchmoecker** [comment]
Hello Greg,
my question wasn't precise I fear.
Please email the xlsm to your emailaccount (  you already did that as I understand ) and after you received the mail **download the attachment from your email-client to your local drive**.  
Then try to open it and tell us if excel complains or not.

**Comment by gsharpe2000** [comment]
HI Stephan,

The email method changes it to an XLSX per my screenshot of the method cl_document->add_attachment's parameter for document_type only being 3 chars long.

**Comment by gsharpe2000** [comment]
I read the XLSM template, populate it and then try to email it. Below is before and after - I saved the file to my local drive from email.

![image](https://cloud.githubusercontent.com/assets/14054489/9942684/c4265f92-5d52-11e5-8ccc-fd07cbd39593.png)

**Comment by gsharpe2000** [comment]
![image](https://cloud.githubusercontent.com/assets/14054489/9942713/ecc17982-5d52-11e5-8627-fe616d77567f.png)

**Comment by StefanSchmoecker** [comment]
Hello Greg,

a) the screenshot you sent with the attachment-type "XLS" should not change the filename!
If you look into our demo-output-include the resulting filename of the attachment is provided a few lines above including a comment.  Are you 100% sure the (complete with extension) filename you provide here is ending with .xlsm
![unbenannt](https://cloud.githubusercontent.com/assets/10195656/9947427/4fde2870-5d9a-11e5-903a-2ea9cd487799.png)

b)  Are you using the XLSM-reader and -writer instead of the XLSX-versions for input and output for both cases - online and email-sending?

c) Can you send or forward such an email ( if you are able to create an example w/o secret information ) to me.  My email is public at the moment

**Comment by ivanfemia** [comment]
Which writer and reader are you using?

**Comment by gsharpe2000** [comment]
Hi,

I'm using the following reader/writer.

![image](https://cloud.githubusercontent.com/assets/14054489/9959025/2f969132-5de6-11e5-9a92-e6820351e123.png)

**Comment by gsharpe2000** [comment]
Hi Stefan,

I've emailed you the program and includes and really appreciate your helping me.  :-)

Greg

**Comment by gsharpe2000** [comment]
Hi Stefan,

I reviewed ZDEMO_EXCEL37 as you mentioned in your email and the below addition of 'iv_writerclass_name' fixed my issue.

```
  lcl_output=>output( cl_excel            = lo_excel
                      iv_writerclass_name = 'ZCL_EXCEL_WRITER_XLSM' ).

*  lcl_output=>output( lo_excel ).  Old Logic didn't work.
```

Thanks you very much for your solution.  :-)

Greg
