### ISSUE TITLE
Method SEND_EMAIL mail_title only 50 characters long.  Need longer.

### ISSUE THREAD

**Issue by gsharpe2000** [abap2xlsx/abap2xlsx#404]
Our client needs the subject line to be more than 50 chars long but MAIL_TITLE is only 50 long.
I tried to make 80 chars but failed as the 

![image](https://cloud.githubusercontent.com/assets/14054489/10463466/34f0f0d0-71bb-11e5-9b46-58051c064f3c.png)

Received this error:
![image](https://cloud.githubusercontent.com/assets/14054489/10463516/6c108800-71bb-11e5-8d38-a92306806745.png)

for this method:
![image](https://cloud.githubusercontent.com/assets/14054489/10463529/7fd3b8e4-71bb-11e5-9a0a-465112a717b0.png)

Method parameters are:
![image](https://cloud.githubusercontent.com/assets/14054489/10463551/9bd532fc-71bb-11e5-920e-f43226cc63cc.png)

How can this be changed?

Regards,

Greg

**Comment by ivanfemia** [comment]
This is the standard SAP limit for email subject. 

Check this thread on SCN https://scn.sap.com/thread/1384324

**Comment by gsharpe2000** [comment]
thank you very much.

Regards,

Greg

**Comment by gregorwolf** [comment]
Please check out Note:
698087 - User-defined mail title without length restriction
http://service.sap.com/sap/support/notes/698087

**Comment by gsharpe2000** [comment]
Thanks Gregor, that worked.

I have a different issue now - if you can help.

![image](https://cloud.githubusercontent.com/assets/14054489/10551630/59f11980-7424-11e5-82c0-f2e8f09899a5.png)

Any help is very much appreciated!

Greg

**Comment by gsharpe2000** [comment]
Thanks Gregor, that worked.

 

I have a different issue now - if you can help.

 



 

With warmest regards,


Greg Sharpe

GFI Consulting Limited

Skype: gsharpe2000 

Mobile: 902-322-4102

Fax       : 902-702-2547



 <http://lnkd.in/bCT-dm>

**Comment by gregorwolf** [comment]
Dear Greg,

it's great when you can quick support for free or? I think you should get a new instance of cl_send_request for each loop.

Best regards
Gregor

**Comment by gsharpe2000** [comment]
Sorry Gregor,

I apologize for asking you this and was thinking the same thing.

Too bad you weren't in Cape Breton. I'd take you out for some well deserved drinks :-)

Cheers,

Greg
