### ISSUE TITLE
Suggestion: Delete 'Col:' in Front of a Column Title

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#409]
Hello Stefan and Ivan,

in the class ZCL_EXCEL_COMMON in the method GET_FIELDCATALOG you have an If condition to set the fieldname as description, for fields without a description:

`CONCATENATE 'Col:' <fcat>-fieldname INTO <fcat>-scrtext_l  SEPARATED BY space.`

In this case I get always Col: in front of any column title, so I changed the code to

`<fcat>-scrtext_l = <fcat>-fieldname.`

that this not longer occurs.

Is it possible for a future release to change that or is it for some reasons necessary?

Thanks and cheers
Stefan

**Comment by plato79** [comment]
I could understand that there may be a need to do it this way. For example you could see that which columns have no title when it appears with "Col:"..

So I think this way is ok, and your workaround is enough to fix it for you.
