### ISSUE TITLE
Question: Column Width Difference in ABAP2XLSX and Excel

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#410]
Hello Stefan and Ivan,

one tiny question about the difference of the column width in ABAP2XLSX and Excel.

Here the part of code:

`lo_worksheet->set_column_width( ip_column = lv_column_alpha ip_width_fix = '13.75' ).`

And here the result in Excel:

![image](https://cloud.githubusercontent.com/assets/13049097/11300062/1f3eb314-8f8c-11e5-8dd5-a7aef8da847e.png)

Why did I have a difference here?

Thanks in advance and cheers
Stefan

**Comment by StefanSchmoecker** [comment]
Hi Stefan,

Long explanations:  See https://msdn.microsoft.com/de-de/library/documentformat.openxml.spreadsheet.column%28v=office.14%29.aspx
Scroll down a bit and you get a lengthy explanation for your effect.

Short explanation:
Subtract 0,7 which corresponds to 9 pixels padding at 96 dpi

**Comment by ghost** [comment]
Hello Stefan,

thank you very much.

Cheers
Stefan
