### ISSUE TITLE
date format is ##########

### ISSUE THREAD

**Issue by runnere** [abap2xlsx/abap2xlsx#411]
I downlad a ITAB with tree columns of date all of the is DATUM...

2 downkoad correct and the tree is '########' it translate the date to number with '-' like -693596.. the date was 08.08.1945..

any idea???

**Comment by runnere** [comment]
I have more detailes  2 coulmns is datum and the problem is GBDAT..  need conversion .. what i need to do...>>>>????

**Comment by runnere** [comment]
O.K more details...

i took program ZDEMO_EXCEL3 and change sflight table to pa0002..

and GBDAT date of birth is download not good '########'...
thanks.

**Comment by ivanfemia** [comment]
Have you tried to enlarge the column in the generated excel?

**Comment by runnere** [comment]
Yes.. this was the first thing i did.

try to run ZDEMO_EXCEL3 and change sflight table to pa0002.. and you will see the result for column GBDAT

**Comment by StefanSchmoecker** [comment]
Actually I did - and after enlarging the column you'll see the birthdates.
Maybe your installation of ABAP2XLSX is too old.  Please update to the latest version.

**Comment by sinekopova** [comment]
The problem occurs for the date type with the conversion-exit in the SET_CELL method of the class ZCL_EXCEL_WORKSHEET
Sample for data element RECNCNENDABS, conversion-exit REDAT.
Field symbol <FS_VALUE> is created with a type DATE and a length of 8 (for example, 20210315). 
After performing GET_VALUE_TYPE with the standard convertion-exit, we get 15.03.20 - the length remains equal to eight.
I think you need to create a <FS_VALUE> length equal to the output length of domain RECADATEEND.
If there is no conversion-exit in the data element, then everything works fine.

**Comment by sandraros** [comment]
@sinekopova I don't think that's the same issue. Could you create a separate issue and provide a program to reproduce the problem? Thank you.

Concerning this issue (cell value ####### for dates), could we close it?

Thank you.

**Comment by sandraros** [comment]
No answer. I propose to close the issue. You may reopen it if you provide more information. Thank you.
