### ISSUE TITLE
Converter doesnt support inherited ALV objects -> solution provided

### ISSUE THREAD

**Issue by Pertekm** [abap2xlsx/abap2xlsx#412]
Hello,
at first thank your for the nice tool!

I found a problem in the converter and provide an solution:

Problem:
When using the converter (Method ZCL_EXCEL_CONVERTER-CONVERT) it will throw an exception, when the given ALV object is not direct an ALV object, because inherition is used.
For example if you use an own extended ALV object (ZCL_ALV instead of CL_GUI_ALV_GRID).
The exception occurs in the method execute_converter because it just checks the direct class name per lo_addit->get_relative_name( ).

Solution:
Check all superclasses too. See part between "MPE" in the attachment for the modified method EXECUTE_CONVERTER. [ZCL_EXCEL_CONVERTER.txt](https://github.com/ivanfemia/abap2xlsx/files/55362/ZCL_EXCEL_CONVERTER.txt)
If this solution sounds good, feel free to use it.

Greets from Hamburg in Germany
Manuel

**Comment by fidley** [comment]
Hello Pertekm, 
such issue was already found and corrected while ago. Could you download and install a new SLNK files and see if it works also for you?

Cheers
Łukasz
