### ISSUE TITLE
Long Column Header Text 

### ISSUE THREAD

**Issue by jaygaro-acn** [abap2xlsx/abap2xlsx#415]
Hi,

I am getting this error when opening the xlsx file I created:
Repaired Records: Table from /xl/tables/table1.xml part (Table)

The reason this happens is because I have a table header text that is more that 20 characters.
In the field catalog, I only assign in the Long Text and cleared the Short(or is it Small?) Text and Medium Text since the column header text are customized and I don't want the value in the Medium to be displayed.

So is there a way to remove this message prompt to repair? I don't want to assign the value in the Long Text to the Medium Text since it will be truncated.

**Comment by fidley** [comment]
Hello, 
do you get it with bind_alv or bind_table method? In bind table I've implemented possibility to choose the type of header text while binding in parameter iv_default_descr (M, L, S).

Can you import new SLNK files and check it?

Cheers
Łukasz

**Comment by sandraros** [comment]
Closing, too old and no answer since last question. I guess that iv_default_descr solves the issue.
