### ISSUE TITLE
"Problem with some content" message when opening XLSM file in Excel

### ISSUE THREAD

**Issue by johnrich1** [abap2xlsx/abap2xlsx#416]
I created a blank macro enabled spreadsheet (blank1.xlsm) file with Excel 2013.  I then used the demo program ZDEMO_EXCEL29 to read and write the spreadsheet producing a new file (blank1FromReader.xlsm).  When I open the new file with excel, I get the following message:
"We found a problem with some content in 'blank1FromReader.xlsm'. Do you want us to try to recover as much as we can?  If you trust the source of this workbook, click Yes."
![image](https://cloud.githubusercontent.com/assets/16295044/11792760/546c660a-a26d-11e5-80b5-8424adcf1669.png)

Pressing "Yes" produces the following message:
![image](https://cloud.githubusercontent.com/assets/16295044/11792507/fe9d95f6-a26b-11e5-818d-b5458ff99670.png)

The spreadsheet seems to be fully functional.  I can save it with Excel and load it without the error later.  

I modified the ZDEMO_EXCEL29 to use the zcl_excel_writer_2007 class to write the file out.  When I do that, it writes the file and I can open it in excel without any issues.

Is there a problem with the class zcl_excel_writer_xlsm?

**Comment by StefanSchmoecker** [comment]
Hello,

add a macro ( can be an empty macro - just make sure there is a vba-section in your document) to your file and try again.  It should work then.

**Comment by johnrich1** [comment]
That fixed it!
