### ISSUE TITLE
Support for Shapes?

### ISSUE THREAD

**Issue by guillaumegarcia13** [abap2xlsx/abap2xlsx#417]
Hi,
Has any of you tried to use Shapes (ellipsis, rectangle, triangle, ...) including embedded text?
Thanks in advance.
Best regards,
Guillaume

**Comment by StefanSchmoecker** [comment]
Hello Guillaume,

I don't think we support this atm.  But to make sure use demoreport 37 and see if the information you need is passed through.  If not it is most likely not supported

---

live long and prosper
Stefan Schmöcker
