### ISSUE TITLE
Development tips for ABAP2XLSX

### ISSUE THREAD

**Issue by guillaumegarcia13** [abap2xlsx/abap2xlsx#419]
Hi gurus,

Just wanted to know whether you add a specific **"development process"** or **"tips"** regarding ABAP2XLSX.
I found myself spending a **lot of times beautifying XML files after unzipping ABAP2XLSX-generated** (or manually saved) .xlsx files or re-compressing into .xslx files.
Have you developped macros or programs (I have one in ABAP that "xlsx-izes" a whole folder but it is actually quite unefficient performance-wise...)?

For the debug time, I would especically find useful to XML-prettyprint all files by simply using cl_proxy_ui_utils=>xml_pretty_print conditionnaly (with a debug flag) on all generated xstrings in the  ZCL_EXCEL_WRITE2007->CREATE method like this:
<code>lv_content = prettify_xml( me->create_content_types( ) ).</code>
 What about it?
_Be warned that it might tamper with the data! (for instance, it may remove some line feed within your text!!)_

Thansk in advance for sharing your tips.

Best regards,
Guillaume

**Comment by ivanfemia** [comment]
check [Package Explorer](https://packageexplorer.codeplex.com/) tool.
It saves me a lot of time

**Comment by guillaumegarcia13** [comment]
Thanks for the tip
