### ISSUE TITLE
Error while executing your demo programs

### ISSUE THREAD

**Issue by sanjayabap** [abap2xlsx/abap2xlsx#429]
![abap2xslx error](https://cloud.githubusercontent.com/assets/18262914/14248150/938f3ab2-fa90-11e5-8211-d6a4a80ab444.png)
Hi Evan,

Whenever i execute your program iam getting an error message, Please help me to avoid this message.
"Excel found unreadable content in '~ SAP{B42E6958-3FA4-4423-9f59}.xlsx'. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes.(Attached screenshot for your reference) 
Thanks ,
Sanjay D

**Comment by ivanfemia** [comment]
Hi,

Have you checked if you have any permission accessing the file?
File name starting with ~ usually is a temporary file created by excel so it seems you're doing something wrong.

Ivan

**Comment by StefanSchmoecker** [comment]
Hello Sanjay,

which version of ABAP2XLSX did you install and did you acgtivate all componetns w/o errors?

**Comment by sanjayabap** [comment]
Hi Ivan,

Yes, I have permission for accessing the file. It seems the problem is with the unreadable content inside the file. Kindly find attached error message for further explanation.

**Request:** Since myself is new to this ABAP2XLSX i am having trouble in coding and utilizing this to the full potential, Hence I would request you to prepare a video tutorial for ABAP2XLSX installation, coding and upload them in "www.udemy.com". Please have a peek at this website you will find lots of tutorials like ABAP and ABAP objects programming and thousands of people being enrolled in them. 
This will have the following benefits:
1. Allow users to fully utilize the potential of ABAP2XLSX.
2.Increase the awareness about ABAP2XLSX to SAP ABAP developers which will create more new users.
3. Generate Revenue to your company.
4. More inputs on Developing ABAP2XLSX further.

![capture](https://cloud.githubusercontent.com/assets/18262914/14272287/5b86b4ee-fb1f-11e5-8774-54bbe25980c0.PNG)

Thanks & Best Regards,
Sanjay D

**Comment by gregorwolf** [comment]
Dear Sanjay D,

great idea with www.udemy.com. Perhaps you can do that when you've got it working. Have you tried to run the report i.e. ZDEMO_EXCEL1 standalone directly from SE38 and open the created file that was saved to your drive? And please provide information what exact ABAP backend you're using and what abap2xlsx version you've installed.

Best regards
Gregor

**Comment by sanjayabap** [comment]
Dear Gregor,

Wow, It would be a honour preparing a tutorial for ABAP2XLSX, maybe i will once i have mastered ABAP2XLSX and i will share the tutorial with you and your team.

I tried to run the report ZDEMO_EXCEL1 standalone directly from SE38 and i am getting the same error messages while opening the file directly from my drive. Our ABAP backend is SQL. 

Best Regards,
Sanjay D

**Comment by gregorwolf** [comment]
Please provide us the informaiton that you can get via System -> Status and there the subelement Components and Kernel information.

**Comment by sanjayabap** [comment]
The abap2xlsx version we've installed is 7.04, Components - EHP6 FOR SAP ERP 6.0 and Kernel information - OS400. My colleagues with MS office 2010 installed in their system are able to open the excel sheet properly but myself with MS office 2007 is getting this error message.

**Comment by gregorwolf** [comment]
Can you please attach the .xlsx file here.

**Comment by sanjayabap** [comment]
[01_HelloWorld.xlsx](https://github.com/ivanfemia/abap2xlsx/files/206029/01_HelloWorld.xlsx)
Kindly find attached excel file.

**Comment by gregorwolf** [comment]
I've opened it without issues in Excel 2007. I think it is a local issue with your Excel installation.

**Comment by sanjayabap** [comment]
hmm, I will try reinstalling ms office 2007, If it doesn't solve my problem i will try installing ms office 2010 which will likely solve my problem.
