### ISSUE TITLE
method CONVERT_COLUMNROW2COLUMN_A_ROW

### ISSUE THREAD

**Issue by ferenci** [abap2xlsx/abap2xlsx#430]
In method CONVERT_COLUMNROW2COLUMN_A_ROW of class zcl_excel_common
there is the search of regex : 
`FIND REGEX '^(\D+)(\d+)$' IN lv_columnrow SUBMATCHES e_column
                                                       pane_cell_row_a.`
I guess it should be like this: 
`FIND REGEX '^(\D*)(\d*)$' IN lv_columnrow SUBMATCHES e_column
                                                     pane_cell_row_a.`,
i am making some custom code using these classes and i am facing with some problems when i am trying to read coordinates of range with value like this : `=Лист1!$B:$C` or this `=Лист1!$8:$8`.
_-------------------------------------------------------------------------------------------------------------------------_
I have create new method and named it CONVERT_RANGE2COORDINATES
with the following code 

```
 data: lv_column_start_alpha type zexcel_cell_column_alpha,
        lv_column_end_alpha type zexcel_cell_column_alpha.
  CONVERT_RANGE2COLUMN_A_ROW(
    exporting
      I_RANGE        = i_range
    importing
      E_COLUMN_START = lv_column_start_alpha    " Cell Column Start
      E_COLUMN_END   = lv_column_end_alpha    " Cell Column End
      E_ROW_START    = e_row_start    " Cell Row
      E_ROW_END      = e_row_end    " Cell Row
      E_SHEET        =  e_sheet   " Title
  ).
  try.
      e_column_start = CONVERT_COLUMN2INT( lv_column_start_alpha ).
    CATCH zcx_excel.
      e_column_start = 0.
  endtry.
  IF lv_column_start_alpha is not initial and lv_column_end_alpha is initial.
    e_column_end = e_column_start.
  else.
    try.
        e_column_end = CONVERT_COLUMN2INT( lv_column_end_alpha ).
      catch zcx_excel.
        e_column_end = 0.
    ENDTRY.
  ENDIF.
```

I suppose that method CONVERT_RANGE2COLUMN_A_ROW should return values e_column_start = B and e_column_end = C in first case ( and zeroes in rows because i am using "infinite" range ) and in second case e_row_start = 8 and e_row_end = 8 ( and zeroes in columns ) , but it returns only empty values because regex is wrong. I guess that my solution with new regex could fix the problem ( DEMO_REGEX_TOY show that its fine ).

**Comment by bigld** [comment]
Hi @ferenci 

With PR #862 there will be an additional paramater to allow/enable 1 dimensional ranges like  $2:$7 or $A:$C parsing
method **zcl_excel_common=>convert_range2column_a_row** parameter **i_allow_1dim_range** = abap_true

**Comment by sandraros** [comment]
@bigld There's no answer, maybe we can close this issue? Thanks.
