### ISSUE TITLE
Having trouble while importing the nugget ABAP2XLSX

### ISSUE THREAD

**Issue by meenakshi99** [abap2xlsx/abap2xlsx#431]
Hi team,

I am trying to install ABAP2XLSX in my SAP system, i tried following you instructions in the below mentioned webpage. https://github.com/ivanfemia/abap2xlsx/wiki/Installation-guide

I am able to install the SAP link without any problem, but i am having trouble while importing and activating ABAP2XLSX.nugg.

Attached screenshot for your reference.

Please advise.

Thanks & Regards
![untitled1](https://cloud.githubusercontent.com/assets/18369275/14405713/2714e1e0-feb2-11e5-8109-c55051cb83ea.JPG)
![untitled2](https://cloud.githubusercontent.com/assets/18369275/14405712/27148d6c-feb2-11e5-9b81-0eaa3ce70716.JPG)
![untitled3](https://cloud.githubusercontent.com/assets/18369275/14405714/27163dba-feb2-11e5-96d1-ad3aaf230913.JPG)

**Comment by fidley** [comment]
As written on the error log, you're missing Data Element plugin for Saplink. Install missing plugin(s) and try again.

Cheers
Łukasz

**Comment by ivanfemia** [comment]
Hi,

you have 2 prerequisites (check the guide)
- SAPlink http://www.saplink.org/ installed in your system.
- SAPlink Plugins http://www.saplink.org/ installed in your system:
  DDic, Interface (I would suggest to install the complete nugg package in
  build/SAPlink-plugins_Daily.nugg)SAP

you are missing the second one

**Comment by sanjayabap** [comment]
Hi Ivan,

I couldn't find the complete nugg package in build/SAPlink-plugins_Daily.nugg)SAP. Would request you to kindly provide me a link for the same.

I am able to find a list of plugins in ZSAP links page, not sure which one is appropriate.
![image](https://cloud.githubusercontent.com/assets/18262914/14417072/a9c563ae-ffce-11e5-8e12-36f7cf0f0c9f.png)

Regards,
Sanjay D

**Comment by gregorwolf** [comment]
Just follow the instructions

> To download the latest Version of all plugins collected in this project please navigate in the SVN tab to the folder "build" where you can find SAPlink-plugins_Daily.nugg.zip which is the always latest and greatest.

**Comment by sanjayabap** [comment]
Hi Gregor,

I followed the instruction but i am able to find only SAPlink_Daily.nugg.zip, which i installed and i am still getting this error.  I am unable to find anything named "SAPlink-plugins_Daily.nugg" in the path you have guided me.

![image](https://cloud.githubusercontent.com/assets/18262914/14417764/5a7c8194-ffd6-11e5-9099-32aa4bb36567.png)

Thanks & Regards,

**Comment by sanjayabap** [comment]
Hi Team,

I am completely lost in here, would request you to help me in installing ABAP2XLSX in SAP.

Thanks & Regards,
Sanjay D

**Comment by gregorwolf** [comment]
Dear Sanjay,

please do not simply post on a closed issue. Read the documentation, try yourself, and if you run in problems that you can't solve after a day get them described in detail and post as a new issue.

Best regards
Gregor
