### ISSUE TITLE
Trademarks.  How to convert <347> to a symbol ?

### ISSUE THREAD

**Issue by gsharpe2000** [abap2xlsx/abap2xlsx#432]
Customer has  <347> for the trade mark symbol.  How can this be converted to show up on the spreadsheet correctly?

Thanks,

Greg Sharpe

**Comment by ivanfemia** [comment]
​Hi Greg,

try to generate the xlsx manually and check with package explorer the
corresponding translation

Check this document
http://officeopenxml.com/WPtextSpecialContent-symbol.php

Ivan​

**Comment by gregorwolf** [comment]
I've just inserted the ® symbol in my unicode ABAP system and had no issues. Can you perhaps exchange <347> to ® before handing it over to abap2xlsx?

**Comment by gsharpe2000** [comment]
Hi Gregor,

How did you insert that symbol in your XLSX?  If you don’t mind sharing. :)

With warmest regards,

Greg Sharpe

**Comment by gsharpe2000** [comment]
Would be great if symbols logic was in a ZDEMOnnn

**Comment by gregorwolf** [comment]
I simply added it to the string literal.

**Comment by gsharpe2000** [comment]
Oh thank you 
I thought you concerted it somehow 

Cheers,

Greg Sharpe

**Comment by sandraros** [comment]
Let's close the question, it's answered. Most of symbols are Unicode characters so there should be no problem to get them into Excel.
Demo:
```abap
REPORT.
CONSTANTS gc_save_file_name TYPE string VALUE 'issue_432.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = '®' ). " trademark symbol
  lcl_output=>output( lo_excel ).
```
Result:
![image](https://user-images.githubusercontent.com/34005250/141382107-6b162e85-d826-414f-b4e8-c1eb93af7412.png)
