### ISSUE TITLE
XLSM with many sheets becomes corrupt

### ISSUE THREAD

**Issue by pgraylish** [abap2xlsx/abap2xlsx#433]
I’ve come across a strange error with ABAP2XLSX when working with Macro Enabled workbooks.

My program is structured like this:-
1.  Open a Macro Enable Workbook (a basic empty workbook with the required macros already embedded).
2.  Read my SAP data.
3.  Create multiple worksheets in the workbook.
4.  Save the results to a network folder.

This works fine if the resultant workbook is small, but once the number of worksheets goes over around 75, then some corruption creeps in.

When you open the resultant workbook in Excel, you get the message:-
“Excel found unreadable content in ‘Test.xlsm’ Do you want to recover the contents of this workbook?”

The log file gives you the useless default Microsoft Message:-
“Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.”

If you open the workbook in the Microsoft Tool “Open XML SDK 2.5 Productivity Tool”, you get the message:-
“Cannot open the file: ‘rId*0 ID is not a valid XSD ID.”

Renaming the file from .xlsm to .zip and opening the container up allowed me to find the issue.
In the “\xl_rels” folder, the file “workbook.xml.rels” has an invalid entry for the vbaProject.bin as below:-
“<Relationship Target="vbaProject.bin" Type="http://schemas.microsoft.com/office/2006/relationships/vbaProject" Id="rId*0"/>”

If you allow Excel to repair the file, then rename to zip and check the “workbook.xml.rels” again, the line is changed to:-
“<Relationship Target="vbaProject.bin" Type="http://schemas.microsoft.com/office/2006/relationships/vbaProject" Id="rId100"/>”

This would appear to me that some low level counter used to generate the rID values is limited to 2 digits when perhaps it should be 3 or more?

The web page will not allow me to upload a xlsm file type to include a sample file.

**Comment by pgraylish** [comment]
Unfortunately, the posting has done something to the quotations I included from the XML file. Here's a shortened version that does not get corrupted.
Initial, broken XML line:-
Type="http://schemas.microsoft.com/office/2006/relationships/vbaProject" Id="rId*0"/>”
Fixed XML line:-
Type="http://schemas.microsoft.com/office/2006/relationships/vbaProject" Id="rId100"/>

**Comment by ivanfemia** [comment]
I tested on the latest version and I didn't find any issue.
Do you have a test case?

**Comment by pgraylish** [comment]
Hi,
This was so long ago, I can't recall if we resolved this or abandoned the project.
I would suggest that you simply close this off, and if it happens again, I'll raise another ticket.
Thanks!
Paul
