### ISSUE TITLE
Issue while trying to use your demo in one of our programs.

### ISSUE THREAD

**Issue by sanjayabap** [abap2xlsx/abap2xlsx#436]
Hello Team,

I am getting an error message while trying to reuse your demo "ZDEMO_EXCEL3" in one of our customized T-code , as i am unable to use the Include inside a subroutine.

Would please assist me in providing an alternative solution or any suggestion for the same.

![untitled](https://cloud.githubusercontent.com/assets/18262914/15243593/2ed98ec6-191a-11e6-894a-1f578f0104ff.png)

Thanks & Regards,
Sanjay D

**Comment by StefanSchmoecker** [comment]
Hello Sanjay,

the include was never meant to be included into any other programs other than the demo-reports.
It's just a simple approach to give the demoreports a similar look and feel.

Please look into the coding of the include and copy and adjust the parts that are relevant to your own program

**Comment by sanjayabap** [comment]
Hello Stefan,

Thanks for the reply, now i understood. we can close this ticket.

Best Regards,
Sanjay D
