### ISSUE TITLE
How to choose the other Table format in excel

### ISSUE THREAD

**Issue by sanjayabap** [abap2xlsx/abap2xlsx#438]
Hi team,

I need to generate an excel sheet using Table style Light 9 format in excel. But in the class you have created it has only Table style Light 1-5. Would request you to kindly assist me on how to choose the style 9.

Attached screenshot for your reference.

Thanks & Regards,
Sanjay D
![style1](https://cloud.githubusercontent.com/assets/18262914/15737118/e24e1934-28c1-11e6-9eca-d7a0075ae6d5.png)
![style2](https://cloud.githubusercontent.com/assets/18262914/15737117/e237ea42-28c1-11e6-8de1-6f1fcc9d6147.png)

**Comment by ivanfemia** [comment]
Have you tried to pass a string TableStyleLight9 instead of the constant?

Ivan

**Comment by sandraros** [comment]
I did a test as Ivan proposed, and it worked for me. I copied the program `ZDEMO_EXCEL10` and I changed this line:
```abap
*ls_table_settings-table_style  = zcl_excel_table=>builtinstyle_medium5.
ls_table_settings-table_style  = 'TableStyleLight13'.
```
If it solves your question, could you close the question? Thanks.

**Comment by sandraros** [comment]
No answer. Closing.
