### ISSUE TITLE
Dump in LOAD_WORKSHEET_COND_FORMAT 

### ISSUE THREAD

**Issue by dkle-1** [abap2xlsx/abap2xlsx#441]
If "lv_area" is not in a regular format like 'A1:A2', a short dump occurs in method SET_RANGE of ZCL_EXCEL_STYLE_CONDITIONAL.
This variable is set in LOAD_WORKSHEET_COND_FORMAT, line 96.

Example values for which the dump occurs:
`BB24`
`J72:J997;J5;J13;J20;J27;J35;J43;J49;J55;J61;J67;J70`

For example 1 I attached a demo file.
Please fix either "zcl_excel_common=>convert_range2column_a_row", which handles the "lv_area" variable, or add a handling in "lo_style_conditional->set_range" if "ip_stop_column" and "-row" are empty. As a workaround, I added ZCX_EXCEL to the exceptions of SET_RANGE.
[ABAP2XLSX_Bug.xlsx](https://github.com/sapmentors/abap2xlsx/files/308640/ABAP2XLSX_Bug.xlsx)

Thanks and Regards
Daniel

**Comment by gregorwolf** [comment]
Hi Daniel,

would be great if you could contribute the fix yourself. Simply fork the project here on GitHub, commit the changes to that repository and create a pull request.

Best regards
Gregor

**Comment by sandraros** [comment]
Unfortunately I can't reproduce the issue with the latest version of abap2xlsx. As it was a long time ago, maybe the issue has been fixed.

Here is the result of program `ZDEMO_EXCEL37` if the input is the file above "ABAP2XLSX_Bug.xlsx": [37- Read template and output.xlsx](https://github.com/sapmentors/abap2xlsx/files/7637455/37-.Read.template.and.output.xlsx)

Could you confirm whether it's fine for you or not?
Thank you.

**Comment by dkle-1** [comment]
Hi sandraros,

I can't reproduce it, too, as method SET_RANGE of ZCL_EXCEL_STYLE_CONDITIONAL is not even run through anymore displaying the demo file with the report you mentioned.

Hence I will close this issue.

Regards
Daniel

**Comment by sandraros** [comment]
Too bad that the method is not even executed. If you have time to find a scenario how to reproduce, then we can reopen the issue and investigate for a solution. By the way, we did recent fixes to propagate all unhandled exceptions, so maybe it's difficult to reproduce anyway. Thanks.
