### ISSUE TITLE
calling fill_struct_from_attributes while "object is bound but initial" short dump - fix attached

### ISSUE THREAD

**Issue by Arvald** [abap2xlsx/abap2xlsx#442]
in ZCL_EXCEL_READER_2007 both LOAD_WORKBOOK and LOAD_WORKSHEET cause short dumps calling fill_struct_from_attributes with a bound but initial object.

I'm not sure if the xlsx I'm reading is malformed but this issue causes a short dump.
I've had this issue on both the August 2015 and the April 2016 builds.
Fix is easy, just check for is bound and not initial.
fix with line numbers below.
ZCL_EXCEL_READER_2007
LOAD_WORKBOOK
167  WHILE lo_node IS BOUND and lo_node is not initial.

LOAD_WORKSHEET
242   WHILE lo_ixml_node IS BOUND and lo_ixml_node is not INITIAL.
282   IF lo_ixml_tabcolor IS BOUND and lo_ixml_tabcolor is not initial.
297   WHILE lo_ixml_row_elem IS BOUND and lo_ixml_row_elem is not initial.
343     WHILE lo_ixml_cell_elem IS BOUND and lo_ixml_cell_elem is not initial.
378       IF lo_ixml_formula_elem IS BOUND and lo_ixml_formula_elem is not initial.
460   WHILE lo_ixml_column_elem IS BOUND and lo_ixml_column_elem is not INITIAL.
561   WHILE lo_ixml_mergecell_elem IS BOUND and lo_ixml_mergecell_elem is not INITIAL.
687   WHILE lo_ixml_datavalidation_elem  IS BOUND and lo_ixml_datavalidation_elem is not INITIAL.

**Comment by Arvald** [comment]
Missed one on the rebuild
line 543 add if around it "if lo_ixml_sheetview_elem is BOUND and lo_ixml_sheetview_elem is not initial."
also 656 around lo_ixml_sheetview_elem
also next line again...
many to add.

**Comment by StefanSchmoecker** [comment]
Can you provide an xlsx that causes this problem, please

**Comment by Arvald** [comment]
Unfortunately I am unable to provide the example as the contents is confidential and proprietary. 
I will check into if I can get an exception. 
 I am certain the xlsx is generated by a tool similar to abap2xlsx as I know of they run SAP

**Comment by StefanSchmoecker** [comment]
Maybe you can provide an example w/o the confidential information.  Basically delete everything unnecessary as long as the dump occurs in the reader

**Comment by Arvald** [comment]
[KPI.xlsx](https://github.com/sapmentors/abap2xlsx/files/348505/KPI.xlsx)
I was able to get the dump with this file.

**Comment by StefanSchmoecker** [comment]
I just downloaded your file and used ZDEMO_EXCEL37 to read it.  No dump.
If the file dumps for you - at which position does the dump occur?  
Maybe someone else can crosscheck whether it dumps on their system (use demoreport 37 for testing)

**Comment by Arvald** [comment]
More details to help.  
Unicode system
ERP 6 EhP7 support stack of about April 2015
It took me a while to have time to fully reverse out my fixes .
here is my calls list for the excel I uploaded.
    7 METHOD       ZCL_EXCEL_READER_2007=========CP    ZCL_EXCEL_READER_2007=========CM001    31
      ZCL_EXCEL_READER_2007=>FILL_STRUCT_FROM_ATTRIBUTES
    6 METHOD       ZCL_EXCEL_READER_2007=========CP    ZCL_EXCEL_READER_2007=========CM00C   636
      ZCL_EXCEL_READER_2007=>LOAD_WORKSHEET
    5 METHOD       ZCL_EXCEL_READER_2007=========CP    ZCL_EXCEL_READER_2007=========CM00B   266
      ZCL_EXCEL_READER_2007=>LOAD_WORKBOOK
    4 METHOD       ZCL_EXCEL_READER_2007=========CP    ZCL_EXCEL_READER_2007=========CM00J    74
      ZCL_EXCEL_READER_2007=>ZIF_EXCEL_READER~LOAD
    3 METHOD       ZCL_EXCEL_READER_2007=========CP    ZCL_EXCEL_READER_2007=========CM00K    17
      ZCL_EXCEL_READER_2007=>ZIF_EXCEL_READER~LOAD_FILE

**Comment by sandraros** [comment]
Unfortunately I can't reproduce the issue with the latest version of abap2xlsx. As it was a long time ago, maybe the issue has been fixed.

Here is the result of program `ZDEMO_EXCEL37` if the input is the file above "KPI.xlsx": [37- Read template and output.xlsx](https://github.com/sapmentors/abap2xlsx/files/7637516/37-.Read.template.and.output.xlsx)

Could you confirm whether it's fine for you also?
Thank you.

**Comment by Arvald** [comment]
The source I had for these files has changed to flat files so I don't even
think I have a copy of the problematic file any more.
I figure it is safe to close.
Thank you for following up after all this time.

**Comment by sandraros** [comment]
Let's close it then. Thank you!
