### ISSUE TITLE
Require same column names in excel file

### ISSUE THREAD

**Issue by mahesh-s-nikam** [abap2xlsx/abap2xlsx#445]
Hello All,

I have downloaded and uploaded nugget ABAP2XLSX_V_7_0_6 - 2016-04-01.nugg in our system.
This nugget works fine. 
But we have little issue that in our excel file that we have same column names.
And this nugget does not allow to have same column names in excel file.
Also we tried to change code in method BIND_TABLE of class ZCL_EXCEL_WORKSHEET. 
We are facing below attached errors.

![excel error if keep same column names](https://cloud.githubusercontent.com/assets/20464002/16985716/fec56c08-4e9f-11e6-91ca-cefd39497951.JPG)
![xml - excel error for same column names](https://cloud.githubusercontent.com/assets/20464002/16985754/3f71848a-4ea0-11e6-864c-3b8520425422.JPG)

As per our business requirement, we want certain columns that should have same column names in excel file.
Please help us resolving this issue.

Regards,
Mahesh Nikam.

**Comment by ivanfemia** [comment]
This is not an issue, but a constrain of Excel tables, you can test the same also directly in excel.
If you want to have same name in different columns you can't use the method bind table.

Ivan

**Comment by mahesh-s-nikam** [comment]
Hello,

Thanks for reply. 
Can you please provide solution for this issue?

Regards,
Mahesh Nikam.
Ph.: +919821394040

**Comment by mahesh-s-nikam** [comment]
Hello,

As we want to have same column names in excel file, we are trying to search that method in every class that starts from name ZCL_EXCEL\* where we can change code to get same column names in excel file.

Regards,
Mahesh Nikam.
Ph.: +919821394040

**Comment by ivanfemia** [comment]
You can't Excel tables don't allow columns with the same name, you have to
manually fill the cells looping rows and columns.

**Comment by mahesh-s-nikam** [comment]
Please let us know in which method cells are filled where lopping of rows and columns are happening.

**Comment by fidley** [comment]
Maybe tou can bind table without headers and then fill manually header
line. But then whole formatting must be done manually.

W dniu środa, 20 lipca 2016 Ivan notifications@github.com napisał(a):

**Comment by ivanfemia** [comment]
BIND_TABLE, but it uses the table object, so the constrain is not in
abap2xlsx but in Excel.

You can technically generate a TABLE object with duplicates name in
abap2xlsx, but excel will raise an issue.

**Comment by StefanSchmoecker** [comment]
Hallo Mahesh Nikam
The solution is quite simple. Use  differing names that look alike by adding whitespaces to some of the columns

**Comment by mahesh-s-nikam** [comment]
Thanks for everyone's reply.

We would really appreciate if any code change can be done in particular method for this type of issue.
We are searching that method where we can have duplicate or same column name before downloading excel file.

Regards,
Mahesh.

**Comment by ivanfemia** [comment]
This is not an issue, but standard Excel behavior
