### ISSUE TITLE
character zero in a char field from internal table are not comming out

### ISSUE THREAD

**Issue by caarbess** [abap2xlsx/abap2xlsx#446]
I have a internal table with a field type CHAR of length 7, possible values are 0,1 or 2 but in the excel output only the 1 and 2 are coming out, zero in field of type integer are coming out ok. Is there a show zero for character field ?

**Comment by ghost** [comment]
Same problem here, char1 field and it loses zero's, alpha & numbers other than zero are fine.

**Comment by sandraros** [comment]
I don't reproduce the problem with the method `BIND_TABLE` (see below program). Maybe you are using another method, or the issue has been fixed. Could you provide a demo program if the issue still occurs.
Thank you.

```abap
REPORT.
CONSTANTS gc_save_file_name TYPE string VALUE 'issue_446.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  TYPES: BEGIN OF ty_struc,
           value TYPE c LENGTH 7,
         END OF ty_struc,
         ty_table TYPE STANDARD TABLE OF ty_struc WITH DEFAULT KEY.
  DATA(itab) = VALUE ty_table( ( value = '0' ) ( value = '1' ) ).
  lo_worksheet->bind_table( ip_table = itab is_table_settings = VALUE #( top_left_column = 'A' top_left_row = 1 ) ).
  lcl_output=>output( lo_excel ).
```

**Comment by sandraros** [comment]
No answer. Proposing to close. You may reopen the issue if needed.
