### ISSUE TITLE
Demo programs empty

### ISSUE THREAD

**Issue by juanlee337** [abap2xlsx/abap2xlsx#449]
I have installed/activated all objects from the  latest nugg (ABAP2XLSX_V_7_0_6 - 2016-04-01.nugg) sucesfully but **all the ZDEMO\*  programs installed are completely  empty** as shown below . 

![emptydemo](https://cloud.githubusercontent.com/assets/20979480/17607524/e555c544-5feb-11e6-9fed-918c4e6e667b.PNG)

**Comment by gregorwolf** [comment]
What SAPlink version do you use? What exact release are you on? Have you checked the Nugget,   with a text editor? are the demos filled there.

**Comment by juanlee337** [comment]
Oddly enough, I looked at the nugg, and all the programs were missing.. I dont know how this happened..(really odd. I never manipulated the file manually).
 I downloaded a new file and re-imported the nugg . Had some major compiling issues but after working through them, I got them to compile. The majority of demos are  present now.

Saplink 2.0
I am kernel 742, sap_basis 740(sp 13).
