### ISSUE TITLE
Load XLSX file from MIME repository

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#452]
Hello community,
I have one suggestion to extend ZCL_EXCEL_READ_2007 class, to add a method load_file_from_mime which loads an XLSX file from MIME repository.

```
    METHODS load_file_from_mime 
      IMPORTING 
                !i_uri             TYPE csequence 
                !i_use_alternate_zip    TYPE seoclsname DEFAULT space 
                !iv_zcl_excel_classname TYPE clike OPTIONAL 
      RETURNING VALUE(r_excel)          TYPE REF TO zcl_excel 
      RAISING 
                zcx_excel.
```

```
  METHOD load_file_from_mime.

    DATA:
      lr_mr_api       TYPE REF TO if_mr_api,
      lv_uri          TYPE string,
      lv_errormessage TYPE string,
      lv_excel_data   TYPE xstring.

    IF lr_mr_api IS INITIAL.
      lr_mr_api = cl_mime_repository_api=>if_mr_api~get_api( ).
    ENDIF.

    CALL METHOD lr_mr_api->get
      EXPORTING
        i_url              = i_uri
      IMPORTING
        e_content          = lv_excel_data
      EXCEPTIONS
        parameter_missing  = 1
        error_occured      = 2
        not_found          = 3
        permission_failure = 4
        OTHERS             = 5.

    IF sy-subrc <> 0.
      lv_errormessage = 'A problem occurred when reading the file'(001).
      RAISE EXCEPTION TYPE zcx_excel
        EXPORTING
          error = lv_errormessage.
    ENDIF.

    r_excel = zcl_if_excel_reader~load(
      i_excel2007            = lv_excel_data
      i_use_alternate_zip    = i_use_alternate_zip
      iv_zcl_excel_classname = iv_zcl_excel_classname
    ).

  ENDMETHOD.
```

I want to use this method to load Excel templates from the MIME repository. I have checked it and it works very well.

What do you think?

Thanks and cheers
Stefan

**Comment by fidley** [comment]
👍 For me seems reasonable and I use same approach

**Comment by StefanSchmoecker** [comment]
MIME is not the only place where you can drop your templates.  I for instance use the Business Object Repository ( transaction OAER ) and there are even more places like the document services ( transaction CV01N, CV02N, CV03N ) or whatever.
And I don't like the idea to have a "READ_FROM_xxx" method for everything that comes up in the readerclass.
Alternate suggestion: Let's create a new class with a few static methods like "GET_EXCEL_AS_XSTRING_FROM_MIME","GET_EXCEL_AS_XSTRING_FROM_BOR","GET_EXCEL_AS_XSTRING_FROM_..." which retunrs the xstring and use this to call the zcl_if_excle_reader~load method.
With the chaining of modern SAP-releases the call would then look like this:

``` ABAP
lo_reader->load( zcl_newclass=>get_excel_as_xstring_from_mime( i_uri = ... ) ).
```

We could even add some "WRITE TO" methods as well to have the result put there

**Comment by ivanfemia** [comment]
Thank you for the suggestion but I would avoid many WRITE_TO methods, but I would suggest to extend the WRITER class adding the method that your business scenario requires or implement that logic in your ABAP program.

Ivan

**Comment by ghost** [comment]
Hello Ivan,
thanks for your reply.
Cheers
Stefan
