### ISSUE TITLE
Subsequent Changes Of Font Attribute Name Doesn't Work

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#455]
Hello community,

to format a range of a worksheet I develop a [class](https://github.com/StefanSchnell/ABAP2XLSXExamples/blob/master/zcl_xlsx_format.abap) which works very good. You can set border, number formats or background colors. But if I use the same procedure with a font attribute, it doesn't work. The font attribute name is always set to the standard font name - in my case Calibri. As far as I can find out the font name is internally set correct but after I write it with the writer class, the style (XML attribute s) of the cells is set to the standard font name. To set the correct font attributes I set it actually with the set_cell method, it works as expected. But my intention is to set the font attributes independently from the set_cell method.

Thanks for tips and hints.

Cheers
Stefan

**Comment by sandraros** [comment]
In the below program, the value is first written with `SET_CELL`, and the font "72" is set afterwards with `SET_CELL_STYLE` and it works for me:
![image](https://user-images.githubusercontent.com/34005250/147415904-dee4a435-99c6-4027-88eb-419e0f8e4e0a.png)

Github user was deleted, so closing.

```abap
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'test.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  DATA(lo_style) = lo_excel->add_new_style( ).
  lo_style->font->name = '72'. " any font name
  lo_style->font->scheme = zcl_excel_style_font=>c_scheme_none.
  lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = 'hello' ).
  lo_worksheet->set_cell_style( ip_column = 'A' ip_row = 1 ip_style = lo_style->get_guid( ) ).
  lcl_output=>output( cl_excel = lo_excel ).
```
Proposing to close.
