### ISSUE TITLE
Support of pivot tables?

### ISSUE THREAD

**Issue by fmacaluso** [abap2xlsx/abap2xlsx#458]
Hello Ivan,
I am working with your amazing tool and business asked me to insert a pivot table within a report.
Is it possible with abap2xlsx?

Thanks,
Francesco

**Comment by ivanfemia** [comment]
Hi Francesco,

Pivot table are not currently available in abap2xlsx.
You can try to implement this functionality by yourself and then share your results with our community... 
I'll be happy to extend abap2xlsx with this feature.

Ivan

**Comment by fmacaluso** [comment]
Ok Ivan,
I can give it a try.. if you have some documentation about the project, would you please send it to me?
In this way I will have a better comprehension on what is already developed and I could use it for implementation of Pivot Table..

Thanks,
Francesco
