### ISSUE TITLE
VERSION constant is 7.0.3 in the 7.0.6 NUGG file

### ISSUE THREAD

**Issue by kbarter** [abap2xlsx/abap2xlsx#459]
I downloaded the uncompressed NUGG for 7.0.6 from (https://github.com/ivanfemia/abap2xlsx/blob/master/build/ABAP2XLSX_V_7_0_6%20-%202016-04-01.nugg), and ran the demo programs.

When looking at the version in the spreadsheets (File Info), you can see that the version says 7.0.3 still.  The wiki says that this should be the version number from 7.0.1 onwards.

The line in the NUGG that needs to be changed is:

> ```
> <attribute CLSNAME="ZCL_EXCEL" CMPNAME="VERSION" VERSION="1" LANGU="E" DESCRIPT="abap2xlsx version" EXPOSURE="0" STATE="1" EDITORDER="1 " ATTDECLTYP="2" ATTVALUE="&apos;7.0.3&apos;" ATTEXPVIRT="0" TYPTYPE="1" TYPE="CHAR10" SRCROW1="0 " SRCCOLUMN1="0 " SRCROW2="0 " SRCCOLUMN2="0 " TYPESRC_LENG="0 "/>
> ```

I think the 7.0.3 should be 7.0.6

I also checked the ZIP version, and it is the same.

Is this something that can be updated?  It is really nice to be able to easily find what version has been installed.

Thanks,

Kevin

**Comment by fidley** [comment]
Seems to be my fault, I haven't notice that during creation of nugget. But seems that it was missed before as well ;)

**Comment by Gh14Cc10** [comment]
Hi @fidley just fixed it :)

Just update the version docs when you have time please

**Comment by fidley** [comment]
@Gh14Cc10 done
