### ISSUE TITLE
String and number cells with same value

### ISSUE THREAD

**Issue by ulyssesb** [abap2xlsx/abap2xlsx#461]
Hello, 

The class ZCL_EXCEL_WRITER_2007 has a small problem writing a sheet containing two cells with same value but of different types, i.e. one string '5' and numeral 5 . 

In this case the string 5 will not be created at create_xl_sharedstrings and a random string (index 0) will be used to generate the file. 

<img width="1673" alt="screen shot 2016-09-21 at 15 25 26" src="https://cloud.githubusercontent.com/assets/26729/18714246/6d7f7bec-8015-11e6-834c-8d0744fd260f.png">

I'm sending a PR with a correction. 

Thank you all

**Comment by ghost** [comment]
Hello ulyssesb,
thanks for your analysis, you are right. I corrected the error in our system with
`DELETE ADJACENT DUPLICATES FROM lt_cell_data COMPARING cell_value data_type.`
on method create_xl_sharedstrings.
Thanks and cheers
Stefan

**Comment by larshp** [comment]
also see pull request: https://github.com/sapmentors/abap2xlsx/pull/462

**Comment by ghost** [comment]
Hello larshp,
thank you very much.
I corrected also the code in the class ZCL_EXCEL_WRITER_HUGE_FILE.
Cheers
Stefan

**Comment by ivanfemia** [comment]
Fixed
