### ISSUE TITLE
New SAP Community

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#466]
Hello community,

one tiny question about the new SAP Community:
Before the relaunch abap2xlsx was discussed in the open source forum. What is now, after the relaunch, the correct forum?

Thanks for tips and hints.

Cheers
Stefan

**Comment by ghost** [comment]
Hello community,

now I use the tag **ABAP Development** for my [abap2xlsx] blog posts.

Cheers
Stefan

**Comment by ivanfemia** [comment]
Stefan I tried to find a better space... but for now ABAP development as you suggested is the best option

Thank you

**Comment by ghost** [comment]
Hello Ivan,

thank you very much for your reply.

Cheers
Stefan
