### ISSUE TITLE
Change ref attribute of file /xl/tables/table1.xml

### ISSUE THREAD

**Issue by MiguelMotta87** [abap2xlsx/abap2xlsx#467]
Hi,

I would like to use BIND_DATA method to set a table and your style.
In a second step, I will fill the cells with the values manually.
For this, I called BIND_DATA method with an empty table for performance issues.
In this way, I can set the total number of rows in my table and it have only header and one item with style defined.
I would like to change the attributes "ref" of file "/xl/tables/table1.xml" to manipulate the size of table.
It is possible?

Thanks!

**Comment by StefanSchmoecker** [comment]
Hi Miguel,

create a subclass of ZCL_EXCEL_WRITER_2007 and redefine method CREATE_XL_TABLE to.
That should fulfill your needs

**Comment by MiguelMotta87** [comment]
Hi Stefan,

Thanks for the sugestion!
To solve the problem I modified the BIND_TABLE method.

Add one importing parameter "IV_ROWS_TABLE" type I.

Change:
`lo_table->set_data( ir_data = ip_table ).`

With:

```
DATA: lr_table_copy TYPE REF TO data.
FIELD-SYMBOLS: <lt_table_copy> TYPE STANDARD TABLE.

IF iv_rows_table IS SUPPLIED.
  "Copy table IP_TABLE
  CREATE DATA lr_table_copy LIKE ip_table.
  ASSIGN lr_table_copy->* TO <lt_table_copy>
  "Insert initial lines in copy table
  DO iv_rows_table TIMES.
    APPEND INITIAL LINE TO <lt_table_copy>.
  ENDDO.
  "Set the table with empty lines for the object,
  "only to be used for reference.
  lo_table->set_data( ir_data = <lt_table_copy> ).
ELSE.
  lo_table->set_data( ir_data = ip_table ).
ENDIF.
```

With this change, I call BIND_TABLE method passing number of rows that I want to IV_ROWS_TABLE parameter and an empty table to IP_TABLE parameter, avoiding the loop in IP_TABLE (where I had performance problem, since my table had approximate dimensions of 25000 rows by 160 columns, and the great most fields had no value).

If anyone has any comments about the changes made, please tell here.
