### ISSUE TITLE
[abap2xlsx] - Issues with image and formula 

### ISSUE THREAD

**Issue by Alessandro-Ieva** [abap2xlsx/abap2xlsx#468]
Hi,
I would like signal two issues.

1. Image in a cell.
When I insert a image in a cell, I can't decide the distace from top and from the side of cell.
In case I have a cell with edges drawn, the image covers the lines of the edges.

2. Formula in a cell.
I save a file with a formula in a cell, after, I open that file and I decide to close it, I display a popup for save the change, but,I don't have changed anything.

I wrong anything?
Thank you all in advance.

Alessandro Ieva

PS.
Congratulation for abap2xlsx. It is very helpfull :)

**Comment by sandraros** [comment]
Sorry for late answer.
1. You may use the parameters `IP_ROWOFF` and `IP_COLOFF` of the method `SET_POSITION`. If you copy the program `ZDEMO_EXCEL16` and add the 2 parameters as shown below, you will see a little shift of the image (NB: big numbers for little shift):
   ```abap
     lo_drawing->set_position( ip_from_row = 3
                               ip_from_col = 'B'
                               ip_rowoff   = 100000
                               ip_coloff   = 50000 ).
   ```
2. Usually, Excel doesn't ask to save. Do you have an Excel file that we can check?
Thank you.

**Comment by sandraros** [comment]
No answer. Closing.
