### ISSUE TITLE
Error in shared strings

### ISSUE THREAD

**Issue by StefanSchmoecker** [abap2xlsx/abap2xlsx#470]
If an excel sheets contains cells with a cell value that may be interpreted as numerical ( i.e. 3 ) and the this cell value appears in the excel-sheet in a numeric format and in a string format ( one cell with integer 3,  another cell with string "3" )  the creation of the string table may fail.

Program error.

**Comment by larshp** [comment]
fixed in PR https://github.com/ivanfemia/abap2xlsx/pull/462 ?

**Comment by StefanSchmoecker** [comment]
Looks like it - and that I have to update my reference system to the latest version of ABAP2XLSX.

Thank you, Lars.

**Comment by sandraros** [comment]
Duplicate of #461
