### ISSUE TITLE
open EXCEL with password

### ISSUE THREAD

**Issue by Happyelsa** [abap2xlsx/abap2xlsx#471]
Dears, i would like to ask there is any possible for AbapXlsx to implement the function: protect EXCEL file with password, means we need to key-in password before opening EXCEL file.

Ref. link: https://support.office.com/en-us/article/Protect-an-Excel-file-7359d4ae-7213-4ac2-b058-f75e9311b599

**Comment by ivanfemia** [comment]
Hi,

This is not possible because, afaik, it is not an ooxml standard but a (Microsoft) functionality to binary encrypt the excel.

Ivan

**Comment by FoxAhead** [comment]
I think it's still possible, but someone would have to dive deep into [MS-OFFCRYPTO documentation](https://msdn.microsoft.com/en-us/library/cc313071(v=office.12).aspx) and implement encryption method in ABAP. Which would take much effort and time. Hoping it's opensource project and someone could take a challenge :)

**Comment by larshp** [comment]
I have an ABAP project implementing much of PGP, https://github.com/larshp/abapPGP

You can have a look, and work on the encryption part if you like, much of the hardcore stuff is already done 😄
