### ISSUE TITLE
loose values in Method CREATE_XL_SHAREDSTRINGS of ZCL_EXCEL_WRITER_2007  

### ISSUE THREAD

**Issue by volhei** [abap2xlsx/abap2xlsx#473]
Hello,
there is an issue with metod create_xl_sharedstrings, when you have a numeric value in a character field, which is already in a previous row in a numeric field.

line 54-56
   SORT lt_cell_data BY cell_value.         
   DELETE ADJACENT DUPLICATES FROM lt_cell_data COMPARING cell_value.

**Issue:**
--> with the delete adjacent duplicates, the entry with data type 's' will be deleted, that means we loose the value in shared string.
   
   
**How to reproduce:**
    DATA lr_excel TYPE REF TO zcl_excel.
    DATA lr_writer TYPE REF TO zif_excel_writer.

    DATA: BEGIN OF ls_test,
            char_field TYPE char5,
            num_field  TYPE i,
          END OF ls_test.
    DATA lt_test LIKE TABLE OF ls_test.

    ls_test-char_field = 'xxx'.
    ls_test-num_field = 52.
    INSERT ls_test INTO TABLE lt_test.
    ls_test-char_field = '52'.
    ls_test-num_field = 111.
    INSERT ls_test INTO TABLE lt_test.

    DATA(lt_field_catalog) = zcl_excel_common=>get_fieldcatalog( ip_table = lt_test ).

    CREATE OBJECT lr_excel.
    " Get active sheet
    DATA(lr_worksheet) = lr_excel->get_active_worksheet( ).

    TRY .
        lr_worksheet->bind_table( ip_table      = lt_test
                                  it_field_catalog  = lt_field_catalog ).

        CREATE OBJECT lr_writer TYPE zcl_excel_writer_2007.
        lv_xdata = lr_writer->write_file( lr_excel ).
        lt_rawdata = cl_bcs_convert=>xstring_to_solix( iv_xstring  = lv_xdata ).
        lv_bytecount = xstrlen( lv_xdata ).

        lv_filename = 'C:\TEMP\TEST.XLSX'.
        cl_gui_frontend_services=>gui_download( EXPORTING bin_filesize = lv_bytecount
                                                          filename     = lv_filename
                                                          filetype     = 'BIN'
                                                 CHANGING data_tab     = lt_rawdata ).

      CATCH zcx_excel.

    ENDTRY.

Result with missing value 
![grafik](https://cloud.githubusercontent.com/assets/25530939/22595706/edb22346-ea28-11e6-89e6-0e105abebb5f.png)

[test.xlsx](https://github.com/ivanfemia/abap2xlsx/files/750749/test.xlsx)

**Proposed solution - works for me :)** 
  SORT lt_cell_data BY cell_value data_type.
  DELETE ADJACENT DUPLICATES FROM lt_cell_data COMPARING cell_value data_type.

Best Regards
Volker

**Comment by ivanfemia** [comment]
We have a pull request #462 that solves the issue but it has conflicts to be analyzed.

**Comment by ivanfemia** [comment]
can you submit the change in the repo so I can include it? you implemented a good fix

**Comment by volhei** [comment]
Hi Ivan, sorry to ask this stupid question.
Can you tell me howq to submit the change in the repo ? 
Best Regards
Volker

**Comment by ivanfemia** [comment]
No problem.
Try to follow this [documentation](https://help.github.com/articles/creating-a-pull-request/)

**Comment by volhei** [comment]
sorry I am not so experienced with git. I have cloned the repo in my eclipse (egit plugin). But for me it's not clear how to proceed further. I will ask a colleague next monday.

**Comment by ivanfemia** [comment]
Thank you for your effort and contribution

**Comment by ivanfemia** [comment]
Fixed in latest release
