### ISSUE TITLE
Closedxml error after merging cells

### ISSUE THREAD

**Issue by 208047758** [abap2xlsx/abap2xlsx#475]
Can anyone assist, I am generating an excel document using C#. I use ClosedXML v0.86.0 to format the document prior saving it into a directory. 

The problem is that when I open the document I get an error: We found a problem with some content in xxxx.xlsx. Do you want us to try recover as much as we can? When I click yes the document open up but I get the following: 

Removed Feature: Table from /xl/tables/table.xml part (Table)
Removed Feature: Table from /xl/tables/table2.xml part (Table)

I tried troubleshooting the problem and it only happens if there merged cells in the spreadsheet. 

Does anyone know how to avoid this issue.

**Comment by gregorwolf** [comment]
As this project is implemented in ABAP I close this incident. Please look for a C# forum.
