### ISSUE TITLE
Slinkee File for DEVC plugin

### ISSUE THREAD

**Issue by asuji20** [abap2xlsx/abap2xlsx#478]
Hi,

Could you please provide a slinkee file for DEVC plugin. ZSAPLINK_DEVC.
I need it to implement several other nuggets.

Thank you very much.

**Comment by ivanfemia** [comment]
Hi please contact SAPLink support 

www.saplink.org/

Ivan

**Comment by asuji20** [comment]
I couldnt find a support link anywhere there. thats y posted here.
