### ISSUE TITLE
Question of oleObject integration

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#479]
Hello Ivan. Stefan and the abap2xlsx team,
I have a question of oleObject integration in abap2xlsx:
In the context of our realisation we want to integrate files as OLE objects in the xlsx. I look in the xlsx file and see that this kind of object was stored as <oleObjects> resp. as <oleObject> node in the XML. So I look at the nugg file and search for xml_node_ole* but I can't find an entry. So I assumee that abap2xlsx doesn't support this kind of object, is that correct? If yes, is there another way to integrate a file into the xlsx via abap2xlsx?
Thanks for an answer, hints and tips.
Cheers
Stefan

**Comment by ivanfemia** [comment]
Hi Stefan,
this functionality has never been implemented, but you're more than welcome to contribute and include also this functionality.
I don't recall any functionality to include Ole object at the moment.

Best,
Ivan

**Comment by ghost** [comment]
Hello Ivan,
thank you very much for your fast reply.
Best regards
Stefan
