### ISSUE TITLE
Multiple styles in one cell

### ISSUE THREAD

**Issue by marian-morzol** [abap2xlsx/abap2xlsx#486]
Hi,

Does ABAP2XSLX support multiple styles in one cell ? For example one half of a word will be bold and second one will be italic ? **Bold**_Italic_

Thank you for your answer.

With regards,

Marian Morzol

**Comment by ivanfemia** [comment]
Hi Marian,

this feature is not implemented, but if you want to contribute you can fork
it in GitHub and propose a solution.

Ivan

**Comment by marian-morzol** [comment]
Hi,
OK. No problem. Your software is awersome and it has to take a lot of time. 
Maybe one more question: Is there any possibility how to determine that some row will be printed on a new page when I consider for example page size A4 ?
So it would be possible to implement some repetitive parts as e.g. Headers and footers of table ?

Thank you for your answer.

With regards.

Marian Morzol

**Comment by sigitas-stumbras** [comment]
Hi,

I am almost done implementing "Multiple styles in one cell" functionality. Well, it is not actually about multiple complete cell styles, but rather about different font styles applied to different parts of string - rich text formatting (RTF).  

- I've used the least invasive approach - I've kept the cell value attributes untouched and the RTF data comes as separate internal table with this record structure: offset, length, font style.
- To minimize the impact on memory use, I've included a reference to RTF table type in existing structures rather than using table type directly. Although this comes at some cost of a little more complicated code.
- I've done this for ZCL_EXCEL_WRITER_2007 and ZCL_EXCEL_READER_2007. I've refactored and reused font processing in reading/writing of cell styles as it is identical for RTF cell values.

Here are some things to consider
1. I  am using plain itab1[] = itab2[] to check for RTF table equality - I am not sure since which ABAP release version this is possible. 
2. Right now the usage for this new functionality is rather Excel-technical. It looks something like this

```
 lt_rtf = VALUE zexcel_t_rtf(
" no need to specify font style for the first part if it is to be the same as the cell style
    ( offset = 0 
      length = 2 )
" and now, ladies and gents, a DIFFERENT!!! font style
    ( offset = 2 
      length = 2 
      font   = lo_bold_style->font->get_structure( ) )
" but after that you must explicitly specify back the font style of the cell style,
" otherwise in Excel this will be rendered in the font style of the default cell style 
" of the worksheet
    ( offset = 4 
      length = 2 
      font   = lo_cell_style->font->get_structure( ) )
   ).
  
" rich text formatting info must exactly cover the entire string value, 
" or an exception is thrown
  lo_worksheet->set_cell( ip_cell = 'B2' 
    ip_style = lo_cell_style 
    ip_value = 'ABCDEF' 
    it_rtf   = lt_rtf  ).
```

Maybe some more relaxed and concise use would be desirable? Something like:
```
lo_worksheet->set_cell( ip_cell = 'B2' ip_value = 'ABCDEF' ).
lo_worksheet->apply_font_style( ip_cell = 'B2' 
  ip_offset = 2 
  ip_length = 2 
  ip_font = lo_bold_style->font ).
```

Sigitas

**Comment by ivanfemia** [comment]
Sigitas,

interesting news!
Thank you so much for your contribution.

Ivan

**Comment by vinhvosap** [comment]
> 
> 
> Hi,
> 
> I am almost done implementing "Multiple styles in one cell" functionality. Well, it is not actually about multiple complete cell styles, but rather about different font styles applied to different parts of string - rich text formatting (RTF).
> 
>     * I've used the least invasive approach - I've kept the cell value attributes untouched and the RTF data comes as separate internal table with this record structure: offset, length, font style.
> 
>     * To minimize the impact on memory use, I've included a reference to RTF table type in existing structures rather than using table type directly. Although this comes at some cost of a little more complicated code.
> 
>     * I've done this for ZCL_EXCEL_WRITER_2007 and ZCL_EXCEL_READER_2007. I've refactored and reused font processing in reading/writing of cell styles as it is identical for RTF cell values.
> 
> 
> Here are some things to consider
> 
>     1. I  am using plain itab1[] = itab2[] to check for RTF table equality - I am not sure since which ABAP release version this is possible.
> 
>     2. Right now the usage for this new functionality is rather Excel-technical. It looks something like this
> 
> 
> ```
>  lt_rtf = VALUE zexcel_t_rtf(
> " no need to specify font style for the first part if it is to be the same as the cell style
>     ( offset = 0 
>       length = 2 )
> " and now, ladies and gents, a DIFFERENT!!! font style
>     ( offset = 2 
>       length = 2 
>       font   = lo_bold_style->font->get_structure( ) )
> " but after that you must explicitly specify back the font style of the cell style,
> " otherwise in Excel this will be rendered in the font style of the default cell style 
> " of the worksheet
>     ( offset = 4 
>       length = 2 
>       font   = lo_cell_style->font->get_structure( ) )
>    ).
>   
> " rich text formatting info must exactly cover the entire string value, 
> " or an exception is thrown
>   lo_worksheet->set_cell( ip_cell = 'B2' 
>     ip_style = lo_cell_style 
>     ip_value = 'ABCDEF' 
>     it_rtf   = lt_rtf  ).
> ```
> 
> Maybe some more relaxed and concise use would be desirable? Something like:
> 
> ```
> lo_worksheet->set_cell( ip_cell = 'B2' ip_value = 'ABCDEF' ).
> lo_worksheet->apply_font_style( ip_cell = 'B2' 
>   ip_offset = 2 
>   ip_length = 2 
>   ip_font = lo_bold_style->font ).
> ```
> 
> Sigitas

**Comment by vinhvosap** [comment]
Dear Sigitas,

We have one requirement to read the XLSX Excel with "multiple styles in one cell" into ZCL_EXCEL_READER_2007, then save the XLSX Excel again by ZCL_EXCEL_WRITER_2007.
So we really need to have this "Multiple styles in one cell" functionality.

Could you please help to share your implementation of "Multiple styles in one cell" functionality?
Thank you very much.

Vinh

**Comment by sandraros** [comment]
For information, inside the XLSX file, the texts are stored in `sharedStrings.xml` like this, where text is "**Read first the instructions ...** Log into SAP. Create a **(** something) ..." (first portion is bold, second is not bold, third is bold, etc.):
<img src="https://user-images.githubusercontent.com/34005250/108223042-aaf21b00-7139-11eb-9fca-a0fd167d7ece.png" width="500">
