### ISSUE TITLE
Some complex(?) formulas don't work..

### ISSUE THREAD

**Issue by plato79** [abap2xlsx/abap2xlsx#487]
Actually not that complex. Let me give you an example..

If I write this it works:

SUM(J2:N2)

But if I like this it doesn't work:

IF(SUM(J2:N2)>0;0;SUM(J2:N2))

What could be the problem?

**Comment by ivanfemia** [comment]
Excel ooxml I think requires coma instead of semi columns could you try

Ivan

**Comment by plato79** [comment]
Is it different from what we wrote in the excel? Because comma doesn't work there. 

    23 Mayıs 2017 15:00 Salı tarihinde Ivan <notifications@github.com> şöyle yazdı:
 

 Excel ooxml I think requires coma instead of semi columns could you try

Ivan

**Comment by ivanfemia** [comment]
Yes, parameter separators depends on language in the Excel program, but OOXML uses always the default (english).

**Comment by ivanfemia** [comment]
closing
