### ISSUE TITLE
Wrong data or empty cells when filling template

### ISSUE THREAD

**Issue by LasseB97** [abap2xlsx/abap2xlsx#488]
Hello,

we have a problem with reading a template, filling it with data and creating an output for it.

The attached file should be filled with data from an internal table and most of it is actually correct but some columns contain weird data. The output file is attached, too.
The last page is created in ABAP and will be added to the template. Some cells on the second and last page now have the content "%-Satz erfasste Lieferposi. 2014". This is the content of one cell on the first page. 
If we do not add the last page these cells on the second page are just empty. 
We looked at the created excel object (lo_excel) with the debugger and there the cell values are correct.

Is this a known problem and do you have any ideas why this happens?

FYI: Because of sensitive customer information we had to edit some columns in the output file. These columns contain the value 'XXX'. If you need to see the original file we can give it to you in private but not public. If needed source code can be provided.
[Excel Input.xlsx](https://github.com/sapmentors/abap2xlsx/files/1101307/Excel.Input.xlsx)
[Excel Output.xlsx](https://github.com/sapmentors/abap2xlsx/files/1101308/Excel.Output.xlsx)

**Comment by LasseB97** [comment]
Hello,

we found the problem. Attached you can see two screenshots. 
In the method "CREATE_XL_SHAREDSTRINGS" you only compare the cell value to delete adjacent duplicates. Additionally you have to comapare the data type.

![code before](https://user-images.githubusercontent.com/29089827/27726032-0f4c196c-5d79-11e7-86da-d602962766f3.png)
![code after](https://user-images.githubusercontent.com/29089827/27726035-1297e222-5d79-11e7-80e7-e03078dfdf16.png)

**Comment by mramesh4** [comment]
Hi,
Were you able to do the data population into template excel in background?

Thanks in Advance,
Ramesh

**Comment by sandraros** [comment]
There was a [fix](https://github.com/sapmentors/abap2xlsx/commit/5d80ca2a41e76dc4b8b15c02bf02ad62fd282976) approximately at the same time in 2017, following this duplicate issue #461. I propose to close this issue. Don't hesitate to reopen it, if needed. Thank you.
