### ISSUE TITLE
Titles on Charts

### ISSUE THREAD

**Issue by hwittler** [abap2xlsx/abap2xlsx#489]
I crated an Excel file with 3 Charts in it (Two Bar Charts, 1 Pie Chart).
The ip_title set in pr_summary->excel->add_new_drawing is ignored in all three of them.
The pie and the Bar Chart with only one series have the ip_sername of the series as title for the Chart,
The bar with 2 series doesn't have a title at all. (if i remove one of the series the sername is used for the title.

I think there is a bug in ZCL_EXCEL_WRITER_2007->CREATE_XL_CHARTS but haven't figuered out where exactly

**Comment by ivanfemia** [comment]
Can you try ZDEMO_EXCEL39?
Do you have a test case?

**Comment by hwittler** [comment]
Hi, thanks for the answer.



ZDEMO_EXCEL39 has the same Problem. :)

In Line 318 add_new_drawing is called with title 'CHART BARS WITH 1 SERIE'.
When Run the Chart Shows the title 'My Serie 1' which is the Label of the first Serie.

For the program i am working on we have removed the second Serie for now.
Coding would be:

CONCATENATE '''' gc_sheet_2 '''' '!$B$4:$B$9' INTO lv_lbl.
CONCATENATE '''' gc_sheet_2 '''' '!$C$4:$C$9' INTO lv_ref.

CALL METHOD lr_bar->create_serie
EXPORTING
ip_order = 0
ip_invertifnegative = zcl_excel_graph_bars=>c_invertifnegative_no
ip_lbl = lv_lbl
ip_ref = lv_ref
ip_sername = 'Verbrauch'.

CONCATENATE '''' gc_sheet_2 '''' '!$B$2:$B$7' INTO lv_lbl.
CONCATENATE '''' gc_sheet_2 '''' '!$D$2:$D$7' INTO lv_ref.

CALL METHOD lr_bar->create_serie
EXPORTING
ip_order = 1
ip_invertifnegative = zcl_excel_graph_bars=>c_invertifnegative_no
ip_lbl = lv_lbl
ip_ref = lv_ref
ip_sername = 'Vorperiode'.

CALL METHOD lr_bar->create_ax
EXPORTING
ip_type = zcl_excel_graph_bars=>c_catax.

CALL METHOD lr_bar->create_ax
EXPORTING
ip_type = zcl_excel_graph_bars=>c_valax.

" Set style
lr_bar->set_style( zcl_excel_graph=>c_style_default ).
lr_bar->set_style( zcl_excel_graph=>c_style_26 ).

________________________________
Von: Ivan <notifications@github.com>
Gesendet: Donnerstag, 5. Oktober 2017 19:20
An: ivanfemia/abap2xlsx
Cc: Wittler, Hans-Christian; Author
Betreff: Re: [ivanfemia/abap2xlsx] Titles on Charts (#489)


Can you try ZDEMO_EXCEL39?
Do you have a test case?

-

**Comment by hwittler** [comment]
lr_drawing = pr_summary->excel->add_new_drawing(
                  ip_type  = zcl_excel_drawing=>type_chart
                  ip_title = 'Chart Nummernkreisverbrauch' ).
  lr_drawing->graph = lr_bar.
  lr_drawing->graph_type = zcl_excel_drawing=>c_graph_bars.
