### ISSUE TITLE
 Range Border

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#49]
Hi all,

Is there any method to set border of ranges? I couldn't find any thing about border of a range..

Thanks.

**Comment by ivanfemia** [comment]
Can you please provide a sample Excel File which contains the feature you're requesting?

**Comment by ivanfemia** [comment]
[[file:bsdo5Ecfer4kHmeJe7bhNc]]

**Comment by ivanfemia** [comment]
Just a simple border for range. Thanks for reply Gregor.

**Comment by ivanfemia** [comment]
Updating issues (#23, #28, #31, #32, #49, #53, #71, #94, #97, #99, #107, #110)

**Comment by ivanfemia** [comment]
Updating issues (#23, #28, #31, #49, #53, #71, #94, #97, #99, #107, #112, #127)

Moved to Release 7.0

**Comment by ivanfemia** [comment]
[[file:cCNj0YdcKr473dacwqjQYw]]

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Closed because no objections have arisen.
