### ISSUE TITLE
Objects (images, formular-objects) get lost

### ISSUE THREAD

**Issue by moasda** [abap2xlsx/abap2xlsx#490]
Hallo, 

I have got a problem with a complex makro excel we use. The file includes some vba code, images and formular objects like checkboxes and buttons.
When I load this excel marko file by class ZCL_EXCEL_READER_XLSM (method load) and write it with class ZCL_EXCEL_WRITER_XLSM (method write_file) all images and formular objects get lost.

Thanks a lot

**Comment by ivanfemia** [comment]
Reader has some limitation.
You can propose an enhancement to include this functionality
