### ISSUE TITLE
Annoying Popup when displaying Excel-file

### ISSUE THREAD

**Issue by INT-Obi** [abap2xlsx/abap2xlsx#491]
Hello Team,

I have a problem with the abap2xlsx functionalities included in one of my programs. To be sure that the problem is not caused by my Code, I tried to run one of your examples and the same behaviour occurred:

Whenever I try to get an Excel-file displayed directly on the screen, for example with the demo-Report ZDEMO_EXCEL2 a popup will Show up as this:
<img width="359" alt="erf_popup" src="https://user-images.githubusercontent.com/29898127/27872318-ae755cbe-61a8-11e7-94b1-a550aa5504b9.PNG">

English Translation:
The file Format and the filename Extension of '~SAP{ ... ... ... }' do not match. The file may be damaged or not safe. You should not open it unless you trust the source. Do you want to open the file? - Yes/No

I have already investigated a little but came to a point deep in the abap2xlsx-coding where I don't know, what to do.
I found this:
After executing this method via 'F6' the error popped up.
<img width="938" alt="erf_ hier druber-dann kam popup" src="https://user-images.githubusercontent.com/29898127/27873665-3542473a-61ad-11e7-9538-0225daf29875.PNG">

So I looked into it and this is the Status of the error-variable right before the flush:
<img width="505" alt="erf - fehler unmittelbar vor dem flush" src="https://user-images.githubusercontent.com/29898127/27873704-5d4da3e6-61ad-11e7-9294-a4c372cd9c94.PNG">

Can you please help me to get rid of that popup?
If I can help by debugging further or providing other details, I will be happy to do so.

Thank you very much.

**Comment by gregorwolf** [comment]
Hello,

this must be a problem with your Office installation. I've just executed the ZDEMO_EXCEL2 report and the generated file was displayed inline without any issues. What happens when you choose the "save to frontend" and open the resulting file?

Best regards
Gregor

**Comment by INT-Obi** [comment]
Hi Gregor,

when I save the file first and then open it manually, it will open totally normal without the popup.
I use Microsoft Office O365, if this is somehow related to the problem.

Thank you for your help.
Mathias

**Comment by gregorwolf** [comment]
Hi Mathias,
currently I would think that this is an issue of SAP GUI with the Office 365 integration. Perhaps there is a standard transaction which uses the embedded display of Excel where you can reproduce the problem and then raise an issue directly at SAP.
Best regards
Gregor

**Comment by ivanfemia** [comment]
Can you send a version of the file before and after the saving?

Thank you
Ivan

**Comment by ivanfemia** [comment]
Closing
