### ISSUE TITLE
[abap2xlsx] New implementation for ZEXCEL_CONDITIONAL_ICONSET

### ISSUE THREAD

**Issue by VLEBOURG** [abap2xlsx/abap2xlsx#496]
Hello,

I use ZEXCEL_CONDITIONAL_ICONSET but some functionnalities are not implemented.

I implement in my version the reverse order (to inverse the order of icons ; 
Red/Orange/Green instead of Green/Orange/Red ) and I implement the option GreatherThanEqual
to define if value must be Greater or GreaterThanEqual.

I add attributs on ZEXCEL_CONDITIONAL_ICONSET. 
I modify method CONSTRUCTOR of ZCL_EXCEL_STYLE_CONDITIONAL to initialize this attributs
and method CREATE_XL_SHEET of ZCL_EXCEL_WRITER_2007 to affect new tag "reverse" and "gte"

I also add a constant in ZCL_EXCEL_STYLE_NUMBER_FORMAT : C_FORMAT_KCURRENCY with value '#,##0.0,'.
It is to use the number in Number format K currency.

How can I give you my implementation ?
It is my first issue and I don't know how can I contribute...
 
Thanks for your answer !

Virginie

**Comment by ivanfemia** [comment]
Hi,

Install abapGit in your system and then

Just fork the project into your git repository
Create the change
Submit a new pull request to the main repository

Ivan

**Comment by sandraros** [comment]
I know it's 4 years old now. Is there any chance that you can provide your fix?
Otherwise, I propose to close the issue.
Thanks.

**Comment by AndreaBorgia-Abo** [comment]
@VLEBOURG as proposed earlier, we're closing this issue. If you ever see this message, feel free to reopen.
