### ISSUE TITLE
Popup displayed, when Excel opened inplace

### ISSUE THREAD

**Issue by INT-Obi** [abap2xlsx/abap2xlsx#500]
Hello Team,

sorry for not replying to the other thread, I was on vacation for the last two weeks.
Now that the original thread is closed, I opened this one. Perhaps you can merge them?
Original thread: https://github.com/sapmentors/abap2xlsx/issues/491

Meanwhile I found an SAP-Standard program, that displays an Excel inplace. It is SAPRDEMO_TABLES_IN_EXCEL and when I execute it, it will not display a popup like your demo-program does.

I will of course provide the files, but I don't know how to get the file before saving. Can you help me here?

Kind regards,
Mathias

**Comment by sandraros** [comment]
Here is the code get the XLSX file as a string of bytes (the variable "xstring" will contain thousands of bytes), and which can be used to display the Excel file inplace (code not provided here):
```
REPORT.
DATA(lo_excel) = NEW zcl_excel( ).
DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
SELECT * FROM t005t INTO TABLE @DATA(countries).
lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = 'Hello world' ).
DATA(lo_writer) = CAST zif_excel_writer( NEW zcl_excel_writer_2007( ) ).
DATA(xstring) = lo_writer->write_file( lo_excel ).
```

If it answers your question, could you please close the issue? Thank you.

**Comment by sandraros** [comment]
I propose to close this issue. If you still have the same issue or have one more question, you may reopen this issue.
