### ISSUE TITLE
XLXS Created without ability to subtotal

### ISSUE THREAD

**Issue by RandyK99** [abap2xlsx/abap2xlsx#501]
Has anyone experienced a problem with the Subtotal button deactivated (grey - not selectable) from sheets generated from this class when opened in Excel?  Tinkering with layout settings doesn't help, and I'm at a loss where the setting might be (or might be missed).

Thanks,

**Comment by bastilimbach** [comment]
You can't add subtotals on excel tables. [Reference](https://support.office.com/en-us/article/Why-can-t-I-add-subtotals-in-an-Excel-table-6e8c9abd-35ca-43b4-b282-029f9710ed3c)
