### ISSUE TITLE
Percentage field in Excel

### ISSUE THREAD

**Issue by ckrueckel** [abap2xlsx/abap2xlsx#502]
Hello,

i need to print a number as a percent value in one field in excel.

Example: 
50%
98%

Can you tell me, how can i do this ? I don't need a string field, i need a number with the % sign.

best regards

Christine

**Comment by ivanfemia** [comment]
​Hi please apply one of the formatters to achieve the result.

Ivan​

**Comment by ckrueckel** [comment]
Hello Ivan, 

i have used this coding (like your example program ZDEMO_EXCEL30)

lo_worksheet->set_cell( ip_column = 'D' ip_row = 2 ip_value = '0%'
                                       ip_abap_type = lc_typekind_num ).

But the result in Excel is not a number, it is a string and i can't sum the values. 

best regards 

Christine

**Comment by ivanfemia** [comment]
Hello 

check ZDEMO_EXCEL2 and how to use ZCL_EXCEL_STYLE class and in particular ZCL_EXCEL_STYLE_NUMBER_FORMAT.

Ivan

**Comment by ckrueckel** [comment]
Ok, Thank your for your response. Im on hollyday and     i will try it,  when I'm back
Am 05.10.17, 18:35, Christine Krueckel <c.krueckel@web.de> schrieb:
Ok, Thank your for your response. Im on hollyday and     i will Hey ihr,  Im back

**Comment by sandraros** [comment]
Could you close the issue if it's solved? Thank you.

**Comment by sandraros** [comment]
No answer. Closing.
