### ISSUE TITLE
Excel removes formula, claims unreadable content

### ISSUE THREAD

**Issue by cabajero** [abap2xlsx/abap2xlsx#506]
Dear community,
I have encountered the following problem. I'm trying to save an excel file with this formula in one of the cells:

> =VLOOKUP(M13;$O$4:$P$8;2;FALSE)

Upon opening excel claims it has encountered unreadable content and removes this formula. When I paste this formula into the file manually it works correctly. 
Other formulas like for example 

> =I13*(1-K13) 

work just fine.
Do you have any advice or previous experience?

I'll appreciate any suggestion.
Regards,
Grzegorz

**Comment by ivanfemia** [comment]
Make sure you are using us notation is the standard in ooxml.
Try to substitute “;” with “,”

Ivan

**Comment by cabajero** [comment]
Thanks Ivan, I just noticed that looking through generated XML files. It works perfectly now.

Grzegorz
