### ISSUE TITLE
Need to download an excel with multiple sheets from SAP Webdynpro view methods...

### ISSUE THREAD

**Issue by laxmi546** [abap2xlsx/abap2xlsx#509]
I need to download an excel with multiple sheets from SAP Webdynpro view methods... I tried OLE but its not supported in UI(Only supported in SAPGUI). Is there any possibility of downloading data of 10+ internal tables into different sheets of an excel using GIT ??

**Comment by gregorwolf** [comment]
Hello,
abap2xlsx is just hosted on GitHub, it doesn't have anything to do with Git. Please check out https://wiki.scn.sap.com/wiki/display/WDABAP/Upload+and+Download+files+in+Webdynpro+ABAP to get an idea how to download a file using WebDynpro.
Best regards
Gregor
