### ISSUE TITLE
Export internal table without header

### ISSUE THREAD

**Issue by spacy0212** [abap2xlsx/abap2xlsx#515]
Dear experts,
I dont known how to export internal table without header.
I have read this issue https://github.com/sapmentors/abap2xlsx/issues/209
But i dont known what is DD structures and how to use this
Can you give me example to resolve.
Thank you.

**Comment by sandraros** [comment]
You may use the method `SET_TABLE` with the parameter `IP_NO_HEADER`. Be careful, the type of the internal table (or at least its structure) must be declared in the ABAP Dictionary (DDIC).

Demo program:
```abap
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'issue_530.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  SELECT * FROM t005t INTO TABLE @DATA(countries).
  lo_worksheet->set_table(
    ip_table           = countries " CAUTION : its type must be defined in the DDIC !!
    ip_table_title     = 'Countries'
    ip_top_left_column = 'A'
    ip_top_left_row    = 1
    ip_no_header        = abap_true ).
  lcl_output=>output( lo_excel ).
```
Result:
![image](https://user-images.githubusercontent.com/34005250/141371621-13e81835-69b3-4db5-a4b5-b16661f3e062.png)

If it answers your question, please close the issue.

**Comment by sandraros** [comment]
I close the issue. If you still have the same issue or one more question, you may reopen it.
