### ISSUE TITLE
Shortdump when installing with latest abapGit 1.55.0

### ISSUE THREAD

**Issue by christianguenter2** [abap2xlsx/abap2xlsx#517]
Due to some changes within abapGit there's a shortdump while installing.
https://github.com/larshp/abapGit/issues/1176

**Comment by larshp** [comment]
@ivanfemia

**Comment by larshp** [comment]
@christianguenter2 guess this one can be closed?

**Comment by christianguenter2** [comment]
@larshp yes. Thanks for notifying
