### ISSUE TITLE
Unable to export CSV file with CRLF eol due to ZCL_EXCEL_WRITER_CSV error

### ISSUE THREAD

**Issue by Cril2000** [abap2xlsx/abap2xlsx#519]
ZCL_EXCEL_WRITER_CSV has incorrect declaration of:

class-data EOL type CHAR01 value CL_ABAP_CHAR_UTILITIES=>CR_LF ##NO_TEXT.

CR_LF is 2 characters long.
Fix in PR #516

**Comment by sandraros** [comment]
I think we can close the issue as the requested fix was done.
