### ISSUE TITLE
get excel cell value from formula 

### ISSUE THREAD

**Issue by cengZiya** [abap2xlsx/abap2xlsx#520]
Hi Friends, i have a question.  I try to read cell value in abap2xlsx class. I read get_cell method from ip_value but not working ip_formula.  Could you help me ? How can i read cell value from formula
![du2ya7pw4aaz0tp](https://user-images.githubusercontent.com/36406371/36094961-47251dda-1001-11e8-8535-c45257b351a0.jpg)

**Comment by cengZiya** [comment]
Hi, this subject important and i need to do it immediately. For example row 4 and column A that cell value is 5. And i get  go_worksheet->get_cell( Exporting ip_row = 4 ip_column = 'A' importing ep_value = lv_value ).  So lv_value = 5. It's working. But row 4 and column A and cell formula = Sum (A1+B1).
i try to get cell value  go_worksheet->get_cell( Exporting ip_row = 4 ip_column = 'A' importing ep_value = lv_value ). ıt's not wirking i dont get value because value is empty end formula field is filled. Could you help me please ? @gregorwolf  @ivanfemia

**Comment by Cril2000** [comment]
Hi, 
get_cell method has ep_value and ep_formula export parameters. 
Use ep_value for cells with value and ep_formula for cells with formula.

**Comment by StefanSchmoecker** [comment]
ABAP2XLSX helps you to create excelsheets or read data from them.  But is in no way a substitute for EXCEL itself including all of it's functionality concerning calculation of formulae.   If you set a formula into a cell EXCEL will calculate the value of the cell upon opening the document.

**Comment by cengZiya** [comment]
Hi Crill, ep_formula return formula like Sum (A1+B1). But i need calculated data and get value.

**Comment by cengZiya** [comment]
Thanks Stefan . You say there is no way what i want ):

**Comment by gregorwolf** [comment]
Not in abap2xlsx. You have to do the calculation in pure ABAP if you need the result there.

**Comment by StefanSchmoecker** [comment]
Frankly, yes!

**Comment by bilencekic** [comment]
:D anyone want to implement this functionality need to rewrite excel functions library in abap i think.

**Comment by ivanfemia** [comment]
Does it really make sense?

**Comment by fidley** [comment]
This would be really a mess. Knowing Excel and the recursive calls between
formulas in cells, sheets and thousands of possibilities to link them
together, it would end with performance problems. It could work only
correctly for simple scenarios and simple formulas.
Rewriting all formulas from excel to abap.... well good luck, it would be
almost like using scan abap and then using tokens in the logic.

2018-03-29 14:14 GMT+02:00 Ivan <notifications@github.com>:

> Does it really make sense?
>

**Comment by larshp** [comment]
but it would be a fun challenge? 😵

**Comment by fidley** [comment]
yeah, definitely :)

2018-03-29 14:48 GMT+02:00 Lars Hvam <notifications@github.com>:

**Comment by cengZiya** [comment]
I uploaded my excell template with macro to smw0. Macro using specal paste and i catch value from formula. I solved my problem like this

**Comment by ivanfemia** [comment]
@fidley Without considering the number of formulas excel has and some of those are really complicated...
SUM.PRODUCT, PMT, VAR.S

**Comment by bilencekic** [comment]
Actually i would write a simple macro to copy contents of each sheet as value into a new sheet name VALUE_<sheetname> on before_Save event. In that case we can reach values easily and will be less effort.
as @fidley  mentioned complicated formulas will lead suicide of developer.

**Comment by sandraros** [comment]
I guess nobody wants to implement such a crazy feature. Could we close the question?
NB: somewhat related to #575.

**Comment by sandraros** [comment]
No answer. Closing.
