### ISSUE TITLE
Erro Fatal error. Include ZCLE_EXCEL_WORKSHEET =============CCAU should have been created previously

### ISSUE THREAD

**Issue by MLDOliveira** [abap2xlsx/abap2xlsx#522]
When I'm importing the repository this error below happen

Fatal error. Include ZCL_EXCEL_WORKSHEET =============CCAU should have been created previously

**Comment by MLDOliveira** [comment]
@ivanfemia I don't know what's rappening, could you help me?

**Comment by larshp** [comment]
see https://github.com/ivanfemia/abap2xlsx/issues/517

PR https://github.com/ivanfemia/abap2xlsx/pull/518 must be merged

**Comment by MLDOliveira** [comment]
Instead of download the maing repository I download the release and worked fine!
