### ISSUE TITLE
Hide Row and Update abap2xlsx Version

### ISSUE THREAD

**Issue by bilencekic** [abap2xlsx/abap2xlsx#526]
Hi everyone,
I know my release is a bit old but below code is not working for row hide option. Column is working very fine but row is not working. I checked sources code here and below method not existing anymore :)
 LR_SHEET->GET_ROW_DIMENSION( IP_ROW = 6 )->SET_VISIBLE( IP_VISIBLE = ABAP_FALSE ).

I want to update but there are many programs using the excel export and i afraid they might give syntax error. Anyway i can take care them, Is there an easy way to update ? abapgit can update as well ?

**Comment by ivanfemia** [comment]
Hi,

abap2xlsx is backward compatible, I don’t recall any big change except for the column / row dimension.
Abapgit can manage the update of the framework and it is highly recommended.

Ivan

**Comment by bilencekic** [comment]
thanks man! 
this class is lifesaver :D
