### ISSUE TITLE
Performance problem after updating the version

### ISSUE THREAD

**Issue by bilencekic** [abap2xlsx/abap2xlsx#527]
Hi Everyone,
I updated abap2xlsx version via abapgit but now i have a huge performance issue. Nothing changed, i am still using BIND_TABLE method with 16K rows and 60 columns. 
Last time it was taking 20-35 seconds with huge file writer but now it is nearly 150 seconds.
I tried SET_TABLE and same issue.
Any advice ?

**Comment by ivanfemia** [comment]
Can you try to do a trace with se30 to identify the bottleneck?

**Comment by bilencekic** [comment]
![xlsx](https://user-images.githubusercontent.com/17006134/37523248-52f7454c-2961-11e8-9027-fbd7eddbe4ce.png)
above is the SAT results, somehow GET_ROW method is taking %91 of total time.
above result is for 10K rows, bind_table is finishing in 23seconds for 16K rows, but excel writer takes so much time. i already have saplink of previois version, worst case i will go back to old version. I am thinking if there is any parameters that i need to set to make it faster.

**Comment by ivanfemia** [comment]
Thanks,
I remember a similar issue in the past, I trying to recall what was the final outcome.

**Comment by bilencekic** [comment]
thank you :D please try to remember  i need to transport requests to test system very soon. now i noticed system is using object_collection_iteration method after version update do get next row. inside iteration method it is using standard table maybe this can cause performance issue i didin't get strange issue. 
will it work if i just replace excel writer methods from the old one but keep other classes up to date ?

**Comment by bilencekic** [comment]
ok i think i found the issue;
first of all that iterator doesn't look necessary, we can store in a global hash table. Each time itearator is instantiated table keep moving from one variable to another variable. 
![iterator](https://user-images.githubusercontent.com/17006134/37550638-b506e6ce-29cb-11e8-8b2b-814c7532438e.png)

and second thing is, program keep doing same search in each line. lets say there is row already in index 10, now it is searching if there is value in index 11, everytime it starts from the beggining. 
So in row number 2000, it works 2000 times to check if there is any value. But if there was a global variable like last_value_cell, it can start directly from 2000 to check.
![row](https://user-images.githubusercontent.com/17006134/37550645-cf7543e8-29cb-11e8-8816-0e258c91d0a7.png)

alright here is the test results;
same number of rows used with the updated log**ic, now it is less then 2 sec** @ivanfemia 

![image](https://user-images.githubusercontent.com/17006134/37551033-0d945dba-29d3-11e8-84ce-d7241b0a4f65.png)
here is what i did to GET_ROW method; i changed ADD_ROW method in ROWS class to my hash table rather than iterator and object collection and reading same table in the GET_ROW.

```
METHOD GET_ROW.

  DATA: LO_ROW_ITERATOR TYPE REF TO CL_OBJECT_COLLECTION_ITERATOR,
        LO_ROW          TYPE REF TO ZCL_EXCEL_ROW.


  IF SY-uname = 'BILEN'.
    READ TABLE ROWS->DT_ROWS ASSIGNING FIELD-SYMBOL(<ls_row>) WITH TABLE KEY ROW_INDEX = IP_ROW.
    IF sy-subrc = 0.
    eo_row = <ls_Row>-ROW.

    ENDIF.
  ELSE.
    LO_ROW_ITERATOR = ME->GET_ROWS_ITERATOR( ).
    WHILE LO_ROW_ITERATOR->HAS_NEXT( ) = ABAP_TRUE.
      LO_ROW ?= LO_ROW_ITERATOR->GET_NEXT( ).
      IF LO_ROW->GET_ROW_INDEX( ) = IP_ROW.
        EO_ROW = LO_ROW.
        EXIT.
      ENDIF.
    ENDWHILE.

  ENDIF.
**  READ TABLE LO_ROW_ITERATOR-> into eo_row INDEX IP_ROW.
  IF EO_ROW IS NOT BOUND.
    EO_ROW = ME->ADD_NEW_ROW( IP_ROW ).
  ENDIF.

ENDMETHOD.
```

edit : somehow column autosize also not working anymore after update :/

**Comment by MLDOliveira** [comment]
Hi @bilencekic I'm haveing the same problemm, all you did was change the method GET_ROW with that code?

**Comment by ivanfemia** [comment]
@bilencekic / @MLDOliveira If you can provide a fix to the project it would be really great!

**Comment by MLDOliveira** [comment]
@bilencekic Could you commit your correction to the projetc?

**Comment by bilencekic** [comment]
@ivanfemia @MLDOliveira alright i will commit. I changed 2 classes in total, i will commit asap.

**Comment by bilencekic** [comment]
@MLDOliveira  have you tested after latest changes ? How is the performance ?

**Comment by sandraros** [comment]
Could we close this issue? Thanks.
