### ISSUE TITLE
Performance issue using zcl_excel_writer_2007

### ISSUE THREAD

**Issue by MLDOliveira** [abap2xlsx/abap2xlsx#528]
Hi.

I'm starting to use ABAP2XLSX and my first was great, but I'm trying to generate a new XLSX file with 300.000,00 lines and the process is going really slow.

I'm using the code from ZDEMO_EXCEL_OUTPUTOPT_INCL.

This is a summary that I'm using in my code.

CREATE OBJECT go_excel.
gs_table_settings-table_style       = zcl_excel_table=>builtinstyle_medium2.
gs_table_settings-show_row_stripes  = abap_true.
gs_table_settings-nofilters         = abap_true.

"After fisrt declarations I fill the internal table  and use bind method
go_worksheet = go_excel->get_active_worksheet( ).
go_worksheet->set_title( "TABLE1" ).
go_worksheet->bind_table( ip_table          = it_001_saida10_exc
                                           is_table_settings = gs_table_settings ).

"After that I basically use the code below. 
lcl_output=>output( go_excel ).

"I'm doing a test right now using the ZCL_EXCEL_WRITER_HUGE_FILE class with the code below instead of code above

lcl_output=>output( cl_excel            = go_excel
                      iv_writerclass_name = 'ZCL_EXCEL_WRITER_HUGE_FILE' ).

My question is, there is a better way to work with huge files? What is the right way to export big files with many tabs?

@ivanfemia @larshp  could you help me?

**Comment by ivanfemia** [comment]
Hi,

big files can have performances issue, I usually consider a batch process
for those.
Btw the class ZCL_EXCEL_WRITER_HUGE_FILE is the one
​ ​
that I
​
use
​ ​
at the moment
​ ​
in case of big files.

If anyone has a better idea to improve this process, I'm available to
discuss.

Ivan

**Comment by MLDOliveira** [comment]
@ivanfemia do you have an example of using the class ZCL_EXCEL_WRITER_HUGE_FILE?
I'm trying to use it but I'm not moving forward

**Comment by ivanfemia** [comment]
Just use that class instead of the classical writer.
It has some limitation on the features available

**Comment by MLDOliveira** [comment]
@ivanfemia the problem is when I use the code below

**Comment by MLDOliveira** [comment]
@ivanfemia the problem is when I use the code below I get a erro message saing that "the method CREATE_XL_SHEET is protected"

CREATE OBJECT cl_writer_huge TYPE zcl_excel_writer_huge_file.
cl_output->xdata = cl_writer_huge->create_xl_sheet( cl_excel ).

**Comment by ivanfemia** [comment]
Huge file writer doesn’t support multi sheets; there are some limitations for using that.

**Comment by Pacojka** [comment]
Hallo Ivan,

i am facing the same problem. 
The main performance issue comes from the getter methods (e.g. ZCL_EXCEL_WORKSHEET->GET_ROW) searching for the right object using an object collection (while/has_next, get_next, if statement).

One quick approach would be to use the object collection and a Hash Table simultaneously. If an object is added to the collection, we add it to the hash table (e.g. key row_id and a reference to the row object). If we need to iterate over all rows, we can still use the object collection. But if we know which object we need, we get it from the hash table with a simple read.

In MLDOliveira´s case, this saves up to 299.999 iterations while calling ZCL_EXCEL_WORKSHEET ->get_row( 300000 ) once. The performance gain while working with big tables should be huge.

I try to find some time to contribute in this great project.

Patrick

**Comment by ivanfemia** [comment]
Hi there was a previous commit that solved that issue, but it was reverted for a syntax error. You can start from that commitment, it would be really great!

Ivan

**Comment by larshp** [comment]
Guess the PR is https://github.com/ivanfemia/abap2xlsx/pull/532

**Comment by ivanfemia** [comment]
Correct...
I was on my iPhone and couldn't check.

Thank Lars

**Comment by larshp** [comment]
guess this issue can be closed?

**Comment by MLDOliveira** [comment]
I didn't test after the merge on July, but I read the comments and apparenty the problem was solved.

**Comment by sandraros** [comment]
Let's close the issue then.
