### ISSUE TITLE
Incomplete Excel file when downloading from IE browser from a SAPUI5 app as frontend

### ISSUE THREAD

**Issue by famaus** [abap2xlsx/abap2xlsx#533]
Hi,

We have a SAPUI5 frontend in which we are using sap.ui.unified.FileUploader control to prompt the user to download Excel file. If the user uses Chrome then the generated Excel file is good but when using Internet Explorer we only get a partial content file. We checked with IT & Basis team and they said that Internet Explorer doesn't like the certificate sent by ABAP2XLSX add-on whereas Chrome doesn't mind this problem.

We have several users who use Internet Explorer and this could become a problem for prod release. Would you know how this can be fixed?

Thanks!

**Comment by gregorwolf** [comment]
I don't understand how sap.ui.unified.FileUploader is used to download the file. Also according to the samples at https://ui5.sap.com/#/entity/sap.ui.unified.FileUploader it is only used for uploading files. Do you have an issue with the upload or download? What certificates does the IT & Basis team talk about? Do you have certificate issues also when accessing the UI5 Applicaiton?

**Comment by famaus** [comment]
My apologies, we have download & upload functionality and for upload, we are using sap.ui.unified.FileUploader. Our problem is with Download scenario only so sap.ui.unified.FileUploader is not relevant. For Download, I don't think there is any particular UI5 object.

I have asked the IT team to provide more details on this certificate as well since I didn't understand why there would be certificate issue for Excel file download in the first place. I thought Excel file is just like a cabinet with a bunch of XML files underneath.

And, NO we do not have any certificate issues when accessing UI5 application. It's only when we download the Excel file from IE, only partial content is populated in Excel file which seems very strange.

**Comment by gregorwolf** [comment]
Please use the Browser developer tools in Chrome and IE to find out if the headers sent from the server are equal. As .xlsx files are binary it's important that the filesize is sent correctly. Please check out https://github.com/sapmentors/SAPCRMa2xExport/blob/master/zcl_chtmlb_tab_excel_export.clas.abap#L546 which is also using abap2xlsx to create an Excel File (in the context of SAP CRM Web UI). Compare the backend coding with that. Or do you have an OData Media resource?

**Comment by famaus** [comment]
We have OData Media resource.

**Comment by bilencekic** [comment]
I am also using ui5 app for both download and upload without any issue. 
During download i think it is releated how you sending content to ie .

**Comment by sandraros** [comment]
I don't think the issue was related to abap2xlsx in any way. Could we close the issue? Thanks.

**Comment by famaus** [comment]
Yes, this was on the UI code. Please close this.
