### ISSUE TITLE
Date format not working in Excel

### ISSUE THREAD

**Issue by rondrury** [abap2xlsx/abap2xlsx#535]
When I look at my spreadsheet after the download I notice the dates were being display in the internal format.
[Excel Date before.pdf](https://github.com/ivanfemia/abap2xlsx/files/1974593/Excel.Date.before.pdf)
 I simply delete the 8 in the cell content box and hit enter and the value is displayed correctly
[Excel date after.pdf](https://github.com/ivanfemia/abap2xlsx/files/1974598/Excel.date.after.pdf)

I turned on the 1904 setting and this did nothing. Is it another Excel setting or is it a code issue?

Thanks in advance,
Ron

**Comment by gregorwolf** [comment]
Does this issue also occur with demo report ZDEMO_EXCEL1?

**Comment by rondrury** [comment]
ZDEMO_EXCEL1 looks good. I will create a small program for testing in your system.

**Comment by gregorwolf** [comment]
Then check what you do differently.

**Comment by rondrury** [comment]
Hi Gregorwolf,
What I am trying to do is the following:
Create the worksheet where column 1 is locked and 2 is unlocked.

Here is the sample code.
[ZRD_EXCEL_DATE_TST.txt](https://github.com/ivanfemia/abap2xlsx/files/1980199/ZRD_EXCEL_DATE_TST.txt)
Thanks again!
Ron

**Comment by gregorwolf** [comment]
Hi Ron,
can you please provide an example that doesn't use data types from Business Suite (viaufkst). I only have the NetWeaver Developer edition for testing.
Best regards
Gregor

**Comment by StefanSchmoecker** [comment]
Hi Ron,
just adjust the large DO-Loop at the end to this simpler Version: 
```  
  lv_column = 2.                                 " Want unlock to start at column 2
  DO lv_highest_row TIMES.
      lo_worksheet->change_cell_style( ip_row               = sy-index
                                       ip_column            = lv_column
                                       ip_protection_locked = '0' ).
  ENDDO.

```

**Comment by rondrury** [comment]
Thanks Stefan! That works great. I should have dug around a bit to find this method. I'll keep that in mind next time.
