### ISSUE TITLE
Collapse outlined columns

### ISSUE THREAD

**Issue by JoseMunozHerrera** [abap2xlsx/abap2xlsx#539]
Hi,

Checking the program ZDEMO_EXCEL12 I can see that you can collapse outlined rows but you cannot collapse outlined columns. Am I right?

To collapse the row exist the following:

  lo_worksheet->set_row_outline( iv_row_from = 10
                                 iv_row_to   = 16
                                 iv_collapsed = abap_true ).  " collapsed

But anything for columns.

Thanks & Regards

**Comment by StefanSchmoecker** [comment]
ZDEMO_EXCEL12 has code to collapse columns as well - just check the demo output and/or the coding.

**Comment by JoseMunozHerrera** [comment]
Hi,

I checked and there is nothing to collapse columns, only rows

Could you show me where a column is collapsed?

Regards

**Comment by StefanSchmoecker** [comment]
The following code is found in the sourcecode of ZDEMO_EXCEL12
```ABAP
DATA: ...
      column_dimension TYPE REF TO zcl_excel_worksheet_columndime,
      ...

  column_dimension = lo_worksheet->get_column_dimension( ip_column = 'F' ).
  column_dimension->set_outline_level( ip_outline_level = 0 ).
  column_dimension = lo_worksheet->get_column_dimension( ip_column = 'G' ).
  column_dimension->set_outline_level( ip_outline_level = 1 ).
  column_dimension = lo_worksheet->get_column_dimension( ip_column = 'H' ).
  column_dimension->set_outline_level( ip_outline_level = 2 ).
```

**Comment by JoseMunozHerrera** [comment]
Thanks for the code although this is only outline on columns, I want to **collapse** the outline

if you execute the program the collumn outlines are **not collapsed**

**Comment by StefanSchmoecker** [comment]
Add the following lines as well
```ABAP
  column_dimension = lo_worksheet->get_column_dimension( ip_column = 'G' ).
  column_dimension->set_visible( abap_false ).
  column_dimension = lo_worksheet->get_column_dimension( ip_column = 'H' ).
  column_dimension->set_visible( abap_false ).
```

**Comment by JoseMunozHerrera** [comment]
I see, thanks for the recomendation but method get_column_dimension does not exist.

However, if you refer to hide a column, is not the same as collapse the outline, that means to press the button +/- in the header of the excel.

Do you know what I mean?

**Comment by Suncatcher** [comment]
> I see, thanks for the recomendation but method get_column_dimension does not exist.

It exists. Check the ZDEMO_EXCEL12 thoroughly. It exists and this approach works.

**Comment by JoseMunozHerrera** [comment]
Ok, there was a commit in 2017 changing some things, I'm in a newer version, same as git source.

That fix deletes the class **zcl_excel_worksheet_rowdimensi** the class that contains the method get_row_dimension and uses a new one, **zcl_excel_column**

I included the set_collapsed in the program ZDEMO_EXCEL12 as in the following code:

```
  lo_column = lo_worksheet->get_column( ip_column = 'F' ).
  lo_column->set_outline_level( ip_outline_level = 0 ).
  lo_column->set_collapsed( ip_collapsed = abap_true ).
  lo_column = lo_worksheet->get_column( ip_column = 'G' ).
  lo_column->set_outline_level( ip_outline_level = 1 ).
  lo_column->set_collapsed( ip_collapsed = abap_true ).
  lo_column = lo_worksheet->get_column( ip_column = 'H' ).
  lo_column->set_outline_level( ip_outline_level = 2 ).
  lo_column->set_collapsed( ip_collapsed = abap_true ).
```

And still does not collapse the outlines.

I don't know if the following comment is related to the issue:

[https://github.com/ivanfemia/abap2xlsx/blob/f2390f63751c4bd3ab50b102e0d8475b2521bc42/src/zdemo_excel12.prog.abap#L66](url)

Regards

**Comment by Suncatcher** [comment]
> I don't know if the following comment is related to the issue:

Exactly! This comment says that this coding is deprecated/not implemented and should not be used.
I don't see method `set_collapsed` anywhere in this demo, do you?
It exists in `ZCL_EXCEL_WORKSHEET_COLUMNDIME` but seems to be left only for downward compatibility.

**Comment by JoseMunozHerrera** [comment]
No it's not in the demo program ZDEMO_EXCEL12, I did a local modification to the program ZDEMO_EXCEL12 in my system to test it. 

But method `set_collapsed` exists in the class `zcl_excel_column` .

So in my opinion it should work, don't you think?

**Comment by Suncatcher** [comment]
> I did a local modification to the program ZDEMO_EXCEL12 in my system to test it.

so you'd better stick to working samples, than do local modifications.

**Comment by StefanSchmoecker** [comment]
Collapsing hides columns.  Try to hide the columns that you want to be collapsed. This had to be done before this change ( old version of demo12 ) - maybe it still has to be done in the new version.....

**Comment by JoseMunozHerrera** [comment]
@StefanSchmoecker you are right, you have to hide columns and then it appears as collapsed.

Tested in new version of demo12.

**Comment by sandraros** [comment]
Could we close the issue? Thank you.
