### ISSUE TITLE
Range style

### ISSUE THREAD

**Issue by Suncatcher** [abap2xlsx/abap2xlsx#541]
Can we apply the style to every cell of the range at once? Or should I use cumbersome loops to fill in every of the 20000 cells?
Otherwise why one need ranges at all? What is their use?

**Comment by bohrh** [comment]
Please see new method set_area introduced today with pull request #574 "style at a merged cell #364".
An example you can find in ZDEMO_EXCEL13

**Comment by sandraros** [comment]
Proposing to close this question, it's answered. There's also the method `set_area_style`.
