### ISSUE TITLE
Methode get_column_dimension is missing in ZCL_EXCEL_WORKSHEET

### ISSUE THREAD

**Issue by rzvg** [abap2xlsx/abap2xlsx#542]
Hello,

we just installed ZABAPGIT and did an update for ABAP2XLSX.
Now the methode get_column_dimension is missing in ZCL_EXCEL_WORKSHEET.

Any suggestions?

Best regards,
Veit

**Comment by larshp** [comment]
abapGit behaviour is as expected, method get_clumn_dimension does not exist in https://github.com/ivanfemia/abap2xlsx/blob/master/src/zcl_excel_worksheet.clas.abap

the method might have been (re)moved or refactored

**Comment by StefanSchmoecker** [comment]
Which isn't really nice for downward compatibility

**Comment by ivanfemia** [comment]
Choice was made to fix an old issue with that method and align the dimension to the whole framework.
Refactoring column dimension is really fast and error free.

**Comment by sandraros** [comment]
I propose to close this issue. It's more than 3 years now and there was not much reaction about `get_column_dimension` being removed.
