### ISSUE TITLE
any method to upload an excel file from my desktop path

### ISSUE THREAD

**Issue by drake316** [abap2xlsx/abap2xlsx#543]
Hi expert, I had installed this beatifull library, and Im looking for a method to import any excel file to an internal table. 
is there one?

**Comment by gregorwolf** [comment]
Please check out the examples:

ZDEMO_EXCEL15                  abap2xlsx Demo: Reader
ZDEMO_EXCEL37                  Read xlsx-file and output = using templates
ZDEMO_EXCEL38                  Read file and output

**Comment by drake316** [comment]
ZDEMO_EXCEL37 it ask me to upload an excel file, but the result is white screen, empty screen.
do i need to use any template?
----Updated---- It Works fine!
![image](https://user-images.githubusercontent.com/1834943/41253516-96986c24-6d8e-11e8-92fd-c5299f12c37c.png)




ZDEMO_EXCEL15 this is Export, what Im searching is importing file from excel.

![image](https://user-images.githubusercontent.com/1834943/41253376-21155070-6d8e-11e8-8a4b-dab062486483.png)
this work fine, after I created all template.

**Comment by drake316** [comment]
Hi Expert. 
Now. Same file same program demo. 
On GUI For Java show this empty screen.
![image](https://user-images.githubusercontent.com/1834943/41258509-64a368f8-6d9e-11e8-8816-04ae8d9871d1.png)
Am I Doing something wrong?

with this zcl_excel_worksheet class, I'm able to bind it_table into worksheet, but how can get values into it_table from worksheet? this other quetions.
----updated----
I thing i found what iam looking for
![image](https://user-images.githubusercontent.com/1834943/41260444-75b72628-6da5-11e8-93d9-dc670321a4c9.png)

OK I found the data, but there must be bin method to transform, excel file into internal table?

**Comment by gregorwolf** [comment]
I think ZDEMO_EXCEL43 brings you the closest to what you want.

**Comment by drake316** [comment]
I dont have ZDEMO_EXCEL43 :(.  please can you share it with me!

----updated---- 
got it ^^. let me check

ok this is what I'm looking for.
![image](https://user-images.githubusercontent.com/1834943/41291862-cec25840-6e1e-11e8-8724-a6bbe046ca74.png)
but the method get_table doesn't exits. that is a miskate or bug?

![image](https://user-images.githubusercontent.com/1834943/41291903-ebf546ac-6e1e-11e8-80fe-e4c3abbf7d5d.png)


Last Updated.
I found the method inside the proyect, i dont know is not in my settings, but i've added manually and now it works perfectly. exactly what i'm looking for. thank you so much, i appreciate your time very well.

**Comment by drake316** [comment]
How can i help you guys, to contribute or donate resources to your excellent work?

**Comment by gregorwolf** [comment]
You can help by watching the project and help to solve issues. Also contributions are always welcome. Get your ABAP Developer Edition install abapGit and clone the repository. Also spread the word about abap2xlsx. And you might hire the contributors as a consultant.

**Comment by drake316** [comment]
Great Work. and I"ll be in contact for sure. !!
