### ISSUE TITLE
Autofilter does not working correctly when using a template

### ISSUE THREAD

**Issue by rotda** [abap2xlsx/abap2xlsx#547]
Hi ,

also there is an problem when you have multiple sheets . Then it not getting the right reference from localSheetId.

Workaround for me is to find the sheet via name. 

Changes for the Workaround  :
zcl_excel_reader_2007:
![abap2xlsx_bug_filter_2](https://user-images.githubusercontent.com/2928848/43314180-79abd4f2-9192-11e8-8d5b-7a56e4a71282.PNG)

**Comment by rotda** [comment]
See Pull request from me

**Comment by sandraros** [comment]
The below Excel file can be used for the tests, by displaying it via program `ZDEMO_EXCEL37`. Weird results.

[issue_547.xlsx](https://github.com/sapmentors/abap2xlsx/files/7272291/issue_547.xlsx)

Excel shows:
![image](https://user-images.githubusercontent.com/34005250/135749399-c8bbc11c-71b7-4f1d-aded-f665f472799d.png)

Program `ZDEMO_EXCEL37` shows incorrectly:
![image](https://user-images.githubusercontent.com/34005250/135749475-3b4d55b3-b5e1-41a8-8622-7abc5465f398.png)

Inside the Excel file:
- /xl/workbook.xml:
  ![image](https://user-images.githubusercontent.com/34005250/135752971-03dd55df-c0dd-4d5c-b68d-59372d1632fb.png)
  - where `localSheetId` in `<definedName>` is the order of the sheet in `<sheets>`, starting from 0
  - NB: ECMA specification says "*localSheetId (Local Name Sheet Id) = Specifies the sheet index in this workbook where data from an external reference is displayed*".
- /xl/_rels/workbook.xml.rels:
  ![image](https://user-images.githubusercontent.com/34005250/135752997-2f21397f-2dd3-4fa1-bc6b-0d603e7c8532.png)

In debug mode, variable `LT_WORKSHEETS` in method `LOAD_WORKBOOK` of `ZCL_EXCEL_READER_2007`:
- We can see
  ![image](https://user-images.githubusercontent.com/34005250/135753232-07fd6ffa-4384-4e4c-9bf5-c3daeade7937.png)
- where the `TITLE` private attribute of `ZCL_EXCEL_WORKSHEET` of each instance is as follows:
  - `{O:167*\CLASS=ZCL_EXCEL_WORKSHEET}` is "Sheet1"
  - `{O:239*\CLASS=ZCL_EXCEL_WORKSHEET}` is "second-sheet"
  - `{O:72*\CLASS=ZCL_EXCEL_WORKSHEET}` is "third-sheet"

So all that is correct:
| Tab order | Sheet name | rId | sheetId | localSheetId | ABAP object | File name in ZIP |
|-|-|-|-|-|-|-|
|1 | third-sheet | rId1 | 3 | 0 | `{O:72}` | `sheet1.xml` | 
|2 | Sheet1 | rId2 | 1 | 1 | `{O:167}` | `sheet2.xml` | 
|3 | second-sheet | rId3 | 2 | 2 | `{O:239}` | `sheet3.xml` | 

but the algorithm in method `LOAD_WORKBOOK` of `ZCL_EXCEL_READER_2007` incorrectly considers that `LT_WORKSHEETS` is ordered in the same order as in `<sheets>`. 
![image](https://user-images.githubusercontent.com/34005250/135754544-c9e4072e-bbcc-4c51-8fb3-17e83949a4fd.png)

**Comment by sandraros** [comment]
@AndreaBorgia-Abo Could you review this PR please? Thanks 👍
Note that it doesn't fix another bug which is referred as #819 (along with a fix), whose consequence is to not show the filter icon in `second-sheet`:
![image](https://user-images.githubusercontent.com/34005250/135755402-8da7b678-a0cc-44d4-8deb-cf2cf3a4c436.png)

The fix of #819 will complete this fix of #547, and we'll get the right icon: 
![image](https://user-images.githubusercontent.com/34005250/135755452-ce3ef78e-7cf8-4e15-8756-8182173b2129.png)

**Comment by AndreaBorgia-Abo** [comment]
Done... on to the last one!
