### ISSUE TITLE
Embedded images via Drawing Object

### ISSUE THREAD

**Issue by mrud0311** [abap2xlsx/abap2xlsx#552]
Hello Team/Community
is it possible to use pictures/images in Excel with binding to a cell?
If you have an image in Excel you can change the option via right mouse click on image -> size and options -> location and size dependent
I cannot see how to use this function via ABAP2XLS framework...

Thanks for response in advance

**Comment by sandraros** [comment]
Sorry for the late answer.

I think it's possible. You can see it in action in the demo program `ZDEMO_EXCEL16`. The image moves when the top rows or left columns are resized:
![image](https://user-images.githubusercontent.com/34005250/141363783-2f1a6586-164d-4d58-83b7-188cd5b54409.png)

**Comment by sandraros** [comment]
No answer. Closing.
