### ISSUE TITLE
Dump when calling Transformation zexcel_tr_sheet

### ISSUE THREAD

**Issue by Demonshooter** [abap2xlsx/abap2xlsx#553]
The Transformation zexcel_tr_sheet dumps when called from Class zcl_excel_writer_huge_file.

The problem is that this line refers to **HIGHT**: https://github.com/sapmentors/abap2xlsx/blob/68707e1469e8a39982f0a672fb8788c3be15337f/src/zexcel_tr_sheet.xslt.source.xml#L116
but the corresponding line of `zcl_excel_writer_huge_file` refers to **HEIGHT** : https://github.com/sapmentors/abap2xlsx/blob/68707e1469e8a39982f0a672fb8788c3be15337f/src/zcl_excel_writer_huge_file.clas.abap#L163

**Comment by Demonshooter** [comment]
The same is true for the Field CUSTOMHEIGHT

**Comment by sandraros** [comment]
Is it possible to add a small program to reproduce the bug?
If not abusing, is it also possible to propose a pull request?
Thank you.

**Comment by sandraros** [comment]
Also concerns `fit_to_height` (typo in the Simple Transformation: `FITTOHIGHT`).

Program to reproduce all the short dumps:
```abap
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'issue_553.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = 'row 1' ).
  lo_worksheet->set_cell( ip_column = 'A' ip_row = 2 ip_value = 'row 2' ).
  lo_worksheet->set_cell( ip_column = 'A' ip_row = 3 ip_value = 'row 3' ).
  lo_worksheet->set_row_height( ip_row = 1 ip_height_fix = 30 ).
  DATA(lo_row) = lo_worksheet->get_row( 2 ).
  lo_row->set_row_height( ip_row_height = 40 ip_custom_height = abap_true ).
  lo_row = lo_worksheet->get_row( 3 ).
  lo_row->set_row_height( ip_row_height = 50 ip_custom_height = abap_false ).
  lo_worksheet->sheet_setup->fit_to_page       = 'X'.  " you should turn this on to activate fit_to_height and fit_to_width
  lo_worksheet->sheet_setup->fit_to_height     = 0.    " used only if ip_fit_to_page = 'X'
  lo_worksheet->sheet_setup->fit_to_width      = 2.    " used only if ip_fit_to_page = 'X'
  TRY.
      lcl_output=>output( cl_excel = lo_excel iv_writerclass_name = 'ZCL_EXCEL_WRITER_HUGE_FILE' ).
    CATCH cx_root INTO DATA(lx).
      MESSAGE lx TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
```
![image](https://user-images.githubusercontent.com/34005250/145629912-b6a4f1f5-5bec-47f6-9b42-e88168a4faa3.png)
