### ISSUE TITLE
Error importing file with Power Query

### ISSUE THREAD

**Issue by MiguelMotta87** [abap2xlsx/abap2xlsx#556]
Hi,

I'm trying to import the xlsx file generated by the ABAP2XLSX class into excel using Power Query. Excel displays a message informing that the file has an invalid format. If I open the generated file, make any changes and save, the modified file is imported without errors.
I have identified that the difference between the original and the modified file that makes the file invalid is in the sheet1.xml file, but I couldn't identify the cause of the error.
Could you help me with the error?

[Sample.xlsx](https://github.com/ivanfemia/abap2xlsx/files/2341089/Sample.xlsx)
![error](https://user-images.githubusercontent.com/20225444/44928902-99311900-ad2f-11e8-9991-b5efaab473bb.png)

Regards,
Miguel Motta

**Comment by ivanfemia** [comment]
I don't knwo Power Query.
I s the excel generated opening correctly with Excel

**Comment by sandraros** [comment]
No answer. Proposing to close.
