### ISSUE TITLE
Multiple Worksheet (1000+): No content (blank) on the 1000th worksheet onwards.

### ISSUE THREAD

**Issue by avafer** [abap2xlsx/abap2xlsx#557]
Hello, Experts! I am facing this issue when generating multiple worksheets. I tried to create a .xlsx file with 1100 worksheets. There are data on sheets 1-999. But on the 1000th - 1100th tab, no data/contents displayed. Got this pop-up message when opening the file "Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
Removed Records: Worksheet properties from /xl/workbook.xml part (Workbook)".

Thanks in advance!

**Comment by AtomKrieg** [comment]
Hello, @avafer!

Here is commit solving this: #563
You also can apply this manually, since this is a very simple change.
