### ISSUE TITLE
Auto Size (Column Size Optimization) Not Working

### ISSUE THREAD

**Issue by rhulme003** [abap2xlsx/abap2xlsx#558]
Hello experts,

We have recently imported the latest version of abap2xlsx and as part of the change are required to replace  code used for auto size/column width optimization for columns (replace method get_column_dimension in class zcl_excel_worksheet_columndime with method get_column in class zcl_excel_column) to then call method set_auto_size to optimize the column width.

In our tests this does not appear to be working, nor does it appear to work in any of the ZDEMO_EXCELxx programs (i.e. ZEMO_EXCEL31).  It appears to work under the old version?  Does anyone have any insight as to what might need to be done?

**Comment by avafer** [comment]
Hello. I applied the code below in my logic:

**lo_worksheet->set_column_width( ip_column = 'A' ).**

The effect is column "A" takes the length of the cell with bigger width. I hope this helps.

**Comment by rhulme003** [comment]
The above answer still did not fix my issue.

I solved this issue by adding the following method call after the set_auto_size call (for all columns):

lo_worksheet->calculate_column_widths( ).

Still not sure what changed between the old version and the update, but this is a successful workaround.

**Comment by rmcknight001** [comment]
this should be re-opened as the demo programs all need to be fixed still.

**Comment by sandraros** [comment]
The program `ZDEMO_EXCEL31` works fine for me. Could we close the issue?

**Comment by avafer** [comment]
Yes. Thanks
