### ISSUE TITLE
ABAP Shortdump when downloading huge no of records

### ISSUE THREAD

**Issue by sdivvela2** [abap2xlsx/abap2xlsx#560]
Hi,
We are using abap2xlsx framework to download the data into excel file in Background.  Download functionality works fine if it has less no of records . In our scenario we have 8 tabs and each tab may contain more than 100,000 records.  Is there any records limit using this approach? Actually it is giving Internal memory issue if it has more records
 **Internally required memory is not available**

*Download file
    CREATE OBJECT lo_excel_writer TYPE zcl_excel_writer_2007.
    lv_file = lo_excel_writer->write_file( go_excel ).

**Comment by AtomKrieg** [comment]
Hi,
Old versions of SAP have IXML memory consuption issue. I solved same dump with SAP-note 1229110. Apply code transfomation from this note to ZCL_EXCEL_WRITER_2007->CREATE_XL_SHEET

**Comment by sdivvela2** [comment]
Hi,
Do you have the updated version of ZCL_EXCEL_WRITER_2007->CREATE_XL_SHEET code?Actually I dont have access to SAP Notes.

**Comment by gregorwolf** [comment]
Working with SAP and having no access to SAP Notes sounds to me like a no-go. Please contact your basis team to get an S-User.

**Comment by ivanfemia** [comment]
Closing the issue, solution provided

**Comment by sdivvela2** [comment]
Could you please provide  me the updated version of the code in ZCL_EXCEL_WRITER_2007->CREATE_XL_SHEET? I
