### ISSUE TITLE
current version for SAP Basis 7.0

### ISSUE THREAD

**Issue by TomLAX** [abap2xlsx/abap2xlsx#562]
Hi guys, 

how can i install your abap2xlsx on a sap basis 7.00 System? i can't use ababgit in my system (abapgit is supported after 7.02)

any suggestion?
Tom

**Comment by StefanSchmoecker** [comment]
Please use the transportfiles K902337.TIR and R902337.TIR provided on github
[https://github.com/ivanfemia/abap2xlsx/tree/master/build](url)

**Comment by TomLAX** [comment]
thank you. 

After the import i get a few syntax errors. I hope you can help: 

unknown types: 
CL_SYSTEM_UUID (ZCL_EXCEL_OBSOLETE_FUNC_WRAP==CM001) ,
ABAP_BOOL (ZCL_EXCEL_THEME===============CI)

Syntax error: ZCL_EXCEL_READER_HUGE_FILE====CCAU --> '`<sst><si><t/></si><si><t>Alpha</t></si><si><t/></si><si><t>Bravo</t></si></sst>`' could not be interpreted

ZCL_EXCEL_THEME_FMT_SCHEME====CM001 -->  lo_xml->parse_string( get_default_fmt( ) ).  --> missing arguments

**Comment by TomLAX** [comment]
**Fix the error:  lo_xml->parse_string( get_default_fmt( ) ). --> missing arguments**

REPLACE        T46K911795                                        1
*\        lo_xml->parse_string( get_default_fmt( ) ).
       _data: strte type string.
       strte = get_default_fmt( ).
       lo_xml->parse_string( strte )._

**Fix the Error: unknown type abap_bool in ZCL_EXCEL_THEME:**
class ZCL_EXCEL_THEME definition
  public
  create public .

public section.
  _type-pools: abap._

**Fix the error: CL_SYSTEM_UUID (ZCL_EXCEL_OBSOLETE_FUNC_WRAP==CM001)**
the solution is already in the coding :) you only have to comment and uncomment the coding snippet

**The Error in ZCL_EXCEL_READER_HUGE_FILE====CCAU is still open** i comment the snippet, because i don't need the method (hopefully) --> if some get a workaround please be free to share.

**Comment by gregorwolf** [comment]
Hi @TomLAX can you please get the current master and install it into a >= 702 system using abapGit, create the transport request and try to import into 700.

**Comment by gregorwolf** [comment]
Hi @TomLAX please check out https://github.com/sapmentors/abap2xlsx/blob/master/build/Transport-2019-02-20.zip which is a transport created in 7.52 containing the todays state. Please give it a try in your 7.0 system and help to fix any issues you're facing.

**Comment by sandraros** [comment]
abap2xlsx is only supported from 7.02. I think that people who want to use it before 7.02 should adapt it themselves.
No answer. Proposing to close.
