### ISSUE TITLE
Totals not generated with BIND_ALV and zcl_excel_writer_huge_file

### ISSUE THREAD

**Issue by sdivvela2** [abap2xlsx/abap2xlsx#567]
Couldn't able to display totals using BIND_ALV method. I am using CL_SALV_TABLE and populating aggregations but still it is not displaying totals. please advise

**Comment by sdivvela2** [comment]
Totals displaying when we use zcl_excel_writer_2007 but in our case we have huge data and we are using zcl_excel_writer_huge_file. In this case totals are not getting displayed. Please let me know what needs to be done.

**Comment by sdivvela2** [comment]
Do I nee write any additional logic in this scenario?

**Comment by sandraros** [comment]
Sorry for the late answer. `zcl_excel_writer_huge_file` is not able to produce an Excel file with all the features that `zcl_excel_writer_2007`.

If you provide a demo program to reproduce the problem, we may have a look at it to implement the feature. You may also help us by providing a pull request.

Thank you.

**Comment by sandraros** [comment]
No answer, proposing to close. You may still reopen the issue if needed. Thank you.
