### ISSUE TITLE
Format Cells containing Quote Character 2010 vs 2016

### ISSUE THREAD

**Issue by mtoumanis** [abap2xlsx/abap2xlsx#569]
So what I practically want to do, without any luck... is to pass a custom cell format containing a quote character like the following: **#'##0,00_ ;[Red]-#'##0,00** 

This would help me solve the following problem which gets more complicated depending on EXCEL version and language.

The aforementioned code is the one that comes out of the following excel default number format.

![image](https://user-images.githubusercontent.com/41059681/48546039-8dcda280-e8c7-11e8-991a-3afc3f85e2b1.png)

In the picture below, I have come up with some alternatives but unfortunately, nothing works properly.

Note that in the following example, there is a comparison of an EXCEL version of 2010 in DE (first image)
between an EXCEL version 2016 in EN (second image).

![image](https://user-images.githubusercontent.com/41059681/48546793-80b1b300-e8c9-11e8-822e-b01ea91351f6.png)

![image](https://user-images.githubusercontent.com/41059681/48546803-87402a80-e8c9-11e8-952a-2a3c893208f0.png)

The following image shows what I want to achieve regardless of the EXCEL version (forget about the RED/ROT part which is because of the language).

![image](https://user-images.githubusercontent.com/41059681/48546759-6d9ee300-e8c9-11e8-9443-8835c402c1f8.png)

**Comment by sandraros** [comment]
Sorry for the late answer. I don't get your exact point.

I think that the number format is language independent. The decimal point is expressed in the number format as a dot. It's only when the number is rendered that it's using the user's country format. For the thousands separator, you must use a comma in the number format. In any case, you can't force how it will be exactly rendered, it's the user who decides what must be displayed for the decimal point or for the thousands separator.

As far as I understand, this is not an abap2xlsx question, unless you give us more information.

Thank you.

**Comment by sandraros** [comment]
No answer. Closing.
