### ISSUE TITLE
Protect sheet with filter caused Excel error

### ISSUE THREAD

**Issue by sylvainliang** [abap2xlsx/abap2xlsx#572]
I tried to protect a sheet that has filter. Then display the excel but encountered this error in Excel: 
"Wir haben ein Problem bei einigen Inhalten in '<temp-filename.xlsx>' erkannt. Sollen wir so viel wei möglich wiederherstellen? Wenn Sie der Quelle dieser Arbeitsmappe vertrauen, klicken Sie auf 'Ja'."

Translate to English:
"We detected a problem with some content in '<temp-filename.xlsx>'. Should we restore as much as possible? If you trust the source of this workbook, click Yes.".

**Comment by gregorwolf** [comment]
Can use post an example based on the demo reports? I think I've also used protected sheets with filters and didn't face this issue.

**Comment by sylvainliang** [comment]
```abap
REPORT zws_test2.

CONSTANTS:
  gc_save_file_name TYPE string VALUE 'test.xlsx'.

DATA:
  lo_excel      TYPE REF TO zcl_excel,
  lo_worksheet  TYPE REF TO zcl_excel_worksheet,
  lo_column     TYPE REF TO zcl_excel_column,
  lo_autofilter TYPE REF TO zcl_excel_autofilter,
  lo_range      TYPE REF TO zcl_excel_range,

  ls_filter     TYPE zexcel_s_autofilter_area.

INCLUDE zdemo_excel_outputopt_incl.

INITIALIZATION.
  IF NOT lo_excel IS BOUND.
    lo_excel = NEW zcl_excel( ).
  ENDIF.

START-OF-SELECTION.
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_title( ip_title = 'Sheet1' ).

  lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = 'Title1' ).

  "Protect sheet
  lo_worksheet->zif_excel_sheet_protection~protected = zif_excel_sheet_protection=>c_protected.
  lo_worksheet->zif_excel_sheet_protection~password  = zcl_excel_common=>encrypt_password( 'secret' ).
  lo_worksheet->zif_excel_sheet_protection~sheet     = zif_excel_sheet_protection=>c_active.
  lo_worksheet->zif_excel_sheet_protection~objects   = zif_excel_sheet_protection=>c_active.
  lo_worksheet->zif_excel_sheet_protection~scenarios = zif_excel_sheet_protection=>c_active.

  lo_worksheet = lo_excel->add_new_worksheet( ).
  lo_worksheet->set_title( ip_title = 'Sheet2' ).

  lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = 'Header 1' ).

  lo_autofilter = lo_excel->add_new_autofilter( io_sheet = lo_worksheet ).

  ls_filter-row_start = 1.
  ls_filter-col_start = 1.
  ls_filter-row_end = lo_worksheet->get_highest_row( ).
  ls_filter-col_end = lo_worksheet->get_highest_column( ).

  "Protect sheet (comment this section out, then Excel will have no error but can't protect sheet)
  lo_worksheet->zif_excel_sheet_protection~protected = zif_excel_sheet_protection=>c_protected.
  lo_worksheet->zif_excel_sheet_protection~password  = zcl_excel_common=>encrypt_password( 'secret' ).
  lo_worksheet->zif_excel_sheet_protection~sheet     = zif_excel_sheet_protection=>c_active.
  lo_worksheet->zif_excel_sheet_protection~objects   = zif_excel_sheet_protection=>c_active.
  lo_worksheet->zif_excel_sheet_protection~scenarios = zif_excel_sheet_protection=>c_active.

  lcl_output=>output( lo_excel ).
```
If you comment out the second protect sheet, then no error with the excel but can't protect sheet.

**Comment by sylvainliang** [comment]
@gregorwolf, did you managed to have a look? Is the implementation for protecting multiple sheets correct?

**Comment by gregorwolf** [comment]
@sylvainliang I was able to replicate your issue. But can only suggest to extract the generated .xlsx file with a ZIP tool and check the XML of the second sheet. That should bring more light into this issue.

**Comment by MCH123** [comment]
I solved this on my side by modifying excel writer class. Sheet protection must be applied BEFORE autofilter.

**Comment by gregorwolf** [comment]
Can you please fork the project, apply the patch and send a pull request?

**Comment by mfallen** [comment]
Hi

Installed the actual version, now CREATE_XL_SHEET of ZCL_EXCEL_WRITER_2007 has an error:

![image](https://user-images.githubusercontent.com/6636061/51021379-aaadeb80-1581-11e9-89ef-b887bbdfc35d.png)


You need to remove the space before the *

**Comment by larshp** [comment]
syntax error fixed as part of https://github.com/ivanfemia/abap2xlsx/pull/582

**Comment by ivanfemia** [comment]
Can we close this issue?

**Comment by sylvainliang** [comment]
@ivanfemia Yes, please close this issue. Thanks!
