### ISSUE TITLE
Error install with abapgit -> PAK129

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#578]
Hi,

still trying to install the git package. Now I have error "Package ZTOOL has no use access to package interface _ABA_DEFAULT", message number PAK129.

Amy idea what happens here?

**Comment by larshp** [comment]
did you install abap2xlsx into package ZTOOL?

do you have package checks enabled in your system, and in specific how is package ZTOOL configured?

**Comment by mfallen** [comment]
ZTOOL is main package, abap2xlsx is in sub-package z_excel

**Comment by larshp** [comment]
do you have package checks enabled in your system, and in specific how is package ZTOOL configured?

**Comment by mfallen** [comment]
What should I check? First what I can see - ZTOOL has a different language than Z_EXCEL

**Comment by mfallen** [comment]
I have moved the subpackage (now it's a "main package").

Error is gone, now I get error "error creating dummy component" (OTR-Based Exception of Class: ZCX_ABAPGIT_EXCEPTION) thrown from lt_updated_files = zcl_abapgit_objects=>deserialize( ... )

**Comment by nidak2501** [comment]
Hey Guys,
Have been trying to install ABAP2XLSX into my SAP system and have been getting a dump in program ZABAPGIT_FULL I have taken from here. May be some basics I'm doing wrong.
Can you please suggest a go through guide for installing in to my SAP S'4HAN 1709 system?
Also tried ZSAPLINK program and getting OBJECT REF NOT ASSIGNED runtime error every time  i run it.
Would appreciate any help guys .
Thanks

**Comment by larshp** [comment]
@nidak2501 please dont double post and hijack issues, from your other issue https://github.com/ivanfemia/abap2xlsx/issues/579, there is nothing indicating that your problem is related to "Package ZTOOL has no use access to package interface _ABA_DEFAULT", message number PAK129." errors

**Comment by larshp** [comment]
@mfallen delete all abap2xlsx objects from your system and try installing again

note that main packages cannot contain repository objects

**Comment by mfallen** [comment]
Got it!!!
Problem now was the WebDynpro -> I can see it in the table (TADIR), but not able to display in SE80. Did some "tricks", using different functions to be able to delete - now all fine!

Only open topic for me now: The classes are still showing differences between local and remote, checking the difference it's only

<EXPOSURE>2</EXPOSURE>
or
<CLSABSTRCT>X</CLSABSTRCT>
or
<CLSFINAL>X</CLSFINAL>

missing in my local class.
Need to check whats wrong here, but seems to be fine for the moment.

Thanks all for your support!

**Comment by larshp** [comment]
in a recent abapGit version, https://github.com/larshp/abapGit/blob/master/changelog.txt#L22 the XML format of CLAS objects have changed a bit, redundant fields cleared, guess thats the diffs you see. If you post a screenshot then it can be verified.

The cleared fields can is listed in https://github.com/larshp/abapGit/pull/2195/commits

**Comment by mfallen** [comment]
Actual version (1.81.1) already installed, 

"Error" looks like that:
![image](https://user-images.githubusercontent.com/6636061/50952053-7cf87200-14af-11e9-836b-97ea376e0606.png)

**Comment by larshp** [comment]
thats not a problem, the abap2xlsx code should be updated, opened https://github.com/ivanfemia/abap2xlsx/issues/580

**Comment by larshp** [comment]
guess this issue can be closed?

**Comment by mfallen** [comment]
Sorry, yes, closed
