### ISSUE TITLE
Not able to install ABAP2XLSX into my SAP s4han 1709 system.

### ISSUE THREAD

**Issue by nidak2501** [abap2xlsx/abap2xlsx#579]
Hey Guys,
Have been trying to install ABAP2XLSX into my SAP system and have been getting a dump in program ZABAPGIT_FULL I have taken from here. May be some basics I'm doing wrong.
Can you please suggest a go through guide for installing in to my SAP S'4HAN 1709 system?
Also tried ZSAPLINK program and getting OBJECT REF NOT ASSIGNED runtime error every time i run it.
Would appreciate any help guys .
Thanks

**Comment by gregorwolf** [comment]
It wold help if you can provide some more details about the dump your getting. We don't have crystal balls here.

**Comment by nidak2501** [comment]
>           It wold help if you can provide some more details about the dump your getting. We don't have crystal balls here.

Hi Gregor,
Sorry for that,,
I am experiencing these issues in two main programs SAPLINK_INSTALLER and ABAPGIT.
SAPLINK Dumps:

![saplink1](https://user-images.githubusercontent.com/46541291/50944332-f5623180-14b5-11e9-9190-7969e875f492.PNG)

![saplink2](https://user-images.githubusercontent.com/46541291/50944349-014df380-14b6-11e9-809e-c9334bf32cac.PNG)

![saplink3](https://user-images.githubusercontent.com/46541291/50944352-090d9800-14b6-11e9-8695-c51c34085065.PNG)

ABAPGIT Dumps:

![abapgit1](https://user-images.githubusercontent.com/46541291/50944360-11fe6980-14b6-11e9-9cbf-b30bb916a3dd.PNG)

As I understand we need main installers to  add components into our systems and SAPLINK and ABAPGIT are those.

Thanks

**Comment by larshp** [comment]
I dont think there is any FORM called "INSTALLNUGGET" in abapGit, as the above dump says, something is wrong in your setup

**Comment by nidak2501** [comment]
I am unsure as well @larshp
Have only copy pasted the code.
Would appreciate any guidance

**Comment by larshp** [comment]
abapGit installation guide is at https://docs.abapgit.org/guide-install.html

looking at https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap there is no FORM called "INSTALLNUGGET"

**Comment by nidak2501** [comment]
@larshp
Does abapgit program have any pre requisite to run successfully?
Have copied program from same link.

**Comment by larshp** [comment]
ABAP application server version must be SAP Basis 702 or higher, thats it

**Comment by nidak2501** [comment]
@larshp
My system is basis 752...

**Comment by larshp** [comment]
can you post the call stack from the abapGit dump, then we can see how it gets to the FORM that does not exist?

**Comment by nidak2501** [comment]
Hi Larshp,
I copied the code from your suggested link and now program is running and displaying output to clone abap2xlsx into my system.
now I am getting SSL Handshake error,have installed certificates into strust tcode....
may have missed some , still looking into it.
How many certificates do I have to install in strust for program to work??

**Comment by gregorwolf** [comment]
Please check the installation guide for more details. It helps when you read before you ask. Also searching in the even closed issues at https://github.com/larshp/abapGit/issues helps a lot for such issues.

But please can you tell use what steps you followed to get into the issues you've described? Or maybe it was just a copy and paste error and you've copied the SAPlink installer code into the ZABAPGIT_FULL report?

**Comment by larshp** [comment]
SSL setup is documented at https://docs.abapgit.org/guide-ssl-setup.html, alternatively use the offline feature which is also described at https://docs.abapgit.org

**Comment by nidak2501** [comment]
Hi Gregor,

I have copied SAPLINK program and ABAPGIT program in my system.
it was giving me dumps as shown before.
Now as per lars suggestion I copied program from his link,
I am getting handshake protocol error, cant seem to do much in this case since I am using my clients system.
I am new to GITHUB and ABAP2XLSX so ,apologies for discrepancies.
I am going through documentations now and hoping to resolve it soon as requirement is urgent.

**Comment by larshp** [comment]
alternatively use the offline feature which is also described at https://docs.abapgit.org

**Comment by nidak2501** [comment]
Hi Lars,
I was into offline feature you suggested and it worked perfectly.
All object are installed in my system now.
All I did was follow the step in you link https://docs.abapgit.org.
imported master zip and pulled them, saved in package and voila.

Thank you @larshp so much for you help and perfect guidance in solving this issue.
Thank you @gregorwolf for your help and support.
