### ISSUE TITLE
Usage in standard report

### ISSUE THREAD

**Issue by Blazerinho** [abap2xlsx/abap2xlsx#586]
Can abap2xlsx used in standard reports or do I have to write a z-report?
8 years ago I added entry XLS in table SXCONVERT2 or SXCONVERT. A custom function module transfer abap lines into xls file separated by tab stops.
Can abap2xlsx class also used for converting attachment in SOST? See setting in SCOT.

**Comment by gregorwolf** [comment]
Hi @Blazerinho,
seems the "only" thing that needs to be implemented to support this is a Z function module that implements the same interface as i.e. SX_OBJECT_CONVERT_ALI_HTM. All needed data should provided via this interface and you "just" have to feed it to abap2xlsx and return the generated file. 

For SOST I would expect the new format maintained in SXCONVERT2 to show up in the drop down of the output formats:

<img width="478" alt="screenshot 2019-01-31 at 10 28 48" src="https://user-images.githubusercontent.com/2639535/52044736-224cb600-2543-11e9-9d6b-2f7b3d5b94d5.png">

So please go ahead and implement it. Looking forward for your pull request.

**Comment by sandraros** [comment]
Hi. Could you propose a pull request?
Otherwise, do you mind if we close the question?
Thank you.

**Comment by sandraros** [comment]
No answer. Closing.
