### ISSUE TITLE
Comment not displayed in second sheet

### ISSUE THREAD

**Issue by jonothomask** [abap2xlsx/abap2xlsx#587]
comments are not displaying in the second sheet if no comments set for the first sheet. Sample program is attached. 

[zjk_excel_comment.abap.txt](https://github.com/ivanfemia/abap2xlsx/files/2827310/zjk_excel_comment.abap.txt)

**Comment by gregorwolf** [comment]
Would be great if you could fork the project, create a patch and send a pull request.
