### ISSUE TITLE
ZCL_EXCEL_WRITER_XLSM->CREATE - obligatory parameter "IV_COMMENT_INDEX" had no value assigned to it

### ISSUE THREAD

**Issue by michaeljohnf** [abap2xlsx/abap2xlsx#588]
Under STEP 10:
    
"lv_content = me->create_xl_sheet_rels( io_worksheet = lo_worksheet
                                           iv_drawing_index = lv_drawing_index )."

is missing required parameter IV_COMMENT_INDEX

**Comment by gregorwolf** [comment]
Can you provide a reference to your "STEP 10"? Or even better clone the repository, fix the bug and send a pull request.

**Comment by Berreke** [comment]
This is related to issue Issue #180. In ZCL_EXCEL_WRITER_2017. After adding the same in ZCL_EXCEL_WRITER_XLSM. I could activate.

**Comment by gregorwolf** [comment]
Would you be so kind and fork the project, add your changes and send a pull request?

**Comment by bigld** [comment]
the issue can be closed?

**Comment by sandraros** [comment]
No answer, closing.
