### ISSUE TITLE
Documentation: moving wiki to docs folder

### ISSUE THREAD

**Issue by larshp** [abap2xlsx/abap2xlsx#589]
Will be migrating the wiki to the docs/ folder, accessible via github pages.

This allows for better control of the layout, plus version history with possibility for pull requests for the documentation

Source = https://github.com/ivanfemia/abap2xlsx/tree/master/docs

Display at http://ivanfemia.github.io/abap2xlsx/

**Comment by ivanfemia** [comment]
@larshp 
I will close this one 
For reference the new documentation is available at 
[http://sapmentors.github.io/abap2xlsx/](http://sapmentors.github.io/abap2xlsx/)
