### ISSUE TITLE
How to filter for not empty

### ISSUE THREAD

**Issue by FETPA** [abap2xlsx/abap2xlsx#600]
Hi,

I tried to generate an Excel via Abap2Xlsx and Add a Filter to it. The Filter should Filter for all Values in the Column wich aren't empty. So I set the Filter in an Example File and watched the XML. There I saw the Filter value is just '*' so i tried to add the filter just like this.

```
LO_AUTOFILTER->SET_VALUE(
 EXPORTING 
    I_COLUMN = 12
    I_VALUE = '*' 
).
```
But when I do it like this, the filter searches explicit for '*' and not for all not empty.

So what's my failure?

Thanks for your help

**Comment by gregorwolf** [comment]
I would think you must use SET_TEXT_FILTER and filter for not empty. Unfortunately there isn't yet a demo report showing that functionality. But that would be a good start for your contribution. Fork the project. Switch abapGit to your own repository, create the sample report and send a pull request. To find out what to provide to IV_LOGICAL_OPERATOR I would suggest that you create an Excel manually with the intended result and look into the generated XML.

**Comment by FETPA** [comment]
Sorry but I can't find out, how to set the Textfilter. Is there somewhere a documentation?
I tried to set the Filter just like this:

`LO_AUTOFILTER->SET_TEXT_FILTER(  EXPORTING I_COLUMN = 1 IV_TEXTFILTER1 = ' ' ).`

But no Filter got set. And is the logical operator not only for linking more than one Filterstring?

**Comment by FETPA** [comment]
I fixed the Problem in a different way, I set all filter to all values I have in this column like this.
```
  DATA: IT_VALUES TYPE ZEXCEL_T_AUTOFILTER_VALUES,
        LS_VALUE  LIKE LINE OF IT_VALUES.
  LS_VALUE-COLUMN = 3.
  LS_VALUE-VALUE = 'AFG'.
  APPEND LS_VALUE TO IT_VALUES.
  LS_VALUE-COLUMN = 3.
  LS_VALUE-VALUE = 'AUS'.
  APPEND LS_VALUE TO IT_VALUES.
  LO_AUTOFILTER->SET_VALUES( IT_VALUES = IT_VALUES ).
```
In the standard only one Filter is active in this case everything is hidden, except the Rows with AFG in the Second Column.
So I had to make a small change in this method:
>ZCL_EXCEL_WRITER_2007->CREATE_XL_SHEET_SHEET_DATA

 I replaced the if with an if and a loop where clause of line 5992:
```
 LOOP AT io_worksheet->sheet_content INTO ls_sheet_content.
    IF lt_values IS INITIAL. " no values attached to autofilter  " issue #368 autofilter filtering too much
      CLEAR l_autofilter_hidden.
    ELSE.
      READ TABLE lt_values INTO ls_values WITH KEY column = ls_last_row-cell_column.
*{   REPLACE        T11K9A2EPA                                        1
*\      IF sy-subrc = 0 AND ls_values-value = ls_last_row-cell_value.
*\        CLEAR l_autofilter_hidden.
*\      ENDIF.
     IF sy-subrc = 0.
      loop at LT_VALUES into ls_values where VALUE = ls_last_row-cell_value and column = ls_last_row-cell_column.
        CLEAR l_autofilter_hidden.
      endloop.
    ENDIF.
*}   REPLACE
    ENDIF.
```

Shall I make a pull request for this? Do you think is this solution also interesting for others?
