### ISSUE TITLE
Delete style conditions of the worksheet

### ISSUE THREAD

**Issue by FETPA** [abap2xlsx/abap2xlsx#602]
Hi everybody, 
is it possible to delete all style conditions of a worksheet?
The Problem is, i load a Excel file wich has a lot of style conditions in the worksheet I want to work with. when I want to add my own necessary style conditions they aren't working right because of the existing.
So my idea was to delete all of them and than ad just my conditions. Is there a function i can do this?

Thanks for your help

Regards,
Patrick

**Comment by ivanfemia** [comment]
No, but you can fork this project and pull that functionality

**Comment by sandraros** [comment]
If you want us to look at this issue, could you provide more information so that we can replicate the issue: the initial Excel file, a small ABAP program to add the conditional formatting, and please tell us what is not working well.

Thank you.

**Comment by sandraros** [comment]
Very old issue -> Closing.
