### ISSUE TITLE
Data Content is being dropped during create_xl_sheet

### ISSUE THREAD

**Issue by OleEinarJansen** [abap2xlsx/abap2xlsx#604]
Hi,
I just noticed that there is an issue with table shared_string of class ZCL_EXCEL_WRITER_2007.
When a text/string cell value is contained in the worksheet (lets say 51897) and at the same time a date value exists in a different cell in the worksheet with an integer representation of that same value (e.g. 31.01.2042 equals 51897) the text/string cell value is lost when the method create_xl_sheet is triggered.
This is because an error in method CREATE_XL_SHAREDSTRINGS . The missing cell value is lost in class attribute C_XL_SHAREDSTRINGS which leads to a return of value 0 in the method GET_SHARED_STRING_INDEX.
There is a delete statement in method CREATE_XL_SHAREDSTRINGS:   DELETE ADJACENT DUPLICATES FROM lt_cell_data COMPARING cell_value.
Within this table at that given point in time - both cell values exist (date & text/string) containing diffferent DATA_TYPE ("a" for date and "s" for text/string). Now the delete duplicates statement leaves the date record alive whereas the text/string record is deleted. Later on the following loop only considers records of data_type "s" which means that the value 51897 is not being added to the shared_strings table.

  LOOP AT lt_cell_data ASSIGNING <fs_sheet_content> where data_type = 's'.
    lv_sytabix = lv_count.
    MOVE lv_sytabix                    TO ls_shared_string-string_no.
    MOVE <fs_sheet_content>-cell_value TO ls_shared_string-string_value.
    MOVE <fs_sheet_content>-data_type TO ls_shared_string-string_type.
    APPEND ls_shared_string TO shared_strings.
    add 1 to lv_count.
  ENDLOOP.

The delete adjacent duplicates must also consider the data_type not just the cell_value!
You can test/reproduce this basically with any date as long as its integer representation exists as well as a cell value as a text/string in the worksheet.
![image](https://user-images.githubusercontent.com/48213677/53740667-00718680-3e95-11e9-824c-e5e6de55500e.png)

**Comment by larshp** [comment]
Are you running the latest version? As far as I remember there was a bug like this some time ago which has been fixed

**Comment by OleEinarJansen** [comment]
I guess not, I am on ABAP2XLSX_V_7_0_6 - 2016-04-01.nugg
Do you have a defect number for me to crosscheck by any chance?

**Comment by OleEinarJansen** [comment]
Found it: #473
This is an exact duplicate. Closing this issue. Sorry about that.

**Comment by larshp** [comment]
yeah, code fixes part of https://github.com/sapmentors/abap2xlsx/pull/462
