### ISSUE TITLE
Exception Handling Missing

### ISSUE THREAD

**Issue by rbaggett** [abap2xlsx/abap2xlsx#606]
Code Inspection checks fail as throughout the code, exceptions are declared and not caught.

**Comment by gregorwolf** [comment]
You're welcome to fork the project, correct it and send a pull request.

**Comment by pokrakam** [comment]
Can assign to me, I have a PR ready once #781 is merged.

**Comment by sandraros** [comment]
There are still a few syntax warnings, see #854, I propose to continue there.

May I close this issue?

**Comment by pokrakam** [comment]
Don't close, I completely forgot about this one still have a PR with some updates ready, let me see what state it's in and will submit if relevant.
