### ISSUE TITLE
Demo program 01_HelloWorld.xlsx no file

### ISSUE THREAD

**Issue by razzzzzzz** [abap2xlsx/abap2xlsx#607]
I tried to start several demo Programs (f.e. ZDEMO_EXCEL1) in background. SAPGui for Windows 750
Get the success message "Data transferred to default backend directory", but there are no files!?

**Comment by razzzzzzz** [comment]
The lokal download is working properly. But the main goal to implement abap2xlsx is the feature to create xlsx files in backend processing. Any ideas are appreciated!

**Comment by razzzzzzz** [comment]
The download folder defined via TRX SO21 is on a Windows Server.

**Comment by ivanfemia** [comment]
Please check the main ZDEMO_EXCEL report to execute the report in the right way in batch mode

**Comment by razzzzzzz** [comment]
In background processing of ZDEMO_EXCEL the Job fails with exception NOT_SUPPORTED_BY_GUI.
Direct in SAPGui startet the reports creates the following files:
01_HelloWorld.xlsx
02_Styles.xlsx
03_iTab.xlsx
04_Sheets.xlsx
05_Conditional.xlsx
06_Formulas.xlsx
07_ConditionalAll.xlsx
08_Range.xlsx
09_DataValidation.xlsx
10_iTabFieldCatalog.xlsx
12_HideSizeOutlineRowsAndColumns.xlsx
13_MergedCells.xlsx
14_Alignment.xlsx
15_01_HelloWorldFromReader.xlsx
15_02_StylesFromReader.xlsx
15_03_iTabFromReader.xlsx
15_04_SheetsFromReader.xlsx
15_08_RangeFromReader.xlsx
15_13_MergedCellsFromReader.xlsx
15_31_AutosizeWithDifferentFontSizesFromReader.xlsx
16_Drawings.xlsx
17_SheetProtection.xlsx
18_BookProtection.xlsx
19_SetActiveSheet.xlsx
21_BackgroundColorPicker.xlsx
22_itab_fieldcatalog.xlsx
23_Sheets_with_and_without_grid_lines.xlsx
24_Sheets_with_different_default_date_formats.xlsx
27_ConditionalFormatting.xlsx
28_HelloWorld_Sheet1.csv
28_HelloWorld_Sheet2.csv
30_CellDataTypes.xlsx
31_AutosizeWithDifferentFontSizes.xlsx
33_autofilter.xlsx
34_Static Styles_Chess.xlsx
35_Static_Styles.xlsx
36_DefaultStyles.xlsx
37- Read template and output.xlsx
38_SAP-Icons.xlsx
39_Charts.xlsx
40_Printsettings.xlsx

But the submitted reports are called with rb_down = abap_true??

**Comment by gregorwolf** [comment]
I've just tested on my ABAP Developer Edition system. When running ZDEMO_EXCEL1 with the option "Save to backend" it stored the created file in /usr/sap/NPL/D00/work

```
vhcalnplci:npladm 10> pwd
/usr/sap/NPL/D00/work
vhcalnplci:npladm 11> ls -la 01*
-rw-rw---- 1 npladm sapsys 5968 Apr  4 09:51 01_HelloWorld.xlsx
```

And you noticed that there is also an option to send the created file via Email.

**Comment by razzzzzzz** [comment]
Thanks Gregor! The files are stored in our works directory F:\usr\sap....\work
E-Mail als works fine!
