### ISSUE TITLE
Freezepane error in method CREATE_XL_SHEET in ZCL_EXCEL_WRITER_HUGE_FILE

### ISSUE THREAD

**Issue by PeterVanGeel** [abap2xlsx/abap2xlsx#609]
When calculating the xsplit value for freeze-panes during huge file creation, I believe it uses the wrong source field (row in stead of column):

ZCL_EXCEL_WRITER_HUGE_FILE->CREATE_XL_SHEET

    IF lv_freeze_cell_column > 1.
      lv_value = lv_freeze_cell_column - 1.
      l_worksheet-xsplit = lv_freeze_cell_row - 1.
    ENDIF.

I think it should be:

    IF lv_freeze_cell_column > 1.
      lv_value = lv_freeze_cell_column - 1.
      l_worksheet-xsplit = lv_freeze_cell_column - 1.
    ENDIF.

**Comment by sandraros** [comment]
Thank you for your help. I confirm that it's a bug and your fix is okay. With the program below, we can reproduce the issue.

First, Excel shows an error:
![image](https://user-images.githubusercontent.com/34005250/141355203-a626f8b3-44ea-4d29-ac2f-f1c1fe9cd782.png)

After asking Excel to repair, there's no frozen column:
![image](https://user-images.githubusercontent.com/34005250/141354754-4a6773a6-89fd-42cb-ba4d-f8bda1e9e68a.png)

After fixing manually via the debugger, according to your proposal, there's no more Excel error, and the first column is frozen:
![image](https://user-images.githubusercontent.com/34005250/141354989-21ecb4ec-84fc-4bc1-bcfc-951504fd51a6.png)

Would you mind proposing the fix via a pull request?
Thank you.

Test program:
```
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'issue_609.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  SELECT land1, landx50 FROM t005t INTO TABLE @DATA(countries) WHERE spras = 'E'.
  lo_worksheet->bind_table(
      ip_table            = countries
      is_table_settings   = VALUE #( top_left_column = 'A' top_left_row = 1 ) ).
  lo_worksheet->freeze_panes( ip_num_columns = 1 ip_num_rows = 2 ).
  lcl_output=>output( cl_excel = lo_excel iv_writerclass_name = 'ZCL_EXCEL_WRITER_HUGE_FILE' ).
```
