### ISSUE TITLE
Error handling in ZCL_EXCEL_WORKSHEET->GET_TABLE

### ISSUE THREAD

**Issue by ivan-re** [abap2xlsx/abap2xlsx#610]
The method ZCL_EXCEL_WORKSHEET-> GET_TABLE generates an error (Sy-subrc = 8) if there is no content in the last row of the last column of Excel.
Please extend the coding with this line (102):
                  **AND lv_rc <> 8.** "rc is 8 when the last row contains cells with zero / no values

Context:
                me-> get_cell (
                  EXPORTING
                    ip_column = lv_actual_col "Cell Column
                    ip_row = lv_actual_row "Cell Row
                  IMPORTING
                    ep_value = lv_value "Cell Value
                    ep_rc = lv_rc "Return Value of ABAP Statements
                ).
                IF lv_rc <> 0
                  AND lv_rc <> 4 "No found error, zero / no value in cell
                  **AND lv_rc <> 8**. "rc is 8 when the last row contains cells with zero / no values
                  lv_errormessage = | {'Error at reading field value (Col:' (007)} {lv_actual_col} {'Row:' (005)} {lv_actual_row} |.
                  zcx_excel => raise_text (lv_errormessage).
                ENDIF.

[GET_TABLE.txt](https://github.com/sapmentors/abap2xlsx/files/3058112/GET_TABLE.txt)

**Comment by gregorwolf** [comment]
Thank you for letting us know. The perfect solution would be if you fork the project, make the correction and send a pull request.
