### ISSUE TITLE
FORMULA NOT WORKING

### ISSUE THREAD

**Issue by Gopalani** [abap2xlsx/abap2xlsx#616]
Hi,
We have been working on ECC 6.0 and wanted to create xlsx files and send them via background jobs, so I have taken help of you guys and have implemented kinda old version( which is suitable with my ECC version) but the slight issue which I am facing is that when using 
*        <fs_field_catalog1>-totals_function = zcl_excel_table=>totals_function_sum.
the sum value is being not generated in outlook preview of excel sheet. However, if I download the file and open it via excel I can view the value. The same thing is happening when I am using the sum formula.

It might be not a big issue but management is interested in the sum by using preview through the mobile app or outlook preview.

Any help would be appreciated.

**Comment by Gopalani** [comment]
![abap2xlsx sum](https://user-images.githubusercontent.com/22073301/61172888-d21f5880-a5a4-11e9-8e54-1e5b41b39f1e.PNG)

The above-mentioned picture is of outlook preview ( the same issue is  being faced on Gmail)

The below-mentioned
![aba2xlsx sum value](https://user-images.githubusercontent.com/22073301/61172927-38a47680-a5a5-11e9-9e12-63368131f2ef.PNG)
 picture of the data after being opened through excel

**Comment by gregorwolf** [comment]
I would suggest you save the file after being opened in Excel with another name. Then extract both files with a ZIP tool (maybe you need to rename to .zip) and then compare the differences. When you find out the difference you might find out that this isn't yet implemented and you can contribute it. But I would think that that would then require to re-create the formula in ABAP to do the calculation in advance and embed that in the file. For contribution you could use the ABAP Developer Edition.

**Comment by Gopalani** [comment]
Thanks for the reply.

I have tried your suggestion of zip, however, the same file is behaving differently with the outlook /Gmail/ default preview and different from excel.
 

I think as I am using the older version of abap2xlsx, there might be an issue with that version and the latest version and upgrades might have solved this issue. Although I have tried to find out the solution but I couldn't find it,

**Comment by gregorwolf** [comment]
I've just tested with the current version of abap2xlsx using the report ZDEMO_EXCEL6. I've sent this result to my Gmail and https://outlook.office.com/ account. There are 3 different behaviours:

- GMail shows only the values not the calculation results in the preview
- https://outlook.office.com calculates the results
- Outlook 2016 behaves like GMail and does not the calculation results in the preview

When I open the file in Excel and save it with another name the calculation is shown in all 3 clients. 

The quickest way to get this issue solved would be to contribute a solution yourself.

**Comment by sandraros** [comment]
This issue is about the formula values described in this other issue: #575 (Empty formula cells in readonly mode).
The proposal in #575 is to calculate the value via ABAP and provide it at the same time as the formula. In read-only mode (so the current case if I'm not wrong), the value is displayed, the formula is not calculated.
If you agree, I propose to close this current issue and work on #575.

**Comment by sandraros** [comment]
No answer, closing. Discussion to be continued in #575 please.
