### ISSUE TITLE
Enhance for ZCL_EXCEL_WORKSHEET->GET_TABLE

### ISSUE THREAD

**Issue by jameshub** [abap2xlsx/abap2xlsx#617]
suggest to enh:  To avoid  error "Internal table has less columns than excel", it will check the number of columns of internal table, then assign the number to lv_max_col. 

    Data:
      oref_table TYPE REF TO cl_abap_tabledescr,
      oref_struc TYPE REF TO cl_abap_structdescr.

    lv_max_col =  me->get_highest_column( ).
    lv_max_row =  me->get_highest_row( ).

    oref_table ?= cl_abap_tabledescr=>describe_by_data( et_table ).
    oref_struc ?= oref_table->get_table_line_type( ).
    lv_max_tablecol = lines( oref_struc->components ).

    if lv_max_tablecol gt 0.
      lv_max_col = lv_max_tablecol.
    endif.

**Comment by gregorwolf** [comment]
I think the GET_TABLE method should only work when the number of colums matches.

**Comment by sandraros** [comment]
For information, the enhancement proposal concerns these lines:
https://github.com/sapmentors/abap2xlsx/blob/5da41aaab2a738023605492b361b1c016c1eaf29/src/zcl_excel_worksheet.clas.abap#L2544-L2576

**Comment by sandraros** [comment]
Below the program to reproduce the error message, run it without selecting the option `MAX_COL`.

By running the program with the option selected, it will call the method `get_table` with `iv_max_col = 2` which prevents the message. I think it's an easy solution and there's no need to enhance the existing code. Or is there something I didn't understand?

```
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'issue_617.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
PARAMETERS max_col AS CHECKBOX.
START-OF-SELECTION.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  SELECT land1, landx50 FROM t005t INTO TABLE @DATA(countries) WHERE spras = 'E'.
  lo_worksheet->bind_table(
      ip_table            = countries
      is_table_settings   = VALUE #( top_left_column = 'A' top_left_row = 1 ) ).
  lo_worksheet->set_cell( ip_column = 'C' ip_row = 1 ip_value = 'test' ).
  TRY.
      IF max_col = abap_false.
        lo_worksheet->get_table(
          EXPORTING
            iv_skipped_rows = 1
          IMPORTING
            et_table        = countries ).
      ELSE.
        lo_worksheet->get_table(
          EXPORTING
            iv_skipped_rows = 1
            iv_max_col      = 2
          IMPORTING
            et_table        = countries ).
      ENDIF.
    CATCH zcx_excel INTO DATA(error).
      MESSAGE error TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
  lcl_output=>output( lo_excel ).
```
Message:
![image](https://user-images.githubusercontent.com/34005250/141333494-0f98e990-0744-457e-adba-b36d497aaf54.png)

**Comment by sandraros** [comment]
No answer. Closing.

**Comment by jinzhu01** [comment]
you need first define country like your excel structure .
