### ISSUE TITLE
abaplint Failed pull request 

### ISSUE THREAD

**Issue by striezl** [abap2xlsx/abap2xlsx#621]
Is this a global configuration issue, or did i miss something? Can you please check? Thanks!

![2019-09-04_18-55-51](https://user-images.githubusercontent.com/3652530/64275797-b9994200-cf46-11e9-8947-5c2538c0e69b.png)

**Comment by larshp** [comment]
thanks, I'll fix this tomorrow, abaplint 2.0.0 with breaking changes was recently released

**Comment by larshp** [comment]
fixed, also applied to your branch, closing

**Comment by striezl** [comment]
Thanks @larshp!
