### ISSUE TITLE
zcl_excel_worksheet->get_table( ) conversion error exponential number

### ISSUE THREAD

**Issue by striezl** [abap2xlsx/abap2xlsx#623]
Hi, 

the method raises an exception, when excel delivers an exponential number like -2.9398924194538267E-2 and the target field is type p (which is used for currency amounts). 

![abap2xlsx](https://user-images.githubusercontent.com/3652530/64414152-26215780-d093-11e9-8d35-f6a5679cb39a.PNG)

Solved it like this - maybe not the cleanest of all solutions, but it should be more robust then the current version:

                "old
                "<lv_value> = lv_value.

               "new
               DATA lx_conversion_error TYPE REF TO cx_sy_conversion_error.
               TRY.
                 <lv_value> = lv_value. "Will raise exception if data type of <lv_value> is not float and excel delivers exponential number e.g. -2.9398924194538267E-2
               CATCH cx_sy_conversion_error INTO lx_conversion_error.
                 "Another try with conversion to float...
                 DATA: lv_float TYPE f,
                       lv_type.
                 DESCRIBE FIELD <lv_value> TYPE lv_type.
                 IF lv_type = 'P'.
                   <lv_value> = lv_float = lv_value.
                 ELSE.
                  RAISE EXCEPTION lx_conversion_error. "Pass on original exception
                 ENDIF.
               ENDTRY.

What do you think?

Kind regards
Bernhard

**Comment by gregorwolf** [comment]
Hi Bernhard,
would be great if you can create a pull request with your correction. And for further robustness you might also be able to create a unit test for that.
Best regards
Gregor
