### ISSUE TITLE
Possible to export the XLSX file to PDF?

### ISSUE THREAD

**Issue by mfallen** [abap2xlsx/abap2xlsx#625]
Hi,
is there a way to export the generated Excel file to a PDF?

Thanks
Michael

**Comment by gregorwolf** [comment]
I would think only on a client with Excel installed.

**Comment by larshp** [comment]
yes, suggest closing this issue

**Comment by sandraros** [comment]
I think that converting to PDF is beyond the current scope of abap2xlsx, and that we should limit OLE features to the minimum.
No answer, closing the question.
