### ISSUE TITLE
Leading SPACE in EXCEL header/footer when using font-size

### ISSUE THREAD

**Issue by howdy64** [abap2xlsx/abap2xlsx#626]
Hi, 

I've tried to create an excel footer with a different font-size. The result was an unwanted leading space in footer/header.

Coding:

```
*   Footer Left
    ls_footer-left_value = ls_value.
    ls_footer-left_font-size = 8.
    ls_footer-left_font-scheme = zcl_excel_style_font=>c_scheme_none.
    ls_footer-left_font-name = zcl_excel_style_font=>c_name_arial.
```

![image](https://user-images.githubusercontent.com/55497895/65157633-51ac2680-da31-11e9-92ed-4a14dd0ebece.png)

I've adjusted the following coding to solve the problem:

![image](https://user-images.githubusercontent.com/55497895/65156885-1d843600-da30-11e9-8443-4d388dd84780.png)

Maybe you can fix it with the next release.

Thanks in advance. 
Marcel

**Comment by gregorwolf** [comment]
Hi Marcel,

you can contribute this fix by forking the project, do the correction and then send a pull request.

Best regards
Gregor

**Comment by gregorwolf** [comment]
Should be fixed with your correction. Thank you so much.
