### ISSUE TITLE
abaplint

### ISSUE THREAD

**Issue by striezl** [abap2xlsx/abap2xlsx#639]
Hi,

I just tried to send in pull request #638 and received the error below - it refers to a class that has not been touched. Please have a look. Thanks!

Kind regards
Bernhard

 Check failure on line 1506 in src/zcl_excel_common.clas.abap

@abaplint
abaplint
/ abaplint

Statement does not exist in ABAPv700(or a parser error)

**Comment by larshp** [comment]
its a bug in abaplint, I'll have a look tomorrow, thanks

**Comment by larshp** [comment]
fixed, sorry about the trouble, closing
