### ISSUE TITLE
Use of Append in a SOrted Table 

### ISSUE THREAD

**Issue by bhavesh4321** [abap2xlsx/abap2xlsx#648]
Class : ZCL_EXCEL_WRITER_2007  method -> CREATE_XL_SHAREDSTRINGS

Line number 66 : -*    APPEND ls_shared_string TO shared_strings. 

appending into a sorted table instead it should be     
INSERT ls_shared_string INTO TABLE shared_strings.

**Comment by larshp** [comment]
thanks, pull requests welcome

**Comment by chrisaasan** [comment]
Looks like this issue has been fixed in #654 and can be closed.
