### ISSUE TITLE
How to pull latest version?

### ISSUE THREAD

**Issue by jasharen** [abap2xlsx/abap2xlsx#651]
I'm not sure where else to ask this, so my apologies in advance.

How do I pull the latest version of the project? I originally pulled the nugget file over a year ago, but I'd like to update to the latest version and I see the nugget hasn't been updated in a long time.

Thanks!!

**Comment by gregorwolf** [comment]
I hope you can use abapGit. That way you can get the latest version just by pulling with abapGit.
