### ISSUE TITLE
Get_comments

### ISSUE THREAD

**Issue by jasharen** [abap2xlsx/abap2xlsx#653]
I have loaded an xlsx file into memory and am attempting to load the comments attached to the file.

    DATA:
      lo_iterator         TYPE REF TO cl_object_collection_iterator,
      lo_comments         TYPE REF TO zcl_excel_comments,
      lo_comment          TYPE REF TO zcl_excel_comment,
      lo_excel_worksheet  TYPE REF TO zcl_excel_worksheet.

      ls_sheet_name = ls_range-sheet.
      lo_excel_worksheet = go_excel->get_worksheet_by_name( ls_sheet_name ) ##NO_TEXT.
      lo_iterator = lo_excel_worksheet->get_comments_iterator( ).
      WHILE lo_iterator->has_next( ) = abap_true.
          lo_comment ?= lo_iterator->get_next( ).
      ENDWHILE.

The excel file has comments in it, however has_next never evaluates to true. Am I doing something wrong, or is the functionality not present?

Thanks,
Jared

**Comment by sandraros** [comment]
Thank you for the information. I reproduced the issue:

1. Run `ZDEMO_EXCEL_COMMENTS` to generate a demo file with comments
2. Run `ZDEMO_EXCEL37` to load and display the file
3. Issue: the comments from the original file were not loaded and consequently are not shown.

I think that the feature of loading the comments has not been developed at all in `ZCL_EXCEL_READER_2007`.
If you have the opportunity to contribute to the project, you are more than welcome to develop this feature (and anything else).
