### ISSUE TITLE
need files of structures to activate abap2xlsx : TT_ALV_TYPES ...

### ISSUE THREAD

**Issue by dorenthe** [abap2xlsx/abap2xlsx#655]
Hi and thanks,
 could you provide me the structure of those types please:

class-data WT_OBJECTS type TT_ALV_TYPES .
 data WT_SORT_VALUES type TT_SORT_VALUES .
 data WT_SUBTOTAL_ROWS type TT_SUBTOTAL_ROWS .
 data WT_STYLES type TT_STYLES .

**Comment by larshp** [comment]
first one: https://github.com/sapmentors/abap2xlsx/search?q=TT_ALV_TYPES

**Comment by dorenthe** [comment]
but fields are inside of those structures?

**Comment by dorenthe** [comment]
oh sorry - now I got it

**Comment by larshp** [comment]
@dorenthe can the issue be closed?

**Comment by dorenthe** [comment]
yes thank you!
