### ISSUE TITLE
pretty printer settings

### ISSUE THREAD

**Issue by larshp** [abap2xlsx/abap2xlsx#658]
Hi,
What should the preferred pretty printer settings be for abap2xlsx?

https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#use-the-pretty-printer-before-activating

Personally I use upper case keywords, which also seems like most of the current code

**Comment by Mind-Open** [comment]
Hi !
For my part everything in lower case

**Comment by gregorwolf** [comment]
+1 for Keywords uppercase

**Comment by mfallen** [comment]
+1 for Keywords upper as well

**Comment by larshp** [comment]
lets go with upper case, also looks like most of the current code is upper cased
