### ISSUE TITLE
ZCL_EXCEL_WORKSHEET->GET_COLUMN_DIMENSIONS not functioning correctly

### ISSUE THREAD

**Issue by SciLor** [abap2xlsx/abap2xlsx#664]
I am using a table bind and after the table bind get_column_dimensions is empty.

This is the same as #213 but for version 7.0.6

**Comment by jasharen** [comment]
get_column_dimensions no longer works as of a while ago. You have to use get_column and access the property you are interested in.

**Comment by SciLor** [comment]
That's impossible for me, as I don't know how many columns I have and I would like to set auto size for all of them. 
Maybe a thing I could try to fix. Is there a kind of method that converts the index of a number to its letter representation?

**Comment by jasharen** [comment]
I believe you can use the iterator for columns to loop through all existing columns on the sheet.

**Comment by sandraros** [comment]
The method `get_column_dimensions` doesn't exist any more so I propose to close this issue.
