### ISSUE TITLE
Method BIND_TABLE does not use Conversion Exit for Unit of Measure

### ISSUE THREAD

**Issue by jpbourne** [abap2xlsx/abap2xlsx#666]
When binding an internal table containing a unit of measure the internal unit of measure is referenced in the Excel worksheet (e.g. internal unit TAG). When the same internal table is displayed in an ALV the external unit is displayed based on the conversion exit (e.g. TAG becomes DAY in English).

**Comment by sandraros** [comment]
Thank you for proposing this issue. If `BIND_TABLE` is called with the field catalog defined with `abap_type = space`, the conversion exit is called.

This code can be used to reproduce both the symptom (no conversion exit), and the solution (conversion exit):
```abap
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'issue_666.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
PARAMETERS convexit AS CHECKBOX.
START-OF-SELECTION.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  SELECT msehi, msehl FROM t006a INTO TABLE @DATA(t006_lines) WHERE spras = 'E' AND msehi LIKE 'T%'.
  DATA(lt_field_catalog) = zcl_excel_common=>get_fieldcatalog( ip_table = t006_lines ).
  IF convexit = abap_true.
    MODIFY lt_field_catalog FROM VALUE #( abap_type = space ) TRANSPORTING abap_type WHERE fieldname = 'MSEHI'.
  ENDIF.
  lo_worksheet->bind_table(
      ip_table            = t006_lines
      it_field_catalog    = lt_field_catalog
      is_table_settings   = VALUE #( top_left_column = 'A' top_left_row = 1 ) ).
  lcl_output=>output( lo_excel ).
```
Output by running the program with `CONVEXIT` not selected:
![image](https://user-images.githubusercontent.com/34005250/141316241-d21148fd-48e8-4e6f-99eb-1ef91f540c68.png)

Output by running the program with `CONVEXIT` selected:
![image](https://user-images.githubusercontent.com/34005250/141320907-538d4d63-ce3a-4630-aa35-47ad2cdd36a6.png)

I think it's worth updating one of the demo programs to demonstrate how to run the conversion exit.

**Comment by sandraros** [comment]
No answer, closing the issue.
