### ISSUE TITLE
unable to display table control in edit code in module pool

### ISSUE THREAD

**Issue by A-S-G-S** [abap2xlsx/abap2xlsx#667]
Hi, im new to github. I currently encountered this issue of displaying table control in edit mode. The function mode for edit/display is 'switch' in the code. Need help.

I have tried these methods to display table control in edit mode when clicked button with 'switch' still not reflected
Method 1:        
IF SCREEN-NAME = 'GWA_ZEKPO-EBELP'.
         IF GWA_ZEKPO-EBELP IS NOT INITIAL.
          SCREEN-INPUT = 0.
          else.
            screen-input = 1.
          MODIFY SCREEN.
        ENDIF.
       endif.

Method 2: 
case ok_code.
 WHEN 'SWITCH'.

IF GV_ACTION = 0.
 GV_ACTION = 1.
ELSE.
 GV_ACTION = 0.
ENDIF.

LOOP AT SCREEN.

IF SCREEN-GROUP1 ='TC_ZEKPO' AND GV_ACTION = 0.
 SCREEN-INPUT = 1.
ELSE.
 SCREEN-INPUT = 0.
ENDIF.
MODIFY SCREEN.
ENDLOOP.
endcase.

Full code is as shown below:
*&---------------------------------------------------------------------*
*& Module Pool      SAPMZDLGPROG_03_REPORT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*

*INCLUDE MZDLGPROG_03_REPORTTOP                  .    " Global Data
*
* INCLUDE MZDLGPROG_03_REPORTO01                  .  " PBO-Modules
* INCLUDE MZDLGPROG_03_REPORTI01                  .  " PAI-Modules
* INCLUDE MZDLGPROG_03_REPORTF01                  .  " FORM-Routines

*&---------------------------------------------------------------------*
*& Include MZDLGPROG_03_REPORTTOP                   - Module Pool      SAPMZDLGPROG_03_REPORT
*&---------------------------------------------------------------------*
PROGRAM SAPMZDLGPROG_03_REPORT.

TABLES: ZEKKO_03,
        ZEKPO_03.

CONTROLS: TC_ZEKPO  TYPE TABLEVIEW USING SCREEN 9002.

DATA : OK_CODE   TYPE SY-UCOMM,
       GT_ZEKKO  TYPE TABLE OF ZEKKO_03,
       GWA_ZEKKO TYPE ZEKKO_03,
       GT_ZEKPO  TYPE TABLE OF ZEKPO_03,
       GWA_ZEKPO LIKE LINE OF GT_ZEKPO,
       F1        TYPE CHAR1,
       GV_LINES  TYPE I,
       GV_TABIX  TYPE SY-TABIX,
       ON_OFF    TYPE C LENGTH 1 VALUE '0',
       GV_ACTION TYPE I.

*&---------------------------------------------------------------------*
*& Include          MZDLGPROG_03_REPORTO01
*&---------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*& Module STATUS_9001 OUTPUT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
MODULE STATUS_9001 OUTPUT.
  SET PF-STATUS 'ZSTATUS'.
  SET TITLEBAR 'ZTITLE'.
ENDMODULE.

*&---------------------------------------------------------------------*
*& Module STATUS_9002 OUTPUT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
MODULE STATUS_9002 OUTPUT.
  SET PF-STATUS 'ZSTATUS'.
  SET TITLEBAR 'ZTITLE1'.

  PERFORM FETCH_DATA.
  PERFORM SWICH.

ENDMODULE.

*&---------------------------------------------------------------------*
*& Include          MZDLGPROG_03_REPORTI01
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_9002  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_9002 INPUT.
  CASE OK_CODE.
    WHEN 'BACK'.
      SET SCREEN 0.
      LEAVE TO SCREEN 0.

    WHEN 'DEL'.
      GET CURSOR LINE GV_TABIX.
      F1 = 1.
      PERFORM FETCH_DATA.
      IF F1 = 1.
        DELETE ZEKKO_03 FROM TABLE GT_ZEKKO.
        DELETE FROM ZEKPO_03 WHERE EBELN = GWA_ZEKKO-EBELN.
        COMMIT WORK.
      ENDIF.

    WHEN 'SVE'.

  ENDCASE.

  CLEAR GT_ZEKKO.
  CLEAR GT_ZEKPO.

ENDMODULE.
*&---------------------------------------------------------------------*
*&      Module  MODIFY_IT_ZEKPO  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE MODIFY_GT_ZEKPO INPUT.

  MODIFY GT_ZEKPO FROM GWA_ZEKPO
  INDEX TC_ZEKPO-CURRENT_LINE.

ENDMODULE.
*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_9001  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_9001 INPUT.
  CASE OK_CODE.
    WHEN 'BACK' OR 'EXIT' OR 'CANC'.
      LEAVE PROGRAM.
    WHEN 'DELETE' OR 'DISPLAY'.
      IF GWA_ZEKKO-EBELN IS INITIAL .
        MESSAGE 'Please enter document number' TYPE 'E'.
      ELSE.
        PERFORM FETCH_DATA.
        CALL SCREEN 9002.
      ENDIF.

    WHEN 'EDIT'  .
      CALL SCREEN 9002.

    WHEN 'CREATE'.
      CALL SCREEN 9002.

  ENDCASE.

ENDMODULE.

*&---------------------------------------------------------------------*
*& Form FETCH_DATA
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM FETCH_DATA .

  IF F1 NE 1.

    SELECT EBELN LIFNR EKORG EKGRP BUKRS WAERS ZTERM ZDESC FROM ZEKKO_03
      INTO CORRESPONDING FIELDS OF TABLE GT_ZEKKO
      WHERE EBELN = GWA_ZEKKO-EBELN.

    SELECT SINGLE EBELN LIFNR EKORG EKGRP BUKRS WAERS ZTERM ZDESC FROM ZEKKO_03
      INTO CORRESPONDING FIELDS OF GWA_ZEKKO
      WHERE EBELN = GWA_ZEKKO-EBELN.

    READ TABLE GT_ZEKKO INTO GWA_ZEKKO INDEX SY-TABIX.

    SELECT EBELP MATNR WERKS LGORT MENGE MEINS
      INTO CORRESPONDING FIELDS OF TABLE GT_ZEKPO FROM ZEKPO_03
       WHERE EBELN = GWA_ZEKKO-EBELN.

  ENDIF.

ENDFORM.

*INCLUDE MZDLGPROG_03_REPORT_FETCH_DO01.

*&---------------------------------------------------------------------*
*& Form SWICH
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM SWICH .

*  SELECT EBELN LIFNR EKORG EKGRP BUKRS WAERS ZTERM ZDESC FROM ZEKKO_03
*INTO CORRESPONDING FIELDS OF TABLE GT_ZEKKO
*WHERE EBELN = GWA_ZEKKO-EBELN.
*
*  SELECT SINGLE EBELN LIFNR EKORG EKGRP BUKRS WAERS ZTERM ZDESC FROM ZEKKO_03
*    INTO CORRESPONDING FIELDS OF GWA_ZEKKO
*    WHERE EBELN = GWA_ZEKKO-EBELN.
*
*  READ TABLE GT_ZEKKO INTO GWA_ZEKKO INDEX SY-TABIX.
*
*  SELECT EBELP MATNR WERKS LGORT MENGE MEINS
*    INTO CORRESPONDING FIELDS OF TABLE GT_ZEKPO FROM ZEKPO_03
*     WHERE EBELN = GWA_ZEKKO-EBELN.

  CASE OK_CODE.
    WHEN 'SWITCH'.
      IF ON_OFF = '0'.
        GV_ACTION = 0.
        ON_OFF = '1'.
      ELSE.
        GV_ACTION = 1.
        ON_OFF = '0'.
      ENDIF.

      LOOP AT SCREEN.

        """header
        IF SCREEN-NAME = 'GWA_ZEKKO-EKGRP'.
          SCREEN-INPUT = GV_ACTION.
          MODIFY SCREEN.
        ENDIF.

        IF SCREEN-NAME = 'GWA_ZEKKO-EKORG'.
          SCREEN-INPUT = GV_ACTION.
          MODIFY SCREEN.
        ENDIF.

        IF SCREEN-NAME = 'GWA_ZEKKO-BUKRS'.
          SCREEN-INPUT = GV_ACTION.
          MODIFY SCREEN.
        ENDIF.

        IF SCREEN-NAME = 'GWA_ZEKKO-LIFNR'.
          SCREEN-INPUT = GV_ACTION.
          MODIFY SCREEN.
        ENDIF.

        IF SCREEN-NAME = 'GWA_ZEKKO-WAERS'.
          SCREEN-INPUT = GV_ACTION.
          MODIFY SCREEN.
        ENDIF.

        IF SCREEN-NAME = 'GWA_ZEKKO-ZTERM'.
          SCREEN-INPUT = GV_ACTION.
          MODIFY SCREEN.
        ENDIF.

        IF SCREEN-NAME = 'GWA_ZEKKO-ZDESC'.
          SCREEN-INPUT = GV_ACTION.
          MODIFY SCREEN.
        ENDIF.

      ENDLOOP.

  ENDCASE.

ENDFORM.

**Comment by larshp** [comment]
GitHub is for collaborating around code, this is the abap2xlsx repository, it looks like the question above is not related to abap2xlsx, ie. out of scope

For general questions refer to http://answers.sap.com

**Comment by larshp** [comment]
closing
