### ISSUE TITLE
Add ability to generate report from template

### ISSUE THREAD

**Issue by AntonSikidin** [abap2xlsx/abap2xlsx#668]
I add some automation to generate report with template.

Article is here https://blogs.sap.com/2020/05/22/best-way-to-generate-microsoft-excel-xlsx-from-template-in-abap/

Is there code standard or guidline? 

I would like to merge my code to master.

**Comment by larshp** [comment]
not really, just upper case keywords, see https://github.com/sapmentors/abap2xlsx/issues/658

**Comment by larshp** [comment]
and the code must work on 702, like all the other code currently in the repository

**Comment by AntonSikidin** [comment]
Ok, I rewrite my code

**Comment by sandraros** [comment]
For information, the PR #669 corresponds to this enhancement proposal.

**Comment by sandraros** [comment]
The PR was merged, let's close this issue.
