### ISSUE TITLE
Missing Vietnamese text when output 

### ISSUE THREAD

**Issue by spacy0212** [abap2xlsx/abap2xlsx#672]
Hi,
I was exported  a demo excel sheet from ZDEMO_EXCEL1 with Vietnamese's character like 'ắ' or 'ớ'.
But character was missing when output.
How to solve this problem?
Please suggest me,
Thank you.
Code in program:
![image](https://user-images.githubusercontent.com/35814498/84924279-80efe100-b0f2-11ea-93c6-6792f37f0da8.png)
Output:
![image](https://user-images.githubusercontent.com/35814498/84924342-936a1a80-b0f2-11ea-91cb-724bc3b46ddf.png)

**Comment by bigld** [comment]
Hi @spacy0212 

you can comment these lines in ZCL_EXCEL_WRITER_2007->RENDER_XML_DOCUMENT

`  TRY.
      CALL METHOD lo_ostream->('SKIP_NON_XML_CHARACTERS')
        EXPORTING
          is_skipping = abap_true.
    CATCH cx_sy_dyn_call_illegal_method.

  ENDTRY.`


see #298

**Comment by sandraros** [comment]
Analysis: depending on kernel and notes installed in the SAP system, and depending on abap2xlsx works with fix 298 or not (respectively calling `SKIP_NON_XML_CHARACTERS` or not), there will be the following effects if Vietnamese text (and any other "non-XML" character) is written to the Excel file. In most (?) of client systems, the text will not be output, so **I would propose that `SKIP_NON_XML_CHARACTERS` is called only if a non-XML character is not serialized correctly, I propose a PR to test that.**

| SKIP_NON_XML_CHARACTERS available (note 1750204 (*)) (always "yes" if abap/kernel > 7.40) | Kernel as per note 2220720 (*) (always "yes" if kernel > 7.47) | Vietnamese text output with abap2xlsx before fix 298 | Vietnamese text output with abap2xlsx after fix 298 |
|-----------|------------|-----------|------------|
| No | No | XLSX file corrupted, Excel can't open it | XLSX file corrupted, Excel can't open it |
| No | Yes | Vietnamese text is output | XLSX file corrupted, Excel can't open it |
| Yes | No | XLSX file corrupted, Excel can't open it | Vietnamese text is not output |
| Yes | Yes | Vietnamese text is output | Vietnamese text is not output |

(*)
- [1750204 - iXML: Treatment of special and invalid characters - SAP for Me](https://me.sap.com/notes/1750204)
- [2220720 - iXML: Missing support in UTF-8 of Unicode characters that are longer than two bytes - SAP for Me](https://me.sap.com/notes/2220720)

The concerned "non-XML" characters which are skipped are those encoded in ABAP character variables with internal 2-byte values 0x0000 to 0x0008, 0x000B, 0x000C and 0x0800 to 0xDFFF (1). Unicode characters U+010000 to U+1FFFFF (Emoji, etc.) are encoded in ABAP characters variables as 2 "surrogate" characters (low 0xD800-0xDBFF and high 0xDC00-0xDFFF). Examples:
- Vietnamese characters ớ and ắ are respectively Unicode U+1EDB and U+1EAF, encoded 0x1EDB and 0x1EAF.
- Emoji characters 🦀🤙🌎🌍🌏 (#688) are respectively Unicode U+1F980, U+1F919, U+1F30E, U+1F30D and U+1F30F, encoded [0xD83E 0xDD80](https://www.google.com/search?q=Unicode+0xD83E+0xDD80), 0xD83E 0xDD19, 0xD83C 0xDF0E, 0xD83C 0xDF0D and 0xD83C 0xDF0F.
- Etc.

NB (1): I checked which "non-XML" characters are skipped by SKIP_NON_XML_CHARACTERS using this program https://gist.github.com/sandraros/ed2808ce00af79e0762b08d9f4514942#file-gistfile1-txt; they are also mentioned in the note [1750204](https://launchpad.support.sap.com/#/notes/1750204) which introduces SKIP_NON_XML_CHARACTERS.

EDIT October 20th, 2025: in case you ask, the method `SKIP_NON_XML_CHARACTERS` is not used by abap2xlsx.

**Comment by spacy0212** [comment]
Tks, issue has been resolved.
