### ISSUE TITLE
Type "ZEXCEL_T_DRAWINGS" is unknown.

### ISSUE THREAD

**Issue by aadjiet** [abap2xlsx/abap2xlsx#674]
Hi,

I did an offline import and when I execute program abend...

Category               ABAP programming error
Runtime Errors         SYNTAX_ERROR
ABAP Program           ZDEMO_EXCEL1
Application Component  Not assigned
Date and Time          26.06.2020 11:08:53

 Short Text
     Syntax error in program "ZDEMO_EXCEL1                            ".

 What happened?
     Error in the ABAP application program.

     The current ABAP program "ZDEMO_EXCEL" had to be terminated because it found a
     statement that could not be executed.
     In include "ZCL_EXCEL_WORKSHEET===========CU        ", in line 545 of program
      "ZDEMO_EXCEL1                            ", the following syntax errors
     have occurred:
     Type "ZEXCEL_T_DRAWINGS" is unknown.

     Author and last person to change the include are:
     Author         XXXXX
     Last changed by "XXXXXX      "

 Error analysis
     The following syntax error has occurred in program ZDEMO_EXCEL1
                  :
     Type "ZEXCEL_T_DRAWINGS" is unknown.

     " "

 Trigger Location of Runtime Error
     Program                                 ZDEMO_EXCEL
     Include                                 ZDEMO_EXCEL
     Row                                     38
     Module Name                             START-OF-SELECTION

**Comment by AndreaBorgia-Abo** [comment]
Somehow the offline import did not create or activate that structure.

This is an issue with abapGit, not abap2xlsx: please try again with a recent version of abapGit, if the problem persists an issue should be [filed for abapGit](https://github.com/abapGit/abapGit/issues)

**Comment by sandraros** [comment]
For information, it was possibly related to abapGit/abapGit#4513
