### ISSUE TITLE
about two bug at the new version abap2xlsx

### ISSUE THREAD

**Issue by syjf1976** [abap2xlsx/abap2xlsx#678]
I find two bugs in this new version.
the first one is : don't support asia language  such as chinese.   and the bug is because the class  ZCL_EXCEL_WRITER_2007 method  RENDER_XML_DOCUMENT  . the follow code skip asia language character.   It's FINE if block these code.
*  TRY.
*      CALL METHOD lo_ostream->('SKIP_NON_XML_CHARACTERS')
*        EXPORTING
*          is_skipping = abap_true.
*    CATCH cx_sy_dyn_call_illegal_method.
*
*  ENDTRY.
the second one is : If an internal table have integer field. a short dump will display  be bug is because  class  ZCL_EXCEL_WORKSHEET method  SET_CELL
        CASE lv_value_type.
          WHEN cl_abap_typedescr=>typekind_int1 OR cl_abap_typedescr=>typekind_int1 OR cl_abap_typedescr=>typekind_int2
            OR <fs_typekind_int8>. "Allow INT8 types columns  
changed to 
        CASE lv_value_type.
          WHEN cl_abap_typedescr=>typekind_int OR cl_abap_typedescr=>typekind_int1 OR cl_abap_typedescr=>typekind_int2
            OR <fs_typekind_int8>. "Allow INT8 types columns

**Comment by bigld** [comment]
introduced with #298

**Comment by sandraros** [comment]
Unicode not rendered should now be fixed (#756). Could you tell us if it's okay for you? Thanks.

**Comment by sandraros** [comment]
No answer. Closing.
