### ISSUE TITLE
Which demo is for xlsx2abap?

### ISSUE THREAD

**Issue by WolfgangZeller** [abap2xlsx/abap2xlsx#686]
I read that the abap2xlsx project includes also the opposite way xlsx2abap - but which demo is the right one?

**Comment by gregorwolf** [comment]
Please check https://github.com/sapmentors/abap2xlsx/blob/3bee79156d6f595eeac8ab2a185ac17101e15afa/src/zdemo_excel.prog.abap#L74 for the reader demo.

**Comment by WolfgangZeller** [comment]
@gregorwolf: thanks.
Where can I find the file for zdemo_excel137? In the src-folder there is no such file.

**Comment by gregorwolf** [comment]
https://github.com/sapmentors/abap2xlsx/blob/master/src/zdemo_excel37.prog.abap

**Comment by WolfgangZeller** [comment]
ufff...got it - sorry

**Comment by sandraros** [comment]
@WolfgangZeller I guess the question is answered. Could you close the issue?

**Comment by WolfgangZeller** [comment]
@sandraros Yes, you can close the issue. Thank you.

**Comment by wagener-mark** [comment]
Hi,
thanks for the answer and pointing out to demo report 37.  What I do not understand is, how I can convert the raw-data-table to a normal internal table with separate columns for each corresponding column in the xlsx spreadsheet. 

`  cl_document->open_document_from_table( EXPORTING document_size    = bytecount
                                                     document_table   = t_rawdata
                                                     open_inplace     = 'X' ).
`

In the demo report there is a call:
` lcl_output=>output( excel ).`
which calls ` cl_output->display_online( ).` when the option Direct Display is chosen. I hoped to fined a "solution" there...but that was not the case.

Would be happy if you could give me a hint ;-)
Thanks,
Mark

**Comment by sandraros** [comment]
> how I can convert the raw-data-table to a normal internal table with separate columns for each corresponding column in the xlsx spreadsheet.

You have to describe the internal table in your own program and use the method `GET_TABLE`. See [https://github.com/sapmentors/abap2xlsx/tree/master/src/demos/zdemo_excel43.prog.abap](https://github.com/sapmentors/abap2xlsx/tree/master/src/demos/zdemo_excel43.prog.abap).
