### ISSUE TITLE
emoji export to excel

### ISSUE THREAD

**Issue by ClarkZH** [abap2xlsx/abap2xlsx#688]
Hi,
 when my data contain the emoji, like this 🦀🦀🤙🤙🤙🌎🌍🌏,used the abap2xlsx to export data,the download file can't be opened. how to solve it ？

**Comment by sandraros** [comment]
That's the same error described in #672 with a workaround explained. I propose to not discuss here about the solution, instead go there: #672 
Thank you

**Comment by sandraros** [comment]
@ClarkZH Could you test the fix and close the issue if it works? Thanks.

**Comment by sandraros** [comment]
No answer. Closing.
