### ISSUE TITLE
how to update the latest version abap2xlsx

### ISSUE THREAD

**Issue by PENGFARLEY** [abap2xlsx/abap2xlsx#689]
Hi Teams,

how to update the latest version abap2xlsx?

**Comment by larshp** [comment]
how to update the latest version:
via a pull request, https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

how to update to the latest version on your local system:
via abapgit, https://docs.abapgit.org/guide-online-install.html

**Comment by PENGFARLEY** [comment]
> how to update the latest version:
> via a pull request, https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
> 
> how to update to the latest version on your local system:
> via abapgit, https://docs.abapgit.org/guide-online-install.html

Hi Larshp,
I have our system, we already have the the class: ZCL_EXCEL, and the abap2xlsx version is '7.0.3'.
and I see now the latest version is 7.10.
I checked this page: I don't have the TCODE or Program: Start ZABAPGIT.

**Comment by larshp** [comment]
https://docs.abapgit.org/guide-install.html

**Comment by PENGFARLEY** [comment]
> https://docs.abapgit.org/guide-install.html

Hi Larshp,

Thanks for you help.

now I have install the abapgit.

and now I want to update the abap2xlsx in our system, shall I import the last release abap2xlsx-7.1.0
[https://github.com/sapmentors/abap2xlsx/releases](url)

or download from here [https://github.com/sapmentors/abap2xlsx](url)?

**Comment by larshp** [comment]
follow https://docs.abapgit.org/guide-online-install.html to install the latest version

**Comment by larshp** [comment]
@PENGFARLEY did above help?

**Comment by PENGFARLEY** [comment]
@larshp Yes, it is working, thanks!
