### ISSUE TITLE
ZABAPGIT_STANDALONE Can’t unzip code master zip file

### ISSUE THREAD

**Issue by anupd007** [abap2xlsx/abap2xlsx#701]
Hello Team,

I am trying to use the project by downloading the code Zip file.  

And doing a manual import via ZABAPGIT_STANALONE 

but when I upload the master zip file it fails to Unzip the master zip file 

I debugged the program to arrive at below note.  And it suggests that the zip file is corrupted. 

2506031 - STRING_OFFSET_LENGTH_TOO_LARGE in CL_ABAP_ZIP

Can someone help on this.  

Thanks.

**Comment by larshp** [comment]
whats the error message, if any?

UPDATE, seems ok here,
![image](https://user-images.githubusercontent.com/5888506/95203623-4b771c80-07e3-11eb-87e0-2a2aa8473742.png)

**Comment by sandraros** [comment]
@anupd007 Could you download the abap2xlsx ZIP file again and import it via abapGit to see if the problem persists?

**Comment by sandraros** [comment]
No answer. Closing.
