### ISSUE TITLE
1000er Delimiter in Cell

### ISSUE THREAD

**Issue by fischicr7** [abap2xlsx/abap2xlsx#706]
Hey guys,

is it possible to convert a cell as a numeric cell with the 1000er delimiter? 
My current workaround is, to export the value as an String, but excel indicates it and shows a warning behind every cell exported as a numeric value in a string format. 

Kind regards
Daniel

**Comment by sandraros** [comment]
Not sure to understand what you mean by "convert". If you are looking for the Excel standard feature "[number formatting](https://support.microsoft.com/en-us/office/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68)". If you want to output the number 23000 with thousands separator, you can use the number format ``.

The following program outputs this Excel file:
![image](https://user-images.githubusercontent.com/34005250/107872983-f04ee800-6eae-11eb-820e-34e816e5fe54.png)

You may see in menu Home > Number this number format:
![image](https://user-images.githubusercontent.com/34005250/107872994-11afd400-6eaf-11eb-9db0-802bc5c7d15f.png)

which corresponds to this custom format `#,##0.00` which can be used in the ABAP program:
![image](https://user-images.githubusercontent.com/34005250/107873005-24c2a400-6eaf-11eb-91dc-a38c13412c05.png)

If that answers your question, could you close the issue please? Thank you.

Code:
```
DATA: lo_excel                TYPE REF TO zcl_excel,
      lo_worksheet            TYPE REF TO zcl_excel_worksheet,
      lo_style                TYPE REF TO zcl_excel_style.
CONSTANTS: gc_save_file_name TYPE string VALUE '22_itab_fieldcatalog.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  CREATE OBJECT lo_excel.
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_style = lo_excel->add_new_style( ).
  lo_style->number_format->format_code = '#,##0.00'.
  lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = 23000 ip_style = lo_style->get_guid( ) ).
  lcl_output=>output( lo_excel ).
```

**Comment by sandraros** [comment]
No answer. Closing.
