### ISSUE TITLE
time to deprecate zcl_excel_aunit?

### ISSUE THREAD

**Issue by larshp** [abap2xlsx/abap2xlsx#715]
Hi,
I think its time to deprecate https://github.com/sapmentors/abap2xlsx/blob/master/src/zcl_excel_aunit.clas.abap

I guess it was needed on 700, to differ between CL_AUNIT_ASSERT and CL_ABAP_UNIT_ASSERT

CL_AUNIT_ASSERT is long time obsolete and CL_ABAP_UNIT_ASSERT exits on all(?) versions 702 and above

```abap
        new  type tv_clsname value 'CL_ABAP_UNIT_ASSERT',
        old  type tv_clsname value 'CL_AUNIT_ASSERT',
```

**Comment by sandraros** [comment]
Do we simply replace all references to `zcl_excel_aunit` with `cl_abap_unit_assert`? If so, I can do that.

**Comment by larshp** [comment]
in my opinion, yes

**Comment by sandraros** [comment]
Please check if this PR is sufficient. Thanks.
