### ISSUE TITLE
refactoring/extract OLE methods

### ISSUE THREAD

**Issue by larshp** [abap2xlsx/abap2xlsx#717]
https://github.com/sapmentors/abap2xlsx/blob/master/src/zcl_excel_worksheet.clas.abap#L84 contains a OLE method

OLE wont work on eg. Steampunk, so suggest to extract this method to a new class/package, so the central worksheet class can be activated

**Comment by sandraros** [comment]
Please check if this PR is sufficient. Thanks.

**Comment by sandraros** [comment]
@larshp Can we close this issue?
