### ISSUE TITLE
cleanup types in zif_excel_book_protection

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abap2xlsx/abap2xlsx#720]
(WIP on https://github.com/sapmentors/abap2xlsx/issues/692)

> anyhow, in my opinion, it looks like this data element can be replaced with a type defined in interface `zif_excel_book_protection`, only reason to have it as a data element would be saving in database or using in a dynpro, which I don't think will happen?

I compared zif_excel_book_protection with zif_excel_sheet_protection and I'm considering these changes:
* clone data element "zexcel_sheet_protection_bool" to "zexcel_book_protection_bool"
* in "zexcel_book_protection" change c_locked  and c_unlocked to "zexcel_book_protection_bool"
* change both zexcel_book_protection and zexcel_sheet_protection to local types

Looks reasonable?

_Originally posted by @AndreaBorgia-Abo in https://github.com/sapmentors/abap2xlsx/issues/714#issuecomment-757139789_

**Comment by larshp** [comment]
yea, sounds good to me

and also delete the data elements, I think its unlikely that they are used in custom code, but it might break existing code...

perhaps its time to keep some kind of changelog, https://docs.abapgit.org/development/guide-changelog.html

**Comment by AndreaBorgia-Abo** [comment]
I'd leave the initial changelog to you, then I can follow along once I have an example.
