### ISSUE TITLE
Feature request for Excel tables: Calculated Column Formula

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#723]
Microsoft Excel has a powerful feature for [tables](https://support.microsoft.com/en-us/office/overview-of-excel-tables-7ab0bb7d-3a9e-4b56-a3c9-6c94334e492c), named the [Calculated Column Formulas](https://support.microsoft.com/en-us/office/use-calculated-columns-in-an-excel-table-873fbac6-7110-4300-8f6f-aafa2ea11ce8):

1. Entering or changing the formula in one cell automatically applies it to all the cells in the same column
2. Resizing the table or inserting a row automatically replicates the calculated column formulas to these new rows
3. The formulas may use the names of the columns instead of classic range references
4. It's still possible to have other values in the column but is marked as an error ("This is generally not recommended though").

Currently, abap2xlsx:

1. may create a table via the method BIND_TABLE (only), the values and formulas of the table are passed via an internal table, another parameter is the field catalog which indicates which columns contain values and which others contain formulas.
2. a repeated formula must be entered in every line of the internal table. Hence the same formula `TblFlights[[#This Row],[Airfare]]+100` can be defined in every row (formula using "[structured references](https://support.microsoft.com/en-us/office/using-structured-references-with-excel-tables-f5ed2452-2337-4f71-bed3-c8ae6d2b276e)"), while a formula using cell references `D2+100` must vary at every row (i.e. the formula in the next row must be `D2+100`).
3. has no demo program of formulas with BIND_TABLE.
4. does not have a way to produce an Excel file where the user can have the calculated formulas automatically replicated when he/she resizes the table
5. does not have a way to hide cell errors (which is especially useful for a calculated column if one cell needs to have a different value).

I propose these features:

1. enter a formula only once via the field catalog (instead of providing/repeating the formula in all lines of the internal table), whatever the formula is of the form `TblFlights[[#This Row],[Airfare]]+100` or `D2+100`
2. provide a demo program of formulas with BIND_TABLE
3. produce an Excel file where the user can have the calculated formulas automatically replicated when he/she resizes the table
4. produce an Excel file where the cell errors can be hidden

NB: it's not possible to enter `[@Airfare]`, only the long formula is permitted `TblFlights[[#This Row],[Airfare]]`.

Illustrations from Microsoft Web site (links above):
![image](https://user-images.githubusercontent.com/34005250/105761007-d591ef00-5f52-11eb-8634-d3bd6c5287b0.png)

**Comment by sandraros** [comment]
I'm currently working on a proposal at https://github.com/sandraros/abap2xlsx/tree/repeated-table-formulas. Almost finished.

**Comment by tk-am501** [comment]
Hello
