### ISSUE TITLE
Respecting blanks & detecting columns in formula

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#728]
This is an issue created after pull request #690. The commit of this pull request contains a test class, but the correction itself is provided as text instead of being in a commit. I have asked the author to update his pull request, otherwise I will create a new one with his code.

All the following test cases currently fail:
```
CLASS ltc_shift_formula DEFINITION
      FOR TESTING
      DURATION SHORT
      RISK LEVEL HARMLESS.
  PRIVATE SECTION.
    METHODS test1 FOR TESTING.
    METHODS test2 FOR TESTING.
    METHODS test3 FOR TESTING.
    METHODS test4 FOR TESTING.
ENDCLASS.

CLASS ltc_shift_formula IMPLEMENTATION.
  METHOD test1.
    cl_abap_unit_assert=>assert_equals( act = zcl_excel_common=>shift_formula(
        iv_reference_formula = `X(B13, "KK" )  `
        iv_shift_cols        = 1
        iv_shift_rows        = 1 ) exp = `X(C14, "KK" )  ` ). " Expected [X(C14, "KK" ) ] Actual [X(C14,"KK")]
  ENDMETHOD.
  METHOD test2.
    cl_abap_unit_assert=>assert_equals( act = zcl_excel_common=>shift_formula(
        iv_reference_formula = `SUBTOTAL(109,Table1[SUM 1])`
        iv_shift_cols        = 1
        iv_shift_rows        = 1 ) exp = `SUBTOTAL(109,Table1[SUM 1])` ). " Expected [* *] Actual [**]
  ENDMETHOD.
  METHOD test3.
    cl_abap_unit_assert=>assert_equals( act = zcl_excel_common=>shift_formula(
        iv_reference_formula = `B4 & C4`
        iv_shift_cols        = 0
        iv_shift_rows        = 1 ) exp = `B5 & C5` ). " Expected [B5 & C5] Actual [B5&C5]
  ENDMETHOD.
  METHOD test4.
    cl_abap_unit_assert=>assert_equals( act = zcl_excel_common=>shift_formula(
        iv_reference_formula = `SUM(F_1,F_2)`
        iv_shift_cols        = 1
        iv_shift_rows        = 1 ) exp = `SUM(F_1,F_2)` ). " Expected [SUM(F_1,F_2)] Actual [SUM(G2,G3)]
  ENDMETHOD.
ENDCLASS.
```

Note that the pull request provides a test case for `INDIRECT("RC[4]",FALSE)` (cell at current row (+ 0) and current column + 4) whose shifting by 1 row and 1 column should return the same formula, which currently works as expected.

NB: I guess that the correction provided in the pull request would correct this issue: #727 (SHIFT_FORMULA interprets incorrectly sheet names with final digit and lower case (e.g. "Sheet1")).

**Comment by AndreaBorgia-Abo** [comment]
The following test cases above have changed names, rightly so; here are the mappings, by comments:
METHOD test1. => superflous blanks, multi-argument functions, literals in function, unknown functions
METHOD test2. => SUBTOTAL(109,Table1[SUM 1]
METHOD test3. => B4 & C4
METHOD test4. => F_1 is a range name, not a cell address
Closing now.
