### ISSUE TITLE
Pull Repo: ERROR while importing Object [...] from the DB

### ISSUE THREAD

**Issue by HuprichT** [abap2xlsx/abap2xlsx#729]
Hello guys, 

I have problems initially setting up the Repo from Github. 
Error Message after Pull: "Error while Importing object ZEXCEL_S_ORG_REL from the Database"
![image](https://user-images.githubusercontent.com/45813255/106883164-e9bab680-66df-11eb-8c96-2c7dab308f6c.png)

This is the only repo object that is not working. 
What did I try to resolve this? 

- Navigate to the Table and activate it by myself 
- Delete the Table and try to pull again
- Make Force Pull

I would highly appreciate it if someone could help me. 

![image](https://user-images.githubusercontent.com/45813255/106883386-32726f80-66e0-11eb-9543-6753e7b83a8a.png)
![image](https://user-images.githubusercontent.com/45813255/106883627-87ae8100-66e0-11eb-9cdb-265154335621.png)

**Comment by larshp** [comment]
does structure `BAPIBUS1006002_CENTRAL` exist in your system?

**Comment by HuprichT** [comment]
> does structure `BAPIBUS1006002_CENTRAL` exist in your system?

Yes it exists

**Comment by larshp** [comment]
from the diff, it looks like ZEXCEL_S_ORG_REL was imported? can you check what it looks like in SE11?

**Comment by HuprichT** [comment]
After (unsuccessful ) pull it's partly active but I can activate it without any errors
![image](https://user-images.githubusercontent.com/45813255/106887291-4076bf00-66e5-11eb-9645-fd05cf02be0e.png)

**Comment by sandraros** [comment]
@seniorFreshmen In your system, it seems that `.INCLUDE BAPIBUS1006002_CENTRAL` is at the 109th position, but in my S/4HANA 1709 system, it's at the **108th** position. So it means that in your system one of the previous SAP structures has more fields. Could that be the reason of the error?

**Comment by larshp** [comment]
@sandraros I think you are right, @seniorFreshmen can you help to open this as an issue in https://github.com/abapGit/abapGit, I think it should be possible to reproduce with some dummy Z structures and a few branches

**Comment by seniorFreshmen** [comment]
[Pull Repo: ERROR while importing Object](https://github.com/abapGit/abapGit/issues/4506)

**Comment by sandraros** [comment]
Hi @seniorFreshmen. Could we close this issue in abap2xlsx as I think it's solved (by abapGit fix)? Thank you.

**Comment by sandraros** [comment]
No answer, closing.
