### ISSUE TITLE
How to upload XLSX to SAP 

### ISSUE THREAD

**Issue by HuprichT** [abap2xlsx/abap2xlsx#736]
Hello, 

currently im struggling with this repo and its demo programs.

My Aim is to upload an XLSX and display it with an itab

Some similiar Issue was posted a time in [Issue 543](https://github.com/sapmentors/abap2xlsx/issues/543) and help was posted by @gregorwolf 

I tried the mentioned programs:

- Demo 15: When inserting XLSX with Path, Error Message is displayed
  `A problem occured when reading the file`
- Demo 37 via Direct Display: Only Blanc Screen is display 
  (At this time I dont know how to handle the demo correctly and what templates are in this context)
- Demo 38: I'm not sure how to use the S_ICON Options and nothing is displayed
  (If i'm not filling the S_ICON Fields correctly i'm getting some kind of overflow btw and after that I have to kill the Session)

Hope somebody can help me with that. 
After resolving this issue I would likely contribute to this project by adding ome documentation for similar lost souls like me.

**Comment by chemik3** [comment]
Send me email (novak@sapnet.cz) and i will help you.

**Comment by sandraros** [comment]
Did you try also "Demo 43" as suggested in Issue 543?
For any question rather than bug, please follow the instructions here: https://github.com/sapmentors/abap2xlsx#discussion-board
If your question is answered, could you please close it?
Thank you.
