### ISSUE TITLE
XLSX template loses custom formatting

### ISSUE THREAD

**Issue by RandyWaterhouse2701** [abap2xlsx/abap2xlsx#751]
Dear colleagues,

lets assume we wanna do something elementary like reading a xlsx template in a report, process it through a writer and display it, analogous to ZDEMO_EXCEL37, afterwards:
```
*&---------------------------------------------------------------------*
*&      Form  READ_TEMPLATE
*&---------------------------------------------------------------------*
FORM read_template RAISING zcx_excel .

  CREATE OBJECT reader TYPE zcl_excel_reader_2007.
  excel = reader->load_file(  p_upfile ).
  "Use template for charts
  excel->use_template = abap_true.

ENDFORM.                    " READ_TEMPLATE

*&---------------------------------------------------------------------*
*&      Form  WRITE_TEMPLATE
*&---------------------------------------------------------------------*
FORM write_template  RAISING zcx_excel.

  REPLACE '&' IN gc_save_file_name WITH 'xlsx'.  " Pass extension for standard writer
  DATA(o_xlwriter) = CAST zif_excel_writer( NEW zcl_excel_writer_2007( ) ).
  excel->use_template = abap_true.
  DATA(lv_xl_xdata) = o_xlwriter->write_file( excel ).
  excel = reader->load( lv_xl_xdata ).
  lcl_output=>output( excel ).

ENDFORM.                    " WRITE_TEMPLATE
```
This will cause loss of any custom styles within the template - the text content will be rendered, but the custom formatting will not be present. My goal would be to save a clean template to a DDIC table and use it afterwards to stream it as base64 (by use of SCMS_BASE64_ENCODE_STR) within a odata function to an ui5 application. Keeping custom formatting would be appreciated.

This sounds suspicious similar to https://github.com/sapmentors/abap2xlsx/issues/205, but its an old issue and was obviously already fixed years ago. I have the strong suspicion it could be layer 8, but I cant help my self, zcl_excel_writer_2007 offers only write_file, I have no idea what could go wrong. Any thoughts? Thank you very much,

br

**Comment by RandyWaterhouse2701** [comment]
[Template.xlsx](https://github.com/sapmentors/abap2xlsx/files/6176804/Template.xlsx)

**Comment by AndreaBorgia-Abo** [comment]
This looks like #722 to me.

**Comment by sandraros** [comment]
Hi @RandyWaterhouse2701. The program `ZDEMO_EXCEL37` doesn't show any problem when re-creating the same file. The original styles are kept. I checked your code and I think that the solution is to re-create the abap2xlsx "reader" object. In the below example, I can reproduce your issue, but if replace the line `excel = ...` with the one below, there's no more issue.
Could you check in your system please, or did I miss something? Thank you.
```
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'test.xlsx'.
PARAMETERS p_upfile TYPE string LOWER CASE DEFAULT 'C:\Temp\Template.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  TRY.
      DATA(reader) = NEW zcl_excel_reader_2007( ).
      DATA(excel) = reader->zif_excel_reader~load_file( p_upfile ).
      DATA(writer) = NEW zcl_excel_writer_2007( ).
      DATA(lv_xl_xdata) = writer->zif_excel_writer~write_file( excel ).
      excel = reader->zif_excel_reader~load( lv_xl_xdata ).                     " <=== produces issue 751
*      excel = NEW zcl_excel_reader_2007( )->zif_excel_reader~load( lv_xl_xdata ). " <=== solves issue 751
      lcl_output=>output( excel ).
    CATCH cx_root INTO DATA(lx_root).
      MESSAGE lx_root TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
```

**Comment by AndreaBorgia-Abo** [comment]
> Could you check in your system please, or did I miss something? Thank you.

Out of curiosity, I also tried that sample with my work laptop and Excel 2013: I can confirm the formatting is lost in the first case and preserved in the second case (new reader object).
(EDIT: ok, the error "can't comment at this time" now is gone!)

**Comment by RandyWaterhouse2701** [comment]
Hey,

sorry for returning late on this. Yes, Sandra's assumption is correct, you need to recreate the reader object, the styles will be kept than. Thank you,

br

**Comment by sandraros** [comment]
Thank you very much for your feedback. Anyway, I think it wouldn't be too much difficult to fix the issue with the reader, it's probably due to an attribute not cleared, and I see only 5 attributes. So I propose to keep the issue opened. We may solve it easily as we have a reproducible example.

**Comment by RandyWaterhouse2701** [comment]
Welcome, its a good idea from my pov to fix it: finding out on my own was pretty tricky, I couldnt wait for a fix and the corresponding ui5 app went live meanwhile. However, the bug is at least documented now, so anybody can at least find a workaround in case they are confrontated with
