### ISSUE TITLE
"The specified type cannot be converted into the target variables" on reader object

### ISSUE THREAD

**Issue by Suncatcher** [abap2xlsx/abap2xlsx#755]
I'm trying [zdemo_excel37](https://github.com/sapmentors/abap2xlsx/blob/master/src/zdemo_excel37.prog.abap) to parse Excel file but I am getting the below error on string 241

    CREATE OBJECT reader TYPE zcl_excel_reader_2007.

![image](https://user-images.githubusercontent.com/6388034/118637485-895b0b00-b7de-11eb-93f6-d0aab9ba6938.png)

System version is 701 SP07.

P.S. Seems I have old version of abap2xlsx so do not propose me to use GET_TABLE method from zcl_excel_worksheet, I miss it on my system.

**Comment by gregorwolf** [comment]
Is a NetWeaver 701 SP07 still supported by SAP?

**Comment by Suncatcher** [comment]
Yes

**Comment by Suncatcher** [comment]
It seems my abap2xlsx installation is corrupted, so closing the issue
