### ISSUE TITLE
proposal for the creation of contribution guidelines (Contributing.md)

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abap2xlsx/abap2xlsx#768]
As suggested by @gregorwolf , I'm turning my questions as a newly added contributor into an issue, to allow for discussion and refinement.

My original questions were:
1) for my own trivial changes, should I still go via the PR route?
2) when dealing with existing PRs, should I wait for approval by other contributors? Any?
3) what is the stance with respect to long-running PRs? Should we ping authors? 

Today I'll write an initial version of Contributing.md, with my own take on at least these questions and a few other bits and pieces which usually belong to such guidelines.

**Comment by AndreaBorgia-Abo** [comment]
Ok, I have created a [PR](https://github.com/sapmentors/abap2xlsx/pull/769), please have a look.

If there are other suggestions, things to be added for example, please discuss them here.

**Comment by AndreaBorgia-Abo** [comment]
One thing I noticed is that occasionally there are comments in code mentioning the author: this is of course out of habit from traditional SAP development but when working with git they're wholly unnecessary.

I propose that we discourage adding such comments, if possibile.

**Comment by AndreaBorgia-Abo** [comment]
Related : #773

**Comment by pokrakam** [comment]
I would take it a step further and delete or refactor many of the superfluous comments.

**Comment by pokrakam** [comment]
Hmm, I read through and am not convinced by the idea that we should use SCN as the main discussion board. Having issues here and discussions on SCN is splitting things up. 
The vast majority of OpenSource GitHub projects, including ABAP based ones, use GitHub Issues because it's simple and it works.

**Comment by AndreaBorgia-Abo** [comment]
@pokrakam I agree, removing spurious comments would increase code quality. Would you file an issue for that, perhaps with an example? I've seen one with both the author name AND the explanation for the change, which should be kept imho.
Ditto for using GH for reporting issues: the SAP forum should be for general "how to" questions.
