### ISSUE TITLE
2 unused DOMA?

### ISSUE THREAD

**Issue by larshp** [abap2xlsx/abap2xlsx#770]
Looks like the following 2 domains can be deleted?

```
./src/zexcel_boole01.doma.xml[1, 1]                 - DOMA ZEXCEL_BOOLE01 not statically referenced (unused_ddic) [E]
./src/zexcel_sheet_bool.doma.xml[1, 1]              - DOMA ZEXCEL_SHEET_BOOL not statically referenced (unused_ddic) [E]
```

https://github.com/sapmentors/abap2xlsx/search?q=ZEXCEL_BOOLE01

https://github.com/sapmentors/abap2xlsx/search?q=ZEXCEL_SHEET_BOOL

**Comment by larshp** [comment]
related = https://github.com/sapmentors/abap2xlsx/pull/738, but it did not remove the domain from the repository. Added to ignore instead of deleting, https://github.com/sapmentors/abap2xlsx/pull/738/commits/d4b36a93d65e7893a8e43afb3acae35da35e9d6e

**Comment by AndreaBorgia-Abo** [comment]
@larshp thanks for catching that, I had forgotten about it and honestly I don't really remember what I did that resulted in the domain being ignored instead of removed. I'll have another look soon.

**Comment by AndreaBorgia-Abo** [comment]
I'm puzzled, really: that commit does not include changes to .abapgit.xml, in fact I had noticed my additional editing, reverted it before sending the PR (and logged it) but I must have forgotten to actually delete the domain, can't find another explanation.

Anyhow, PR incoming shortly.

**Comment by larshp** [comment]
yea, well, 🤷‍♂️ it can be fixed in a follow up PR 😄
