### ISSUE TITLE
We are Unable to Pull all the structures and Table type 

### ISSUE THREAD

**Issue by pmehta07** [abap2xlsx/abap2xlsx#771]
Hi Team SAPMENTORS,

We are unable to pull some dictionary objects, Could you please assist us on this? Kindly see the enclosed errors.

We are on S4/HANA 2020.

Thanks,
Puneet Mehta

![Pull Error2](https://user-images.githubusercontent.com/87070972/124747710-d5edd780-df3f-11eb-96c0-ec5b65acd074.jpg)
![Pull Error1](https://user-images.githubusercontent.com/87070972/124747717-d8503180-df3f-11eb-9f42-54e1b12faf58.jpg)

**Comment by larshp** [comment]
are you running the latest abapGit version?

**Comment by pmehta07** [comment]
Thank you very much for the quick response. I was able to download with the latest abapGit version. Issue can be closed..
