### ISSUE TITLE
Harmonize pretty print settings

### ISSUE THREAD

**Issue by pokrakam** [abap2xlsx/abap2xlsx#780]
In the same principle as #773, different code uses different styles for keyword/identifier upper/lower case. 

Propose standardising on the most commonly used format of keyword upper / identifier lower case to minimise large diffs due to pretty print.

See also [Style Guides](https://github.com/SAP/styleguides/blob/main/clean-abap/sub-sections/UpperVsLowerCase.md) on the topic.

**Comment by larshp** [comment]
also see https://github.com/sapmentors/abap2xlsx/issues/658

**Comment by pokrakam** [comment]
Didn't spot that one. I did search for an issue about this, but only open ones.

**Comment by AndreaBorgia-Abo** [comment]
So, if I understand it correctly, this should be once-in-project-lifetime occurrence: once the "keywords in uppercase / identifiers in lowercase" consensus reached in #658 is implemented, we shouldn't have to deal with this issue any more. 
In this case, I'll move this one to my todolist and review it quickly.

**Comment by pokrakam** [comment]
Correct, and with abapLint we can verify that all PRs conform in future.

**Comment by AndreaBorgia-Abo** [comment]
Guess I'll now have to learn how to deploy the linter in my setup, now :)
