### ISSUE TITLE
Conditional Formatting for Cells that "Begin With" a certain string

### ISSUE THREAD

**Issue by hardyp** [abap2xlsx/abap2xlsx#783]
I have made a change in my system to enable ABAP2XLS to do conditional formatting to - for example - turn cells a different color if they begin with a certain string. That may not be a common requirement but nonetheless I am going to submit this change as a possible enhancement to the core project. The change is in class  ZCL_EXCEL_WRITER_2007 method CREATE_XL_SHEET.
It's going to look like this:-
![image](https://user-images.githubusercontent.com/7078215/126464544-dac819f4-8793-4ec4-8357-7d0926683ab0.png)

**Comment by sandraros** [comment]
pull request : #786

**Comment by sandraros** [comment]
To reproduce the issue
- Duplicate ZDEMO_EXCEL27
- Replace
  ```
  lo_style_cond->rule         = zcl_excel_style_cond=>c_rule_cellis.
  ls_cellis-formula           = '"Carp"'.
  ls_cellis-operator          = zcl_excel_style_cond=>c_operator_equal.
  ```
  with
  ```
  lo_style_cond->rule         = zcl_excel_style_cond=>c_rule_cellis.
  ls_cellis-formula           = '"C"'.
  ls_cellis-operator          = zcl_excel_style_cond=>c_operator_beginswith.
  ```
- Run the program and display the result → this error:
  &nbsp;
![image](https://user-images.githubusercontent.com/34005250/127751411-8b8d2abb-508d-4b80-a9c3-e37863a44632.png)

Analysis of Excel file contents:
- What is currently generated by abap2xlsx
  in `sheet1.xml`:
![image](https://user-images.githubusercontent.com/34005250/127751274-9e2f28c2-da08-4bee-aea6-a7762b8fcfb8.png)
  in `styles.xml` 
![image](https://user-images.githubusercontent.com/34005250/127751358-7dbfd221-6d39-46a8-ad70-9cd8ee50e07b.png)
- What Excel generates when the condition is created manually:
  &nbsp; 
![image](https://user-images.githubusercontent.com/34005250/127751459-39e50067-71f1-4b97-b8bb-418b06090f66.png)
- This also works:
  &nbsp;
![image](https://user-images.githubusercontent.com/34005250/127751235-284732ff-7c7a-464f-97f7-ce0c2fb36643.png)

Further analysis to be done:
- There is also an issue with c_rule_containstext and c_operator_containstext, that doesn't work. I feel there are more issues → check all other possible types of conditions (ends with, contains, free formula, etc.)
- See if it's possible to make it simple for the developer to choose between "rule" and "operator" → one demo program with all conditional formatting possible? (currently too many demo programs according to me: existing test programs: zdemo_excel27 for cell equal to value ; zdemo_excel5 and zdemo_excel10 for icon set ; zdemo_excel7 for icon set, databar, color scale ; zdemo_teched8 for cell equal or greater than value -- and zdemo_teched9 is the same)
- test to be done with condition applying on several cells

**Comment by AndreaBorgia-Abo** [comment]
PR has been merged, out of an abundance of caution I have rechecked with a modified ZDEMO_EXCEL27 and it works as expected. Closing now, thank you @hardyp and @sandraros .
