### ISSUE TITLE
Highest row calculated incorrectly

### ISSUE THREAD

**Issue by striezl** [abap2xlsx/abap2xlsx#787]
Hi, 

the method `ZCL_EXCEL_WORKSHEET->get_table()` returns rows in the exporting parameter `et_table` which are empty in the input Excel worksheet except from formatting. 

In the screenshot you can see that the excel file contains only one row with actual data, but et_table returns 9 rows (the first line is skipped according to parameter` iv_skipped_rows = 1`).

![Bug](https://user-images.githubusercontent.com/3652530/128174749-42fc6526-4c0f-49a4-a37e-160ef4b058e6.PNG)

Especially in connection with the issue https://github.com/sapmentors/abap2xlsx/issues/703 regarding wrong initial date values (18991231 instead of empty) this is a problem, because empty rows are not initial and can therefore not be deleted easily from the internal table.

I saw in the debugger that the attribute `LOWER_CELL-CELL_ROW` of the class `ZCL_EXCEL_WORKSHEET` was set incorrectly (actual value 10, expected 2).

![Bug3](https://user-images.githubusercontent.com/3652530/128175121-df6c0629-fcb2-4e08-80b4-222c2f50515c.PNG)

This is an expample file with formatted but empty cells:

[Empty2.xlsx](https://github.com/sapmentors/abap2xlsx/files/6930915/Empty2.xlsx)

Thanks!

Kind regards
Bernhard

**Comment by sandraros** [comment]
Thank you for posting this issue.
Concerning #703 I have proposed a fix. As soon as it's accepted and merged, it will simplify your task a lot to get rid of the extra initial lines.

About the number of rows returned, abap2xlsx returns the rows that Excel itself is proposing. I'm not fan of changing it.

Instead, I would opt for deleting the initial lines at the end of GET_TABLE. I feel that determining which values are initial should be based on the target internal table (ET_TABLE), and that deleting the last initial lines could break something in existing applications, so I would opt for adding a parameter to activate this feature.

Please tell me your opinion. (@AndreaBorgia-Abo fyi)

**Comment by sandraros** [comment]
@striezl Hi. The fix for #703 has been merged into the master branch. You can now easily delete the empty lines, until a enhancement is done for GET_TABLE to delete the last empty lines. Your opinion is appreciated. Thanks! @AndreaBorgia-Abo Thanks for reviewing and merging!

**Comment by AndreaBorgia-Abo** [comment]
"Internal table has less columns than excel", when reading "Empty2.xlsx" above... but that's me being dense, the demo program does indeed say the structure should match the input ;)
