### ISSUE TITLE
ABAP2XLSX - Reading Spreadsheet with existing charts

### ISSUE THREAD

**Issue by rwilson2021** [abap2xlsx/abap2xlsx#790]
I am using ABAP2XLSX to read an existing spreadsheet. The existing charts that are defined in this spreadsheet appear to get lost when I do this. 

I tested this with ZDEMO_EXCEL37. The source spreadsheet I read had existing charts. It is attached.  In the new spreadsheet that is created after I run the transaction, the charts are no longer there.

[VGV_UTILIZATION_81321.xlsx](https://github.com/sapmentors/abap2xlsx/files/7008490/VGV_UTILIZATION_81321.xlsx)

**Comment by sandraros** [comment]
@rwilson2021 Thank you for posting this issue. I tried to reproduce with `ZDEMO_EXCEL37` but I get the below error message (popup + list of messages). Could you confirm?
```
Error reading excelfile
Errormessage: An exception with the type CX_SY_REF_IS_INITIAL was raised, but was not handled locally or declared in a RAISING clause.
Errorposition:
         Program: ZCL_EXCEL_READER_2007=========CP
         include_name: ZCL_EXCEL_READER_2007=========CM003
         source_line:          1
```
If that's it, I think I can quickly do a fix.
Thank you for your confirmation.

**Comment by sandraros** [comment]
Steps to reproduce the bug:
1. Run the program `ZDEMO_EXCEL39` and save the file on the frontend. Open this file and you see this:
   ![image](https://user-images.githubusercontent.com/34005250/145111913-4d73da52-748e-4699-b91a-8519a2a8e5e1.png)
2. Run the program `ZDEMO_EXCEL37` to read and display the file above (using `ZCL_EXCEL_READER_2007`), this produces:
   ![image](https://user-images.githubusercontent.com/34005250/145111972-4a6837bb-9cf0-4b6c-aee3-6c184c2df1a2.png)

**Comment by sandraros** [comment]
@rwilson2021 Could you check if the proposed PR solves the issue? Thank you.
