### ISSUE TITLE
Page Breaks:  Is it possible to have only 1 page break for the whole work sheet?

### ISSUE THREAD

**Issue by ZhaoHongtao0** [abap2xlsx/abap2xlsx#791]
Hello Friends,

  We are now using this excellent tool to export excel file in our project. Thank you guys for this great tool.

  We are facing a problem here: the exported excel file will have default page break settings, for example, it will divided into  4 pages  automatically once exported. 
  But we want it have only 1 page, not 4. So I tried to work with class [ZCL_EXCEL_WORKSHEET_PAGEBREAKS], which can get from method [GET_PAGEBREAKS] of class [ZCL_EXCEL_WORKSHEET]. Unfortunately, seems this method can only insert new page breaks to the existing page breaks, it cannot merge all pages into 1, or delete existing breaks then create a new one.
  I also tried to add a new method to class [ZCL_EXCEL_WORKSHEET_PAGEBREAKS], which will delete all page breaks in table [MT_PAGEBREAKS], and insert only 1 page break into it. Still, not working....
  
  Really appreciated if you experts can help me out here, Thank you so much in advance.

Hongtao Zhao

**Comment by sandraros** [comment]
Thank you for your kind words.
In Excel, the page breaks are only defined by the paper/printer to which you print (or do a print preview), and you can only set explicit page breaks, nothing more.
abap2xlsx cannot do more than what Excel does.
Could you clarify if you can do it in Excel alone, how, and if yes could you provide an example?
I will then be able to look at it in abap2xlsx.
Thank you.

**Comment by ZhaoHongtao0** [comment]
> Thank you for your kind words.
> In Excel, the page breaks are only defined by the paper/printer to which you print (or do a print preview), and you can only set explicit page breaks, nothing more.
> abap2xlsx cannot do more than what Excel does.
> Could you clarify if you can do it in Excel alone, how, and if yes could you provide an example?
> I will then be able to look at it in abap2xlsx.
> Thank you.

Thank you so much for your reply.

i attached a file which has screen shots in it, show how to make it have only 1 page. 
bascialy, its done in page setup when we print, or we drag the page break lines manually use mouse.

Not sure whether this can be done in our abap2xlsx or not....   Thank you again.

[make to only 1 page.xlsx](https://github.com/sapmentors/abap2xlsx/files/7150634/make.to.only.1.page.xlsx)

**Comment by sandraros** [comment]
Thanks, got it! I think you can use the below code (2 lines containing `lo_worksheet->sheet_setup`). It it's correct and that solves the issue, you can close it, but if not please let's keep discussing.
```
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'Issue_791.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  SELECT * FROM sflight INTO TABLE @DATA(sflight).
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_table(
    EXPORTING
      ip_table       = sflight
      ip_table_title = '' ).
  lo_worksheet->sheet_setup->fit_to_page = abap_true.
  lo_worksheet->sheet_setup->fit_to_width = 1.
  lcl_output=>output( cl_excel = lo_excel ).
```

**Comment by ZhaoHongtao0** [comment]
> Thanks, got it! I think you can use the below code (2 lines containing `lo_worksheet->sheet_setup`). It it's correct and that solves the issue, you can close it, but if not please let's keep discussing.


THANK YOU SO MUCH!! It works! Really appreciated your help. Issue closed.
