### ISSUE TITLE
Popup "File '/usr/NPL/lokal/temp/001/25_HelloWorld.xlsx' could not be opened" of ZDEMO_EXCEL and ZDEMO_EXCEL25

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#823]
Run ZDEMO_EXCEL25 or ZDEMO_EXCEL. This popup is shown:
![image](https://user-images.githubusercontent.com/34005250/135758230-c79f7684-cd0d-4216-9e1b-eefb97cf3ff0.png)

> Information The file '/usr/NPL/lokal/temp/001/25_HelloWorld.xlsx' is not open

What does it mean?

EDIT: or more recently after PR:
![image](https://user-images.githubusercontent.com/34005250/137619218-37781c6e-4234-40ff-880a-bd4a094f0604.png)

**Comment by AndreaBorgia-Abo** [comment]
With ZDEMO_EXCEL25 I get no such warning, odd. Anyway, in my demo environment the FILE entry for LOCAL_TEMPORARY_FILES points to /tmp and that's where the file lands, using either SAPGUI Java 7.70rev3 or Windows 7.70pl3fix2

With ZDEMO_EXCEL with the Java GUI the program defaults to /tmp/andrea/SAPGUI/NPL.2fd637a/work as directory and I get the ludicrous message that's clearly out of place
![image](https://user-images.githubusercontent.com/25269970/136535755-8e1123b4-ab99-4119-944f-a3a3b866e592.png)
then it goes on to dump in ZEXCEL_DEMO28 with RAISE UNKNOWN_DP_ERROR, not unexpected, there is no feature parity between the different GUI versions. If I run it from the Windows version, it just works, the whole set of demos I mean.

**Comment by sandraros** [comment]
@AndreaBorgia-Abo @bigld 
- In my 7.52 SP01 Developer Edition, the logical path `LOCAL_TEMPORARY_FILES` points to `/usr/<SYSID>/lokal/temp/<MANDT>/<FILENAME>`, that's why... And `zdemo_excel` calls `zdemo_excel25` (NB: I don't understand what is the benefit; I think the goal of `zdemo_excel` is to generate all Excel files to demonstrate all abap2xlsx features, no good reason to create an Excel file "Hello world", as it's already done by `zdemo_excel1`)
- I find it a little bit harsh to not have this logical path as a modifiable parameter.
- Anyway, what is the interest of this demo program, to show how Logical File/Path works? I don't think it's the goal of a demo program to demonstrate something unrelated to abap2xlsx.
- Maybe we could give another meaning to this little demo program to demonstrate how easy it is to create an abap2xlsx file to the frontend or to the application server, because maybe people are not experienced enough to debug how `zdemo_excel_outputopt_incl` works? (and of course, without logical path, no interest)
- Moreover, we could adapt `zdemo_excel` to not call `zdemo_excel25` anymore?
What do you think?

**Comment by sandraros** [comment]
I think we should reopen the issue. The problem is still here for me. See previous comments.

NB: after the PR, I now have this popup:
![image](https://user-images.githubusercontent.com/34005250/137619218-37781c6e-4234-40ff-880a-bd4a094f0604.png)

```
Information 

File '/usr/NPL/lokal/temp/001/25_HelloWorld.xlsx' 
could not be opened; operating system error: 0 
(Cannot create or open file - Check Tx FILE 
Logical Path 'LOCAL _ TEMPORARY_FILES' )
```
