### ISSUE TITLE
ABAP 1909 Developer Trial - Import of Online/Offline Git Zip fails with Activation Errors

### ISSUE THREAD

**Issue by peterli-code** [abap2xlsx/abap2xlsx#827]
Hello

New here. Tried to install the abap2xlsx package in either online or offline mode using ZABAPGIT program within abap 1909  platform but keep getting activation errors in particular with importing the dictionary table types (and structures do not import at all) . Has anyone noticed this problem before? If so, please suggest solution/workaround.  If you need more info please let me know. 

Thanks in advance

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/issues/5001 ?

**Comment by larshp** [comment]
are you running the latest abapGit?

**Comment by peterli-code** [comment]
Hi Lars
I ran the version which came with the ABAP trial installation (c. June 2021) . Is there a link for the latest version that I can try with? Thanks.
Regards 
    On Tuesday, 5 October 2021, 13:54:21 BST, Lars Hvam ***@***.***> wrote:  
 
 


are you running the latest abapGit?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by larshp** [comment]
see https://docs.abapgit.org

**Comment by peterli-code** [comment]
Thanks I will try this and update if succesful with latest version. 
Regards
    On Tuesday, 5 October 2021, 15:31:12 BST, Lars Hvam ***@***.***> wrote:  
 
 


see https://docs.abapgit.org

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by peterli-code** [comment]
Hi Lars

I finally got round to running with latest abagit version from your link and behold I did get further with the missing structures etc, Seems that the latest abapgit has done some magic and the problem is resolved. Now I need to run upload another package to see if it will work wonders again there. So thanks for the tip. 

I would advise others to do the same and save time in working out where things have gone wrong when installing Z packages.

I am a bit surprised that the abagit which came with the 1909 was not able to do this. Big thanks and keep up the good work.

PS Please close issue in case it is not as I am not that familiar with the process. Ta.

Kind regards
Peter

**Comment by larshp** [comment]
abapGit evolves, https://github.com/abapGit/abapGit/blob/main/changelog.txt

I dont know which version is delivered with ABAP Platform, Developer Edition 1909
