### ISSUE TITLE
Feature request for Ignored Errors

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#836]
In Excel, there is a feature to ignore the "errors" (can also be warnings). Currently, this feature doesn't exist in abap2xlsx. Is it possible to add it? It's quite a minor feature, essentially aesthetic.

# Example 1
```
CONSTANTS gc_save_file_name TYPE string VALUE 'issue-836.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  SELECT carrid, connid, fldate, bookid FROM sbook UP TO 3 ROWS
  INTO TABLE @DATA(gt_sbook).
  TRY.
      DATA(excel) = NEW zcl_excel( ).
      DATA(worksheet) = excel->get_active_worksheet( ).
      worksheet->bind_table( ip_table = gt_sbook ).
      lcl_output=>output( excel ).
    CATCH cx_root INTO DATA(lx).
      MESSAGE lx TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
```
- Result of the program above:
  ![image](https://user-images.githubusercontent.com/34005250/136442300-7cd665cd-9776-43bc-99e0-7f434c96499a.png)
- Manual fix:
  ![image](https://user-images.githubusercontent.com/34005250/136442473-dc6a1d6c-6fc2-42c6-92f8-52cb086180ae.png)
- Expected result (what we should be able to do with abap2xlsx):
  ![image](https://user-images.githubusercontent.com/34005250/136442441-c9148bf5-8e0e-425c-9791-7f3ec4b834fb.png)
 
# Example 2
See [file attached](https://github.com/sapmentors/abap2xlsx/files/7305277/abap2xlsx_ignored_errors.xlsx) (NB: the error indicator may happen in many other situations):
- Create this worksheet containing a Table, with Column2 containing formula `=[@Column1]`, and force a text in cell `B4`, it then shows an error indicator, see here:
  ![image](https://user-images.githubusercontent.com/34005250/136421029-eaefdc98-15ca-4736-b560-7cda0ad3e9e3.png)
- Click the "`!` losange" icon, and choose "Ignore Error":
  ![image](https://user-images.githubusercontent.com/34005250/136421740-ba06879c-21e7-411c-a79e-675c56129151.png)
- It's not shown any more as an error:
  ![image](https://user-images.githubusercontent.com/34005250/136421802-4e69d87b-c9ee-4f64-b2c7-0933cf28d39e.png)

NB: this issue is created to simplify the solution provided in #734 which is about adding the Excel feature "Calculated Columns".

**Comment by sandraros** [comment]
Minimal code to demonstrate the feature (see also in program `ZDEMO_EXCEL3`):
```
CONSTANTS gc_save_file_name TYPE string VALUE 'issue-836.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  SELECT carrid, connid, fldate, bookid FROM sbook UP TO 3 ROWS
  INTO TABLE @DATA(gt_sbook).
  TRY.
      DATA(excel) = NEW zcl_excel( ).
      DATA(worksheet) = excel->get_active_worksheet( ).
      worksheet->bind_table( ip_table = gt_sbook ).
      worksheet->set_ignored_errors( VALUE #( ( cell_coords = 'B2:B4' number_stored_as_text = abap_true )
                                              ( cell_coords = 'D2:D4' number_stored_as_text = abap_true ) ) ).
      lcl_output=>output( excel ).
    CATCH cx_root INTO DATA(lx).
      MESSAGE lx TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
```

**Comment by AndreaBorgia-Abo** [comment]
Using code from Example1 or the file attached in Example2 with Libreoffice I cannot get any errors even with the current master. I will have to try again using the company laptop, middle of next week.

**Comment by AndreaBorgia-Abo** [comment]
Please ignore the revert commit above: issue is indeed fixed.
