### ISSUE TITLE
split unit tests into one method per case

### ISSUE THREAD

**Issue by larshp** [abap2xlsx/abap2xlsx#859]
the unit test method in https://github.com/sapmentors/abap2xlsx/blob/master/src/zcl_excel_common.clas.testclasses.abap contains 26 different testcases

suggest splitting into 26 different methods, so each case becomes more visible

**Comment by larshp** [comment]
- method `shift_formula` contains 26 cases ( #886 )
- method `convert_column2int` contains 4 cases ( #864 )
- method `is_cell_in_range` contains 6 cases ( #865 )
- method `calculate_cell_distance` contains 10 cases ( #871 )
- method `convert_column2alpha` contains 4 cases ( #892 )
- method `excel_string_to_date` contains 9 cases
- method `split_file` contains 2 cases
- method `convert_range2column_a_row` contains 7 cases
- method `macro_calculate_cell_distance` contains 2 cases

**Comment by AndreaBorgia-Abo** [comment]
@larshp I have checked the other test cases and edited the summary above, I'd like to know if, in your opinion, those other tests should also be split.

**Comment by larshp** [comment]
good for now, closing, thanks
