### ISSUE TITLE
Demo reports in production

### ISSUE THREAD

**Issue by d-schaaf** [abap2xlsx/abap2xlsx#861]
Hi, most or all of the demo reports are flagged as "test program" in their attributes. Normally we do not need or even want demo reports in productive systems. However, whenever we upgrade to a newer version changed demo reports are added to the transport. Of course we can delete these reports all the time from the transport but this is time consuming.
What are others thinking about demo reports. Are they needed in production (so only we have this issue) or do you have the same issue like we have?
Or is there an easy way to get rid of them in production that we don't know?

**Comment by sandraros** [comment]
When you create your transport request to move the abap2xlsx programs in production, you have to choose which objects to embed. The easiest solution I know is to use `SE80`, select the abap2xlsx package(s) (currently, there are 3 packages including one for the demos) and in the context menu choose to add all its contained objects to the transport request. You can do it for all abap2xlsx packages except the package containing the demo programs, abap2xlsx classes can work without the demonstration programs.

**Comment by d-schaaf** [comment]
Hi, yes, this is what we are doing manually all the time ;-) Additionally we need to clear the original transport that is used by the git client while the objects are imported.
But maybe this is more a feature request of the git client itself: New setting so that users can decide if test programs are written into the transport or not.

**Comment by larshp** [comment]
objects in transported packages should be transported, and if there is no open transports, personally I assume the object is identical to production

demo reports should IMHO be optional to install, the easy solution is to move them to a separate repository

for long term: I envision the demo reports to run in the browser, ABAP code on the left side, the excel file being shown on the right side. Changing the ABAP code in the lefthand editor will update the preview immediately. This way, the demo reports will typically not be required in any customer systems.

**Comment by d-schaaf** [comment]
Cool vision however a separate repository would solve our issue 👍

**Comment by larshp** [comment]
fyi, I have now squatted organization https://github.com/abap2xlsx

my _suggestion_ would be to have something like, long term,
* https://github.com/abap2xlsx/abap2xlsx the actual source
* https://github.com/abap2xlsx/demos demo programs
* https://github.com/abap2xlsx/old the old stuff from the various root folders
* https://github.com/abap2xlsx/api auto generated webpage describing api, something like https://devdocs.io
* https://github.com/abap2xlsx/web webpage to host/run demo programs

note, we can setup [static analysi](https://abaplint.org)s to work across both the demo and source code repos

@gregorwolf any thoughts on moving the abap2xlsx stuff to the abap2xlsx organization?

**Comment by gregorwolf** [comment]
I think it's a good step to give abap2xlsx it's own organization.

**Comment by larshp** [comment]
@sandraros @AndreaBorgia-Abo any thoughts on moving abap2xlsx to the abap2xlsx organization?

note: old links and all will still work, we did not have any problems when abapGit was moved to the abapGit organization

**Comment by AndreaBorgia-Abo** [comment]
@larshp I'm not (yet) able to fully appreciate the advantages of a dedicated organization but I have nothing against it. What I totally support, though, is splitting the project in dedicated repos to keep demos as local objects in the development system and only transport the library itself. If a dedicated org is needed or even simply helps to achieve this goal, then count me as totally in favour :)

**Comment by sandraros** [comment]
No clear idea, but basically nothing against it too. Proposing to setup APACK and versions to make a link between demos and abap2xlsx. In abapGit, is it possible to facilitate a "bundle" of repositories (abap2xlsx and demos especially) so that newbies can easily download the repositories at once? (APACK currently says that there's a missing repository or too old version, but there's no unique UI to enter once all packages, descriptions (etc.), as far as I know, i.e. it requires to install the two repositories separately)

**Comment by larshp** [comment]
side effect: the url of https://sapmentors.github.io/abap2xlsx/ will change

**Comment by larshp** [comment]
moved

**Comment by sandraros** [comment]
Could we close this issue now that demo programs have been moved to [abap2xlsx/demos](https://github.com/abap2xlsx/demos)? Thanks!
