### ISSUE TITLE
Set up a Change Log for abap2xlsx

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#885]
Proposing to create a [`changelog.txt`](https://docs.abapgit.org/development/guide-changelog.html) file to display the latest changes of abap2xlsx when pulling the repository with abapGit.

Request from:
- @larshp (https://github.com/sapmentors/abap2xlsx/issues/720#issuecomment-757140976)
  > perhaps its time to keep some kind of changelog, https://docs.abapgit.org/development/guide-changelog.html
- @AndreaBorgia-Abo (https://github.com/sapmentors/abap2xlsx/pull/869#issuecomment-962605526)
  > this might be the right time to start a BREAKINGCHANGES file or something to that effect

@AndreaBorgia-Abo @larshp @gregorwolf Any idea which version number should be first used? 

One solution to get the first number is to take the [official release of abap2xlsx in July 12, 2010](https://blogs.sap.com/2010/07/12/abap2xlsx-generate-your-professional-excel-spreadsheet-from-abap/) as being version 1.0.0, we could count the number of months, Nov 12, 2021 would be 136 months after 1.0. So, version **1.136.0**?

After that we could release a new version at each beginning of month, as far as possible...

**Comment by AndreaBorgia-Abo** [comment]
No idea but we already have a version 7.1.0 :)
Another option would be a date-based version number, for example 2021.11.12 and 2010.07.12

**Comment by AlexandreHT** [comment]
From a user/consumer point of view, the most convenient would be [GitHub release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)  with [Semantic versioning ](https://semver.org/) :
- I can pick up a release or the _nightly build_
- i can subscribe to release notifications only (and avoid PR/Issue notifications)
- Version number indicates whether I should expected compatibility breaks

**Comment by sandraros** [comment]
List of all abap2xlsx versions in `ZCL_EXCEL` since it was moved to GitHub:
- `7.0.6` ([initial version in GitHub, 5 years ago](https://github.com/sapmentors/abap2xlsx/commit/f8b0e354dbccfb92dcc308558b6a7ce215058ff8)):
 https://github.com/sapmentors/abap2xlsx/blob/74c1a543cd86e8e4703cceb3f595b474b196c18e/src/zcl_excel.clas.abap#L154
- `7.2.0` (changed [12 months ago, Nov 10th, 2020](https://github.com/sapmentors/abap2xlsx/commit/1c276c6027e91fa3ba388c33ca617498342b091c)):
https://github.com/sapmentors/abap2xlsx/blob/74345edd326e221736684787e8622bd657d2a2a0/src/zcl_excel.clas.abap#L159

NB: the version is stored in the "Comments" of the generated workbook:
![image](https://user-images.githubusercontent.com/34005250/140656092-7ded2d88-2be8-4e8e-b173-df26373155ca.png)

**Comment by sandraros** [comment]
@AndreaBorgia-Abo If we stick to [semantic versioning](https://semver.org/), the version is to be MAJOR.MINOR.PATCH, major should be +1 if we do an incompatible API change, so using the year is maybe not a good idea if we have to do an incompatible change. Why not starting from `7.14.0` then, 12 months after `7.2.0`, assuming we had one new functionality per month?

@AlexandreHT Thanks. I have absolutely no experience with GitHub releases. It seems to me that the abapGit solution is very simple to handle, I like to see the change log in abapGit without going to GitHub, e.g.:
![image](https://user-images.githubusercontent.com/34005250/140657819-5616c0ce-296c-499d-8283-7df33b831a29.png)

**Comment by AlexandreHT** [comment]
The abapGit solution seems nice but I’m restricted to offline repo.

**Comment by sandraros** [comment]
@gregorwolf @larshp I'd like your approval (you as abap2xlsx owners) for version number `7.14.0`. Do you agree? See log proposal in PR. Thank you. @AndreaBorgia-Abo fyi

After agreeing, as @AlexandreHT said, we should also create a GitHub Release with same number. Currently:
![image](https://user-images.githubusercontent.com/34005250/141695089-b5e8a36a-d1f6-4b70-8034-fcf41ae13616.png)

**Comment by gregorwolf** [comment]
If there are no breaking I agree.

**Comment by sandraros** [comment]
Thanks, so let's start "Version Management" and "Change Log" !
