### ISSUE TITLE
creating right to left spreadsheets

### ISSUE THREAD

**Issue by yuval74** [abap2xlsx/abap2xlsx#890]
hi 
is there a parameter/attribute to use in order to create a right to left oriented spreadsheets?
Tnx
Yuval

**Comment by sandraros** [comment]
I never saw that in abap2xlsx, but I'm far from having seen everything. Could you post a sample Excel file with Right-To-Left writing so that I can have a look at it, please? Thank you.

**Comment by yuval74** [comment]
hi
the issue is with right to left option of the worksheet.
with right to left languages its more convenient to work that way.
i added  a screenshot and xlxs file for the example
Thanks
yuval 

![screen](https://user-images.githubusercontent.com/94438654/142145621-d3fe4313-4ea5-4644-8949-993ab65f3a92.png)
[right to left sheet.xlsx](https://github.com/sapmentors/abap2xlsx/files/7552245/right.to.left.sheet.xlsx)

**Comment by sandraros** [comment]
Thank you very much. I confirm this feature doesn't exist in abap2xlsx yet, but it could be very quick to do.

If it's possible for you to do a fix, you could fork the project and do a pull request.

The `rightToLeft` option is to be set to `1` in the `<sheetnumber>.xml` file:
![image](https://user-images.githubusercontent.com/34005250/142682586-2df82fc8-9ed6-491a-9245-aff836cdcdb1.png)

**Comment by yuval74** [comment]
work like a charm
tnx

**Comment by sandraros** [comment]
Good to know. I propose to keep the issue open, so that you or someone else can propose a fix.

**Comment by sandraros** [comment]
Test program of proposed PR:
```abap
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'issue_890.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
PARAMETERS rtl AS CHECKBOX DEFAULT abap_true.
PARAMETERS ltr AS CHECKBOX.
PARAMETERS huge AS CHECKBOX.

START-OF-SELECTION.
  SELECT * FROM scarr INTO TABLE @DATA(scarr_lines).
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->bind_table(
      ip_table          = scarr_lines
      is_table_settings = VALUE zexcel_s_table_settings( top_left_column = 'B' top_left_row = 2 ) ).
  IF rtl = abap_true.
    lo_worksheet->zif_excel_sheet_properties~set_right_to_left( abap_true ).
  ENDIF.
  IF ltr = abap_true.
    lo_worksheet->zif_excel_sheet_properties~set_right_to_left( abap_false ).
  ENDIF.
  lcl_output=>output( cl_excel = lo_excel iv_writerclass_name = COND seoclsname( 
      WHEN huge = '' THEN 'ZCL_EXCEL_WRITER_2007' ELSE 'ZCL_EXCEL_WRITER_HUGE_FILE' ) ).
```

**Comment by GauravKulkarni24** [comment]
Hi,
how can we set only specific cells right_to_left instead of Whole worksheet. Manually we can set it in excel but in abap2xlsx I couldn't find it.
any inputs please.

**Comment by sandraros** [comment]
@GauravKulkarni24 Please open a new issue. In this question, could you provide an Excel example of what you expect? Thank you.
