### ISSUE TITLE
Program to help analyzing bugs and developing new features in abap2xlsx

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#891]
With the below ABAP program (see next comment), and VSCode installed on your laptop, it's possible in a few clicks to directly see how an Excel feature is encoded in the `.xlsx` file.

Example to see how the feature "Sheet Right-To-Left" is encoded in the `.xlsx` file, with legend below for each step:
![image](https://user-images.githubusercontent.com/34005250/142683610-bf540a3f-38c2-4a28-8515-8e2deac1e518.png)

0. Run the ABAP program → Screen with Excel file is shown
1. Do any change in the workbook (here: "right to left")
2. Click "Compare" → Tree of modified files is shown on the right
   - Yellow: changed
   - Green: added
   - Red: deleted
   - No color: unchanged 
3. Click one of the changed files you want to see (here: `sheet1.xml`) → VSCode is started and shows the diff immediately.

If you find this program useful, how can we share it, and possibly store it in the abap2xlsx repository so that it can be maintained the same way as the rest of abap2xlsx?

Thank you!

**Comment by sandraros** [comment]
Code of ABAP program described in previous comment:
[xlsx_diff_program_issue_891.txt](https://github.com/sapmentors/abap2xlsx/files/7612065/xlsx_diff_program_issue_891.txt)

**Comment by AndreaBorgia-Abo** [comment]
I absolutely adore the concept of this program and I fully support the idea of adding this tool to the repository, perhaps under "not_cloud". Some random thoughts after a few minutes playtime:

- VSC in the lower portion of the screen: I assume you simply resized the respective windows and stacked them on top of each other, right? I kind of assumed it would fit in the SAPGUI container but is that at all doable?
- the handler presently reacts to changed (yellow) files only but I believe it might be useful to see the files also before any changes are made, so green ones, too. I bypassed the diff check and apparently nothing broke.
- thinking out loud: would it be possible, and would it make sense, to close the loop by editing the "new" xml to check if Excel likes the change we have in mind?

Once again, I'm impressed!

**Comment by sandraros** [comment]
1. I don't think it's possible. Maybe with a lightweight HTML/JavaScript diff tool instead, whose diff would be done exclusively inside the user's Web browser. No idea what exists. Version 1 would be with VS Code displayed out of SAP GUI.
2. Sure, good idea.
3. Good idea. Not sure how to do it.

**Comment by sandraros** [comment]
As already discussed elsewhere, I created a separate tool, [zip-diff](https://github.com/sandraros/zip-diff), which evolves separately. #940 introduced `zdemo_excel_checker` program whose button "compare" calls zip-diff if it's installed, and displays "Viewer error (https://github.com/sandraros/zip-diff): ..." if not.

The 3 previous points can be discussed at https://github.com/sandraros/zip-diff:
1. https://github.com/sandraros/zip-diff/issues/9
2. https://github.com/sandraros/zip-diff/issues/10
3. https://github.com/sandraros/zip-diff/issues/11

So, closing this issue.
