### ISSUE TITLE
Reader considers that a number is a text

### ISSUE THREAD

**Issue by tr4pt** [abap2xlsx/abap2xlsx#903]
Hi guys,

just a question cuz I've searched for solutions and haven't found one.

When I'm reading worksheet content

        DATA(o_reader) = CAST zif_excel_reader( NEW zcl_excel_reader_2007( ) ).
        DATA(o_excel) = o_reader->load_file( filename ).

        o_excel->set_active_sheet_index( o_excel->get_active_sheet_index( ) ).
        DATA(o_worksheet) = o_excel->get_active_worksheet( ).

        LOOP AT o_worksheet->sheet_content ASSIGNING FIELD-SYMBOL(<cell>) GROUP BY <cell>-cell_row ASSIGNING FIELD- 
        SYMBOL(<row>).
        ....
        
        ENDLOOP.

when reading an amount which is in format xxxx,xx it's automatically converted to xxxx.xx in the sheet_content. data_format is blank/empty
But when reading an amount in the same column in format xxxx,xx- it's not converted to xxxx.xx-. It stays the same. data_format is 's'.

Does anybody have a solution for this issue? 

Best regards

**Comment by sandraros** [comment]
I think the way `xxxx,xx-` has been stored in your file, made Excel consider it's not a number, but only a text. Could you share your Excel file so that we may have a look at it, to confirm? Thank you.

**Comment by tr4pt** [comment]
Hi sandraros,

thanks for your reply. Here's the file. 

[Excel file to read in.xlsx](https://github.com/sapmentors/abap2xlsx/files/7666108/Excel.file.to.read.in.xlsx)

**Comment by sandraros** [comment]
Thank you. I confirm they are not defined as numbers (by adding zero, it returns an error for negative numbers), so it's normal that abap2xlsx returns these "numbers" as texts:
![image](https://user-images.githubusercontent.com/34005250/144981892-0d0a2c06-aab3-4964-8724-58d877ffd237.png)

**Comment by tr4pt** [comment]
Yeah, that is correct. They are probably just copy & pasted out of the system, but anyway I have to read them in and post them.
As this file is created by the enduser and the enduser will call my program to read this file into the system, I have to get the right amount.

The issue is that right now, these common numbers can be interpreted like numbers, even if the cell is not formatted.
The negative ones can not be interpreted. 

I was just thinking if the cell number_format can always be the same? Like if they are just entered and not formatted, that they can be interpreted as text/string?

**Comment by sandraros** [comment]
I think the best solution is to educate the users to be responsible of providing data in the right format. If you, as a developer, interprets those information according to rules known by only you, you will be responsible of any issue. You'd better send a clear error message to the user.

Concerning the component `data_format` in `sheet_content`, the value "`s`" means a string.

**Comment by tr4pt** [comment]
Alright, thank you. 
I'll try to educate them :).

Thanks for your help. This issue can be closed
