### ISSUE TITLE
Pulled ABAP2XLSX but not working in Dev TRIAL ABAP1909

### ISSUE THREAD

**Issue by ojnc** [abap2xlsx/abap2xlsx#907]
[LOG1.txt](https://github.com/sapmentors/abap2xlsx/files/7676117/LOG1.txt)
[LOG2.txt](https://github.com/sapmentors/abap2xlsx/files/7676118/LOG2.txt)  **IMPORTANT ONE**

A lot of errors came initially as perhaps  Field name ROW is reserved (see LOG1)

LOG2 I think may be the last mile for success 
The  following do not exist
ZEXCEL_S_WORKSHEET_COLUMNDIME  and ZEXCEL_T_WORKSHEET_ROWDIMENSIO

I searched and found 
[Link with above text](https://github.com/sapmentors/abap2xlsx/blob/a9be231d99291760edf9164aad1be31c4b9f6def/docs/SAPLink-installation.md)

It may be as my initial scare with errors and being new to **abapgit** that I installed zsaplink and tried to install old version
This may have messed up

I deleted package $ABAPXLSX and sub-packages and tried pull again but no success.

Please suggest ways of wiping clean and re-fetching abap2xlsx via abapgit

Looking forward to your help

**Comment by ojnc** [comment]
**NOW ABAP2XLSX Working perfectly installed with ABAPGIT**.
I attended LIVE the magical 30 minute ABAPGIT presentation 
16:00 abapGit for Beginners Speaker Marc Bernard English
[AbapConf2021](https://wiki.scn.sap.com/wiki/display/events/ABAPConf+2021)
[Live Stream 1 4pm](https://www.abapconf.org/#/agenda/channel1) 


_Glad I did not give up and now have 100% faith in_ 
_BOTH Abap2XLSX and esp. ABAPGIT_

**Comment by mbtools** [comment]
I'm happy you liked my session, @ojnc!

abap2xlsx is a quite substantial repo with lots of DDIC dependencies. Even one small issue can lead to many inactive objects. If you're stuck with something like this again, feel free to open an issue in the abapGit repo or join our slack channel at
https://abapgit-slackinviter.herokuapp.com/

**Comment by mbtools** [comment]
FYI, I just did a fresh pull into a 7.5 system using AG 1.113.0 and it worked without any problems.

**Comment by ojnc** [comment]
_Thanks a lot!_
I worked in SAP 2004 to 2014(age 53-Age63)
Then after a long break of dabbling with too  many things decided to try my luck with SAP ABAP @70 age!

Realized AbapGit has great future but as I could not install ABAP2XLSX made cardinal mistake of trying ZSAPLINK.
I must have uninstalled and installed at least 6 times and still persisted.
God of Internet sent me a invite to ABAPConf2021 and I decided to attend your session 8:30pm IST
After the session I saw the remnants of my diversion!

**Suggestion**: After Pull ABAPGIT may give a warning - :you have pre-existing ABAP objects with names clashing first time and in other packages".

Justified for 2 cases
a) Very first  pull
b) if clashing objects belong to "other" packages

In ReactJS Angular+ we clone to a directory;  so no chance of clashes
But in ABAP,  package is nearest to a OS directory

Bulletproof solution may be to generate unique names by unique id appending or same namespace 

Thanks again for reaching out to old man in Kolkata!

**Comment by mbtools** [comment]
You are the best. abapGit for everyone! 

There's no general way to determine if pre-existing objects are "left by accident" or some development that you might want to push to the remote repo. At least with abapGit, you clearly see what's there. 

One trick is to create the online repo and if you see only local objects you don't want anymore, uninstall the repo. This will delete all old objects. Then clone again and pull. 

The renaming is on Lars' agenda (https://blogs.sap.com/2021/04/20/automagic-standalone-renaming-of-abap-objects/). It's working already pretty well and I'm using it to mirror 3 repos into my [Marc Bernard Tools](https://github.com/Marc-Bernard-Tools).

**Comment by ojnc** [comment]
Thanks for your very nice response!
