### ISSUE TITLE
Moving old builds to separate repo

### ISSUE THREAD

**Issue by mbtools** [abap2xlsx/abap2xlsx#908]
Working with this repo in abapGit consumes a lot of memory. All (!) files of the repo are read and kept in memory at every fetch from GitHub. This impacts network transfer time as well.

![image](https://user-images.githubusercontent.com/59966492/145464860-3b7c2e82-744f-4aeb-9849-db80212d653e.png)

You can see it in the abapGit stats as well:

![image](https://user-images.githubusercontent.com/59966492/145465224-c1bc9760-302b-4056-95bf-ea8dc6e94143.png)

Only 10% of the repo size (the /src/ folder) is actually relevant for abapGit:

![image](https://user-images.githubusercontent.com/59966492/145465541-6da49687-a08b-4ce7-8d8d-675832212204.png)

Suggestion:

Split off the /build/ folder into a separate "abap2xlsx archive" repo.

**Comment by larshp** [comment]
yea, also see https://github.com/sapmentors/abap2xlsx/issues/861 we will move abap2xlsx to a separate organization, just been busy :)

**Comment by larshp** [comment]
can these 4 folders be moved to https://github.com/abap2xlsx/archive-abap2xlsx ?

- `additional objects`
- `build`
- `resources`
- `tools`

**Comment by AndreaBorgia-Abo** [comment]
According to the FAQ, resources/TestMacro.xlsm is meant to be used with ZDEMO_EXCEL29 so it might make sense to keep it in the main package, whereas the rest can be moved, I'd say.

**Comment by sandraros** [comment]
@larshp `resources/TestMacro.xlsm` has been removed. The 3 other folders may be moved. I'm not authorized to the target repository, could you do it? @gregorwolf fyi

**Comment by larshp** [comment]
sorry, I've added you all to https://github.com/abap2xlsx/archive-abap2xlsx
