### ISSUE TITLE
Repository moved to abap2xlsx/abap2xlsx

### ISSUE THREAD

**Issue by larshp** [abap2xlsx/abap2xlsx#913]
https://github.com/abap2xlsx/abap2xlsx

please post issues regarding this below, if any. Typically renaming works, with github redirecting

see discussion in https://github.com/abap2xlsx/abap2xlsx/issues/861

**Comment by larshp** [comment]
Icon/avatar suggestions welcome

**Comment by larshp** [comment]
let me know if more people would like invitations to the organization(to get the cool icon)

**Comment by AndreaBorgia-Abo** [comment]
Invitation accepted, thanks. Regarding the project icon, I envision something like a crane lifting blocks to finish writing an already recognizable "XLSX". Now we only need an artist :D
EDIT: already asked an acquaintance about this, let's see what he comes up with :)

**Comment by sandraros** [comment]
@gregorwolf @larshp Could you give me write access to the repository please? (same for Andrea I guess) Thanks!

**Comment by gregorwolf** [comment]
Done @sandraros

**Comment by gregorwolf** [comment]
I've updated https://wiki.scn.sap.com/wiki/display/ABAP/abap2xlsx

**Comment by chrisaasan** [comment]
Looks like the links to github.io (documentation and abapgit installation) in the readme are broken after the move.

**Comment by larshp** [comment]
@chrisaasan yea, thanks, can you help opening a PR with the fixes?

**Comment by chrisaasan** [comment]
@larshp PR #916 created. Let me know if I did something wrong in the process.

**Comment by AndreaBorgia-Abo** [comment]
[Contributing](https://github.com/abap2xlsx/abap2xlsx/blob/master/CONTRIBUTING.md) still has the old org name but it's the Slack channel so I'm not touching it, same for the invite app and the [SapLink](https://github.com/abap2xlsx/abap2xlsx/blob/master/docs/SAPLink-installation.md) guide.

**Comment by AndreaBorgia-Abo** [comment]
#919 also deals with changed links

**Comment by gregorwolf** [comment]
Description of the Slack channel was updated.

**Comment by larshp** [comment]
done, closing, open a new issue if problems are found
