### ISSUE TITLE
Read sheet_protection and book_protection

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#92]
Read properties of zif_excel_book_protection and zif_excel_sheet_protection from xlsx

**Comment by ivanfemia** [comment]
Updating issues (#23, #28, #31, #32, #49, #53, #71, #94, #97, #99, #107, #110)

**Comment by ivanfemia** [comment]
Updating issues (#23, #28, #31, #49, #53, #71, #94, #97, #99, #107, #112, #127)

Moved to Release 7.0

**Comment by StefanSchmoecker** [comment]
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by StefanSchmoecker** [comment]
Closed because no objections have arisen.
