### ISSUE TITLE
Contiguous spaces in formula are condensed

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#921]
To reproduce:
```abap
REPORT.
DATA: lo_excel     TYPE REF TO zcl_excel,
      lo_worksheet TYPE REF TO zcl_excel_worksheet.
CONSTANTS: gc_save_file_name TYPE string VALUE 'contiguous_spaces_in_formula.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  CREATE OBJECT lo_excel.
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_cell(
        ip_column  = 1
        ip_row     = 1
        ip_formula = '"    A    B    "' ).
  lcl_output=>output( lo_excel ).
```

Actual result:
![image](https://user-images.githubusercontent.com/34005250/146648893-0cf0379d-6d13-4cc8-a046-f729e8617540.png)

Expected result:
![image](https://user-images.githubusercontent.com/34005250/146648914-6b378b12-e4f4-45c7-b84e-9c0cbac6ceb6.png)

Concerned code (`CONDENSE lv_value` deletes the contiguous spaces):
https://github.com/abap2xlsx/abap2xlsx/blob/a479c0b337bcc6af7dac4b7ae6137a2dc35520a7/src/zcl_excel_writer_2007.clas.abap#L6247-L6254

**Comment by AndreaBorgia-Abo** [comment]
When testing your new demo checker, I tried simply disabling that CONDENSE and all tests still passed. To double-check, I added a string after the quotes, thus making the formula invalid, and the checker picked it up.
So my question is: other than this minimal example, can you think of a real-life formula that would be adversely affected by leaving all spaces untouched?

**Comment by sandraros** [comment]
I guess removing `CONDENSE` would be fine, no idea what it was for. Better let the developers fully responsible of formula content.
