### ISSUE TITLE
abapgit does not create ICF node of webdynpro application and downloaded filename wrong

### ISSUE THREAD

**Issue by ojnc** [abap2xlsx/abap2xlsx#923]
After installing ABAP2XLSX **ZDEMO_EXCEL_WDA01** does not work
After much debugging found WebDynpro needs a ICF Node /sap/bc/webdynpro/sap/zdemo_excel_wda01
**which abapgit  does not create**

I deleted and re-created the application
Ran successfully - downloaded file was wda01.txt not wda01.xls as coded in **onactionbtn_download**
Please fix this

**Comment by sandraros** [comment]
I reproduce for the ICF Service which was missing. I created [the branch demo-webdynpro-ICF](https://github.com/abap2xlsx/abap2xlsx/tree/sandraros/demo-webdynpro-ICF), could you pull it and check if it solves?

I don't reproduce the second point about `wda01.xlsx`. My Web browser (Edge) downloads the file as expected (and the Excel file opens successfully after that):
https://github.com/abap2xlsx/abap2xlsx/blob/6efa4c6904f3ce9ce04ed1a0091475eac272df17/src/demos/zdemo_excel_wda01.wdyn.xml#L1074
![image](https://user-images.githubusercontent.com/34005250/146677391-87b9282c-7118-48e7-bae1-6eb8df415fbf.png)

EDIT: but I have a big doubt about the below line, I would assume that the MIME type `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` is more correct than just `EXCEL`. Could you test that at your side by pulling the same branch as above?
https://github.com/abap2xlsx/abap2xlsx/blob/6efa4c6904f3ce9ce04ed1a0091475eac272df17/src/demos/zdemo_excel_wda01.wdyn.xml#L1115

Also having an empty button, so proposing the text "Download" (in same branch above):
Before: 
![image](https://user-images.githubusercontent.com/34005250/146678841-8d0d0fc0-ccd2-4782-acfd-43b473e0f739.png)
After:
![image](https://user-images.githubusercontent.com/34005250/146678848-5d371637-3f7f-4837-895d-1c18379783f7.png)

**Comment by ojnc** [comment]
Thanks for prompt response.
Will try tomorrow latest and let you know

**Comment by ojnc** [comment]
Worked!
I am no expert but just interested

Deleted only ZDEMO_EXCEL_WDA01 and pulled your branch
Had to put above in a different class 
Pulled; got 1 error 
_**Invalid alias
Import of object ZDEMO_EXCEL_WDA01 failed**_

Tried the WebDynpro; worked and also downloaded as **xlsx**

However the button did not have the shape as in the VIEW in SE80
It was not pretty but worked - see snip below
![Screenshot 2021-12-19 223016](https://user-images.githubusercontent.com/7992652/146683851-e55017b2-07fa-4c47-8c42-3ccdb0d0083c.png)

1 Class and 1 Interface too got added both named **ZCL_EXCEL_STYLE_CHANGER**
Was not there in my original I assume

**Comment by sandraros** [comment]
Thanks for the feedback.
For "invalid alias", I have opened https://github.com/abapGit/abapGit/issues/5232. You see the OTR concept number `0800271...70D19` instead of "Download" probably because of "invalid alias".
NB: extra objects are normal because abap2xlsx continuously evolves.

**Comment by sandraros** [comment]
I changed the WDA to not use an OTR text anymore, could you do a pull again please? Thanks.

**Comment by ojnc** [comment]
Worked fine.
Filename OK
No errors and beautiful button
![Screenshot 2021-12-20 163002](https://user-images.githubusercontent.com/7992652/146757261-29752233-f914-4baa-9cc0-281de888d60e.png)

Thanks!
