### ISSUE TITLE
lint rule for checking pretty print (keyword upper case)

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#941]
We'd better enforce the keyword upper case as discussed in #780, #893, and [here about problem with `CLASS ZCL_<ALLUPPERCASE> IMPLEMENTATION` when using the Class Builder SE24/SE80](https://github.com/abap2xlsx/abap2xlsx/pull/937#issuecomment-1003525533) (whatever using the form-based or source code-based editor, it's changed to upper case after activation).

Concerned abap lint rule:
https://github.com/abap2xlsx/abap2xlsx/blob/master/abaplint.json#L109

@pokrakam @AndreaBorgia-Abo @larshp What do you think?

**Comment by larshp** [comment]
keyword upper case no problem

just personally, I dont like to tell people, that wants to contribute, that they cannot use SE80 or SE24 to edit code

**Comment by sandraros** [comment]
They can easily switch to the source code-based editor of SE24/SE80 and fix it manually (or pretty print if their default setting is keyword upper case).

EDIT: too bad, it's the activation which enforces class name to upper case, even with source code-based editor :(

**Comment by larshp** [comment]
The upper/lower case of CLASS BAR IMPLEMENTATION, is not something that I typically read, there are many other things, which will increase quality and readability IMHO.

The developer cannot change it, if using SE24/SE80,
![Animation](https://user-images.githubusercontent.com/5888506/147849088-550d98d9-0165-4ac6-b7fd-2772058c5877.gif)

**Comment by sandraros** [comment]
So, with same configuration as in abapGit (`"ignoreLowerClassImplmentationStatement": true`), developers could continue using the Class Builder.
https://github.com/abapGit/abapGit/blob/22a455e10c3d3272ef35ddf20b837fb421c8ddc3/abaplint.json#L255-L264
```json
    "keyword_case": {
      "style": "upper",
      "ignoreExceptions": true,
      "ignoreLowerClassImplmentationStatement": true,
      "ignoreGlobalClassDefinition": false,
      "ignoreGlobalInterface": false,
      "ignoreKeywords": [],
      "ignoreGlobalClassBoundaries": false,
      "ignoreFunctionModuleName": false
    },
```
Proposing #942 (currently a few case errors that I need to fix)
Ready for review
