### ISSUE TITLE
Read Conditional Formatting

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#95]

**Comment by ivanfemia** [comment]
Updating issues (#23, #28, #31, #32, #49, #53, #71, #94, #97, #99, #107, #110)

**Comment by ivanfemia** [comment]
Updating issues (#23, #28, #31, #49, #53, #71, #94, #97, #99, #107, #112, #127)

Moved to Release 7.0

**Comment by ivanfemia** [comment]
[[file:bK73R40Cqr4BQzeJe8ay1r]]: Corrections for conditional formatting enhancement

**Comment by ivanfemia** [comment]
Attached SAPlink nugget containing enhancement to read conditional formatting.

**Comment by ivanfemia** [comment]
Some important notes:
- included handling of the following attributes:
   stopIfTrue - attribute of the conditionalFormatting element
   reverse - attribute of the iconSet element
- included handling of a second formula in the cellIs element.  In the case of operator 'between', there are two 'formula' sub-elements.
- modified implemention for the stop / start cell of the ZCL_EXCEL_STYLE_CONDITIONAL class.
   No change to the interface - so it should be fully backward compatible.
   Problem: the conditionalFormatting 'sqref' attribute allows for multiple ranges to be assigned. 
   Solution: change the start_cell / stop_cell attributes to a table of start / stop cell data.
- modified READER_2007 class to load the 'dxfs' element from styles.xml
   Also updated the calls to LOAD_STYLE_\* to use IF_IXML_ELEMENT instead of _DOCUMENT to allow reuse within new method LOAD_STYLE_DXFS.
- modified READER_2007 class to load conditional formating.
- modified WRITER_2007 class to write new values: stopIfTrue, reverse, formula2.

All code changes are marked with comment: " #97

**Comment by ivanfemia** [comment]
[[file:b7gqsk0CGr4BQzeJe8ay1r]]: Reader class

**Comment by ivanfemia** [comment]
[[file:b7iLMA0CGr4BQzeJe8ay1r]]: Conditional formatting class

**Comment by ivanfemia** [comment]
[[file:b7ledc0CGr4BQzeJe8ay1r]]: Writer class

**Comment by ivanfemia** [comment]
[[file:aYelrI0CKr4BQzeJe8ay1r]]: Reverse DTEL

**Comment by ivanfemia** [comment]
[[file:aYh7gW0CKr4BQzeJe8ay1r]]: Show value DTEL (corrected descriptions)

**Comment by ivanfemia** [comment]
[[file:aYu-5o0CKr4BQzeJe8ay1r]]: Stop if true DTEL

**Comment by ivanfemia** [comment]
[[file:bpEDUm0CKr4BQzeJe8ay1r]]: Cell Is structure

**Comment by ivanfemia** [comment]
[[file:bpT8A40CKr4BQzeJe8ay1r]]: Icon Set structure

**Comment by ivanfemia** [comment]
[[file:ctusZu0CKr4BQzeJe8ay1r]]: Cell range structure

**Comment by ivanfemia** [comment]
[[file:ctwFw80CKr4BQzeJe8ay1r]]: Cell range table type

**Comment by ivanfemia** [comment]
It came to me that you would rather have the slinkees for file comparisons.  Enjoy. :)

**Comment by ivanfemia** [comment]
[[file:dhU4rg0Dqr4yNxeJe8ay1r]]: Conditional formatting class

**Comment by ivanfemia** [comment]
Please ignore STYLE_CONDITIONAL attachment at July 19 13:37.  Instead use the attachment from Jul 19 15:06.

(Would be nice to have a [delete attachment] function.)

**Comment by ivanfemia** [comment]
deleted, I can do it.

**Comment by ivanfemia** [comment]
Excellent - thank you.

**Comment by ivanfemia** [comment]
[[file:cylTxUdcKr473dacwqjQYw]]
Reverse DTEL

**Comment by ivanfemia** [comment]
[[file:cyp5xsdcKr473dacwqjQYw]]
Show value DTEL (corrected descriptions)

**Comment by ivanfemia** [comment]
[[file:cyujn4dcKr473dacwqjQYw]]
Stop if true DTEL

**Comment by ivanfemia** [comment]
[[file:czUTLSdcKr473dacwqjQYw]]
Reader class

**Comment by ivanfemia** [comment]
[[file:cz0VEKdcKr473dacwqjQYw]]
Writer class

**Comment by ivanfemia** [comment]
[[file:cBA4_0dcKr473dacwqjQYw]]
Corrections for conditional formatting enhancement

**Comment by ivanfemia** [comment]
[[file:cCzfB8dcKr473dacwqjQYw]]
Cell Is structure

**Comment by ivanfemia** [comment]
[[file:cCFNkudcKr473dacwqjQYw]]
Icon Set structure

**Comment by ivanfemia** [comment]
[[file:cGBMjwdcKr473dacwqjQYw]]
Cell range structure

**Comment by ivanfemia** [comment]
[[file:cGNRnidcKr473dacwqjQYw]]
Cell range table type

**Comment by ivanfemia** [comment]
[[file:cJGkqedcKr473dacwqjQYw]]
Conditional formatting class

**Comment by StefanSchmoecker** [comment]
Lots of changes in the previous years to conditional styles and reader class.
I close this topic since we have a newer discussion in topic #366
