### ISSUE TITLE
ZDEMO_EXCEL_CHECKER points to ZIP-DIFF repo

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abap2xlsx/abap2xlsx#972]
The viewer error message points to the [ZIP-DIFF repo](https://github.com/sandraros/zip-diff) since it originated from there.
Now that a revised version has been incorporated into abap2xlsx does it still make sense to refer to the original repo?
I'm not saying this is a bug, a lot depends on the plans for zip-diff's future.

**Comment by sandraros** [comment]
In fact, `ZDEMO_EXCEL_CHECKER` contains 300 lines of code to do a simple ZIP equal/not-equal calculation (probably the part you are talking about), and one part to view the exact differences (installing ZIP-DIFF is needed) . I guess the 300 lines should not be part of abap2xlsx project, and I'd better move them to ZIP-DIFF repository.

As the code for comparing and viewing the differences between two ZIP files is big, and is used by maintainers only (you and I, and possibly by experienced contributors in the future), I thought the code should not be part of abap2xlsx. I feel that the code in `ZDEMO_EXCEL_CHECKER` should concentrate on abap2xlsx/XLSX only, ZIP diff algorithms is another story. The interest of using external projects is to not mix issues, commits and pull requests, about topics unrelated to abap2xlsx.

If it's really a problem that the maintainers need to install ZIP-DIFF to use `ZDEMO_EXCEL_CHECKER`, I'm fine with integrating ZIP-DIFF as local classes inside `ZDEMO_EXCEL_CHECKER`. Note that ZIP-DIFF has also one separate program to compare 2 ZIP files on the laptop. I also have a pull request to add another test program.

**Comment by AndreaBorgia-Abo** [comment]
First off, thanks for the memory jogging: I believe we had (parts of) this conversation during the review and I unsurprisingly forgot about it, my bad. What a coincidence we just finished talking of people forgetting stuff during installation! ;)

Pro keeping ZDEMO_EXCEL_CHECKER in abap2xlsx, including the 300 lines, is the possibility of one day scripting regression testing in GitHub (that would be @larshp domain). This would be a use case where lack of ZIP-DIFF would be perfectly acceptable.

OTOH, a developer digging into XLSX files is almost surely interested in examining whatever differences arise in detail, hence the need for ZIP-DIFF. Using APACK for this is overkill and just just wrong (saying this to my future self, mostly).

Let's hear Lars first: if automated testing is feasible, I'm for keeping things as they're now (internal compare, external viewer)
Actually, you may even add a memo in [the code](https://github.com/abap2xlsx/abap2xlsx/blob/bffb01c7b94fdfd5305ac381721f5a0f06a2d2a7/src/demos/zdemo_excel_checker.prog.abap#L1099) like "yes, Andrea, that means you!" just for the lulz :)

If not, I kind of feel ZDEMO_EXCEL_CHECKER and ZIP-DIFF sort of belong together: end users of the library won't care anyway and we may even end up spinning off demos altogether in a [separate package](https://github.com/abap2xlsx/abap2xlsx/issues/861#issuecomment-957347278).

**Comment by sandraros** [comment]
Could you recreate this issue in https://github.com/abap2xlsx/demos, and then close this one? Thanks!

**Comment by AndreaBorgia-Abo** [comment]
@sandraros why would we want to do that? After all, this discussion is about moving ZDEMO_EXCEL_CHECKER from here to the demos repo and, as such, I believe both places are perfectly good for the issue.
Taking a larger view, this repo (library) should be just that and the demos should include support tool for devs as well.

@larshp what are your thoughts on such a move in relation to automatic testing? 
EDIT: scratch that, I see [cross-repo testing](https://github.com/abap2xlsx/abap2xlsx/issues/861#issuecomment-958652077) was already mentioned!

**Comment by sandraros** [comment]
It's just that it was obvious to me that demo issues should be in the demos repository. I already moved my own demo issues to https://github.com/abap2xlsx/demos/issues. It's not an issue if you don't agree, let's keep it here. Concerning ZIP-DIFF, I agree that we should copy it to the demos repository, maybe doing it more specific as an XLSX-DIFF (this way, we may also solve diff issues which occur only in XLSX), which might both evolve separately.

**Comment by larshp** [comment]
yea, it cross checks automatically, for each push, https://github.com/abap2xlsx/abap2xlsx/pull/1024/checks?check_run_id=6340439572, https://blogs.sap.com/2022/05/03/cross-repository-syntax-check-before-merge/

https://github.com/abap2xlsx/abap2xlsx/pull/872 is the first steps for getting unit tests running, when unit test work, we can start moving into integration tests. And I also see all the demo reports running in the browser sometime, so its not needed to install them, and possible to "fiddle" with the ABAP code in the browser

**Comment by AndreaBorgia-Abo** [comment]
@sandraros ok, then you may go ahead with the move and then close this issue.
Also, if you all agree, I propose that we make a new release so that the split repos go live for release-oriented users, such as my colleagues :)

**Comment by AndreaBorgia-Abo** [comment]
So, trying to clean things up for the next release:

- ZDEMO_EXCEL_CHECKER had already been [moved to the demos rep](https://github.com/abap2xlsx/demos/commit/30dbbb4463e04fdc396f42d8203592ba5b2495df) by the time we last [discussed this](https://github.com/abap2xlsx/abap2xlsx/issues/972#issuecomment-1120393808) so I guess the issue may be safely closed
- opening a new issue in "demos" rep specifically for XLSX-DIFF as mentioned earlier
