### ISSUE TITLE
Problem with reading INT8 number via ZCL_EXCEL_WORKSHEET=>SET_CELL( )

### ISSUE THREAD

**Issue by tr4pt** [abap2xlsx/abap2xlsx#977]
Hi team,

I'm facing an issue while trying to set an INT8 Value via SET_CELL to convert it to a file.
As you can see, in this method. The INT8 value should be assigned to a regular numeric field.
<img width="565" alt="image" src="https://user-images.githubusercontent.com/95632896/151365099-ca0a89ab-205e-4ac7-9de1-0454888079b5.png">

<img width="526" alt="image" src="https://user-images.githubusercontent.com/95632896/151364852-d5c4d14a-481f-47a7-93de-4e4033314ca2.png">

Can you please fix this issue? Thanks in advance and best regards

**Comment by sandraros** [comment]
Hello. Could you provide the steps or a program to reproduce the issue? Thank you, that will help us!

**Comment by tr4pt** [comment]
Hmm can't give you a program. But when using a big amount for VND like 33.400.000.000 VND, which data type is INT8, the report dumps, cuz the <fs_numeric> field-symbol is just an Integer (I(4)). The following method number_to_excel_string uses a numeric parameter too.

**Comment by sandraros** [comment]
Thanks, sorry I understand now. The issue is that even the "value type" is integer 8 bytes, the method `GET_I` will create a work field of type integer 4 bytes, so there will raise an exception of type `CX_SY_CONVERSION_OVERFLOW`. Could you run this program below, and confirm if it's the same issue that you are describing? Thanks!
```abap
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'test.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  TRY.
      DATA(lo_excel) = NEW zcl_excel( ).
      DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
      lo_worksheet->set_cell( ip_column = 'A' ip_row = 1 ip_value = conv int8( 33400000000 ) ).
      lcl_output=>output( cl_excel = lo_excel ).
    CATCH cx_root INTO DATA(lx_root).
      MESSAGE lx_root TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
```

**Comment by tr4pt** [comment]
Good morning.
Yes, this is exactly the issue. :) That an int8 data type will be assigned to a numeric field_symbol.

**Comment by sandraros** [comment]
@tr4pt Please tell us if it solves your problem. If yes, could you close the issue. Thanks!

**Comment by tr4pt** [comment]
The issue is fixed now. Thank you so much for the fast solution. 
GOnna close it
