### ISSUE TITLE
zif_apack_manifest is missing on target system

### ISSUE THREAD

**Issue by ElNovi** [abap2xlsx/abap2xlsx#978]
Transport from dev systems to our testing system is failing cos class **zcl_excel_apack** is using interface **zif_apack_manifest** which is only local to dev system. Should I add it to transport request or it should be part of abap2xlsx repo?

![image](https://user-images.githubusercontent.com/14199592/151564320-41c59b75-6f85-4349-be3a-5acdb75f3996.png)

We are using https://github.com/abap2xlsx/abap2xlsx/releases/tag/7.15.0

**Comment by sandraros** [comment]
Thanks. To install abap2xlsx, which abapGit version are you using? Did you try with the latest abapGit version?

**Comment by ElNovi** [comment]
Hi Sandra, abapGit is version 1.114.0 i try to keep it updated. However that zif_apack_manifest is generated on first launch of abapGit to package $TMP on behalf of user who launched it - if i'm not mistaken. 

Yep it is, see https://docs.abapgit.org/ref-apack.html#transporting-apack-implementation-classes. So it is not problem of ABAP2XLSX.

**Comment by sandraros** [comment]
Thanks for looking into it, didn't know that. And APACK seems to bring more trouble than just a cool feature (just to display the latest changes of abap2xlsx in `zabapgit`). Not sure we'll keep that feature in abap2xlsx then... @AndreaBorgia-Abo @larshp Do you think it's better to stop using APACK in abap2xlsx? (people will go to GitHub if they want to see the changes of the latest release)

**Comment by gregorwolf** [comment]
I haven't yet dug into APACK but it would also allow me to create an application that uses abap2xlsx and there I could specify that I rely on a specific minimum version of abap2xlsx or?

**Comment by larshp** [comment]
Personally I choose to _not_ use APACK

abapGit can pull a specific tag, or commit. Just consider the default branch to be latest, anyhow its not possible to have multiple versions installed, without [copy and renaming](https://github.com/larshp/abap2xslx-rename)

**Comment by sandraros** [comment]
@gregorwolf I added APACK to abap2xlsx so that people pulling abap2xlsx from abapGit can see the change log of latest changes. abapGit does that by looking at the version defined in the dedicated APACK class. The change log is the same feature as the abapGit change log, except that code of abapGit doesn't rely on APACK... abap2xlsx doesn't use any other feature of APACK.

**Comment by AndreaBorgia-Abo** [comment]
Weird! Granted, I have only 2 real world installations as experience, but I did not enocunter that issue.
@sandraros when was it added? I kind of like the idea of APACK but I admit I haven't played with it yet.

**Comment by larshp** [comment]
yea, well, I'd like to change the news feature somehow, so it does not rely on APACK

**Comment by sandraros** [comment]
@AndreaBorgia-Abo With the version 7.14.0, when I proposed to roll out a new release.

**Comment by AndreaBorgia-Abo** [comment]
If I understand it correctly, we can highlight this step in the installation guide and that should cover it, right?

**Comment by sandraros** [comment]
Yes, that's also a solution. But you know how people are. They won't understand, or will leave it for later, and they will forget.
