### ISSUE TITLE
syntax error after installation (pull)

### ISSUE THREAD

**Issue by LAT2** [abap2xlsx/abap2xlsx#986]
Hi,
when searching how to create xlsx with abap of course I got to here eventually.
Pulled the package but when activating I get syntax error in
ZCL_EXCEL_WRITER_2007->CREATE_XL_DRAWINGS_HDFT_RELS (actually I get a dump when running any of the demo programs:
```
Category               ABAP programming error
Runtime Errors         SYNTAX_ERROR
ABAP Program           ZCL_EXCEL_WRITER_2007
Application Component  Not assigned
```

Line 49: Error in
arithmetic expression: A field, a function, or
"(" was expected instead of "<FS_DRAWINGS>-
DRAWING->GET_INDEX(". 

section of the code:
46    lt_drawings = io_worksheet->get_header_footer_drawings( ).
47    LOOP AT lt_drawings ASSIGNING <fs_drawings>. "Header or footer image exist
48      ADD 1 TO lv_relation_id.
49      lv_value = <fs_drawings>-drawing->get_index( ).            <<<=== line giving error
50      READ TABLE lt_temp WITH KEY str = lv_value TRANSPORTING NO FIELDS.
51      IF sy-subrc NE 0.
52        APPEND INITIAL LINE TO lt_temp ASSIGNING <fs_temp>.
53        <fs_temp>-row_index = sy-tabix.
54        <fs_temp>-str = lv_value.
55        CONDENSE lv_value.

Can't figure out what should be wrong with the code.
I'm running on SAP_BASIS & SAP_ABA	Release 750	SP-level: 0019	
Any help is very much appreciated.
Thanks
Regards
LAT2

**Comment by sandraros** [comment]
Maybe the mass activation of abapGit didn't activate the ABAP dictionary objects of abap2xlsx. What version of abapGit do you use?

For instance, is the table type `ZEXCEL_T_DRAWINGS` activated? (`SE11`)

**Comment by sandraros** [comment]
Same issue already reported (#674 @AndreaBorgia-Abo fyi). It doesn't seem this was reported to [abapGit](https://github.com/abapGit/abapGit/issues), maybe you could report it to abapGit?

**Comment by LAT2** [comment]
Thank you. I'm just wondering why i did't find #674 ? I searched, of course, with exactly those key words.
Thanks for your help. I check activation and open a ticket with gitHub
Regards & Thanks for your extrem fast reply.
LAT2

**Comment by sandraros** [comment]
Probably because #674 was closed and GitHub search default options are `is:issue is:open`. You may find closed issues by clearing `is:open`.

**Comment by AndreaBorgia-Abo** [comment]
@sandraros I'm having the same issue pulling tag 7.15 but in this case the activation error is spurious, objects are active. Will see if I can find a pattern, no further updates here.

**Comment by LAT2** [comment]
I pulled the full abap2xlsx again and after that everything was fine.
so actually I don't know what went wrong the first time.

**Comment by AndreaBorgia-Abo** [comment]
@LAT2 in this case, the objects were already in the system and active. Unless you want to restore the system from backups just to run that test, that's hardly surprising, imho.
