### ISSUE TITLE
zif_apack_manifest is missing on target system (BIS)

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#992]
Proposing to continue the discussion after #978, so that to either:
1. fix the installation documentation, to tell the clients to assign `ZCL_EXCEL_APACK` to the abap2xlsx main package, for permitting safe transport
2. remove `ZCL_EXCEL_APACK` and `changelog.txt` + update documentation to indicate the change log can be found in the GitHub Releases

I would go for solution 2 as per @larshp opinion.

**Comment by AndreaBorgia-Abo** [comment]
Just this week I installed 7.15.0 in a customer system, moved the interface to its own package and transported first one CR (apack only) and then the main library, all went smoothly. So it is doable :)
Anyway, in general I agree: if we need apack only for the cool changelog, we might as well lose it.

**Comment by AndreaBorgia-Abo** [comment]
Removal PR has been merged, closing.
