### ISSUE TITLE
Syntax Error ZCL_EXCEL_WRITER_2007=========CP

### ISSUE THREAD

**Issue by mikibarzilay** [abap2xlsx/abap2xlsx#993]
I have installed a fresh new SAP NW 750 with the latest support pack 22.
I installed Microsoft Office 2016 on the application server too (I'm not sure it's necessary).

Then I pull the ABAP2XSLX package using ABAPGIT.

Now, when I'm trying to execute several demo programs. 
Unfortunately, all fails with the same error:

Category               ABAP programming error
Runtime Errors         SYNTAX_ERROR
ABAP Program           ZCL_EXCEL_WRITER_2007=========CP

>>>>>           CREATE OBJECT cl_writer TYPE zcl_excel_writer_2007.

When I'm checking the ZCL_EXCEL_WRITER_2007 class, there are several errors:

Method CREATE_XL_DRAWINGS_HDFT_RELS
Error in arithmetic expression: A field, a function, or "(" was expected instead of "<FS_DRAWINGS>-DRAWING->GET_INDEX(".
Method CREATE_XL_DRAWINGS_HDFT_RELS
Method "GET_MEDIA_NAME" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_FOOTER
Method "GET_POSITION" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_FOOTER
Method "GET_INDEX" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_FOOTER
Method "GET_POSITION" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_FOOTER
Method "GET_INDEX" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_FOOTER
Method "GET_POSITION" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_FOOTER
Method "GET_INDEX" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_HEADER
Method "GET_POSITION" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_HEADER
Method "GET_INDEX" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_HEADER
Method "GET_POSITION" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_HEADER
Method "GET_INDEX" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_HEADER
Method "GET_POSITION" is unknown or PROTECTED or PRIVATE.
Method SET_VML_SHAPE_HEADER
Method "GET_INDEX" is unknown or PROTECTED or PRIVATE.

Any Idea?

**Comment by mikibarzilay** [comment]
The issue is in CREATE_XL_DRAWINGS_HDFT_RELS method at line 49
v_value = <fs_drawings>-drawing->get_index( ).

Method CREATE_XL_DRAWINGS_HDFT_RELS
Error in arithmetic expression: A field, a function, or "(" was expected instead of "<FS_DRAWINGS>-DRAWING->GET_INDEX(".
Method CREATE_XL_DRAWINGS_HDFT_RELS
Method "GET_MEDIA_NAME" is unknown or PROTECTED or PRIVATE.

**Comment by sandraros** [comment]
Hi, thanks. Let me check that.

**Comment by AndreaBorgia-Abo** [comment]
@sandraros could it be an incomplete pull?
@mikibarzilay does the source of zcl_excel_writer_2007 look anything [like this?](https://raw.githubusercontent.com/abap2xlsx/abap2xlsx/master/src/zcl_excel_writer_2007.clas.abap)

**Comment by sandraros** [comment]
It's the same issue as #674 and #986. The solution is to pull again, check the objects activated, etc. That's something related to abapGit, not sure what the exact error is. Maybe @larshp @mbtools could help us.

**Comment by mikibarzilay** [comment]
I tried to pull it online several times and also using the zip file as
offline repository with no luck.

Micky

**Comment by sandraros** [comment]
Did you check the list of "Inactive Objects" in `SE80`, and activate all of them manually?

**Comment by mikibarzilay** [comment]
I really appreciate your support.
Checking for Inactive Object in SE80, there is no inactive objects.

**Comment by AndreaBorgia-Abo** [comment]
@mikibarzilay did you get [any errors](https://github.com/abapGit/abapGit/issues/5325) during pull?

**Comment by mikibarzilay** [comment]
When I clicked "pull" for the first time I received an error, then I clicked again and it complete without any error.
However, I found that the  ZEXCEL_S_DRAWINGS structure wasn't activated, I activate it manually. This didn't solve the issue yet.

One more interesting issue, I CREATE_XL_DRAWINGS_HDFT_RELS method when I'm double-clicking on ger_index( ) in line 49 (where the error points) I'm getting the message "Class (Definition) ZCL_EXCEL_WRITER_2007 does not exist" although in SE24 it exist.

**Comment by sandraros** [comment]
You may use abapGit menu Advanced > Syntax Check to see all objects with syntax error. Try to activate inactive DDIC objects first.
Be careful with objects which seem active, I think abapGit forces the activation, while they may still contain syntax errors.

Bed time for me, I hope you can find out the issue...

**Comment by mikibarzilay** [comment]
Hi again, 
In abapGIT I clicked on several items and one after one I can confirm they are "partly activated".

**Comment by AndreaBorgia-Abo** [comment]
At this stage, I think this is really an issue with abapGit and not with abap2xlsx, unfortunately.
You should try filing an issue [there.](https://github.com/abapGit/abapGit/issues/new/choose)

**Comment by mikibarzilay** [comment]
Thank you Abo,
Is there any way to received a Change Request transport  (data and cofile files) instead of using abapGIT?

**Comment by AndreaBorgia-Abo** [comment]
@mikibarzilay with an abapgit project, this is neither supplied nor recommended. The two installations I encountered where somebody had already tried that approach were **hell** to clean up: some objects had different transport layers, some were local, a mess you don't want to have, believe me.

**Comment by mbtools** [comment]
This project contains XSLT and if those objects don't activate properly, then nothing else will work (due to Ddic and code dependencies). 

Therefore, please check SAP note https://launchpad.support.sap.com/#/notes/2859159 first and make sure you have the right kernel version running. 

Secondly, run the very latest version since we continuously improve things like #5303 which shows inactive TABL objects correctly (note: similar handling of other DDIC types is still missing). 

To have a reproducible case, uninstall the complete repo and install it again. Attach output of Utilities > Debug info and screenshot after initial pull.

**Comment by sandraros** [comment]
Thanks Marc. I just created #994. I'll try to work on the abap2xlsx fix this evening (not guaranteed as I'm quite busy currently).

**Comment by sandraros** [comment]
For information, I think all these PRs in abap2xlsx and abapGit could help solving - Please wait till they are merged:
- #995 
- https://github.com/abapGit/abapGit/pull/5369
- https://github.com/abapGit/abapGit/pull/5370
- https://github.com/abapGit/abapGit/pull/5371

**Comment by gerschler** [comment]
I had the same problem and it happens in our release because the dynamic TYPE REF TO OBJECT in the structures like ZEXCEL_S_WORKSHEET_HEAD_FOOT doesn't allow the syntax check in calling methods like get_index( ).

I simply adapted the coding and cast it to type-specific reference variables:

`
   OLD: 
    lv_value = <fs_drawings>-drawing->get_index( ).  


     NEW:
      data lr_drawing type ref to ZCL_EXCEL_DRAWING.        
      
      lr_drawing ?= <fs_drawings>-drawing.       
                         
      lv_value = lr_drawing->get_index( ).                          
`
I don't know if it's the best solution, but it works as a fix workaround until a new version is available.

**Comment by sandraros** [comment]
After we moved the Demo programs to a separate repository (#998), the issue doesn't happen anymore.
Could you try? If okay, I propose to close the issue.

**Comment by AndreaBorgia-Abo** [comment]
Using my AS ABAP 7.52SP04 installation, which was known to suffer from the activation issue due to the missing note, I removed all traces of abap2xlsx and dependent programs, then installed first the base package and then the demos. Activation was completed without errors.

**Comment by mbtools** [comment]
I tested main and demo repos with v1.115.0 on 7.54. Both can be pulled without errors (just some warnings due to reserved field names)

Suggest closing

**Comment by sandraros** [comment]
I agree. Let's close it then. Thanks!
