### ISSUE TITLE
Install issues - Make transfo ZEXCEL_TR_SHEET independent from class

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/abap2xlsx#994]
We had many abap2xlsx installation issues recently (#993, [abapGit/#5262](https://github.com/abapGit/abapGit/issues/5262), etc.) because many SAP systems still use old kernels, without patch [2859159](https://launchpad.support.sap.com/#/notes/2859159), it implies a bug related to Transformation objects, and next objects are not activated.

The transformation `ZEXCEL_TR_SHEET` currently receives an instance of the class `ZCL_EXCEL_WRITER_HUGE_FILE`, and this is the starting point of installation problems.

By replacing the class with a structure or an internal table, I guess it should solve the issue.

**Comment by mbtools** [comment]
the note does not explicitly talk about ddic vs non-ddic object dependencies but replacing the class with ddic will ensure that the xslt object will be in the same activation step. this has the best chance of working. :-)

**Comment by sandraros** [comment]
@AndreaBorgia-Abo For information, removing the class from the transformation is not so much trivial, because the class (`tt:call-method`) is needed to use less memory (imagine we have 1 million lines in the workbook... of course there's no target volume that `ZCL_EXCEL_WRITER_HUGE_FILE` should support, it depends on server/app available memory)
1. We should just go for the solution which saves memory as much as possible.
1. It's not possible to refer dynamically to the class in the transformation, its name must be statically defined.
2. So, currently, I have no idea how to proceed...

**Comment by mbtools** [comment]
Maybe we need to approach it in abapGit as we do for other DDIC objects with code dependencies (like TABL using REF TO CLAS). Once using a generic object reference (REF TO OBJECT) and later again after the class exists (LATE phase). 

Could `ZEXCEL_TR_SHEET` (or other XSLTs) be activated in the DDIC phase using a generic class (OBJECT) or an existing SAP class? 

In other words, is there a general way that abapGit could temporarily modify the xslt source so it activates (since the class isn't there yet)? Maybe just a "dummy source"?

**Comment by sandraros** [comment]
I'll check if I can find something.

**Comment by AndreaBorgia-Abo** [comment]
I smell a new PR to review ;)

**Comment by larshp** [comment]
any thoughts on using string concatenation instead of transformations?

**Comment by sandraros** [comment]
Yes, it's a possibility. We are also moving the demo programs to another repository and it might solve the issue (#998).

**Comment by larshp** [comment]
string concatenation is probably fast, not sure how it compares to transformations. But transformations is a different language than ABAP, which makes it difficult IMHO. Plus ABAP can be debugged.

**Comment by sandraros** [comment]
Yes, many people don't know ST and XSLT and are reluctant to learn these languages. They can be both debugged though.

I see that the installation of abap2xlsx works fine now, no more issues with transformations, so I close this issue. Anyone is welcome to convert the transformations to ABAP.
